SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [sf].[fApplicationUser#IsDeleteEnabled]
	(
	@ApplicationUserSID int
	)
returns bit
as
/*********************************************************************************************************************************
ScalarF : sf.fApplicationUser#IsDeleteEnabled
Notice  : Copyright © 2018 Softworks Group Inc.
Summary : Returns 1 (bit) when deletion of the record is allowed
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pIsDeleteEnabledFcnGen | Designer: Tim Edlund
Version : May 2018
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------

The function is called by the entity view to set a calculated bit column "IsDeleteEnabled". The column is typically bound to a
delete button on the UI.  The results of the function determine whether or not deletion should be allowed.  The function tests
one or more of the following factors: 1) whether the table contains a system code column in which case deletion is
not allowed, 2) the security granted to the logged in user, and, 3) the existence of child records.

When a child table is related through a foreign key with cascade delete, and all descendants of that table are also related with
cascade delete constraints, then the child table is not considered blocking and will not appear in the SELECT statement.

Table-specific logic can be added through tagged sections (pre and post check). An extended version of the function is not
supported.  Code implemented within code tags is part of the base product and applies to all client configurations.

Example
-------

select top (10)
   x.ApplicationUserSID
  ,sf.fApplicationUser#IsDeleteEnabled(x.ApplicationUserSID) IsDeleteEnabled
from
  sf.ApplicationUser x
order by
  newid()

-------------------------------------------------------------------------------------------------------------------------------- */

begin

	declare
		 @isDeleteEnabled                 bit																	-- return value
		,@ON                              bit = cast(1 as bit)								-- constant to eliminate repetitive casting syntax
		,@OFF                             bit = cast(0 as bit)								-- constant to eliminate repetitive casting syntax
	
	set @isDeleteEnabled = @ON																							-- set return value to ON then check for blocking conditions
	
	--! <PreCheck>
	--  insert pre-check logic here ...
	--! </PreCheck>
	
	if @isDeleteEnabled = @ON																								-- check for existence of child records
	begin
	
		if
		(
			select
				  count(x01.ApplicationUserSessionSID)
				+ count(x02.EmailMessageSID)
				+ count(x03.EmailTriggerSID)
				+ count(x04.FormSID)
				+ count(x05.PersonGroupSID)
				+ count(x06.TaskSID)
				+ count(x08.TaskQueueSID)
				+ count(x09.TaskTriggerSID)
				+ count(x10.TextMessageSID)
				+ count(x11.TextTriggerSID)
				+ count(x12.PersonProfileSID)
			from
				sf.ApplicationUser        x00
			left outer join
				  (select top (1) x.ApplicationUserSessionSID, x.ApplicationUserSID from sf.ApplicationUserSession x where x.ApplicationUserSID = @ApplicationUserSID) x01 on x00.ApplicationUserSID =  x01.ApplicationUserSID
			left outer join
				  (select top (1) x.EmailMessageSID, x.ApplicationUserSID from sf.EmailMessage x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x02 on x00.ApplicationUserSID =  x02.ApplicationUserSID
			left outer join
				  (select top (1) x.EmailTriggerSID, x.ApplicationUserSID from sf.EmailTrigger x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x03 on x00.ApplicationUserSID =  x03.ApplicationUserSID
			left outer join
				  (select top (1) x.FormSID, x.ApplicationUserSID from sf.Form x where x.ApplicationUserSID = @ApplicationUserSID) x04 on x00.ApplicationUserSID =  x04.ApplicationUserSID
			left outer join
				  (select top (1) x.PersonGroupSID, x.ApplicationUserSID from sf.PersonGroup x where x.ApplicationUserSID = @ApplicationUserSID) x05 on x00.ApplicationUserSID =  x05.ApplicationUserSID
			left outer join
				  (select top (1) x.TaskSID, x.ApplicationUserSID from sf.Task x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x06 on x00.ApplicationUserSID =  x06.ApplicationUserSID
			left outer join
				  (select top (1) x.TaskQueueSID, x.ApplicationUserSID from sf.TaskQueue x where x.ApplicationUserSID = @ApplicationUserSID) x08 on x00.ApplicationUserSID =  x08.ApplicationUserSID
			left outer join
				  (select top (1) x.TaskTriggerSID, x.ApplicationUserSID from sf.TaskTrigger x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x09 on x00.ApplicationUserSID =  x09.ApplicationUserSID
			left outer join
				  (select top (1) x.TextMessageSID, x.ApplicationUserSID from sf.TextMessage x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x10 on x00.ApplicationUserSID =  x10.ApplicationUserSID
			left outer join
				  (select top (1) x.TextTriggerSID, x.ApplicationUserSID from sf.TextTrigger x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x11 on x00.ApplicationUserSID =  x11.ApplicationUserSID
			left outer join
				  (select top (1) x.PersonProfileSID, x.ApplicationUserSID from stg.PersonProfile x where isnull(x.ApplicationUserSID, -1) = @ApplicationUserSID) x12 on x00.ApplicationUserSID =  x12.ApplicationUserSID
			where
				x00.ApplicationUserSID = @ApplicationUserSID
		) > 0 set @isDeleteEnabled = @OFF
		
	end
	
	--! <PostCheck>
	if @isDeleteEnabled = @ON
	and exists
	(
		select																																-- job executor and help desk accounts cannot be deleted!	
			1
		from
			sf.ApplicationUser au
		where
			au.ApplicationUserSID = @ApplicationUserSID
		and
			(au.UserName = N'JobExec' or au.UserName = N'admin@helpdesk')
	)
	begin
		set @isDeleteEnabled = @OFF
	end

	if @isDeleteEnabled = @ON																								-- block unless current user an SA
	begin
		set @isDeleteEnabled = sf.fIsSysAdmin()
	end
	--! </PostCheck>
	
	return(@isDeleteEnabled)
end

GO
