SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [sf].[fFormVersion#IsDeleteEnabled]
	(
	@FormVersionSID int
	)
returns bit
as
/*********************************************************************************************************************************
ScalarF : sf.fFormVersion#IsDeleteEnabled
Notice  : Copyright © 2018 Softworks Group Inc.
Summary : Returns 1 (bit) when deletion of the record is allowed
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pIsDeleteEnabledFcnGen | Designer: Tim Edlund
Version : May 2018
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------

The function is called by the entity view to set a calculated bit column "IsDeleteEnabled". The column is typically bound to a
delete button on the UI.  The results of the function determine whether or not deletion should be allowed.  The function tests
one or more of the following factors: 1) whether the table contains a system code column in which case deletion is
not allowed, 2) the security granted to the logged in user, and, 3) the existence of child records.

When a child table is related through a foreign key with cascade delete, and all descendants of that table are also related with
cascade delete constraints, then the child table is not considered blocking and will not appear in the SELECT statement.

Table-specific logic can be added through tagged sections (pre and post check). An extended version of the function is not
supported.  Code implemented within code tags is part of the base product and applies to all client configurations.

Example
-------

select top (10)
   x.FormVersionSID
  ,sf.fFormVersion#IsDeleteEnabled(x.FormVersionSID) IsDeleteEnabled
from
  sf.FormVersion x
order by
  newid()

-------------------------------------------------------------------------------------------------------------------------------- */

begin

	declare
		 @isDeleteEnabled                 bit																	-- return value
		,@ON                              bit = cast(1 as bit)								-- constant to eliminate repetitive casting syntax
		,@OFF                             bit = cast(0 as bit)								-- constant to eliminate repetitive casting syntax
	
	set @isDeleteEnabled = @ON																							-- set return value to ON then check for blocking conditions
	
	--! <PreCheck>
	--  insert pre-check logic here ...
	--! </PreCheck>
	
	if @isDeleteEnabled = @ON																								-- check for existence of child records
	begin
	
		if
		(
			select
				  count(x01.ProfileUpdateSID)
				+ count(x02.RegistrantAppSID)
				+ count(x03.RegistrantAppReviewSID)
				+ count(x04.RegistrantAuditSID)
				+ count(x05.RegistrantAuditReviewSID)
				+ count(x06.RegistrantLearningPlanSID)
				+ count(x07.RegistrantRenewalSID)
				+ count(x08.ReinstatementSID)
			from
				sf.FormVersion             x00
			left outer join
				  (select top (1) x.ProfileUpdateSID, x.FormVersionSID from dbo.ProfileUpdate x where x.FormVersionSID = @FormVersionSID) x01 on x00.FormVersionSID =  x01.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantAppSID, x.FormVersionSID from dbo.RegistrantApp x where x.FormVersionSID = @FormVersionSID) x02 on x00.FormVersionSID =  x02.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantAppReviewSID, x.FormVersionSID from dbo.RegistrantAppReview x where x.FormVersionSID = @FormVersionSID) x03 on x00.FormVersionSID =  x03.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantAuditSID, x.FormVersionSID from dbo.RegistrantAudit x where x.FormVersionSID = @FormVersionSID) x04 on x00.FormVersionSID =  x04.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantAuditReviewSID, x.FormVersionSID from dbo.RegistrantAuditReview x where x.FormVersionSID = @FormVersionSID) x05 on x00.FormVersionSID =  x05.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantLearningPlanSID, x.FormVersionSID from dbo.RegistrantLearningPlan x where x.FormVersionSID = @FormVersionSID) x06 on x00.FormVersionSID =  x06.FormVersionSID
			left outer join
				  (select top (1) x.RegistrantRenewalSID, x.FormVersionSID from dbo.RegistrantRenewal x where x.FormVersionSID = @FormVersionSID) x07 on x00.FormVersionSID =  x07.FormVersionSID
			left outer join
				  (select top (1) x.ReinstatementSID, x.FormVersionSID from dbo.Reinstatement x where x.FormVersionSID = @FormVersionSID) x08 on x00.FormVersionSID =  x08.FormVersionSID
			where
				x00.FormVersionSID = @FormVersionSID
		) > 0 set @isDeleteEnabled = @OFF
		
	end
	
	--! <PostCheck>
	if @isDeleteEnabled = @ON																								-- block unless current user inserted the row or is an administrator
	begin
	
		if
		(
			select
				x.CreateUser
			from
				sf.FormVersion x
			where
				x.FormVersionSID = @FormVersionSID
			) <> sf.fApplicationUserSession#UserName() set @isDeleteEnabled = sf.fIsGranted('ADMIN.BASE')
	
	end
	--! </PostCheck>
	
	return(@isDeleteEnabled)
end

GO
