SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [sf].[fPersonEmailMessage#IsDeleteEnabled]
	(
	@PersonEmailMessageSID int
	)
returns bit
as
/*********************************************************************************************************************************
ScalarF : sf.fPersonEmailMessage#IsDeleteEnabled
Notice  : Copyright © 2018 Softworks Group Inc.
Summary : Returns 1 (bit) when deletion of the record is allowed
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pIsDeleteEnabledFcnGen | Designer: Tim Edlund
Version : May 2018
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------

The function is called by the entity view to set a calculated bit column "IsDeleteEnabled". The column is typically bound to a
delete button on the UI.  The results of the function determine whether or not deletion should be allowed.  The function tests
one or more of the following factors: 1) whether the table contains a system code column in which case deletion is
not allowed, 2) the security granted to the logged in user, and, 3) the existence of child records.

When a child table is related through a foreign key with cascade delete, and all descendants of that table are also related with
cascade delete constraints, then the child table is not considered blocking and will not appear in the SELECT statement.

Table-specific logic can be added through tagged sections (pre and post check). An extended version of the function is not
supported.  Code implemented within code tags is part of the base product and applies to all client configurations.

Example
-------

select top (10)
   x.PersonEmailMessageSID
  ,sf.fPersonEmailMessage#IsDeleteEnabled(x.PersonEmailMessageSID) IsDeleteEnabled
from
  sf.PersonEmailMessage x
order by
  newid()

-------------------------------------------------------------------------------------------------------------------------------- */

begin

	declare
		 @isDeleteEnabled                 bit																	-- return value
		,@ON                              bit = cast(1 as bit)								-- constant to eliminate repetitive casting syntax
		,@OFF                             bit = cast(0 as bit)								-- constant to eliminate repetitive casting syntax
	
	set @isDeleteEnabled = @ON																							-- set return value to ON then check for blocking conditions
	
	--! <PreCheck>
	-- Tim Edlund | Apr 2015
	-- Email messages cannot be deleted once sent to any recipients of the parent. This blocks deletion
	-- once the email sending process has been initiated.  Note that deletion is allowed for queued
	-- messages by system administrators only.

	if exists
	(
		select
			1
		from
			sf.PersonEmailMessage pem
		where
			pem.PersonEmailMessageSID = @PersonEmailMessageSID and pem.SentTime is not null
		)
	begin
		set @isDeleteEnabled = @OFF
	end
	
	if @isDeleteEnabled = @ON
	begin

		if exists
		(
			select
				1
			from
				sf.PersonEmailMessage pem
			join
				sf.EmailMessage				em on pem.EmailMessageSID = em.EmailMessageSID and em.QueuedTime is not null												-- parent message is queued; must be SA to delete
			where
				pem.PersonEmailMessageSID = @PersonEmailMessageSID
			)
		begin
			set @isDeleteEnabled = sf.fIsSysAdmin()
		end
	end

	--! </PreCheck>
	
	--! <PostCheck>
	if @isDeleteEnabled = @ON																								-- block unless current user inserted the row or is an administrator
	begin
	
		if
		(
			select
				x.CreateUser
			from
				sf.PersonEmailMessage x
			where
				x.PersonEmailMessageSID = @PersonEmailMessageSID
			) <> sf.fApplicationUserSession#UserName() set @isDeleteEnabled = sf.fIsGranted('ADMIN.BASE')
	
	end
	--! </PostCheck>
	
	return(@isDeleteEnabled)
end

GO
