SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [sf].[fEmailMessage#IsDeleteEnabled]
	(
	@EmailMessageSID int
	)
returns bit
as
/*********************************************************************************************************************************
ScalarF : sf.fEmailMessage#IsDeleteEnabled
Notice  : Copyright © 2018 Softworks Group Inc.
Summary : Returns 1 (bit) when deletion of the record is allowed
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pIsDeleteEnabledFcnGen | Designer: Tim Edlund
Version : May 2018
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------

The function is called by the entity view to set a calculated bit column "IsDeleteEnabled". The column is typically bound to a
delete button on the UI.  The results of the function determine whether or not deletion should be allowed.  The function tests
one or more of the following factors: 1) whether the table contains a system code column in which case deletion is
not allowed, 2) the security granted to the logged in user, and, 3) the existence of child records.

When a child table is related through a foreign key with cascade delete, and all descendants of that table are also related with
cascade delete constraints, then the child table is not considered blocking and will not appear in the SELECT statement.

Table-specific logic can be added through tagged sections (pre and post check). An extended version of the function is not
supported.  Code implemented within code tags is part of the base product and applies to all client configurations.

Example
-------

select top (10)
   x.EmailMessageSID
  ,sf.fEmailMessage#IsDeleteEnabled(x.EmailMessageSID) IsDeleteEnabled
from
  sf.EmailMessage x
order by
  newid()

-------------------------------------------------------------------------------------------------------------------------------- */

begin

	declare
		 @isDeleteEnabled                 bit																	-- return value
		,@ON                              bit = cast(1 as bit)								-- constant to eliminate repetitive casting syntax
		,@OFF                             bit = cast(0 as bit)								-- constant to eliminate repetitive casting syntax
	
	set @isDeleteEnabled = @ON																							-- set return value to ON then check for blocking conditions
	
	--! <PreCheck>
	-- Tim Edlund | Mar 2017
	-- Disable deletion unless its a draft or is archived.

	if exists
	(
		select
			1
		from
			sf.EmailMessage em
		where
			em.EmailMessageSID = @EmailMessageSID
		and
		(
			em.QueuedTime is not null																						-- if queued or merged, it is NOT a draft
		or
		 em.MergedTime is not null
		)
		and						
		 em.ArchivedTime is null																							-- if archived, deletion IS allowed
	)
	begin
		 set @isDeleteEnabled = @OFF
	end
	--! </PreCheck>
	
	--! <PostCheck>
	if @isDeleteEnabled = @ON																								-- block unless current user inserted the row or is an administrator
	begin
	
		if
		(
			select
				x.CreateUser
			from
				sf.EmailMessage x
			where
				x.EmailMessageSID = @EmailMessageSID
			) <> sf.fApplicationUserSession#UserName() set @isDeleteEnabled = sf.fIsGranted('ADMIN.BASE')
	
	end
	--! </PostCheck>
	
	return(@isDeleteEnabled)
end

GO
