SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPersonMailingAddress#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vPersonMailingAddress#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.PersonMailingAddress base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vPersonMailingAddress (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 pma.PersonMailingAddressSID
	,city.CityName
	,city.StateProvinceSID
	,city.IsDefault                                                         CityIsDefault
	,city.IsActive                                                          CityIsActive
	,city.IsAdminReviewRequired                                             CityIsAdminReviewRequired
	,city.RowGUID                                                           CityRowGUID
	,region.RegionLabel
	,region.RegionName
	,region.IsDefault                                                       RegionIsDefault
	,region.IsActive                                                        RegionIsActive
	,region.RowGUID                                                         RegionRowGUID
	,person.GenderSID
	,person.NamePrefixSID
	,person.FirstName
	,person.CommonName
	,person.MiddleNames
	,person.LastName
	,person.BirthDate
	,person.DeathDate
	,person.HomePhone
	,person.MobilePhone
	,person.IsTextMessagingEnabled
	,person.ImportBatch
	,person.RowGUID                                                         PersonRowGUID
	,dbo.fPersonMailingAddress#IsDeleteEnabled(pma.PersonMailingAddressSID) IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
 --! <MoreColumns>
 ,sf.fFormatAddressForHTML(
														isnull(person.CommonName, person.FirstName) + ' ' + person.LastName
													 ,pma.StreetAddress1
													 ,pma.StreetAddress2
													 ,pma.StreetAddress3
													 ,city.CityName
													 ,(case
														when zsp.IsDisplayed = cast(0 as bit) then cast(null as nvarchar(30))  -- suppress province name if IsDisplayed bit not set
														when len(city.CityName + zsp.StateProvinceName) > 29 then zsp.StateProvinceCode
														else zsp.StateProvinceName
														end)
													 ,pma.PostalCode
													 ,(case when zctry.IsDefault = cast(1 as bit) then null else zctry.CountryName end)
													)																																												HtmlAddress
 ,zsp.StateProvinceCode
 ,zsp.StateProvinceName
 ,zctry.ISOA3
 ,zctry.CountryName
 ,cast(case when isnull(zpmac.PersonMailingAddressSID, 0) = pma.PersonMailingAddressSID then 1 else 0 end as bit) IsCurrentAddress
 ,zctry.CountrySID																																																CountrySID
--! </MoreColumns>
from
	dbo.PersonMailingAddress pma
join
	dbo.City                 city   on pma.CitySID = city.CitySID
join
	dbo.Region               region on pma.RegionSID = region.RegionSID
join
	sf.Person                person on pma.PersonSID = person.PersonSID
--! <MoreJoins>
join
	dbo.StateProvince																					 zsp on city.StateProvinceSID = zsp.StateProvinceSID
join
	dbo.Country																								 zctry on zsp.CountrySID = zctry.CountrySID
outer apply dbo.fPersonMailingAddress#Current(pma.PersonSID) zpmac;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person mailing address assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'PersonMailingAddressSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The state province this city is in', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'StateProvinceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default city to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CityIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this city record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CityIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CityIsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the city record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the region to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'RegionLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the region to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'RegionName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default region to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'RegionIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this region record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'RegionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the region record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'RegionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress#Ext', 'COLUMN', N'zContext'
GO
