SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vComplaintContact]
as
/*********************************************************************************************************************************
View    : dbo.vComplaintContact
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.ComplaintContact - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.ComplaintContact table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vComplaintContactExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vComplaintContactExt documentation for details. To add additional content to this view, customize
the dbo.vComplaintContactExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 cc.ComplaintContactSID
	,cc.ComplaintSID
	,cc.PersonSID
	,cc.ComplaintContactRoleSID
	,cc.EffectiveTime
	,cc.ExpiryTime
	,cc.UserDefinedColumns
	,cc.ComplaintContactXID
	,cc.LegacyKey
	,cc.IsDeleted
	,cc.CreateUser
	,cc.CreateTime
	,cc.UpdateUser
	,cc.UpdateTime
	,cc.RowGUID
	,cc.RowStamp
	,ccx.ComplaintNo
	,ccx.RegistrantSID
	,ccx.ComplaintTypeSID
	,ccx.ComplainantTypeSID
	,ccx.ApplicationUserSID
	,ccx.OpenedDate
	,ccx.ConductStartDate
	,ccx.ConductEndDate
	,ccx.ComplaintSeveritySID
	,ccx.IsDisplayedOnPublicRegistry
	,ccx.ClosedDate
	,ccx.DismissedDate
	,ccx.ReasonSID
	,ccx.FileExtension
	,ccx.ComplaintRowGUID
	,ccx.ComplaintContactRoleSCD
	,ccx.ComplaintContactRoleName
	,ccx.ComplaintContactRoleIsDefault
	,ccx.ComplaintContactRoleRowGUID
	,ccx.GenderSID
	,ccx.NamePrefixSID
	,ccx.FirstName
	,ccx.CommonName
	,ccx.MiddleNames
	,ccx.LastName
	,ccx.BirthDate
	,ccx.DeathDate
	,ccx.HomePhone
	,ccx.MobilePhone
	,ccx.IsTextMessagingEnabled
	,ccx.ImportBatch
	,ccx.PersonRowGUID
	,ccx.IsActive
	,ccx.IsPending
	,ccx.IsDeleteEnabled
	,ccx.IsReselected
	,ccx.IsNullApplied
	,ccx.zContext
from
	dbo.ComplaintContact      cc
join
	dbo.vComplaintContact#Ext ccx	on cc.ComplaintContactSID = ccx.ComplaintContactSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.ComplaintContact', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the complaint contact assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The complaint this contact is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this complaint contact is based on', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the complaint contact role assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactRoleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the person was assigned to the complaint case', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the person''s assignment to the case ended', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the complaint contact | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the complaint contact | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this complaint contact record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the complaint contact | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the complaint contact record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the complaint contact record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of complaint', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of complaint', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplainantTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this complaint', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the complaint was reported. | Normally the record entry date but provided to support back-dating when received through other channels', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'OpenedDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the reported conduct took place or the start of the period the reported conduct took place', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ConductStartDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the reported conduct took place or the end of the period the reported conduct took place', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ConductEndDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The complaint severity assigned to this complaint', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintSeveritySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the outcome text is displayed on the public directory', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsDisplayedOnPublicRegistry'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason assigned to this complaint', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ReasonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A value required by the system to perform full-text indexing on the HTML formatted content in the record (do not expose in user interface).', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'FileExtension'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the complaint record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the complaint contact role | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactRoleSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the complaint contact role to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactRoleName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default complaint contact role to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactRoleIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the complaint contact role record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ComplaintContactRoleRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment is currently active (not expired or future dated)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment will come into effect in the future', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsPending'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vComplaintContact', 'COLUMN', N'zContext'
GO
