SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrationProfile]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrationProfile
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.RegistrationProfile - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.RegistrationProfile table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vRegistrationProfileExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vRegistrationProfileExt documentation for details. To add additional content to this view, customize
the dbo.vRegistrationProfileExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rp.RegistrationProfileSID
	,rp.RegistrationSnapshotSID
	,rp.JursidictionStateProvinceISONumber
	,rp.RegistrantSID
	,rp.RegistrantNo
	,rp.GenderSCD
	,rp.BirthDate
	,rp.PersonMailingAddressSID
	,rp.ResidenceStateProvinceISONumber
	,rp.ResidencePostalCode
	,rp.ResidenceCountryISONumber
	,rp.ResidenceIsDefaultCountry
	,rp.RegistrationSID
	,rp.IsActivePractice
	,rp.Education1RegistrantCredentialSID
	,rp.Education1CredentialCode
	,rp.Education1GraduationYear
	,rp.Education1StateProvinceISONumber
	,rp.Education1CountryISONumber
	,rp.Education1IsDefaultCountry
	,rp.Education2RegistrantCredentialSID
	,rp.Education2CredentialCode
	,rp.Education2GraduationYear
	,rp.Education2StateProvinceISONumber
	,rp.Education2CountryISONumber
	,rp.Education2IsDefaultCountry
	,rp.Education3RegistrantCredentialSID
	,rp.Education3CredentialCode
	,rp.Education3GraduationYear
	,rp.Education3StateProvinceISONumber
	,rp.Education3CountryISONumber
	,rp.Education3IsDefaultCountry
	,rp.RegistrantPracticeSID
	,rp.EmploymentStatusCode
	,rp.EmploymentCount
	,rp.PracticeHours
	,rp.Employment1RegistrantEmploymentSID
	,rp.Employment1TypeCode
	,rp.Employment1StateProvinceISONumber
	,rp.Employment1CountryISONumber
	,rp.Employment1IsDefaultCountry
	,rp.Employment1PostalCode
	,rp.Employment1OrgTypeCode
	,rp.Employment1PracticeAreaCode
	,rp.Employment1PracticeScopeCode
	,rp.Employment1RoleCode
	,rp.Employment2RegistrantEmploymentSID
	,rp.Employment2TypeCode
	,rp.Employment2StateProvinceISONumber
	,rp.Employment2IsDefaultCountry
	,rp.Employment2CountryISONumber
	,rp.Employment2PostalCode
	,rp.Employment2OrgTypeCode
	,rp.Employment2PracticeAreaCode
	,rp.Employment2PracticeScopeCode
	,rp.Employment2RoleCode
	,rp.Employment3RegistrantEmploymentSID
	,rp.Employment3TypeCode
	,rp.Employment3StateProvinceISONumber
	,rp.Employment3CountryISONumber
	,rp.Employment3IsDefaultCountry
	,rp.Employment3PostalCode
	,rp.Employment3OrgTypeCode
	,rp.Employment3PracticeAreaCode
	,rp.Employment3PracticeScopeCode
	,rp.Employment3RoleCode
	,rp.IsInvalid
	,rp.MessageText
	,rp.CheckSumOnLastExport
	,rp.UserDefinedColumns
	,rp.RegistrationProfileXID
	,rp.LegacyKey
	,rp.IsDeleted
	,rp.CreateUser
	,rp.CreateTime
	,rp.UpdateUser
	,rp.UpdateTime
	,rp.RowGUID
	,rp.RowStamp
	,rpx.RegistrantPersonSID
	,rpx.RegistrantRegistrantNo
	,rpx.YearOfInitialEmployment
	,rpx.RegistrantIsOnPublicRegistry
	,rpx.CityNameOfBirth
	,rpx.CountrySID
	,rpx.DirectedAuditYearCompetence
	,rpx.DirectedAuditYearPracticeHours
	,rpx.LateFeeExclusionYear
	,rpx.IsRenewalAutoApprovalBlocked
	,rpx.RenewalExtensionExpiryTime
	,rpx.ArchivedTime
	,rpx.RegistrantRowGUID
	,rpx.RegistrationRegistrantSID
	,rpx.PracticeRegisterSectionSID
	,rpx.RegistrationNo
	,rpx.RegistrationRegistrationYear
	,rpx.RegistrationEffectiveTime
	,rpx.RegistrationExpiryTime
	,rpx.CardPrintedTime
	,rpx.InvoiceSID
	,rpx.ReasonSID
	,rpx.FormGUID
	,rpx.RegistrationRowGUID
	,rpx.RegistrationSnapshotTypeSID
	,rpx.RegistrationSnapshotLabel
	,rpx.RegistrationSnapshotRegistrationYear
	,rpx.QueuedTime
	,rpx.LockedTime
	,rpx.LastCodeUpdateTime
	,rpx.RegistrationSnapshotLastVerifiedTime
	,rpx.JobRunSID
	,rpx.RegistrationSnapshotRowGUID
	,rpx.PersonMailingAddressPersonSID
	,rpx.StreetAddress1
	,rpx.StreetAddress2
	,rpx.StreetAddress3
	,rpx.CitySID
	,rpx.PostalCode
	,rpx.RegionSID
	,rpx.PersonMailingAddressEffectiveTime
	,rpx.IsAdminReviewRequired
	,rpx.PersonMailingAddressLastVerifiedTime
	,rpx.PersonMailingAddressRowGUID
	,rpx.RegistrantCredentialEducation1RegistrantSID
	,rpx.RegistrantCredentialEducation1CredentialSID
	,rpx.RegistrantCredentialEducation1OrgSID
	,rpx.RegistrantCredentialEducation1ProgramName
	,rpx.RegistrantCredentialEducation1ProgramStartDate
	,rpx.RegistrantCredentialEducation1ProgramTargetCompletionDate
	,rpx.RegistrantCredentialEducation1EffectiveTime
	,rpx.RegistrantCredentialEducation1ExpiryTime
	,rpx.RegistrantCredentialEducation1FieldOfStudySID
	,rpx.RegistrantCredentialEducation1RowGUID
	,rpx.RegistrantCredentialEducation2RegistrantSID
	,rpx.RegistrantCredentialEducation2CredentialSID
	,rpx.RegistrantCredentialEducation2OrgSID
	,rpx.RegistrantCredentialEducation2ProgramName
	,rpx.RegistrantCredentialEducation2ProgramStartDate
	,rpx.RegistrantCredentialEducation2ProgramTargetCompletionDate
	,rpx.RegistrantCredentialEducation2EffectiveTime
	,rpx.RegistrantCredentialEducation2ExpiryTime
	,rpx.RegistrantCredentialEducation2FieldOfStudySID
	,rpx.RegistrantCredentialEducation2RowGUID
	,rpx.RegistrantCredentialEducation3RegistrantSID
	,rpx.RegistrantCredentialEducation3CredentialSID
	,rpx.RegistrantCredentialEducation3OrgSID
	,rpx.RegistrantCredentialEducation3ProgramName
	,rpx.RegistrantCredentialEducation3ProgramStartDate
	,rpx.RegistrantCredentialEducation3ProgramTargetCompletionDate
	,rpx.RegistrantCredentialEducation3EffectiveTime
	,rpx.RegistrantCredentialEducation3ExpiryTime
	,rpx.RegistrantCredentialEducation3FieldOfStudySID
	,rpx.RegistrantCredentialEducation3RowGUID
	,rpx.RegistrantEmploymentEmployment1RegistrantSID
	,rpx.RegistrantEmploymentEmployment1OrgSID
	,rpx.RegistrantEmploymentEmployment1RegistrationYear
	,rpx.RegistrantEmploymentEmployment1EmploymentTypeSID
	,rpx.RegistrantEmploymentEmployment1EmploymentRoleSID
	,rpx.RegistrantEmploymentEmployment1PracticeHours
	,rpx.RegistrantEmploymentEmployment1PracticeScopeSID
	,rpx.RegistrantEmploymentEmployment1AgeRangeSID
	,rpx.RegistrantEmploymentEmployment1IsOnPublicRegistry
	,rpx.RegistrantEmploymentEmployment1Phone
	,rpx.RegistrantEmploymentEmployment1SiteLocation
	,rpx.RegistrantEmploymentEmployment1EffectiveTime
	,rpx.RegistrantEmploymentEmployment1ExpiryTime
	,rpx.RegistrantEmploymentEmployment1Rank
	,rpx.RegistrantEmploymentEmployment1OwnershipPercentage
	,rpx.RegistrantEmploymentEmployment1IsEmployerInsurance
	,rpx.RegistrantEmploymentEmployment1InsuranceOrgSID
	,rpx.RegistrantEmploymentEmployment1InsurancePolicyNo
	,rpx.RegistrantEmploymentEmployment1InsuranceAmount
	,rpx.RegistrantEmploymentEmployment1RowGUID
	,rpx.RegistrantEmploymentEmployment2RegistrantSID
	,rpx.RegistrantEmploymentEmployment2OrgSID
	,rpx.RegistrantEmploymentEmployment2RegistrationYear
	,rpx.RegistrantEmploymentEmployment2EmploymentTypeSID
	,rpx.RegistrantEmploymentEmployment2EmploymentRoleSID
	,rpx.RegistrantEmploymentEmployment2PracticeHours
	,rpx.RegistrantEmploymentEmployment2PracticeScopeSID
	,rpx.RegistrantEmploymentEmployment2AgeRangeSID
	,rpx.RegistrantEmploymentEmployment2IsOnPublicRegistry
	,rpx.RegistrantEmploymentEmployment2Phone
	,rpx.RegistrantEmploymentEmployment2SiteLocation
	,rpx.RegistrantEmploymentEmployment2EffectiveTime
	,rpx.RegistrantEmploymentEmployment2ExpiryTime
	,rpx.RegistrantEmploymentEmployment2Rank
	,rpx.RegistrantEmploymentEmployment2OwnershipPercentage
	,rpx.RegistrantEmploymentEmployment2IsEmployerInsurance
	,rpx.RegistrantEmploymentEmployment2InsuranceOrgSID
	,rpx.RegistrantEmploymentEmployment2InsurancePolicyNo
	,rpx.RegistrantEmploymentEmployment2InsuranceAmount
	,rpx.RegistrantEmploymentEmployment2RowGUID
	,rpx.RegistrantEmploymentEmployment3RegistrantSID
	,rpx.RegistrantEmploymentEmployment3OrgSID
	,rpx.RegistrantEmploymentEmployment3RegistrationYear
	,rpx.RegistrantEmploymentEmployment3EmploymentTypeSID
	,rpx.RegistrantEmploymentEmployment3EmploymentRoleSID
	,rpx.RegistrantEmploymentEmployment3PracticeHours
	,rpx.RegistrantEmploymentEmployment3PracticeScopeSID
	,rpx.RegistrantEmploymentEmployment3AgeRangeSID
	,rpx.RegistrantEmploymentEmployment3IsOnPublicRegistry
	,rpx.RegistrantEmploymentEmployment3Phone
	,rpx.RegistrantEmploymentEmployment3SiteLocation
	,rpx.RegistrantEmploymentEmployment3EffectiveTime
	,rpx.RegistrantEmploymentEmployment3ExpiryTime
	,rpx.RegistrantEmploymentEmployment3Rank
	,rpx.RegistrantEmploymentEmployment3OwnershipPercentage
	,rpx.RegistrantEmploymentEmployment3IsEmployerInsurance
	,rpx.RegistrantEmploymentEmployment3InsuranceOrgSID
	,rpx.RegistrantEmploymentEmployment3InsurancePolicyNo
	,rpx.RegistrantEmploymentEmployment3InsuranceAmount
	,rpx.RegistrantEmploymentEmployment3RowGUID
	,rpx.RegistrantPracticeRegistrantSID
	,rpx.RegistrantPracticeRegistrationYear
	,rpx.EmploymentStatusSID
	,rpx.PlannedRetirementDate
	,rpx.OtherJurisdiction
	,rpx.OtherJurisdictionHours
	,rpx.TotalPracticeHours
	,rpx.RegistrantPracticeOrgSID
	,rpx.RegistrantPracticeInsurancePolicyNo
	,rpx.RegistrantPracticeInsuranceAmount
	,rpx.InsuranceCertificateNo
	,rpx.RegistrantPracticeRowGUID
	,rpx.IsDeleteEnabled
	,rpx.IsReselected
	,rpx.IsNullApplied
	,rpx.zContext
	,rpx.RegistrantLabel
	,rpx.FirstName
	,rpx.CommonName
	,rpx.MiddleNames
	,rpx.LastName
	,rpx.DeathDate
	,rpx.HomePhone
	,rpx.MobilePhone
	,rpx.IsValid
	,rpx.CIHIGenderCD
	,rpx.CIHIBirthYear
	,rpx.CIHIEducation1CredentialCode
	,rpx.CIHIEducation1GraduationYear
	,rpx.CIHIEducation1Location
	,rpx.CIHIEducation2CredentialCode
	,rpx.CIHIEducation3CredentialCode
	,rpx.CIHIEmploymentStatusCode
	,rpx.CIHIEmployment1TypeCode
	,rpx.CIHIMultipleEmploymentStatus
	,rpx.CIHIEmployment1Location
	,rpx.CIHIEmployment1OrgTypeCode
	,rpx.CIHIEmployment1PracticeAreaCode
	,rpx.CIHIEmployment1PracticeScopeCode
	,rpx.CIHIEmployment1RoleCode
	,rpx.CIHIResidenceLocation
	,rpx.CIHIResidencePostalCode
	,rpx.CIHIEmployment1PostalCode
	,rpx.CIHIRegistrationYearMonth
	,rpx.CIHIEmployment2PostalCode
	,rpx.CIHIEmployment2Location
	,rpx.CIHIEmployment2OrgTypeCode
	,rpx.CIHIEmployment2PracticeAreaCode
	,rpx.CIHIEmployment2PracticeScopeCode
	,rpx.CIHIEmployment2RoleCode
	,rpx.CIHIEmployment3PostalCode
	,rpx.CIHIEmployment3Location
	,rpx.CIHIEmployment3OrgTypeCode
	,rpx.CIHIEmployment3PracticeAreaCode
	,rpx.CIHIEmployment3PracticeScopeCode
	,rpx.CIHIEmployment3RoleCode
	,rpx.CurrentCheckSum
	,rpx.IsModified
from
	dbo.RegistrationProfile      rp
join
	dbo.vRegistrationProfile#Ext rpx	on rp.RegistrationProfileSID = rpx.RegistrationProfileSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.RegistrationProfile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration profile assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationProfileSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration snapshot assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSnapshotSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person mailing address assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PersonMailingAddressSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant credential assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Education1RegistrantCredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant credential assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Education2RegistrantCredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant credential assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Education3RegistrantCredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant practice assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantPracticeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total hours reported for the year', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PracticeHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant employment assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Employment1RegistrantEmploymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant employment assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Employment2RegistrantEmploymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant employment assigned to this registration profile', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'Employment3RegistrantEmploymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the record has been marked invalid by the receving 3rd party (see Message Text)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsInvalid'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A message from a 3rd party receiver of the record about its status or errors detected', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'MessageText'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The value of the record''s checksum on the last export (used to determine if record has been modified)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CheckSumOnLastExport'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the registration profile | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationProfileXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the registration profile | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this registration profile record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the registration profile | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the registration profile record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration profile record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantPersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The year of initial employment in the profession if required for reporting and full history of employment was not converted', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'YearOfInitialEmployment'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CityNameOfBirth'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The country assigned to this registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CountrySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of continuing competence/education claims (non-random, direct audit inclusion)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'DirectedAuditYearCompetence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of practice hours (non-random, direct audit inclusion)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'DirectedAuditYearPracticeHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When filled out ensures the member will not be assessed late fees for the registration year selected (limited to one year)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'LateFeeExclusionYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates automatic approval of this form type is disabled for the registrant.  Administrator review and approval is required.  This setting is only required where rules in the form would not otherwise block automatic approval. (e.g. the form may block auto-approval if a criminal record is reported or other non-qualifying details.) The setting is relevant only where automatic approval is configured for the form type.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsRenewalAutoApprovalBlocked'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a date to extend the renewal period for this specific registrant to the end of the day entered.  | The later of this value and the standard schedule is applied. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RenewalExtensionExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationRegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice register section assigned to this registration', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PracticeRegisterSectionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A combination of the Registrant No + Registration Year + Registration Sequence - e.g. 12345.2019.1 for the registrant 12345''s first registration of 2019.  This format is set by the application and cannot be modified. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationNo'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when a card was printed (if the College prints cards for this Registration type)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CardPrintedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the invoice assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'InvoiceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason assigned to this registration', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'ReasonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The identifier for the member form (renewal, reinstatement) this registration resulted from if any | This value is blank if the registration was the result of an Administrator entered change since no member form is involved', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'FormGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration snapshot type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSnapshotTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration snapshot to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSnapshotLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the generation of this snapshot should begin ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'QueuedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the snapshot is marked as locked which disallows further editing. A system-administrator can unlock.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'LockedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the code update process was last run on this snapshot.  Blank when pending (in process).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'LastCodeUpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the verification process was last run on this snapshot.  Blank when pending (in process).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSnapshotLastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the job run assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'JobRunSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration snapshot record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrationSnapshotRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PersonMailingAddressPersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this person mailing address is in', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this person mailing address', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new address through a profile update or renewal entered online).  The form can be configured to block automatic approval when addresses change in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PersonMailingAddressLastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person mailing address record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'PersonMailingAddressRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The credential assigned to this registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1CredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this restriction/condition was put into effect or most recently changed | Check Change Audit column for history', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1ProgramStartDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending time this restriction/condition was effective.  When blank indicates restriction remains in effect. | See Change Audit for history of restriction being turned on/off', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1ProgramTargetCompletionDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The starting date this specialization or credential was effective', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending date the specialization or credential was effective.  When blank indicates the specialization remains in effect. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The field of study assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1FieldOfStudySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant credential record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation1RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The credential assigned to this registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2CredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this restriction/condition was put into effect or most recently changed | Check Change Audit column for history', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2ProgramStartDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending time this restriction/condition was effective.  When blank indicates restriction remains in effect. | See Change Audit for history of restriction being turned on/off', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2ProgramTargetCompletionDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The starting date this specialization or credential was effective', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending date the specialization or credential was effective.  When blank indicates the specialization remains in effect. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The field of study assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2FieldOfStudySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant credential record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation2RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The credential assigned to this registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3CredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this restriction/condition was put into effect or most recently changed | Check Change Audit column for history', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3ProgramStartDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending time this restriction/condition was effective.  When blank indicates restriction remains in effect. | See Change Audit for history of restriction being turned on/off', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3ProgramTargetCompletionDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The starting date this specialization or credential was effective', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending date the specialization or credential was effective.  When blank indicates the specialization remains in effect. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The field of study assigned to this registrant credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3FieldOfStudySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant credential record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantCredentialEducation3RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this employment is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1EmploymentTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1EmploymentRoleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice scope assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1PracticeScopeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the Age Range assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1AgeRangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this employer should be included in employers listed for the registrant on the public directly. The default setting is on, however, if the public registry configuration does not include employment, this setting has no impact.  Where employment is included in the public registry, this value should be included in the Profile Update form so that registrants can turn on/off the employers which display during the year as their employment changes.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1IsOnPublicRegistry'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A phone number for this individual at their place of employment (do not enter mobile phone numbers here)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A location of employment within the organization facility (optional)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1SiteLocation'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the employment started if precision beyond registration year is required ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when employment ended (blank if employment is still ongoing or expiry is unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Where no hours have been reported for the employer, a ranking value used to set primary, secondary, etc. employer position.  ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1Rank'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When non-zero indicates member is self-employed. When value is > 0, then a specific share-percentage of ownership is specified. | Note that the value "-1"  is used to indicate a member is self-employed but ownership is unknown or not specified.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1OwnershipPercentage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant employment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment1RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this employment is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2EmploymentTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2EmploymentRoleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice scope assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2PracticeScopeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the Age Range assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2AgeRangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this employer should be included in employers listed for the registrant on the public directly. The default setting is on, however, if the public registry configuration does not include employment, this setting has no impact.  Where employment is included in the public registry, this value should be included in the Profile Update form so that registrants can turn on/off the employers which display during the year as their employment changes.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2IsOnPublicRegistry'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A phone number for this individual at their place of employment (do not enter mobile phone numbers here)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A location of employment within the organization facility (optional)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2SiteLocation'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the employment started if precision beyond registration year is required ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when employment ended (blank if employment is still ongoing or expiry is unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Where no hours have been reported for the employer, a ranking value used to set primary, secondary, etc. employer position.  ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2Rank'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When non-zero indicates member is self-employed. When value is > 0, then a specific share-percentage of ownership is specified. | Note that the value "-1"  is used to indicate a member is self-employed but ownership is unknown or not specified.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2OwnershipPercentage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant employment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment2RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this employment is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3EmploymentTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3EmploymentRoleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice scope assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3PracticeScopeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the Age Range assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3AgeRangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this employer should be included in employers listed for the registrant on the public directly. The default setting is on, however, if the public registry configuration does not include employment, this setting has no impact.  Where employment is included in the public registry, this value should be included in the Profile Update form so that registrants can turn on/off the employers which display during the year as their employment changes.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3IsOnPublicRegistry'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A phone number for this individual at their place of employment (do not enter mobile phone numbers here)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A location of employment within the organization facility (optional)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3SiteLocation'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the employment started if precision beyond registration year is required ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when employment ended (blank if employment is still ongoing or expiry is unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Where no hours have been reported for the employer, a ranking value used to set primary, secondary, etc. employer position.  ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3Rank'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When non-zero indicates member is self-employed. When value is > 0, then a specific share-percentage of ownership is specified. | Note that the value "-1"  is used to indicate a member is self-employed but ownership is unknown or not specified.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3OwnershipPercentage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant employment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantEmploymentEmployment3RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this practice is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantPracticeRegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The status of the registrant practice', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'EmploymentStatusSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When reporting hours from another jurisdiction, the name of the jurisdiction or employer can be collected here.  For many configurations only the total hours is recorded.  ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'OtherJurisdiction'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Records the number of hours worked outside of the jurisdiction when reporting of such hours is required in the configuration. Only total hours are captured and employers are generally not specified, however, a field for capturing the jurisdiction name and/or employer is provided but not validated against a master list.  Note that these hours are typically not qualifying for a minimum hours requirement if one exists for the registration/registration.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'OtherJurisdictionHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total practice hours in the year when hours by employer cannot be reported | When this value is 0 hours are determined by adding up employment hours', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'TotalPracticeHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant practice', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantPracticeOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional certificate number provided to the member where a common policy is provided by the insurer', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'InsuranceCertificateNo'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant practice record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantPracticeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'RegistrantLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationProfile', 'COLUMN', N'LastName'
GO
