SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPAPBatch]
as
/*********************************************************************************************************************************
View    : dbo.vPAPBatch
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.PAPBatch - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.PAPBatch table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vPAPBatchExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vPAPBatchExt documentation for details. To add additional content to this view, customize
the dbo.vPAPBatchExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 papb.PAPBatchSID
	,papb.BatchID
	,papb.BatchSequence
	,papb.WithdrawalDate
	,papb.ExportFile
	,papb.LockedTime
	,papb.ProcessedTime
	,papb.UserDefinedColumns
	,papb.PAPBatchXID
	,papb.LegacyKey
	,papb.IsDeleted
	,papb.CreateUser
	,papb.CreateTime
	,papb.UpdateUser
	,papb.UpdateTime
	,papb.RowGUID
	,papb.RowStamp
	,papbx.IsDeleteEnabled
	,papbx.IsReselected
	,papbx.IsNullApplied
	,papbx.zContext
	,papbx.IsLocked
	,papbx.IsProcessed
	,papbx.TrxCount
	,papbx.RejectedTrxCount
	,papbx.TotalWithdrawalAmount
	,papbx.TotalPaid
	,papbx.TotalUnapplied
from
	dbo.PAPBatch      papb
join
	dbo.vPAPBatch#Ext papbx	on papb.PAPBatchSID = papbx.PAPBatchSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.PAPBatch', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the papbatch assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'PAPBatchSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A sequential number assigned when batch export is generated (required by some financial institutions)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'BatchSequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the batch is marked locked.  This is set automatically when the export file to the bank is generated but can be unlocked to regenerate the file.', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'LockedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the transactions are procssed into payment records.  After this time the batch can no longer be edited.', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'ProcessedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the papbatch | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'PAPBatchXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the papbatch | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this papbatch record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the papbatch | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the papbatch record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the papbatch record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the batch is currently in a locked status (set when export file is generated)', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsLocked'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the batch has been processed - editing not allowed after posting', 'SCHEMA', N'dbo', 'VIEW', N'vPAPBatch', 'COLUMN', N'IsProcessed'
GO
