SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vLearningPlanActivity#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vLearningPlanActivity#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.LearningPlanActivity base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vLearningPlanActivity (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 lpa.LearningPlanActivitySID
	,cta.CompetenceTypeSID
	,cta.CompetenceActivitySID
	,cta.EffectiveTime
	,cta.ExpiryTime
	,cta.RowGUID                                                            CompetenceTypeActivityRowGUID
	,lct.LearningClaimTypeLabel
	,lct.LearningClaimTypeCategory
	,lct.IsValidForRenewal
	,lct.IsComplete
	,lct.IsWithdrawn
	,lct.IsDefault                                                          LearningClaimTypeIsDefault
	,lct.IsActive                                                           LearningClaimTypeIsActive
	,lct.RowGUID                                                            LearningClaimTypeRowGUID
	,rlp.RegistrantSID
	,rlp.RegistrationYear
	,rlp.LearningModelSID
	,rlp.FormVersionSID
	,rlp.LastValidateTime
	,rlp.NextFollowUp
	,rlp.ReasonSID
	,rlp.IsAutoApprovalEnabled
	,rlp.ParentRowGUID
	,rlp.RowGUID                                                            RegistrantLearningPlanRowGUID
	,o.ParentOrgSID
	,o.OrgTypeSID
	,o.OrgName
	,o.OrgLabel
	,o.StreetAddress1
	,o.StreetAddress2
	,o.StreetAddress3
	,o.CitySID
	,o.PostalCode
	,o.RegionSID
	,o.Phone
	,o.Fax
	,o.WebSite
	,o.EmailAddress
	,o.InsuranceOrgSID
	,o.InsurancePolicyNo
	,o.InsuranceAmount
	,o.IsEmployer
	,o.IsCredentialAuthority
	,o.IsInsurer
	,o.IsInsuranceCertificateRequired
	,o.IsPublic
	,o.IsActive                                                             OrgIsActive
	,o.IsAdminReviewRequired
	,o.LastVerifiedTime
	,o.RowGUID                                                              OrgRowGUID
	,dbo.fLearningPlanActivity#IsDeleteEnabled(lpa.LearningPlanActivitySID) IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
  --! </MoreColumns>
from
	dbo.LearningPlanActivity   lpa
join
	dbo.CompetenceTypeActivity cta    on lpa.CompetenceTypeActivitySID = cta.CompetenceTypeActivitySID
join
	dbo.LearningClaimType      lct    on lpa.LearningClaimTypeSID = lct.LearningClaimTypeSID
join
	dbo.RegistrantLearningPlan rlp    on lpa.RegistrantLearningPlanSID = rlp.RegistrantLearningPlanSID
left outer join
	dbo.Org                    o      on lpa.OrgSID = o.OrgSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the learning plan activity assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningPlanActivitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the competence type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'CompetenceTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The competence activity assigned to this competence type activity', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'CompetenceActivitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this restriction/condition was put into effect or most recently changed | Check Change Audit column for history', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last day this Competence can be selected for learning plans and renewal reporting (only applies when Competence Type is "Active")', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the competence type activity record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'CompetenceTypeActivityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the learning claim type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningClaimTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningClaimTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When not checked, this item is only valid during planning and not for claiming at renewal time (e.g. "Unknown")', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsValidForRenewal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the learning activity is to be considered complete and included in the total credits/hours for the learning cycle', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsComplete'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the learning plan activity has been removed (equivalent to deleted)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsWithdrawn'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default learning claim type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningClaimTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this learning claim type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningClaimTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the learning claim type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningClaimTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this learning plan is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The learning model assigned to this registrant learning plan', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LearningModelSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the form version assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'FormVersionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the form content successfully passed validations', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LastValidateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date when the next follow-up is required on the form.  Leave blank if no follow-up required.  When this date is reached the record appears on the Administrators list for "next-to-act".', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'NextFollowUp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason assigned to this registrant learning plan', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'ReasonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This value is set by customized rules in the form configuration to enable automatic approval of the form when required conditions have been met.  If all forms should be reviewed by adminsitrators, then the value is left turned off by the form. Note that the condition of making payment (e.g. to pay for the form if charges apply) is automatically taken into account and need not be addressed in the form configuration. It is possible to block automatic approval on any registrant through their profile.  That setting overrides the setting recorded here by rules in the form.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsAutoApprovalEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The unique identifier of the parent form (typically a renewal or reinstatement) the Learning Plan is connected to.  | Null (blank) if this learning plan form is not part of a form-set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'ParentRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant learning plan record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'RegistrantLearningPlanRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningPlanActivity#Ext', 'COLUMN', N'zContext'
GO
