SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vCatalogItemPrice#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vCatalogItemPrice#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.CatalogItemPrice base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vCatalogItemPrice (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 cip.CatalogItemPriceSID
	,ci.CatalogItemLabel
	,ci.InvoiceItemDescription
	,ci.IsLateFee
	,ci.ImageAlternateText
	,ci.IsAvailableOnClientPortal
	,ci.IsComplaintPenalty
	,ci.GLAccountSID
	,ci.IsTaxRate1Applied
	,ci.IsTaxRate2Applied
	,ci.IsTaxRate3Applied
	,ci.IsTaxDeductible
	,ci.EffectiveTime                                                       CatalogItemEffectiveTime
	,ci.ExpiryTime
	,ci.FileTypeSCD
	,ci.FileTypeSID
	,ci.RowGUID                                                             CatalogItemRowGUID
	,dbo.fCatalogItemPrice#IsDeleteEnabled(cip.CatalogItemPriceSID)         IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
	,zcp.CatalogItemPriceProrationSID
	,zcp.Price CurrentPrice
	,zcp.IsProrated
  --! </MoreColumns>
from
	dbo.CatalogItemPrice cip
join
	dbo.CatalogItem      ci     on cip.CatalogItemSID = ci.CatalogItemSID
--! <MoreJoins>
cross apply
	dbo.fCatalogItem#CurrentPrice(cip.CatalogItemSID, null) zcp
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the catalog item price assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'CatalogItemPriceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the catalog item to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'CatalogItemLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A description of the item to include on the invoice line', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'InvoiceItemDescription'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this is a late fee (applies to renewals only) - the effective date for which is defined on the practice register', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsLateFee'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Text to display instead of the image if image display is turned off on the client browser', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'ImageAlternateText'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is available for selection by members on the website (otherwise it is available to administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsAvailableOnClientPortal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this catalog item should appear in the list of penalties/fines displayed for recording complaint outcomes', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsComplaintPenalty'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The glaccount assigned to this catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'GLAccountSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if GST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsTaxRate1Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if PST/HST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsTaxRate2Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if [Tax Type #3] should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsTaxRate3Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is considered tax deductible (includes the item on tax receipts)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsTaxDeductible'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item becomes available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'CatalogItemEffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item is no longer available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document the email is stored as | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".PDF" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'FileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'FileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the catalog item record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'CatalogItemRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCatalogItemPrice#Ext', 'COLUMN', N'zContext'
GO
