SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPracticeRegisterCatalogItem]
as
/*********************************************************************************************************************************
View    : dbo.vPracticeRegisterCatalogItem
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.PracticeRegisterCatalogItem - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.PracticeRegisterCatalogItem table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vPracticeRegisterCatalogItemExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vPracticeRegisterCatalogItemExt documentation for details. To add additional content to this view, customize
the dbo.vPracticeRegisterCatalogItemExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 prci.PracticeRegisterCatalogItemSID
	,prci.PracticeRegisterSID
	,prci.CatalogItemSID
	,prci.IsAppliedOnApplication
	,prci.IsAppliedOnApplicationApproval
	,prci.IsAppliedOnRenewal
	,prci.IsAppliedOnReinstatement
	,prci.IsAppliedOnRegChange
	,prci.IsAppliedToPAPSubscribers
	,prci.PracticeRegisterSectionSID
	,prci.PracticeRegisterChangeSID
	,prci.FeeSequence
	,prci.EffectiveTime
	,prci.ExpiryTime
	,prci.UserDefinedColumns
	,prci.PracticeRegisterCatalogItemXID
	,prci.LegacyKey
	,prci.IsDeleted
	,prci.CreateUser
	,prci.CreateTime
	,prci.UpdateUser
	,prci.UpdateTime
	,prci.RowGUID
	,prci.RowStamp
	,prcix.CatalogItemLabel
	,prcix.InvoiceItemDescription
	,prcix.IsLateFee
	,prcix.ImageAlternateText
	,prcix.IsAvailableOnClientPortal
	,prcix.IsComplaintPenalty
	,prcix.GLAccountSID
	,prcix.IsTaxRate1Applied
	,prcix.IsTaxRate2Applied
	,prcix.IsTaxRate3Applied
	,prcix.IsTaxDeductible
	,prcix.CatalogItemEffectiveTime
	,prcix.CatalogItemExpiryTime
	,prcix.FileTypeSCD
	,prcix.FileTypeSID
	,prcix.CatalogItemRowGUID
	,prcix.PracticeRegisterTypeSID
	,prcix.RegistrationScheduleSID
	,prcix.PracticeRegisterName
	,prcix.PracticeRegisterLabel
	,prcix.IsActivePractice
	,prcix.IsPublicRegistryEnabled
	,prcix.IsRenewalEnabled
	,prcix.IsLearningPlanEnabled
	,prcix.IsNextCEFormAutoAdded
	,prcix.IsEligibleSupervisor
	,prcix.IsSupervisionRequired
	,prcix.IsEmploymentTerminated
	,prcix.IsGroupMembershipTerminated
	,prcix.TermPermitDays
	,prcix.RegisterRank
	,prcix.LearningModelSID
	,prcix.ReasonGroupSID
	,prcix.PracticeRegisterIsDefault
	,prcix.IsDefaultInactivePractice
	,prcix.PracticeRegisterIsActive
	,prcix.PracticeRegisterRowGUID
	,prcix.PracticeRegisterChangePracticeRegisterSID
	,prcix.PracticeRegisterChangePracticeRegisterSectionSID
	,prcix.PracticeRegisterChangeIsActive
	,prcix.ToolTip
	,prcix.IsEnabledForRegistrant
	,prcix.PracticeRegisterChangeRowGUID
	,prcix.PracticeRegisterSectionPracticeRegisterSID
	,prcix.PracticeRegisterSectionLabel
	,prcix.PracticeRegisterSectionIsDefault
	,prcix.IsDisplayedOnLicense
	,prcix.PracticeRegisterSectionIsActive
	,prcix.PracticeRegisterSectionRowGUID
	,prcix.IsActive
	,prcix.IsPending
	,prcix.IsDeleteEnabled
	,prcix.IsReselected
	,prcix.IsNullApplied
	,prcix.zContext
from
	dbo.PracticeRegisterCatalogItem      prci
join
	dbo.vPracticeRegisterCatalogItem#Ext prcix	on prci.PracticeRegisterCatalogItemSID = prcix.PracticeRegisterCatalogItemSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.PracticeRegisterCatalogItem', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register catalog item assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterCatalogItemSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice register this catalog item is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The catalog item assigned to this practice register', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CatalogItemSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies when an application is first initiated (separate fee(s) must be configured for application approval)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedOnApplication'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies when then application is approved ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedOnApplicationApproval'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies for renewal invoices (disabled if this register does not allow renewals)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedOnRenewal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies for reinstatement transactions (disabled if this register does not allow reinstatements)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedOnReinstatement'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies for registration change. The amount can be refined through proration and deducting prior fees paid in the same registration year.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedOnRegChange'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this fee applies only to Pre-Authorized Payment subscribers (this is typically used for an Admin Fee charged to PAP subsribers at Renewal time).', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAppliedToPAPSubscribers'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register section assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register change assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterChangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A value to control the display order of fees on the invoice.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'FeeSequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item becomes available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item is no longer available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the practice register catalog item | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterCatalogItemXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the practice register catalog item | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this practice register catalog item record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the practice register catalog item | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the practice register catalog item record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register catalog item record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the catalog item to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CatalogItemLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A description of the item to include on the invoice line', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'InvoiceItemDescription'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this is a late fee (applies to renewals only) - the effective date for which is defined on the practice register', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsLateFee'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Text to display instead of the image if image display is turned off on the client browser', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'ImageAlternateText'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is available for selection by members on the website (otherwise it is available to administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsAvailableOnClientPortal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this catalog item should appear in the list of penalties/fines displayed for recording complaint outcomes', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsComplaintPenalty'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The glaccount assigned to this catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'GLAccountSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if GST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsTaxRate1Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if PST/HST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsTaxRate2Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if [Tax Type #3] should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsTaxRate3Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is considered tax deductible (includes the item on tax receipts)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsTaxDeductible'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item becomes available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CatalogItemEffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item is no longer available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CatalogItemExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document the email is stored as | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".PDF" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'FileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'FileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the catalog item record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'CatalogItemRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of practice register', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration schedule assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'RegistrationScheduleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the practice register to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the practice register to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates people on this register are authorized for active practice - if not checked, then the register is for non-practicing members which may include retired, maternity leave, students, etc. and competence requirements do not apply', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsActivePractice'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates people included on this register will appear on the College''s public website unless they have opted out individually.  Note that this value is automatically disabled for in-active practice registers.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsPublicRegistryEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the renewal process is enabled for this register.  This value will generally be on except for some types of permits which cannot renew.  ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsRenewalEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether a CE/Learning plan should be enabled for members on this register  | This value must be checked for active-practice registers', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsLearningPlanEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether a Learning Plan/CE form should automatically be added for the next reporting period when the previous CE report is complete', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsNextCEFormAutoAdded'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates members on this register are eligible to act as employment supervisors for other members', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsEligibleSupervisor'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates members on this register must have supervisors on practice (e.g. applies to provisional, student registers, etc.)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsSupervisionRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Directs the application to expire active employment records when the member is moved onto this register | This setting only applies where employment terms are used (effective time must be filled in)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsEmploymentTerminated'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Directs the application to expire all group memberships when the member is moved onto this register ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsGroupMembershipTerminated'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The default length of the term in days - applies only to Term-Permits | An administrator can override the default length of the term-permit by setting specific effective and expiry dates when the registration is created', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'TermPermitDays'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This value is relevant to Colleges that allow multiple concurrent registrations only.  It is used to set the priority or sequence of the most important registration where registrations on multiple registers exist for the same type period (does not apply to most configurations).', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'RegisterRank'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The learning model assigned to this practice register', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'LearningModelSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason group assigned to this practice register', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'ReasonGroupSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default practice register to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this register is the default for in-active practice status | UI only enables access where Is-Active-Practice is not checked. The value is used mostly during conversion to avoid gaps in registration history.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsDefaultInactivePractice'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this practice register record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterChangePracticeRegisterSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register section assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterChangePracticeRegisterSectionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this practice register change record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterChangeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Documentation about the scenarios this practice-register-change applies to - available as help text on selection. ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register change record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterChangeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice register this section is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionPracticeRegisterSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the practice register section to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default practice register section to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this section should be shown on a certificate or the public registry. This is defaulted as on by design. It is more important to make sure the public is protected than it is to prevent a section accidentally being shown on the certficate or the public registry. The Ui should reflect the importance of this distinction very obviously. ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsDisplayedOnLicense'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this practice register section record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register section record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'PracticeRegisterSectionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment is currently active (not expired or future dated)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment will come into effect in the future', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsPending'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterCatalogItem', 'COLUMN', N'zContext'
GO
