SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrationSnapshot]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrationSnapshot
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.RegistrationSnapshot - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.RegistrationSnapshot table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vRegistrationSnapshotExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vRegistrationSnapshotExt documentation for details. To add additional content to this view, customize
the dbo.vRegistrationSnapshotExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rs.RegistrationSnapshotSID
	,rs.RegistrationSnapshotTypeSID
	,rs.RegistrationSnapshotLabel
	,rs.RegistrationYear
	,rs.Description
	,rs.QueuedTime
	,rs.LockedTime
	,rs.LastCodeUpdateTime
	,rs.LastVerifiedTime
	,rs.JobRunSID
	,rs.UserDefinedColumns
	,rs.RegistrationSnapshotXID
	,rs.LegacyKey
	,rs.IsDeleted
	,rs.CreateUser
	,rs.CreateTime
	,rs.UpdateUser
	,rs.UpdateTime
	,rs.RowGUID
	,rs.RowStamp
	,rsx.RegistrationSnapshotTypeLabel
	,rsx.RegistrationSnapshotTypeSCD
	,rsx.RegistrationSnapshotLabelTemplate
	,rsx.RegistrationSnapshotTypeIsDefault
	,rsx.RegistrationSnapshotTypeIsActive
	,rsx.RegistrationSnapshotTypeRowGUID
	,rsx.JobSID
	,rsx.ConversationHandle
	,rsx.StartTime
	,rsx.EndTime
	,rsx.TotalRecords
	,rsx.TotalErrors
	,rsx.RecordsProcessed
	,rsx.CurrentProcessLabel
	,rsx.IsFailed
	,rsx.IsFailureCleared
	,rsx.CancellationRequestTime
	,rsx.IsCancelled
	,rsx.JobRunRowGUID
	,rsx.IsDeleteEnabled
	,rsx.IsReselected
	,rsx.IsNullApplied
	,rsx.zContext
	,rsx.IsLocked
	,rsx.IsLockEnabled
	,rsx.IsUnlockEnabled
	,rsx.IsUpdateEnabled
	,rsx.ProfileCount
	,rsx.InValidCount
	,rsx.ModifiedCount
	,rsx.QueuedDateCTZ
	,rsx.QueuedTimeCTZ
	,rsx.QueuedDateTimeCTZ
	,rsx.RegistrationYearLabel
	,rsx.SnapshotStatusLabel
	,rsx.LastCodeUpdateStatus
	,rsx.LastVerifiedStatus
from
	dbo.RegistrationSnapshot      rs
join
	dbo.vRegistrationSnapshot#Ext rsx	on rs.RegistrationSnapshotSID = rsx.RegistrationSnapshotSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.RegistrationSnapshot', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration snapshot assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration snapshot type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration snapshot to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional description of what the snapshot was generated for.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'Description'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the generation of this snapshot should begin ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'QueuedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the snapshot is marked as locked which disallows further editing. A system-administrator can unlock.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'LockedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the code update process was last run on this snapshot.  Blank when pending (in process).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'LastCodeUpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the verification process was last run on this snapshot.  Blank when pending (in process).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the job run assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'JobRunSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the registration snapshot | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the registration snapshot | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this registration snapshot record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the registration snapshot | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the registration snapshot record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration snapshot record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration snapshot type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the registration snapshot type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default registration snapshot type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this registration snapshot type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration snapshot type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RegistrationSnapshotTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The job this run is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'JobSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An internal system value used to coordinate communication about job status within the SQL Server message broker service', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'ConversationHandle'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job began running', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'StartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job completed successfully, failed, or was cancelled | Job run records where this value is not filled in are considered to be running', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'EndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total count of records to process in the job (if set) | This value must be set by the job procedure at startup.  The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'TotalRecords'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of errors encountered during the job run | This value must be set by the job procedure as errors are encountered.  The value is used in status reporting and may be used to abort the job automatically if the error rate exceeds the max rate defined in the Job table (only applies where at least 100 records have been processed).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'TotalErrors'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The count of records processed in the job so far (if set) | This value must be set by the job procedure as records are processed. The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'RecordsProcessed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier displayed on the job monitoring screen in the UI advising the user what stage or operation is currently being carried out by the job - e.g. "Retrieving Records ..." | Note that the value can be replaced for display on the UI by defining a mapping record in sf.TermLabel', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'CurrentProcessLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job ended in an error or was aborted because the maximum error ratio, as defined in the Job table, was exceeded', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsFailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that the failed status of the job has been cleared so that it can be run again if a "max retry on failure" limit was set for the job | This value is only enabled in the UI if the job run is showing a failed status', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsFailureCleared'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time a request to cancel the job was made | If the job is non-responsive, the cancellation will not occur and the job must be set to Failed manually from the Job Management screen', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'CancellationRequestTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job was cancelled before it completed', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the job run record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'JobRunRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether lock option is available to prevent further editing (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsLockEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether un-lock option is available to enabled editing (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsUnlockEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the UPDATE processing option is available (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'IsUpdateEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total profile records in this snapshot', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'ProfileCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total invalid profile records in this snapshot', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'InValidCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total records that have not been exported and are modified since the last export (all records if never exported)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'ModifiedCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued date for editing (in the client timezone)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'QueuedDateCTZ'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued time for editing in the client timezone', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'QueuedTimeCTZ'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued date time for display in the client timezone', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot', 'COLUMN', N'QueuedDateTimeCTZ'
GO
