SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vExamOffering]
as
/*********************************************************************************************************************************
View    : dbo.vExamOffering
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.ExamOffering - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.ExamOffering table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vExamOfferingExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vExamOfferingExt documentation for details. To add additional content to this view, customize
the dbo.vExamOfferingExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 eo.ExamOfferingSID
	,eo.ExamSID
	,eo.OrgSID
	,eo.ExamTime
	,eo.SeatingCapacity
	,eo.CatalogItemSID
	,eo.BookingCutOffDate
	,eo.VendorExamOfferingID
	,eo.UserDefinedColumns
	,eo.ExamOfferingXID
	,eo.LegacyKey
	,eo.IsDeleted
	,eo.CreateUser
	,eo.CreateTime
	,eo.UpdateUser
	,eo.UpdateTime
	,eo.RowGUID
	,eo.RowStamp
	,eox.ExamName
	,eox.ExamCategory
	,eox.PassingScore
	,eox.ExamEffectiveTime
	,eox.ExamExpiryTime
	,eox.IsOnlineExam
	,eox.IsEnabledOnPortal
	,eox.Sequence
	,eox.CultureSID
	,eox.ExamLastVerifiedTime
	,eox.MinLagDaysBetweenAttempts
	,eox.MaxAttemptsPerYear
	,eox.VendorExamID
	,eox.ExamRowGUID
	,eox.ParentOrgSID
	,eox.OrgTypeSID
	,eox.OrgName
	,eox.OrgLabel
	,eox.StreetAddress1
	,eox.StreetAddress2
	,eox.StreetAddress3
	,eox.CitySID
	,eox.PostalCode
	,eox.RegionSID
	,eox.Phone
	,eox.Fax
	,eox.WebSite
	,eox.EmailAddress
	,eox.InsuranceOrgSID
	,eox.InsurancePolicyNo
	,eox.InsuranceAmount
	,eox.IsEmployer
	,eox.IsCredentialAuthority
	,eox.IsInsurer
	,eox.IsInsuranceCertificateRequired
	,eox.IsPublic
	,eox.OrgIsActive
	,eox.IsAdminReviewRequired
	,eox.OrgLastVerifiedTime
	,eox.OrgRowGUID
	,eox.CatalogItemLabel
	,eox.InvoiceItemDescription
	,eox.IsLateFee
	,eox.ImageAlternateText
	,eox.IsAvailableOnClientPortal
	,eox.IsComplaintPenalty
	,eox.GLAccountSID
	,eox.IsTaxRate1Applied
	,eox.IsTaxRate2Applied
	,eox.IsTaxRate3Applied
	,eox.IsTaxDeductible
	,eox.CatalogItemEffectiveTime
	,eox.CatalogItemExpiryTime
	,eox.FileTypeSCD
	,eox.FileTypeSID
	,eox.CatalogItemRowGUID
	,eox.IsDeleteEnabled
	,eox.IsReselected
	,eox.IsNullApplied
	,eox.zContext
	,eox.IsDetailedOffering
from
	dbo.ExamOffering      eo
join
	dbo.vExamOffering#Ext eox	on eo.ExamOfferingSID = eox.ExamOfferingSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.ExamOffering', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the exam offering assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamOfferingSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The exam this offering is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this exam offering', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the exam was taken', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The catalog item assigned to this exam offering', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CatalogItemSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional and unique identifier provided by the vendor/service to identify the exam offering | This value can be used when importing exam candidates to automatically book or associate a result with the exam offering ', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'VendorExamOfferingID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the exam offering | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamOfferingXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the exam offering | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this exam offering record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the exam offering | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the exam offering record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam offering record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the exam to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize exams (e.g. for display in different areas on member forms)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Minimum score for passing the exam (required for Alinity exams). Leave blank to always record pass/fail manually for external exams.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'PassingScore'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the exam is enabled for selection on the member portal (applies only to online exams)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsEnabledOnPortal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Controls order this exam appears in relative to other exams associated with the same credential | If not set the order defaults to entry order of the record', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'Sequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the culture assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CultureSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The minimum days a member must wait between attempts at writing the exam', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'MinLagDaysBetweenAttempts'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The maximum number of attempts a member is alloted to pass the exam within a registration year.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'MaxAttemptsPerYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional and unique identifier provided by the vendor/service to identify the exam  | This value can be used when importing exam candidates to associate results with the correct exam', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'VendorExamID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ExamRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgLastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the catalog item to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CatalogItemLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A description of the item to include on the invoice line', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'InvoiceItemDescription'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this is a late fee (applies to renewals only) - the effective date for which is defined on the practice register', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsLateFee'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Text to display instead of the image if image display is turned off on the client browser', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'ImageAlternateText'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is available for selection by members on the website (otherwise it is available to administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsAvailableOnClientPortal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this catalog item should appear in the list of penalties/fines displayed for recording complaint outcomes', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsComplaintPenalty'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The glaccount assigned to this catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'GLAccountSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if GST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsTaxRate1Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if PST/HST should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsTaxRate2Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if [Tax Type #3] should be applied to the revenue item when invoiced', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsTaxRate3Applied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is considered tax deductible (includes the item on tax receipts)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsTaxDeductible'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item becomes available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CatalogItemEffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the item is no longer available for including on invoices.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CatalogItemExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document the email is stored as | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".PDF" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'FileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of catalog item', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'FileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the catalog item record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'CatalogItemRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether detailed offering fields are available', 'SCHEMA', N'dbo', 'VIEW', N'vExamOffering', 'COLUMN', N'IsDetailedOffering'
GO
