SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vOrg#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vOrg#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.Org base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vOrg (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 o.OrgSID
	,city.CityName
	,city.StateProvinceSID
	,city.IsDefault                                                         CityIsDefault
	,city.IsActive                                                          CityIsActive
	,city.IsAdminReviewRequired                                             CityIsAdminReviewRequired
	,city.RowGUID                                                           CityRowGUID
	,otype.OrgTypeName
	,otype.OrgTypeCode
	,otype.SectorCode
	,otype.OrgTypeCategory
	,otype.IsDefault                                                        OrgTypeIsDefault
	,otype.IsActive                                                         OrgTypeIsActive
	,otype.RowGUID                                                          OrgTypeRowGUID
	,region.RegionLabel
	,region.RegionName
	,region.IsDefault                                                       RegionIsDefault
	,region.IsActive                                                        RegionIsActive
	,region.RowGUID                                                         RegionRowGUID
	,dbo.fOrg#IsDeleteEnabled(o.OrgSID)                                     IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
--! <MoreColumns>
 ,dbo.fOrg#FullLabel(o.OrgSID)																								FullOrgLabel							--# Organization label including all parent organizations separated by a dash
 ,zsp.StateProvinceName
 ,zsp.StateProvinceCode
 ,zctry.CountrySID
 ,zctry.CountryName
 ,(select count(1) from dbo.RegistrantCredential x where x.OrgSID = o.OrgSID) CredentialCount						--# The total number of times this organization appears as a credential authority on registrant credentials
 ,(
		select count (1) from dbo.QualifyingCredentialOrg x where x.OrgSID = o.OrgSID
	)																																						QualifiedCredentialCount	--# The total number of credentials this organization is a certifying authority for
 ,(
		select
			count(1)
		from
		(
			select
				rm.RegistrantSID
			from
				dbo.RegistrantEmployment rm
			where
				rm.OrgSID = o.OrgSID
			group by
				rm.RegistrantSID
		) x
	)																																						EmploymentCount						--# The total number of times this organization appears as an employer on registrant-employment records
 ,znr.NextReviewTime																																										--# The date the next review is due to occur
 ,cast(case
				 when o.LastVerifiedTime is null then 1
				 when znr.NextReviewTime < convert(smalldatetime, sysdatetimeoffset()) then 1
				 else 0
			 end as bit)																														IsNextReviewDue
 ,zins.IsInsuranceEnabled
 ,zned.OrgNameEffectiveDate																																							--# The date the organization name was first effective (blank if unknown)
--! </MoreColumns>
from
	dbo.Org      o
join
	dbo.City     city   on o.CitySID = city.CitySID
join
	dbo.OrgType  otype  on o.OrgTypeSID = otype.OrgTypeSID
join
	dbo.Region   region on o.RegionSID = region.RegionSID
--! <MoreJoins>
join
	dbo.StateProvince zsp on city.StateProvinceSID = zsp.StateProvinceSID
join
	dbo.Country				zctry on zsp.CountrySID = zctry.CountrySID
join
(
	select
		isnull(convert(bit, sf.fConfigParam#Value('IsInsuranceEnabled')), 1) IsInsuranceEnabled
)										zins on 1 = 1
outer apply
(
	select
		dateadd(month, isnull(convert(smallint, sf.fConfigParam#Value('OrgReviewMonths')), 12), convert(smalldatetime, o.LastVerifiedTime)) NextReviewTime
)										znr
outer apply
(
	select
		dateadd(day, 1, max(oon.ExpiryDate)) OrgNameEffectiveDate
	from
		dbo.OrgOtherName oon
	where
		oon.OrgSID = o.OrgSID
) zned;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The state province this city is in', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'StateProvinceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default city to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CityIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this city record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CityIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CityIsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the city record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org type to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgTypeName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional value used for external reporting of the oranization sector - e.g. "14" and "24" are the CIHI codes for Public and Private sectors', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'SectorCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default org type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the region to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'RegionLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the region to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'RegionName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default region to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'RegionIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this region record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'RegionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the region record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'RegionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Organization label including all parent organizations separated by a dash', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'FullOrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of credentials this organization is a certifying authority for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'CredentialCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of credentials this organization is a certifying authority for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'QualifiedCredentialCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of times this organization appears as an employer on registrant-employment records', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'EmploymentCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the next review is due to occur', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'NextReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the organization name was first effective (blank if unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg#Ext', 'COLUMN', N'OrgNameEffectiveDate'
GO
