SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vQualifyingCredentialOrg#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vQualifyingCredentialOrg#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.QualifyingCredentialOrg base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vQualifyingCredentialOrg (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 qco.QualifyingCredentialOrgSID
	,credential.CredentialTypeSID
	,credential.CredentialLabel
	,credential.ToolTip
	,credential.IsRelatedToProfession
	,credential.IsProgramRequired
	,credential.IsSpecialization
	,credential.IsActive                                                          CredentialIsActive
	,credential.CredentialCode
	,credential.RowGUID                                                           CredentialRowGUID
	,o.ParentOrgSID
	,o.OrgTypeSID
	,o.OrgName
	,o.OrgLabel
	,o.StreetAddress1
	,o.StreetAddress2
	,o.StreetAddress3
	,o.CitySID
	,o.PostalCode
	,o.RegionSID
	,o.Phone
	,o.Fax
	,o.WebSite
	,o.EmailAddress
	,o.InsuranceOrgSID
	,o.InsurancePolicyNo
	,o.InsuranceAmount
	,o.IsEmployer
	,o.IsCredentialAuthority
	,o.IsInsurer
	,o.IsInsuranceCertificateRequired
	,o.IsPublic
	,o.IsActive                                                                   OrgIsActive
	,o.IsAdminReviewRequired
	,o.LastVerifiedTime
	,o.RowGUID                                                                    OrgRowGUID
	,dbo.fQualifyingCredentialOrg#IsDeleteEnabled(qco.QualifyingCredentialOrgSID) IsDeleteEnabled			--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                           IsReselected				-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                               IsNullApplied				-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                            zContext						-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
  --! </MoreColumns>
from
	dbo.QualifyingCredentialOrg qco
join
	dbo.Credential              credential on qco.CredentialSID = credential.CredentialSID
join
	dbo.Org                     o          on qco.OrgSID = o.OrgSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the qualifying credential org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'QualifyingCredentialOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of credential', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CredentialTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the credential to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CredentialLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short explanatory text describing the credential often shown to end-users on mouse-over and/or press of info button', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this credential is related to professional practice | This value is automaticallly set on by the application where the credential is set a qualifying', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsRelatedToProfession'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if a program-name must be entered when this credential is claimed | This option should be checked if the credential is a generic type like "Diploma", "Certificate", etc. where a specific field of study is not mentioned.', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsProgramRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this credential should be displayed as a specialization on the license/permit and Public Directory', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsSpecialization'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this credential record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CredentialIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A code used to report on this credential either internally or externally.  The code for CIHI for "Not Provided" is "9" (set as default)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CredentialCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the credential record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CredentialRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vQualifyingCredentialOrg#Ext', 'COLUMN', N'zContext'
GO
