SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vEmploymentSupervisor]
as
/*********************************************************************************************************************************
View    : dbo.vEmploymentSupervisor
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.EmploymentSupervisor - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.EmploymentSupervisor table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vEmploymentSupervisorExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vEmploymentSupervisorExt documentation for details. To add additional content to this view, customize
the dbo.vEmploymentSupervisorExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 es.EmploymentSupervisorSID
	,es.RegistrantEmploymentSID
	,es.PersonSID
	,es.ExpiryTime
	,es.UserDefinedColumns
	,es.EmploymentSupervisorXID
	,es.LegacyKey
	,es.IsDeleted
	,es.CreateUser
	,es.CreateTime
	,es.UpdateUser
	,es.UpdateTime
	,es.RowGUID
	,es.RowStamp
	,esx.RegistrantSID
	,esx.OrgSID
	,esx.RegistrationYear
	,esx.EmploymentTypeSID
	,esx.EmploymentRoleSID
	,esx.PracticeHours
	,esx.PracticeScopeSID
	,esx.AgeRangeSID
	,esx.IsOnPublicRegistry
	,esx.Phone
	,esx.SiteLocation
	,esx.EffectiveTime
	,esx.RegistrantEmploymentExpiryTime
	,esx.Rank
	,esx.OwnershipPercentage
	,esx.IsEmployerInsurance
	,esx.InsuranceOrgSID
	,esx.InsurancePolicyNo
	,esx.InsuranceAmount
	,esx.RegistrantEmploymentRowGUID
	,esx.GenderSID
	,esx.NamePrefixSID
	,esx.FirstName
	,esx.CommonName
	,esx.MiddleNames
	,esx.LastName
	,esx.BirthDate
	,esx.DeathDate
	,esx.HomePhone
	,esx.MobilePhone
	,esx.IsTextMessagingEnabled
	,esx.ImportBatch
	,esx.PersonRowGUID
	,esx.IsDeleteEnabled
	,esx.IsReselected
	,esx.IsNullApplied
	,esx.zContext
	,esx.SupervisorRegistrantLabel
	,esx.IsAgreementValid
	,esx.AgreementStatusLabel
	,esx.SupervisorRegistrantSID
	,esx.SupervisorRegistrantEmploymentSID
from
	dbo.EmploymentSupervisor      es
join
	dbo.vEmploymentSupervisor#Ext esx	on es.EmploymentSupervisorSID = esx.EmploymentSupervisorSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.EmploymentSupervisor', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment supervisor assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'EmploymentSupervisorSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant employment assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RegistrantEmploymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this employment supervisor is based on', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the Supervisory Agreement was terminated if it does not continue through the end of registration year', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the employment supervisor | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'EmploymentSupervisorXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the employment supervisor | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this employment supervisor record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the employment supervisor | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the employment supervisor record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the employment supervisor record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registrant this employment is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'EmploymentTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the employment type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'EmploymentRoleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice scope assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'PracticeScopeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the Age Range assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'AgeRangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this employer should be included in employers listed for the registrant on the public directly. The default setting is on, however, if the public registry configuration does not include employment, this setting has no impact.  Where employment is included in the public registry, this value should be included in the Profile Update form so that registrants can turn on/off the employers which display during the year as their employment changes.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsOnPublicRegistry'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A phone number for this individual at their place of employment (do not enter mobile phone numbers here)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A location of employment within the organization facility (optional)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'SiteLocation'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the employment started if precision beyond registration year is required ', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when employment ended (blank if employment is still ongoing or expiry is unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RegistrantEmploymentExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Where no hours have been reported for the employer, a ranking value used to set primary, secondary, etc. employer position.  ', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'Rank'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When non-zero indicates member is self-employed. When value is > 0, then a specific share-percentage of ownership is specified. | Note that the value "-1"  is used to indicate a member is self-employed but ownership is unknown or not specified.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'OwnershipPercentage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this registrant employment', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant employment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'RegistrantEmploymentRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Identifying label for the supervisor', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'SupervisorRegistrantLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether supervisory relationship is not expired and conforms to business rules', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'IsAgreementValid'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A label describing the status of the supervisory relationship (valid/invalid: reason for not being valid)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'AgreementStatusLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Registrant key of the supervisor', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'SupervisorRegistrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Registrant key of the supervisor employment record (if at same organization in same registration year)', 'SCHEMA', N'dbo', 'VIEW', N'vEmploymentSupervisor', 'COLUMN', N'SupervisorRegistrantEmploymentSID'
GO
