SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vIdentifierType]
as
/*********************************************************************************************************************************
View    : dbo.vIdentifierType
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.IdentifierType - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.IdentifierType table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vIdentifierTypeExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vIdentifierTypeExt documentation for details. To add additional content to this view, customize
the dbo.vIdentifierTypeExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 itype.IdentifierTypeSID
	,itype.OrgSID
	,itype.IdentifierTypeLabel
	,itype.IdentifierTypeCategory
	,itype.IsOtherRegistration
	,itype.DisplayRank
	,itype.EditMask
	,itype.IdentifierCode
	,itype.IsDefault
	,itype.UserDefinedColumns
	,itype.IdentifierTypeXID
	,itype.LegacyKey
	,itype.IsDeleted
	,itype.CreateUser
	,itype.CreateTime
	,itype.UpdateUser
	,itype.UpdateTime
	,itype.RowGUID
	,itype.RowStamp
	,itypex.ParentOrgSID
	,itypex.OrgTypeSID
	,itypex.OrgName
	,itypex.OrgLabel
	,itypex.StreetAddress1
	,itypex.StreetAddress2
	,itypex.StreetAddress3
	,itypex.CitySID
	,itypex.PostalCode
	,itypex.RegionSID
	,itypex.Phone
	,itypex.Fax
	,itypex.WebSite
	,itypex.EmailAddress
	,itypex.InsuranceOrgSID
	,itypex.InsurancePolicyNo
	,itypex.InsuranceAmount
	,itypex.IsEmployer
	,itypex.IsCredentialAuthority
	,itypex.IsInsurer
	,itypex.IsInsuranceCertificateRequired
	,itypex.IsPublic
	,itypex.OrgIsActive
	,itypex.IsAdminReviewRequired
	,itypex.LastVerifiedTime
	,itypex.OrgRowGUID
	,itypex.IsDeleteEnabled
	,itypex.IsReselected
	,itypex.IsNullApplied
	,itypex.zContext
	,itypex.OrgTypeCode
	,itypex.OrgTypeName
	,itypex.OrgTypeCategory
	,itypex.OrgTypeIsDefault
	,itypex.OrgCitySID
	,itypex.OrgCityName
	,itypex.OrgCountrySID
	,itypex.OrgCountryName
from
	dbo.IdentifierType      itype
join
	dbo.vIdentifierType#Ext itypex	on itype.IdentifierTypeSID = itypex.IdentifierTypeSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.IdentifierType', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the identifier type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IdentifierTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this identifier type', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the identifier type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IdentifierTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these identifier types.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IdentifierTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this identifier type is issued from another Regulator in the same or related profession to include the type in "Other registrations" queries and reports', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsOtherRegistration'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A value defining the format of letters, numbers and constants the ID must follow to be valid (uses "REGEX" format)| Assistance is required from the help desk to set it.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'EditMask'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code used to represent this type of identifier to external systems', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IdentifierCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default identifier type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the identifier type | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IdentifierTypeXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the identifier type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this identifier type record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the identifier type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the identifier type record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the identifier type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vIdentifierType', 'COLUMN', N'zContext'
GO
