SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPracticeRegisterChangeRequirement]
as
/*********************************************************************************************************************************
View    : dbo.vPracticeRegisterChangeRequirement
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.PracticeRegisterChangeRequirement - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.PracticeRegisterChangeRequirement table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vPracticeRegisterChangeRequirementExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vPracticeRegisterChangeRequirementExt documentation for details. To add additional content to this view, customize
the dbo.vPracticeRegisterChangeRequirementExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 prcr.PracticeRegisterChangeRequirementSID
	,prcr.PracticeRegisterChangeSID
	,prcr.RegistrationRequirementSID
	,prcr.IsMandatory
	,prcr.ExpiryMonths
	,prcr.IsActive
	,prcr.RequirementSequence
	,prcr.UserDefinedColumns
	,prcr.PracticeRegisterChangeRequirementXID
	,prcr.LegacyKey
	,prcr.IsDeleted
	,prcr.CreateUser
	,prcr.CreateTime
	,prcr.UpdateUser
	,prcr.UpdateTime
	,prcr.RowGUID
	,prcr.RowStamp
	,prcrx.PracticeRegisterSID
	,prcrx.PracticeRegisterSectionSID
	,prcrx.PracticeRegisterChangeIsActive
	,prcrx.ToolTip
	,prcrx.IsEnabledForRegistrant
	,prcrx.PracticeRegisterChangeRowGUID
	,prcrx.RegistrationRequirementTypeSID
	,prcrx.RegistrationRequirementLabel
	,prcrx.PersonDocTypeSID
	,prcrx.ExamSID
	,prcrx.RegistrationRequirementExpiryMonths
	,prcrx.RegistrationRequirementIsActive
	,prcrx.RegistrationRequirementRowGUID
	,prcrx.IsDeleteEnabled
	,prcrx.IsReselected
	,prcrx.IsNullApplied
	,prcrx.zContext
	,prcrx.PracticeRegisterChangeLabel
from
	dbo.PracticeRegisterChangeRequirement      prcr
join
	dbo.vPracticeRegisterChangeRequirement#Ext prcrx	on prcr.PracticeRegisterChangeRequirementSID = prcrx.PracticeRegisterChangeRequirementSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.PracticeRegisterChangeRequirement', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register change requirement assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeRequirementSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register change assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registration requirement assigned to this practice register change requirement', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the requirement is mandatory for this practice register change | When checked, the UI will not display the option for administrators to mark the requirement "Not Applicable" ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsMandatory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of months a reviewed document or exam remains valid - e.g. a new Crimincal Record Check may be required every 36 months | This is a deafult copied to the change-requirement since the setting may be different in different registration-change contexts.  UI does not prompt unless Doc-Type or Exam Type is set.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'ExpiryMonths'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this practice register change requirement record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An value for ordering the presentation of requirements on the screen', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RequirementSequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the practice register change requirement | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeRequirementXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the practice register change requirement | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this practice register change requirement record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the practice register change requirement | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the practice register change requirement record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register change requirement record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the practice register section assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterSectionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this practice register change record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Documentation about the scenarios this practice-register-change applies to - available as help text on selection. ', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the practice register change record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of registration requirement', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration requirement to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the Person Doc Type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PersonDocTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the exam type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'ExamSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of months a reviewed document or exam remains valid - e.g. a new Crimincal Record Check may be required every 36 months | This is a deafult copied to the change-requirement since the setting may be different in different registration-change contexts.  UI does not prompt unless Doc-Type or Exam Type is set.', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementExpiryMonths'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this registration requirement record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration requirement record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'RegistrationRequirementRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see functi', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A label showing the from->to registers involved in this transition', 'SCHEMA', N'dbo', 'VIEW', N'vPracticeRegisterChangeRequirement', 'COLUMN', N'PracticeRegisterChangeLabel'
GO
