SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrantCredential#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrantCredential#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.RegistrantCredential base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vRegistrantCredential (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rc.RegistrantCredentialSID
	,credential.CredentialTypeSID
	,credential.CredentialLabel
	,credential.ToolTip
	,credential.IsRelatedToProfession
	,credential.IsProgramRequired
	,credential.IsSpecialization
	,credential.IsActive                                                    CredentialIsActive
	,credential.CredentialCode
	,credential.RowGUID                                                     CredentialRowGUID
	,fos.FieldOfStudyName
	,fos.FieldOfStudyCode
	,fos.FieldOfStudyCategory
	,fos.IsDefault                                                          FieldOfStudyIsDefault
	,fos.IsActive                                                           FieldOfStudyIsActive
	,fos.RowGUID                                                            FieldOfStudyRowGUID
	,registrant.PersonSID
	,registrant.RegistrantNo
	,registrant.YearOfInitialEmployment
	,registrant.IsOnPublicRegistry
	,registrant.CityNameOfBirth
	,registrant.CountrySID
	,registrant.DirectedAuditYearCompetence
	,registrant.DirectedAuditYearPracticeHours
	,registrant.LateFeeExclusionYear
	,registrant.IsRenewalAutoApprovalBlocked
	,registrant.RenewalExtensionExpiryTime
	,registrant.ArchivedTime
	,registrant.RowGUID                                                     RegistrantRowGUID
	,o.ParentOrgSID
	,o.OrgTypeSID
	,o.OrgName
	,o.OrgLabel
	,o.StreetAddress1
	,o.StreetAddress2
	,o.StreetAddress3
	,o.CitySID
	,o.PostalCode
	,o.RegionSID
	,o.Phone
	,o.Fax
	,o.WebSite
	,o.EmailAddress
	,o.InsuranceOrgSID
	,o.InsurancePolicyNo
	,o.InsuranceAmount
	,o.IsEmployer
	,o.IsCredentialAuthority
	,o.IsInsurer
	,o.IsInsuranceCertificateRequired
	,o.IsPublic
	,o.IsActive                                                             OrgIsActive
	,o.IsAdminReviewRequired
	,o.LastVerifiedTime
	,o.RowGUID                                                              OrgRowGUID
	,sf.fIsActive(rc.EffectiveTime, rc.ExpiryTime)                          IsActive									--# Indicates if the assignment is currently active (not expired or future dated)
	,sf.fIsPending(rc.EffectiveTime, rc.ExpiryTime)                         IsPending									--# Indicates if the assignment will come into effect in the future
	,dbo.fRegistrantCredential#IsDeleteEnabled(rc.RegistrantCredentialSID)  IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
--! <MoreColumns>
 ,(case
		 when credential.IsSpecialization = cast(1 as bit) then cast(0 as bit)
		 else cast(zqco.QualifyingCredentialOrgSID as bit)
	 end
	)																																			IsQualifying		--# Indicates if the credential is qualifying for practice in the profession
--! </MoreColumns>
from
	dbo.RegistrantCredential rc
join
	dbo.Credential           credential on rc.CredentialSID = credential.CredentialSID
join
	dbo.FieldOfStudy         fos        on rc.FieldOfStudySID = fos.FieldOfStudySID
join
	dbo.Registrant           registrant on rc.RegistrantSID = registrant.RegistrantSID
left outer join
	dbo.Org                  o          on rc.OrgSID = o.OrgSID
--! <MoreJoins>
left outer join
	dbo.QualifyingCredentialOrg zqco on credential.CredentialSID = zqco.CredentialSID and o.OrgSID = zqco.OrgSID;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant credential assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'RegistrantCredentialSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of credential', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CredentialTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the credential to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CredentialLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short explanatory text describing the credential often shown to end-users on mouse-over and/or press of info button', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this credential is related to professional practice | This value is automaticallly set on by the application where the credential is set a qualifying', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsRelatedToProfession'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if a program-name must be entered when this credential is claimed | This option should be checked if the credential is a generic type like "Diploma", "Certificate", etc. where a specific field of study is not mentioned.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsProgramRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this credential should be displayed as a specialization on the license/permit and Public Directory', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsSpecialization'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this credential record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CredentialIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A code used to report on this credential either internally or externally.  The code for CIHI for "Not Provided" is "9" (set as default)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CredentialCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the credential record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CredentialRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the field of study to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'FieldOfStudyName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize the practice areas', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'FieldOfStudyCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default field of study to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'FieldOfStudyIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this field of study record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'FieldOfStudyIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the field of study record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'FieldOfStudyRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The year of initial employment in the profession if required for reporting and full history of employment was not converted', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'YearOfInitialEmployment'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CityNameOfBirth'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The country assigned to this registrant', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CountrySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of continuing competence/education claims (non-random, direct audit inclusion)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'DirectedAuditYearCompetence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of practice hours (non-random, direct audit inclusion)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'DirectedAuditYearPracticeHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When filled out ensures the member will not be assessed late fees for the registration year selected (limited to one year)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'LateFeeExclusionYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates automatic approval of this form type is disabled for the registrant.  Administrator review and approval is required.  This setting is only required where rules in the form would not otherwise block automatic approval. (e.g. the form may block auto-approval if a criminal record is reported or other non-qualifying details.) The setting is relevant only where automatic approval is configured for the form type.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsRenewalAutoApprovalBlocked'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a date to extend the renewal period for this specific registrant to the end of the day entered.  | The later of this value and the standard schedule is applied. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'RenewalExtensionExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'RegistrantRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment is currently active (not expired or future dated)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment will come into effect in the future', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsPending'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the credential is qualifying for practice in the profession', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrantCredential#Ext', 'COLUMN', N'IsQualifying'
GO
