SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPayment]
as
/*********************************************************************************************************************************
View    : dbo.vPayment
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.Payment - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.Payment table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vPaymentExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vPaymentExt documentation for details. To add additional content to this view, customize
the dbo.vPaymentExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 payment.PaymentSID
	,payment.PersonSID
	,payment.PaymentTypeSID
	,payment.PaymentStatusSID
	,payment.GLAccountCode
	,payment.GLPostingDate
	,payment.DepositDate
	,payment.AmountPaid
	,payment.Reference
	,payment.NameOnCard
	,payment.PaymentCard
	,payment.TransactionID
	,payment.LastResponseCode
	,payment.LastResponseMessage
	,payment.VerifiedTime
	,payment.CancelledTime
	,payment.ReasonSID
	,payment.UserDefinedColumns
	,payment.PaymentXID
	,payment.LegacyKey
	,payment.IsDeleted
	,payment.CreateUser
	,payment.CreateTime
	,payment.UpdateUser
	,payment.UpdateTime
	,payment.RowGUID
	,payment.RowStamp
	,paymentx.PaymentStatusSCD
	,paymentx.PaymentStatusLabel
	,paymentx.IsPaid
	,paymentx.PaymentStatusSequence
	,paymentx.PaymentStatusRowGUID
	,paymentx.PaymentTypeSCD
	,paymentx.PaymentTypeLabel
	,paymentx.PaymentTypeCategory
	,paymentx.GLAccountSID
	,paymentx.PaymentTypePaymentStatusSID
	,paymentx.IsReferenceRequired
	,paymentx.DepositDateLagDays
	,paymentx.IsRefundExcludedFromGL
	,paymentx.ExcludeDepositFromGLBefore
	,paymentx.PaymentTypeIsDefault
	,paymentx.PaymentTypeIsActive
	,paymentx.PaymentTypeRowGUID
	,paymentx.GenderSID
	,paymentx.NamePrefixSID
	,paymentx.FirstName
	,paymentx.CommonName
	,paymentx.MiddleNames
	,paymentx.LastName
	,paymentx.BirthDate
	,paymentx.DeathDate
	,paymentx.HomePhone
	,paymentx.MobilePhone
	,paymentx.IsTextMessagingEnabled
	,paymentx.ImportBatch
	,paymentx.PersonRowGUID
	,paymentx.ReasonGroupSID
	,paymentx.ReasonName
	,paymentx.ReasonCode
	,paymentx.ReasonSequence
	,paymentx.ToolTip
	,paymentx.ReasonIsActive
	,paymentx.ReasonRowGUID
	,paymentx.IsDeleteEnabled
	,paymentx.IsReselected
	,paymentx.IsNullApplied
	,paymentx.zContext
	,paymentx.PaymentLabel
	,paymentx.PaymentShortLabel
	,paymentx.RegistrantLabel
	,paymentx.IsOnlinePayment
	,paymentx.TotalApplied
	,paymentx.TotalUnapplied
	,paymentx.IsFullyApplied
	,paymentx.IsNotApplied
	,paymentx.IsPartiallyApplied
	,paymentx.IsOverApplied
	,paymentx.IsCancelled
	,paymentx.IsCancelEnabled
	,paymentx.IsEditEnabled
	,paymentx.GLCheckSum
	,paymentx.LatestTransactionID
	,paymentx.LatestChargeTotal
	,paymentx.LatestResponseCode
	,paymentx.LatestMessage
	,paymentx.LatestApprovalCode
	,paymentx.LatestIsPaid
	,paymentx.LatestVerifiedTime
	,paymentx.IsRetryEnabled
	,paymentx.IsReapplyEnabled
	,paymentx.TransactionIDReference
	,paymentx.VerifiedTimeComponent
	,paymentx.InvoiceSID
from
	dbo.Payment      payment
join
	dbo.vPayment#Ext paymentx	on payment.PaymentSID = paymentx.PaymentSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.Payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the payment assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this payment is based on', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The status of the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentStatusSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date the payment transaction is posted for inclusion in the General Ledger | This value is set by the system automatically for online payments but can be overriden for manual payments.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'GLPostingDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the payment was deposited or settled', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'DepositDate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The monetary value of the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'AmountPaid'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Records the check/cheque# or other reference for the payment.  This value can be set as required for certain types of payments through Payment Type in settings.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'Reference'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name on the card used for payment. This value is used to help identify how a payment was made during follow-up.  The value is blank except where an payment card was used.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'NameOnCard'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The masked card number used for the online payment. This value is used to help identify how payment was made during follow-up. Only the first 4 and last 4 digits of the card number are retained. ', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentCard'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The transaction or reference number of the payment to allow tracking.  This can be a cheque number, the transaction number of a debit reciept, transaction number from a 3rd party payment processor, etc...', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'TransactionID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This value is supported by some online payment processors only (e.g. Moneris).  It indicates the time when a server-to-server verification of the transaction processed occurred.  Other details of the verification are stored in the ProcessingLog.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'VerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The datetime when the invoice was cancelled', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'CancelledTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason assigned to this payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the payment | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the payment | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this payment record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the payment | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the payment record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the payment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the payment status | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentStatusSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the payment status to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentStatusLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this status indicates the payment is in good standing and money was successfully received (or is assumed to be received as in the case of a check).', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsPaid'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the payment status record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentStatusRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the payment type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the payment type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the glaccount assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'GLAccountSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The status of the payment type', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypePaymentStatusSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that the payment reference field must be filled in when checked.  This is normally required for check/cheque payment types.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsReferenceRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of days ahead of the date the transaction is recorded, payments of this type are expected to appear on the bank statement.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'DepositDateLagDays'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if refunds processed on this payment type should be exlcuded from reporting to external general ledgers. This value should be checked if refunds for this payment type are initiated in your GL program (typically as checks/cheques).', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsRefundExcludedFromGL'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Allows deposits for this payment type to be excluded from reporting to external GL when the transaction occurs prior to this date.  Typically only applies to PAP bank accounts for conversion period.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ExcludeDepositFromGLBefore'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default payment type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this payment type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the payment type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason group assigned to this reason', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonGroupSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the reason to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional code used to refer to this reason - most often applicable where reason coding is provided to external parties - e.g. Provider Directory, Workforce Planning authority, etc. ', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this reason record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the reason record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'ReasonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the payment to use select among payments to apply', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'a shorter form of the display label to use when registrant is known', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'PaymentShortLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant or user making the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'RegistrantLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the payment type goes through an online payment processor', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsOnlinePayment'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount of the payment which has been applied to invoices	', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'TotalApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount remaining from the payment which can be applied to other invoices or refunded if no other invoices exist', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'TotalUnapplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this payment has been fully applied (no amount remaining to apply)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsFullyApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if no amount has yet been applied to an invoice from this payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsNotApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the payment is partially applied to invoices (more amount remains to be applied)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsPartiallyApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if amount applied is greater than the amount originally paid (this is an ERROR condition)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsOverApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the payment has been cancelled', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether cancellation of the current payment is allowed', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsCancelEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if current user can edit the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsEditEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used by the system to detect changes to the record impacting GL transactions', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'GLCheckSum'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether or not payment can be retried. Allowed when no response after 15 minutes', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsRetryEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates an inconsistency exists between the response of the payment process and the status of the record', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'IsReapplyEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Provides the transaction ID(s) for online payments and the manual reference (e.g. check no.) for other types', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'TransactionIDReference'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The invoice to be paid by this payment - used on Insert only', 'SCHEMA', N'dbo', 'VIEW', N'vPayment', 'COLUMN', N'InvoiceSID'
GO
