SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vExamQuestionReference]
as
/*********************************************************************************************************************************
View    : dbo.vExamQuestionReference
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.ExamQuestionReference - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.ExamQuestionReference table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vExamQuestionReferenceExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vExamQuestionReferenceExt documentation for details. To add additional content to this view, customize
the dbo.vExamQuestionReferenceExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 eqr.ExamQuestionReferenceSID
	,eqr.ExamQuestionSID
	,eqr.ReferenceTitle
	,eqr.ReferenceURL
	,eqr.UserDefinedColumns
	,eqr.ExamQuestionReferenceXID
	,eqr.LegacyKey
	,eqr.IsDeleted
	,eqr.CreateUser
	,eqr.CreateTime
	,eqr.UpdateUser
	,eqr.UpdateTime
	,eqr.RowGUID
	,eqr.RowStamp
	,eqrx.ExamSectionSID
	,eqrx.Sequence
	,eqrx.AttemptsAllowed
	,eqrx.KnowledgeDomainSID
	,eqrx.ExamQuestionIsActive
	,eqrx.ExamQuestionRowGUID
	,eqrx.IsDeleteEnabled
	,eqrx.IsReselected
	,eqrx.IsNullApplied
	,eqrx.zContext
from
	dbo.ExamQuestionReference      eqr
join
	dbo.vExamQuestionReference#Ext eqrx	on eqr.ExamQuestionReferenceSID = eqrx.ExamQuestionReferenceSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.ExamQuestionReference', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the exam question reference assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamQuestionReferenceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The exam question this reference is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamQuestionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the exam question reference | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamQuestionReferenceXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the exam question reference | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this exam question reference record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the exam question reference | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the exam question reference record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam question reference record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The exam section assigned to this exam question', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamSectionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Controls the display order of the question within the section | If value is not set the order defaults to the entry order of the records', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'Sequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of attempts the exam candidate is provided to select the correct answer.', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'AttemptsAllowed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The knowledge domain assigned to this exam question', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'KnowledgeDomainSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this exam question record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamQuestionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam question record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'ExamQuestionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vExamQuestionReference', 'COLUMN', N'zContext'
GO
