SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vCompetenceActivity]
as
/*********************************************************************************************************************************
View    : dbo.vCompetenceActivity
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.CompetenceActivity - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.CompetenceActivity table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vCompetenceActivityExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vCompetenceActivityExt documentation for details. To add additional content to this view, customize
the dbo.vCompetenceActivityExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 ca.CompetenceActivitySID
	,ca.CompetenceActivityLabel
	,ca.CompetenceActivityName
	,ca.UnitValue
	,ca.HelpPrompt
	,ca.IsActive
	,ca.UserDefinedColumns
	,ca.CompetenceActivityXID
	,ca.LegacyKey
	,ca.IsDeleted
	,ca.CreateUser
	,ca.CreateTime
	,ca.UpdateUser
	,ca.UpdateTime
	,ca.RowGUID
	,ca.RowStamp
	,cax.IsDeleteEnabled
	,cax.IsReselected
	,cax.IsNullApplied
	,cax.zContext
from
	dbo.CompetenceActivity      ca
join
	dbo.vCompetenceActivity#Ext cax	on ca.CompetenceActivitySID = cax.CompetenceActivitySID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.CompetenceActivity', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the competence activity assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CompetenceActivitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the competence activity to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CompetenceActivityLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the competence activity to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CompetenceActivityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'If the competence has a fixed value - e.g. "3 credits" -  enter it here.  Otherwise (when 0), the registrant will be able to enter the value of the item on their Learning Plan or Competency Claim.', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'UnitValue'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Help text to display to the end user explaining this Competence Type (may be referred to as a "Practice Standard" or "Competence Band".  HTML formatting is supported.', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'HelpPrompt'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this competence activity record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the competence activity | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CompetenceActivityXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the competence activity | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this competence activity record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the competence activity | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the competence activity record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the competence activity record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCompetenceActivity', 'COLUMN', N'zContext'
GO
