SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vOrgType]
as
/*********************************************************************************************************************************
View    : dbo.vOrgType
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.OrgType - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.OrgType table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vOrgTypeExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vOrgTypeExt documentation for details. To add additional content to this view, customize
the dbo.vOrgTypeExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 otype.OrgTypeSID
	,otype.OrgTypeName
	,otype.OrgTypeCode
	,otype.SectorCode
	,otype.OrgTypeCategory
	,otype.IsDefault
	,otype.IsActive
	,otype.UserDefinedColumns
	,otype.OrgTypeXID
	,otype.LegacyKey
	,otype.IsDeleted
	,otype.CreateUser
	,otype.CreateTime
	,otype.UpdateUser
	,otype.UpdateTime
	,otype.RowGUID
	,otype.RowStamp
	,otypex.IsDeleteEnabled
	,otypex.IsReselected
	,otypex.IsNullApplied
	,otypex.zContext
from
	dbo.OrgType      otype
join
	dbo.vOrgType#Ext otypex	on otype.OrgTypeSID = otypex.OrgTypeSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.OrgType', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org type to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'OrgTypeName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional value used for external reporting of the oranization sector - e.g. "14" and "24" are the CIHI codes for Public and Private sectors', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'SectorCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'OrgTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default org type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the org type | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'OrgTypeXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the org type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this org type record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the org type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the org type record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrgType', 'COLUMN', N'zContext'
GO
