SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrationScheduleYear]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrationScheduleYear
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.RegistrationScheduleYear - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.RegistrationScheduleYear table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vRegistrationScheduleYearExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vRegistrationScheduleYearExt documentation for details. To add additional content to this view, customize
the dbo.vRegistrationScheduleYearExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rsy.RegistrationScheduleYearSID
	,rsy.RegistrationScheduleSID
	,rsy.RegistrationYear
	,rsy.YearStartTime
	,rsy.YearEndTime
	,rsy.RenewalVerificationOpenTime
	,rsy.RenewalGeneralOpenTime
	,rsy.RenewalLateFeeStartTime
	,rsy.RenewalEndTime
	,rsy.ReinstatementVerificationOpenTime
	,rsy.ReinstatementGeneralOpenTime
	,rsy.ReinstatementEndTime
	,rsy.CECollectionStartTime
	,rsy.CECollectionEndTime
	,rsy.PAPBlockStartTime
	,rsy.PAPBlockEndTime
	,rsy.UserDefinedColumns
	,rsy.RegistrationScheduleYearXID
	,rsy.LegacyKey
	,rsy.IsDeleted
	,rsy.CreateUser
	,rsy.CreateTime
	,rsy.UpdateUser
	,rsy.UpdateTime
	,rsy.RowGUID
	,rsy.RowStamp
	,rsyx.RegistrationScheduleLabel
	,rsyx.RegistrationScheduleIsDefault
	,rsyx.RegistrationScheduleIsActive
	,rsyx.RegistrationScheduleRowGUID
	,rsyx.IsDeleteEnabled
	,rsyx.IsReselected
	,rsyx.IsNullApplied
	,rsyx.zContext
	,rsyx.RegistrationYearLabel
	,rsyx.RenewalVerificationOpenTimeComponent
	,rsyx.RenewalGeneralOpenTimeComponent
	,rsyx.ReinstatementVerificationOpenTimeComponent
	,rsyx.ReinstatementGeneralOpenTimeComponent
	,rsyx.YearStartTimeComponent
	,rsyx.YearEndTimeComponent
	,rsyx.RenewalLateFeeStartTimeComponent
	,rsyx.RenewalEndTimeComponent
	,rsyx.ReinstatementEndTimeComponent
	,rsyx.PAPBlockStartTimeComponent
	,rsyx.PAPBlockEndTimeComponent
	,rsyx.IsEditEnabled
from
	dbo.RegistrationScheduleYear      rsy
join
	dbo.vRegistrationScheduleYear#Ext rsyx	on rsy.RegistrationScheduleYearSID = rsyx.RegistrationScheduleYearSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.RegistrationScheduleYear', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration schedule year assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleYearSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The registration schedule this year is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A 4 digit numeric year set by the system based on the end of the term (entered into Year-End-Time).  For example, a year starting October 1st 2019 and ending September 30, 2020 is referred to by the system as the "2020" Registration Year.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first day in the registration year.  When registrations are renewed in advance of the registration year, this becomes the effective time of the new registration. | This value is entered as a full date but the system stores it with a time component to make comparisons easier. The time component is always 0:00:00 indicating the first moment of the year.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'YearStartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last day in the registration year.  When registrations are renewed before the registration year or during it, this becomes the expiry time of the new registration.  For temporary permits, the term may be shorter. This value is entered on the user interface as a date but the system stores it with a time component to make comparisons easier.  The time component is always set to 23:59:59 indicating the last moment of the year.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'YearEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when the online renewal process for this registration year is opened to selected verifiers.  Verifiers are staff or committee members who hold registrations that you wish to check the configuration of the renewal before opening it to the general membership.  This date is typically set a few days before the general renewal open date.  Note that you must assign the "Verification" grant in security settings in order that the early renewal will appear on the members dashboard. If no specific time component is entered the time defaults to 0:00:00 indicating the first moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalVerificationOpenTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when the online renewal process for this registration year is opened to the general membership.  If no specific time component is entered the time defaults to 0:00:00 indicating the first moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalGeneralOpenTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when the late fee should be applied to renewal charges.  If no specific time component is entered the time defaults to 0:00:00 indicating the first moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalLateFeeStartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when renewal for the given registration year should close.  This results in the option not being selectable from the member dashboard, however, if the member has already started their renewal they will be able to save it - however automatic approval will not occur.  If no specific time component is entered the time defaults to 23:59:59 indicating the last moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the reinstatement process for this registration year is opened to selected verifiers.  Verifiers are staff or committee members who hold registrations that you wish to check the configuration of the reinstatement before opening it to the general membership.  This date is typically set a few days before the general reinstatement open date.  Note that you must assign the "Verification" grant in security settings in order that the early renewal will appear on the members dashboard. If no specific time component is entered the time defaults to 0:00:00 indicating the first moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'ReinstatementVerificationOpenTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when the online reinstatement process for this registration year is opened to the general membership.  If no specific time component is entered the time defaults to 0:00:00 indicating the first moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'ReinstatementGeneralOpenTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time when reinstatement process for the given registration year should close.  This results in the option not being selectable from the member dashboard, however, if the member has already started their reinstatement they will be able to save it - however automatic approval will not occur.  If no specific time component is entered the time defaults to 23:59:59 indicating the last moment of the day.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'ReinstatementEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date when collection for continuing education unit/hours compliance starts for this registration year', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'CECollectionStartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date when collection for continuing education unit/hours compliance ends for this registration year', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'CECollectionEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the registration schedule year | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleYearXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the registration schedule year | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this registration schedule year record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the registration schedule year | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the registration schedule year record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration schedule year record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration schedule to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default registration schedule to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this registration schedule record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration schedule record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationScheduleRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Text label for the registration (shows start and end year if calendar year end is crossed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RegistrationYearLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when renewal for verifiers should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalVerificationOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when renewal for all members should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'RenewalGeneralOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when reinstatement for verifiers should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'ReinstatementVerificationOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when reinstatement for all members should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'ReinstatementGeneralOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates editing of parameters allowed (blocked for previous years)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear', 'COLUMN', N'IsEditEnabled'
GO
