SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrationScheduleYear#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrationScheduleYear#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.RegistrationScheduleYear base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vRegistrationScheduleYear (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rsy.RegistrationScheduleYearSID
	,rs.RegistrationScheduleLabel
	,rs.IsDefault                                                                   RegistrationScheduleIsDefault
	,rs.IsActive                                                                    RegistrationScheduleIsActive
	,rs.RowGUID                                                                     RegistrationScheduleRowGUID
	,dbo.fRegistrationScheduleYear#IsDeleteEnabled(rsy.RegistrationScheduleYearSID) IsDeleteEnabled		--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                             IsReselected			-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                                 IsNullApplied			-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                              zContext					-- parameter for sproc calls through EF - utility parameter for customization
																																																																														--! <MoreColumns>
 ,(case
		 when year(rsy.YearStartTime) = year(rsy.YearEndTime) then ltrim(rsy.RegistrationYear)
		 else ltrim(year(rsy.YearStartTime)) + '/' + ltrim(year(rsy.YearEndTime))
	 end
	)																																																							RegistrationYearLabel												--# Text label for the registration (shows start and end year if calendar year end is crossed)
 ,convert(time, rsy.RenewalVerificationOpenTime)																																RenewalVerificationOpenTimeComponent				--# The time on the opening day when renewal for verifiers should appear on the dashboard
 ,convert(time, rsy.RenewalGeneralOpenTime)																																			RenewalGeneralOpenTimeComponent							--# The time on the opening day when renewal for all members should appear on the dashboard
 ,convert(time, rsy.ReinstatementVerificationOpenTime)																													ReinstatementVerificationOpenTimeComponent	--# The time on the opening day when reinstatement for verifiers should appear on the dashboard
 ,convert(time, rsy.ReinstatementGeneralOpenTime)																																ReinstatementGeneralOpenTimeComponent				--# The time on the opening day when reinstatement for all members should appear on the dashboard
 ,convert(time, rsy.YearStartTime)																																							YearStartTimeComponent											-- remaining time components are display only!
 ,convert(time, rsy.YearEndTime)																																								YearEndTimeComponent
 ,convert(time, rsy.RenewalLateFeeStartTime)																																		RenewalLateFeeStartTimeComponent
 ,convert(time, rsy.RenewalEndTime)																																							RenewalEndTimeComponent
 ,convert(time, rsy.ReinstatementEndTime)																																				ReinstatementEndTimeComponent
 ,convert(time, rsy.PAPBlockStartTime)																																					PAPBlockStartTimeComponent
 ,convert(time, rsy.PAPBlockEndTime)																																						PAPBlockEndTimeComponent
 ,(case when rsy.RegistrationYear >= dbo.fRegistrationYear#Current() then cast(1 as bit)else cast(0 as bit)end) IsEditEnabled																--# Indicates editing of parameters allowed (blocked for previous years)
--! </MoreColumns>
from
	dbo.RegistrationScheduleYear rsy
join
	dbo.RegistrationSchedule     rs     on rsy.RegistrationScheduleSID = rs.RegistrationScheduleSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration schedule year assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationScheduleYearSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration schedule to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationScheduleLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default registration schedule to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationScheduleIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this registration schedule record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationScheduleIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration schedule record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationScheduleRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Text label for the registration (shows start and end year if calendar year end is crossed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RegistrationYearLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when renewal for verifiers should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RenewalVerificationOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when renewal for all members should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'RenewalGeneralOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when reinstatement for verifiers should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'ReinstatementVerificationOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time on the opening day when reinstatement for all members should appear on the dashboard', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'ReinstatementGeneralOpenTimeComponent'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates editing of parameters allowed (blocked for previous years)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationScheduleYear#Ext', 'COLUMN', N'IsEditEnabled'
GO
