SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPersonMailingAddress]
as
/*********************************************************************************************************************************
View    : dbo.vPersonMailingAddress
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.PersonMailingAddress - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.PersonMailingAddress table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vPersonMailingAddressExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vPersonMailingAddressExt documentation for details. To add additional content to this view, customize
the dbo.vPersonMailingAddressExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 pma.PersonMailingAddressSID
	,pma.PersonSID
	,pma.StreetAddress1
	,pma.StreetAddress2
	,pma.StreetAddress3
	,pma.CitySID
	,pma.PostalCode
	,pma.RegionSID
	,pma.EffectiveTime
	,pma.IsAdminReviewRequired
	,pma.LastVerifiedTime
	,pma.ChangeLog
	,pma.UserDefinedColumns
	,pma.PersonMailingAddressXID
	,pma.LegacyKey
	,pma.IsDeleted
	,pma.CreateUser
	,pma.CreateTime
	,pma.UpdateUser
	,pma.UpdateTime
	,pma.RowGUID
	,pma.RowStamp
	,pmax.CityName
	,pmax.StateProvinceSID
	,pmax.CityIsDefault
	,pmax.CityIsActive
	,pmax.CityIsAdminReviewRequired
	,pmax.CityRowGUID
	,pmax.RegionLabel
	,pmax.RegionName
	,pmax.RegionIsDefault
	,pmax.RegionIsActive
	,pmax.RegionRowGUID
	,pmax.GenderSID
	,pmax.NamePrefixSID
	,pmax.FirstName
	,pmax.CommonName
	,pmax.MiddleNames
	,pmax.LastName
	,pmax.BirthDate
	,pmax.DeathDate
	,pmax.HomePhone
	,pmax.MobilePhone
	,pmax.IsTextMessagingEnabled
	,pmax.ImportBatch
	,pmax.PersonRowGUID
	,pmax.IsDeleteEnabled
	,pmax.IsReselected
	,pmax.IsNullApplied
	,pmax.zContext
	,pmax.HtmlAddress
	,pmax.StateProvinceCode
	,pmax.StateProvinceName
	,pmax.ISOA3
	,pmax.CountryName
	,pmax.IsCurrentAddress
	,pmax.CountrySID
from
	dbo.PersonMailingAddress      pma
join
	dbo.vPersonMailingAddress#Ext pmax	on pma.PersonMailingAddressSID = pmax.PersonMailingAddressSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.PersonMailingAddress', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person mailing address assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'PersonMailingAddressSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this person mailing address is in', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this person mailing address', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new address through a profile update or renewal entered online).  The form can be configured to block automatic approval when addresses change in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'History of changes of audit interest made to the record', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'ChangeLog'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the person mailing address | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'PersonMailingAddressXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the person mailing address | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this person mailing address record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the person mailing address | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the person mailing address record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person mailing address record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The state province this city is in', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'StateProvinceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default city to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CityIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this city record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CityIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CityIsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the city record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the region to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the region to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default region to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this region record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the region record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'RegionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonMailingAddress', 'COLUMN', N'zContext'
GO
