SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vRegistrationSnapshot#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vRegistrationSnapshot#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.RegistrationSnapshot base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vRegistrationSnapshot (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rs.RegistrationSnapshotSID
	,rst.RegistrationSnapshotTypeLabel
	,rst.RegistrationSnapshotTypeSCD
	,rst.RegistrationSnapshotLabelTemplate
	,rst.IsDefault                                                          RegistrationSnapshotTypeIsDefault
	,rst.IsActive                                                           RegistrationSnapshotTypeIsActive
	,rst.RowGUID                                                            RegistrationSnapshotTypeRowGUID
	,jr.JobSID
	,jr.ConversationHandle
	,jr.StartTime
	,jr.EndTime
	,jr.TotalRecords
	,jr.TotalErrors
	,jr.RecordsProcessed
	,jr.CurrentProcessLabel
	,jr.IsFailed
	,jr.IsFailureCleared
	,jr.CancellationRequestTime
	,jr.IsCancelled
	,jr.RowGUID                                                             JobRunRowGUID
	,dbo.fRegistrationSnapshot#IsDeleteEnabled(rs.RegistrationSnapshotSID)  IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
--! <MoreColumns>
 ,cast(case when rs.LockedTime is not null then 1 else 0 end as bit)						 IsLocked
 ,(case when rs.LockedTime is null then sf.fIsSysAdmin() else cast(0 as bit)end) IsLockEnabled			--# Indicates whether lock option is available to prevent further editing (system-administrators only)
 ,(case when rs.LockedTime is null then cast(0 as bit)else sf.fIsSysAdmin() end) IsUnlockEnabled		--# Indicates whether un-lock option is available to enabled editing (system-administrators only)
 ,cast(case when rs.LockedTime is not null then 0 else 1 end as bit)						 IsUpdateEnabled		--# Indicates whether the UPDATE processing option is available (system-administrators only)
 ,zrp.ProfileCount																																									--# Total profile records in this snapshot
 ,zrp.InValidCount																																									--# Total invalid profile records in this snapshot
 ,zrp.ModifiedCount																																									--# Total records that have not been exported and are modified since the last export (all records if never exported)
 ,sf.fDTOffsetToClientDate(rs.QueuedTime)																				 QueuedDateCTZ			--# The queued date for editing (in the client timezone)
 ,cast(sf.fDTOffsetToClientDateTime(rs.QueuedTime) as time)											 QueuedTimeCTZ			--# The queued time for editing in the client timezone
 ,sf.fDTOffsetToClientDateTime(rs.QueuedTime)																		 QueuedDateTimeCTZ	--# The queued date time for display in the client timezone
 ,(case
		 when year(zrsy.YearStartTime) = year(zrsy.YearEndTime) then ltrim(zrsy.RegistrationYear)
		 else ltrim(year(zrsy.YearStartTime)) + '/' + ltrim(year(zrsy.YearEndTime))
	 end
	)																																							 RegistrationYearLabel
 ,(case
		 when rs.JobRunSID is not null then zjr.JobStatusLabel
		 when zrp.ProfileCount > 0 then 'Complete (No Job)'
		 when rs.QueuedTime is not null then 'Pending'
		 else 'Unknown'
	 end
	)																																							 SnapshotStatusLabel
 ,(case
		 when rs.LastCodeUpdateTime is null then 'Pending'
		 else format(sf.fDTOffsetToClientDateTime(rs.LastCodeUpdateTime), 'dd-MMM-yyy hh:mm tt')
	 end
	)																																							 LastCodeUpdateStatus
 ,(case
		 when rs.LastVerifiedTime is null then 'Pending'
		 else format(sf.fDTOffsetToClientDateTime(rs.LastCodeUpdateTime), 'dd-MMM-yyy hh:mm tt')
	 end
	)																																							 LastVerifiedStatus
--! </MoreColumns>
from
	dbo.RegistrationSnapshot     rs
join
	dbo.RegistrationSnapshotType rst    on rs.RegistrationSnapshotTypeSID = rst.RegistrationSnapshotTypeSID
left outer join
	sf.JobRun                    jr     on rs.JobRunSID = jr.JobRunSID
--! <MoreJoins>
left outer join
	dbo.RegistrationScheduleYear					 zrsy on rs.RegistrationYear = zrsy.RegistrationYear
left outer join
(
	select
		rp.RegistrationSnapshotSID
	 ,count(1)												ProfileCount
	 ,sum(cast(rp.IsInvalid as int))	InValidCount
	 ,sum(cast(rp.IsModified as int)) ModifiedCount
	from
		dbo.vRegistrationProfile rp
	group by
		rp.RegistrationSnapshotSID
)																				 zrp on rs.RegistrationSnapshotSID = zrp.RegistrationSnapshotSID
outer apply sf.fJobRun#Ext(rs.JobRunSID) zjr;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registration snapshot assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the registration snapshot type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the registration snapshot type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default registration snapshot type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this registration snapshot type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registration snapshot type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RegistrationSnapshotTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The job this run is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'JobSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An internal system value used to coordinate communication about job status within the SQL Server message broker service', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'ConversationHandle'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job began running', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'StartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job completed successfully, failed, or was cancelled | Job run records where this value is not filled in are considered to be running', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'EndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total count of records to process in the job (if set) | This value must be set by the job procedure at startup.  The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'TotalRecords'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of errors encountered during the job run | This value must be set by the job procedure as errors are encountered.  The value is used in status reporting and may be used to abort the job automatically if the error rate exceeds the max rate defined in the Job table (only applies where at least 100 records have been processed).', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'TotalErrors'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The count of records processed in the job so far (if set) | This value must be set by the job procedure as records are processed. The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'RecordsProcessed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier displayed on the job monitoring screen in the UI advising the user what stage or operation is currently being carried out by the job - e.g. "Retrieving Records ..." | Note that the value can be replaced for display on the UI by defining a mapping record in sf.TermLabel', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'CurrentProcessLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job ended in an error or was aborted because the maximum error ratio, as defined in the Job table, was exceeded', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsFailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that the failed status of the job has been cleared so that it can be run again if a "max retry on failure" limit was set for the job | This value is only enabled in the UI if the job run is showing a failed status', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsFailureCleared'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time a request to cancel the job was made | If the job is non-responsive, the cancellation will not occur and the job must be set to Failed manually from the Job Management screen', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'CancellationRequestTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job was cancelled before it completed', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the job run record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'JobRunRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether lock option is available to prevent further editing (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsLockEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether un-lock option is available to enabled editing (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsUnlockEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the UPDATE processing option is available (system-administrators only)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'IsUpdateEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total profile records in this snapshot', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'ProfileCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total invalid profile records in this snapshot', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'InValidCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Total records that have not been exported and are modified since the last export (all records if never exported)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'ModifiedCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued date for editing (in the client timezone)', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'QueuedDateCTZ'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued time for editing in the client timezone', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'QueuedTimeCTZ'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The queued date time for display in the client timezone', 'SCHEMA', N'dbo', 'VIEW', N'vRegistrationSnapshot#Ext', 'COLUMN', N'QueuedDateTimeCTZ'
GO
