SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPayment#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vPayment#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.Payment base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vPayment (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 payment.PaymentSID
	,ps.PaymentStatusSCD
	,ps.PaymentStatusLabel
	,ps.IsPaid
	,ps.PaymentStatusSequence
	,ps.RowGUID                                                             PaymentStatusRowGUID
	,ptype.PaymentTypeSCD
	,ptype.PaymentTypeLabel
	,ptype.PaymentTypeCategory
	,ptype.GLAccountSID
	,ptype.PaymentStatusSID                                                 PaymentTypePaymentStatusSID
	,ptype.IsReferenceRequired
	,ptype.DepositDateLagDays
	,ptype.IsRefundExcludedFromGL
	,ptype.ExcludeDepositFromGLBefore
	,ptype.IsDefault                                                        PaymentTypeIsDefault
	,ptype.IsActive                                                         PaymentTypeIsActive
	,ptype.RowGUID                                                          PaymentTypeRowGUID
	,person.GenderSID
	,person.NamePrefixSID
	,person.FirstName
	,person.CommonName
	,person.MiddleNames
	,person.LastName
	,person.BirthDate
	,person.DeathDate
	,person.HomePhone
	,person.MobilePhone
	,person.IsTextMessagingEnabled
	,person.ImportBatch
	,person.RowGUID                                                         PersonRowGUID
	,reason.ReasonGroupSID
	,reason.ReasonName
	,reason.ReasonCode
	,reason.ReasonSequence
	,reason.ToolTip
	,reason.IsActive                                                        ReasonIsActive
	,reason.RowGUID                                                         ReasonRowGUID
	,dbo.fPayment#IsDeleteEnabled(payment.PaymentSID)                       IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
--! <MoreColumns>
 ,dbo.fRegistrant#Label(person.LastName, person.FirstName, person.MiddleNames, r.RegistrantNo, 'REGISTRANT') + ' '
	+ cast(sf.fDTOffsetToClientDate(payment.CreateTime) as varchar(10)) + ' ' + format(payment.AmountPaid, 'C')																				PaymentLabel						--# display label for the payment to use select among payments to apply
 ,'#' + ltrim(payment.PaymentSID) + ' ' + cast(sf.fDTOffsetToClientDate(payment.CreateTime) as varchar(10)) + ' ' + format(payment.AmountPaid, 'C') PaymentShortLabel				--# a shorter form of the display label to use when registrant is known
 ,dbo.fRegistrant#Label(person.LastName, person.FirstName, person.MiddleNames, r.RegistrantNo, 'REGISTRANT')																				RegistrantLabel					--# display label for the registrant or user making the payment
 ,cast(case when left(ptype.PaymentTypeSCD, 3) = 'PP.' then 1 else 0 end as bit)																																		IsOnlinePayment					--# Indicates whether the payment type goes through an online payment processor
 ,zta.TotalApplied																																																																													--# Amount of the payment which has been applied to invoices	
 ,zta.TotalUnapplied																																																																												--# Amount remaining from the payment which can be applied to other invoices or refunded if no other invoices exist
 ,zta.IsFullyApplied																																																																												--# Indicates if this payment has been fully applied (no amount remaining to apply)
 ,zta.IsNotApplied																																																																													--# Indicates if no amount has yet been applied to an invoice from this payment
 ,zta.IsPartiallyApplied																																																																										--# Indicates if the payment is partially applied to invoices (more amount remains to be applied)
 ,zta.IsOverApplied																																																																													--# Indicates if amount applied is greater than the amount originally paid (this is an ERROR condition)
 ,cast((case when payment.CancelledTime is null then 0 else 1 end) as bit)																																					IsCancelled							--# Indicates the payment has been cancelled
 ,cast(case
				 when payment.CancelledTime is null and sf.fIsSysAdmin() = cast(1 as bit) then 1
				 when payment.CancelledTime is null and (left(ptype.PaymentTypeSCD, 3) <> 'PP.' or ps.PaymentStatusSCD = 'PENDING' or payment.AmountPaid = 0.00) then 1
				 else 0
			 end as bit)																																																																	IsCancelEnabled					--# Indicates whether cancellation of the current payment is allowed
 ,case when payment.CancelledTime is null and payment.AmountPaid <> 0.00 then sf.fIsGranted('ADMIN.ACCOUNTING') else cast(0 as bit)end							IsEditEnabled						--# Indicates if current user can edit the payment
 ,checksum(payment.GLPostingDate, payment.GLAccountCode, payment.AmountPaid, payment.PaymentStatusSID)																							GLCheckSum							--# Used by the system to detect changes to the record impacting GL transactions
 ,zlpr.LatestTransactionID
 ,zlpr.LatestChargeTotal
 ,zlpr.LatestResponseCode
 ,zlpr.LatestMessage
 ,zlpr.LatestApprovalCode
 ,zlpr.LatestIsPaid
 ,zlpr.LatestVerifiedTime
 ,(case
		 when ps.PaymentStatusSCD = 'PENDING' -- when in a pending status check if response received
					and datediff(minute, payment.UpdateTime, sysdatetimeoffset()) > 15 -- if 15 minutes since last attempt
					and (zlpr.PaymentSID is null or zlpr.LatestIsPaid = cast(0 as bit)) then cast(1 as bit) -- no response or last response was declined - so allow a retry
		 else cast(0 as bit)																	-- response was received so retry is not allowed
	 end)																																																																							IsRetryEnabled					--# Indicates whether or not payment can be retried. Allowed when no response after 15 minutes
 ,(case
		 when ps.PaymentStatusSCD = 'PENDING' -- when in a pending status check if processor responded with a paid status
					and zlpr.PaymentSID is not null and zlpr.LatestIsPaid = cast(1 as bit) then cast(1 as bit) -- a response does exist for the processor
		 else cast(0 as bit)
	 end)																																																																							IsReapplyEnabled				--# Indicates an inconsistency exists between the response of the payment process and the status of the record
 ,isnull(dbo.fPayment#TransactionIDs(payment.PaymentSID), payment.Reference)																																				TransactionIDReference	--# Provides the transaction ID(s) for online payments and the manual reference (e.g. check no.) for other types
 ,convert(time, payment.VerifiedTime)																																																								VerifiedTimeComponent
 ,cast(null as int)																																																																	InvoiceSID							--# The invoice to be paid by this payment - used on Insert only
--! </MoreColumns>
from
	dbo.Payment       payment
join
	dbo.PaymentStatus ps      on payment.PaymentStatusSID = ps.PaymentStatusSID
join
	dbo.PaymentType   ptype   on payment.PaymentTypeSID = ptype.PaymentTypeSID
join
	sf.Person         person  on payment.PersonSID = person.PersonSID
left outer join
	dbo.Reason        reason  on payment.ReasonSID = reason.ReasonSID
--! <MoreJoins>
left outer join
	dbo.Registrant																	 r on person.PersonSID = r.PersonSID
outer apply dbo.fPayment#Total(payment.PaymentSID) zta
outer apply dbo.fPayment#LatestProcessorResponse(payment.PaymentSID) zlpr;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the payment assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the payment status | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentStatusSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the payment status to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentStatusLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this status indicates the payment is in good standing and money was successfully received (or is assumed to be received as in the case of a check).', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsPaid'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the payment status record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentStatusRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the payment type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the payment type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the glaccount assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'GLAccountSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The status of the payment type', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypePaymentStatusSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that the payment reference field must be filled in when checked.  This is normally required for check/cheque payment types.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsReferenceRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of days ahead of the date the transaction is recorded, payments of this type are expected to appear on the bank statement.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'DepositDateLagDays'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if refunds processed on this payment type should be exlcuded from reporting to external general ledgers. This value should be checked if refunds for this payment type are initiated in your GL program (typically as checks/cheques).', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsRefundExcludedFromGL'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Allows deposits for this payment type to be excluded from reporting to external GL when the transaction occurs prior to this date.  Typically only applies to PAP bank accounts for conversion period.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ExcludeDepositFromGLBefore'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default payment type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this payment type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the payment type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The reason group assigned to this reason', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ReasonGroupSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the reason to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ReasonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional code used to refer to this reason - most often applicable where reason coding is provided to external parties - e.g. Provider Directory, Workforce Planning authority, etc. ', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ReasonCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this reason record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ReasonIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the reason record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'ReasonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the payment to use select among payments to apply', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'a shorter form of the display label to use when registrant is known', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'PaymentShortLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'display label for the registrant or user making the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'RegistrantLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the payment type goes through an online payment processor', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsOnlinePayment'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount of the payment which has been applied to invoices	', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'TotalApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Amount remaining from the payment which can be applied to other invoices or refunded if no other invoices exist', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'TotalUnapplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this payment has been fully applied (no amount remaining to apply)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsFullyApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if no amount has yet been applied to an invoice from this payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsNotApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the payment is partially applied to invoices (more amount remains to be applied)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsPartiallyApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if amount applied is greater than the amount originally paid (this is an ERROR condition)', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsOverApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the payment has been cancelled', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether cancellation of the current payment is allowed', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsCancelEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if current user can edit the payment', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsEditEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used by the system to detect changes to the record impacting GL transactions', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'GLCheckSum'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether or not payment can be retried. Allowed when no response after 15 minutes', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsRetryEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates an inconsistency exists between the response of the payment process and the status of the record', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'IsReapplyEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Provides the transaction ID(s) for online payments and the manual reference (e.g. check no.) for other types', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'TransactionIDReference'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The invoice to be paid by this payment - used on Insert only', 'SCHEMA', N'dbo', 'VIEW', N'vPayment#Ext', 'COLUMN', N'InvoiceSID'
GO
