SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vLearningRequirementCompetenceType]
as
/*********************************************************************************************************************************
View    : dbo.vLearningRequirementCompetenceType
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.LearningRequirementCompetenceType - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.LearningRequirementCompetenceType table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vLearningRequirementCompetenceTypeExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vLearningRequirementCompetenceTypeExt documentation for details. To add additional content to this view, customize
the dbo.vLearningRequirementCompetenceTypeExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 lrct.LearningRequirementCompetenceTypeSID
	,lrct.LearningRequirementSID
	,lrct.CompetenceTypeSID
	,lrct.UserDefinedColumns
	,lrct.LearningRequirementCompetenceTypeXID
	,lrct.LegacyKey
	,lrct.IsDeleted
	,lrct.CreateUser
	,lrct.CreateTime
	,lrct.UpdateUser
	,lrct.UpdateTime
	,lrct.RowGUID
	,lrct.RowStamp
	,lrctx.CompetenceTypeLabel
	,lrctx.CompetenceTypeCategory
	,lrctx.CompetenceTypeIsDefault
	,lrctx.CompetenceTypeIsActive
	,lrctx.CompetenceTypeRowGUID
	,lrctx.PracticeRegisterSID
	,lrctx.LearningRequirementLabel
	,lrctx.StartingRegistrationYear
	,lrctx.Minimum
	,lrctx.Maximum
	,lrctx.MaximumCarryOver
	,lrctx.LearningRequirementRowGUID
	,lrctx.IsDeleteEnabled
	,lrctx.IsReselected
	,lrctx.IsNullApplied
	,lrctx.zContext
from
	dbo.LearningRequirementCompetenceType      lrct
join
	dbo.vLearningRequirementCompetenceType#Ext lrctx	on lrct.LearningRequirementCompetenceTypeSID = lrctx.LearningRequirementCompetenceTypeSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.LearningRequirementCompetenceType', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the learning requirement competence type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LearningRequirementCompetenceTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the learning requirement assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LearningRequirementSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the competence type assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the learning requirement competence type | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LearningRequirementCompetenceTypeXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the learning requirement competence type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this learning requirement competence type record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the learning requirement competence type | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the learning requirement competence type record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the learning requirement competence type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the competence type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default competence type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this competence type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the competence type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'CompetenceTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The practice register assigned to this learning requirement', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'PracticeRegisterSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the learning requirement to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LearningRequirementLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The maximum number of units that can be applied to the next cycle when the minimum units are exceeded - enter 9999 for unlimited, default is 0 (no carry over)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'MaximumCarryOver'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the learning requirement record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'LearningRequirementRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see functi', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vLearningRequirementCompetenceType', 'COLUMN', N'zContext'
GO
