SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPersonNote#Ext]
as
/*********************************************************************************************************************************
View    : dbo.vPersonNote#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the dbo.PersonNote base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vPersonNote (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 pn.PersonNoteSID
	,pnt.PersonNoteTypeLabel
	,pnt.PersonNoteTypeCategory
	,pnt.IsDefault                                                          PersonNoteTypeIsDefault
	,pnt.IsActive                                                           PersonNoteTypeIsActive
	,pnt.RowGUID                                                            PersonNoteTypeRowGUID
	,person.GenderSID
	,person.NamePrefixSID
	,person.FirstName
	,person.CommonName
	,person.MiddleNames
	,person.LastName
	,person.BirthDate
	,person.DeathDate
	,person.HomePhone
	,person.MobilePhone
	,person.IsTextMessagingEnabled
	,person.ImportBatch
	,person.RowGUID                                                         PersonRowGUID
	,ag.ApplicationGrantSCD
	,ag.ApplicationGrantName
	,ag.IsDefault                                                           ApplicationGrantIsDefault
	,ag.RowGUID                                                             ApplicationGrantRowGUID
	,dbo.fPersonNote#IsDeleteEnabled(pn.PersonNoteSID)                      IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
																																														--! <MoreColumns>
 ,dbo.fPersonNote#IsReadGranted(pn.PersonNoteSID, ag.ApplicationGrantSCD) IsReadGranted			--# Indicates if the current session user has access to view the note record
 ,isnull(pn.NoteTitle, left(pn.NoteContent, 65))													NoteDisplayTitle	--# A title for the note - uses first part of note content if no title specified
--! </MoreColumns>
from
	dbo.PersonNote      pn
join
	dbo.PersonNoteType  pnt    on pn.PersonNoteTypeSID = pnt.PersonNoteTypeSID
join
	sf.Person           person on pn.PersonSID = person.PersonSID
left outer join
	sf.ApplicationGrant ag     on pn.ApplicationGrantSID = ag.ApplicationGrantSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person note assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the person note type to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default person note type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this person note type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person note type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonNoteTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the application grant | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'ApplicationGrantSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the application grant to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'ApplicationGrantName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default application grant to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'ApplicationGrantIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application grant record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'ApplicationGrantRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the current session user has access to view the note record', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'IsReadGranted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A title for the note - uses first part of note content if no title specified', 'SCHEMA', N'dbo', 'VIEW', N'vPersonNote#Ext', 'COLUMN', N'NoteDisplayTitle'
GO
