SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vCity]
as
/*********************************************************************************************************************************
View    : dbo.vCity
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.City - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.City table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vCityExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vCityExt documentation for details. To add additional content to this view, customize
the dbo.vCityExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 city.CitySID
	,city.CityName
	,city.StateProvinceSID
	,city.IsDefault
	,city.IsActive
	,city.IsAdminReviewRequired
	,city.ChangeLog
	,city.UserDefinedColumns
	,city.CityXID
	,city.LegacyKey
	,city.IsDeleted
	,city.CreateUser
	,city.CreateTime
	,city.UpdateUser
	,city.UpdateTime
	,city.RowGUID
	,city.RowStamp
	,cityx.StateProvinceName
	,cityx.StateProvinceCode
	,cityx.CountrySID
	,cityx.ISONumber
	,cityx.IsDisplayed
	,cityx.StateProvinceIsDefault
	,cityx.StateProvinceIsActive
	,cityx.StateProvinceIsAdminReviewRequired
	,cityx.StateProvinceRowGUID
	,cityx.IsDeleteEnabled
	,cityx.IsReselected
	,cityx.IsNullApplied
	,cityx.zContext
	,cityx.CitySearch
from
	dbo.City      city
join
	dbo.vCity#Ext cityx	on city.CitySID = cityx.CitySID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.City', 'SCHEMA', N'dbo', 'VIEW', N'vCity', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the city assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The state province this city is in', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default city to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this city record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'History of changes of audit interest made to the record', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'ChangeLog'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the city | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CityXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the city | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this city record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the city | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the city record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the city record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the state province to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The country assigned to this state province', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'CountrySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A number to refer to the state or province using a coding standard - e.g. the  ISO 3166 standard for principal subdivisions of countries', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'ISONumber'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default state province to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this state province record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceIsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the state province record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'StateProvinceRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vCity', 'COLUMN', N'zContext'
GO
