SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vOrg]
as
/*********************************************************************************************************************************
View    : dbo.vOrg
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for dbo.Org - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the dbo.Org table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to dbo.vOrgExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See dbo.vOrgExt documentation for details. To add additional content to this view, customize
the dbo.vOrgExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 o.OrgSID
	,o.ParentOrgSID
	,o.OrgTypeSID
	,o.OrgName
	,o.OrgLabel
	,o.StreetAddress1
	,o.StreetAddress2
	,o.StreetAddress3
	,o.CitySID
	,o.PostalCode
	,o.RegionSID
	,o.Phone
	,o.Fax
	,o.WebSite
	,o.EmailAddress
	,o.InsuranceOrgSID
	,o.InsurancePolicyNo
	,o.InsuranceAmount
	,o.IsEmployer
	,o.IsCredentialAuthority
	,o.IsInsurer
	,o.IsInsuranceCertificateRequired
	,o.IsPublic
	,o.Comments
	,o.TagList
	,o.IsActive
	,o.IsAdminReviewRequired
	,o.LastVerifiedTime
	,o.ChangeLog
	,o.UserDefinedColumns
	,o.OrgXID
	,o.LegacyKey
	,o.IsDeleted
	,o.CreateUser
	,o.CreateTime
	,o.UpdateUser
	,o.UpdateTime
	,o.RowGUID
	,o.RowStamp
	,ox.CityName
	,ox.StateProvinceSID
	,ox.CityIsDefault
	,ox.CityIsActive
	,ox.CityIsAdminReviewRequired
	,ox.CityRowGUID
	,ox.OrgTypeName
	,ox.OrgTypeCode
	,ox.SectorCode
	,ox.OrgTypeCategory
	,ox.OrgTypeIsDefault
	,ox.OrgTypeIsActive
	,ox.OrgTypeRowGUID
	,ox.RegionLabel
	,ox.RegionName
	,ox.RegionIsDefault
	,ox.RegionIsActive
	,ox.RegionRowGUID
	,ox.IsDeleteEnabled
	,ox.IsReselected
	,ox.IsNullApplied
	,ox.zContext
	,ox.FullOrgLabel
	,ox.StateProvinceName
	,ox.StateProvinceCode
	,ox.CountrySID
	,ox.CountryName
	,ox.CredentialCount
	,ox.QualifiedCredentialCount
	,ox.EmploymentCount
	,ox.NextReviewTime
	,ox.IsNextReviewDue
	,ox.IsInsuranceEnabled
	,ox.OrgNameEffectiveDate
from
	dbo.Org      o
join
	dbo.vOrg#Ext ox	on o.OrgSID = ox.OrgSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'dbo.Org', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the org assigned by the system | Primary key - not editable', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'EmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Additional comments or notes related to the organization.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'Comments'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'LastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'History of changes of audit interest made to the record', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'ChangeLog'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the org | Forms customization is required to access extended XML content', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the org | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this org record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the org | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the org record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The state province this city is in', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'StateProvinceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default city to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CityIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this city record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CityIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added through conversion or an address entered online)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CityIsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the city record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org type to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional value used for external reporting of the oranization sector - e.g. "14" and "24" are the CIHI codes for Public and Private sectors', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'SectorCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize these types', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default org type to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the region to present in lists and look ups (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the region to display on search results and reports (must be unique)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default region to assign when new records are added', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this region record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the region record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'RegionRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Organization label including all parent organizations separated by a dash', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'FullOrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of credentials this organization is a certifying authority for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'CredentialCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of credentials this organization is a certifying authority for', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'QualifiedCredentialCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of times this organization appears as an employer on registrant-employment records', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'EmploymentCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the next review is due to occur', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'NextReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the organization name was first effective (blank if unknown)', 'SCHEMA', N'dbo', 'VIEW', N'vOrg', 'COLUMN', N'OrgNameEffectiveDate'
GO
