SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vJobRunError#Ext]
as
/*********************************************************************************************************************************
View    : sf.vJobRunError#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the sf.JobRunError base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vJobRunError (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 jre.JobRunErrorSID
	,jr.JobSID
	,jr.ConversationHandle
	,jr.StartTime
	,jr.EndTime
	,jr.TotalRecords
	,jr.TotalErrors
	,jr.RecordsProcessed
	,jr.CurrentProcessLabel
	,jr.IsFailed
	,jr.IsFailureCleared
	,jr.CancellationRequestTime
	,jr.IsCancelled
	,jr.RowGUID                                                             JobRunRowGUID
	,sf.fJobRunError#IsDeleteEnabled(jre.JobRunErrorSID)                    IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
  --! </MoreColumns>
from
	sf.JobRunError jre
join
	sf.JobRun      jr     on jre.JobRunSID = jr.JobRunSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the job run error assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'JobRunErrorSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The job this run is defined for', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'JobSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An internal system value used to coordinate communication about job status within the SQL Server message broker service', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'ConversationHandle'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job began running', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'StartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the job completed successfully, failed, or was cancelled | Job run records where this value is not filled in are considered to be running', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'EndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total count of records to process in the job (if set) | This value must be set by the job procedure at startup.  The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'TotalRecords'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of errors encountered during the job run | This value must be set by the job procedure as errors are encountered.  The value is used in status reporting and may be used to abort the job automatically if the error rate exceeds the max rate defined in the Job table (only applies where at least 100 records have been processed).', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'TotalErrors'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The count of records processed in the job so far (if set) | This value must be set by the job procedure as records are processed. The value is used for calculating percent complete and estimated time of completion.', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'RecordsProcessed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier displayed on the job monitoring screen in the UI advising the user what stage or operation is currently being carried out by the job - e.g. "Retrieving Records ..." | Note that the value can be replaced for display on the UI by defining a mapping record in sf.TermLabel', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'CurrentProcessLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job ended in an error or was aborted because the maximum error ratio, as defined in the Job table, was exceeded', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsFailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that the failed status of the job has been cleared so that it can be run again if a "max retry on failure" limit was set for the job | This value is only enabled in the UI if the job run is showing a failed status', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsFailureCleared'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time a request to cancel the job was made | If the job is non-responsive, the cancellation will not occur and the job must be set to Failed manually from the Job Management screen', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'CancellationRequestTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the job was cancelled before it completed', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the job run record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'JobRunRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vJobRunError#Ext', 'COLUMN', N'zContext'
GO
