SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vDataSource]
as
/*********************************************************************************************************************************
View    : sf.vDataSource
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.DataSource - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.DataSource table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vDataSourceExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vDataSourceExt documentation for details. To add additional content to this view, customize
the sf.vDataSourceExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 ds.DataSourceSID
	,ds.DataSourceLabel
	,ds.DBObjectName
	,ds.ToolTip
	,ds.FileFormatSID
	,ds.ExportDefaults
	,ds.LastExecuteTime
	,ds.LastExecuteUser
	,ds.ExecuteCount
	,ds.UserDefinedColumns
	,ds.DataSourceXID
	,ds.LegacyKey
	,ds.IsDeleted
	,ds.CreateUser
	,ds.CreateTime
	,ds.UpdateUser
	,ds.UpdateTime
	,ds.RowGUID
	,ds.RowStamp
	,dsx.FileFormatSCD
	,dsx.FileFormatLabel
	,dsx.FileFormatIsDefault
	,dsx.FileFormatRowGUID
	,dsx.IsDeleteEnabled
	,dsx.IsReselected
	,dsx.IsNullApplied
	,dsx.zContext
from
	sf.DataSource      ds
join
	sf.vDataSource#Ext dsx	on ds.DataSourceSID = dsx.DataSourceSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.DataSource', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the data source assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'DataSourceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the data source to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'DataSourceLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name of the database table, view or table-function | This is the technical name in the schema', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'DBObjectName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A brief description to show to end-users selecting from among available data sources (e.g. for export)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the file format assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'FileFormatSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A list of defaults to apply when the data source is selected for export (columns to include, sort order, file-name, etc.)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'ExportDefaults'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time this query was last used | This value can be helpful in determining queries which are not being used and can be removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'LastExecuteTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The identity of the user who last used this query | This value can be helpful in investigating queries which are not being used to ensure they are removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'LastExecuteUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of times this query has been used | This value can be helpful in determining queries which are not being used and can be removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'ExecuteCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the data source | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'DataSourceXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the data source | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this data source record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the data source | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the data source record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the data source record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the file format | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'FileFormatSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the file format to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'FileFormatLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default file format to assign when new records are added', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'FileFormatIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the file format record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'FileFormatRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSource', 'COLUMN', N'zContext'
GO
