SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vPersonGroupMember#Ext]
as
/*********************************************************************************************************************************
View    : sf.vPersonGroupMember#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the sf.PersonGroupMember base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vPersonGroupMember (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 pgm.PersonGroupMemberSID
	,person.GenderSID
	,person.NamePrefixSID
	,person.FirstName
	,person.CommonName
	,person.MiddleNames
	,person.LastName
	,person.BirthDate
	,person.DeathDate
	,person.HomePhone
	,person.MobilePhone
	,person.IsTextMessagingEnabled
	,person.ImportBatch
	,person.RowGUID                                                         PersonRowGUID
	,pg.PersonGroupName
	,pg.PersonGroupLabel
	,pg.PersonGroupCategory
	,pg.Description
	,pg.ApplicationUserSID
	,pg.IsPreference
	,pg.IsDocumentLibraryEnabled
	,pg.QuerySID
	,pg.LastReviewUser
	,pg.LastReviewTime
	,pg.SmartGroupCount
	,pg.SmartGroupCountTime
	,pg.IsActive                                                            PersonGroupIsActive
	,pg.RowGUID                                                             PersonGroupRowGUID
	,sf.fIsActive(pgm.EffectiveTime, pgm.ExpiryTime)                        IsActive									--# Indicates if the assignment is currently active (not expired or future dated)
	,sf.fIsPending(pgm.EffectiveTime, pgm.ExpiryTime)                       IsPending									--# Indicates if the assignment will come into effect in the future
	,sf.fPersonGroupMember#IsDeleteEnabled(pgm.PersonGroupMemberSID)        IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
	--! <MoreColumns>
 ,sf.fFormatDisplayName(person.LastName, person.FirstName)																							 DisplayName						--# name of group member
 ,zpea.EmailAddress
 ,isnull(person.MobilePhone, person.HomePhone)																													 PhoneNumber						--# mobile (preferred) or home phone number
 ,cast(case when x.CurrentDateTime > pgm.ExpiryTime then 1 else 0 end as bit)														 IsTermExpired					--# Indicates whether the group member term is now over
 ,format(pgm.EffectiveTime, 'dd-MMM-yyyy') + isnull(' - ' + format(pgm.ExpiryTime, 'dd-MMM-yyyy'), ' -') TermLabel							-- a label showing effective and expiry dates for UI/reporting
 ,cast(case
				 when x.CurrentDateTime > pgm.ExpiryTime and pgm.IsReplacementRequiredAfterTerm = cast(1 as bit) and pgm.ReplacementClearedDate is null then 1
				 else 0
			 end as bit)																																											 IsReplacementRequired	--# Indicates that a replacement is required for this person
--! </MoreColumns>
from
	sf.PersonGroupMember pgm
join
	sf.Person            person on pgm.PersonSID = person.PersonSID
join
	sf.PersonGroup       pg     on pgm.PersonGroupSID = pg.PersonGroupSID
--! <MoreJoins>
left outer join
	sf.PersonEmailAddress						 zpea on pgm.PersonSID = zpea.PersonSID and zpea.IsPrimary = cast(1 as bit) and zpea.IsActive = cast(1 as bit)
cross apply
(select sf.fNow() CurrentDateTime) x;
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person group member assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupMemberSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the person group to display on search results and reports (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the person group to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize groups under', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this person group', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the member/client can manage membership in the group as a preference in their profile', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsPreference'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The query assigned to this person group', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'QuerySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Identity of the user (an administrator) who completed the last review of this group', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'LastReviewUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this group was last reviewed to ensure it is still required', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'LastReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The total number of group members the last time the  smart-group query was executed', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'SmartGroupCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the count of members in the smart group was last updated', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'SmartGroupCountTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this person group record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person group record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PersonGroupRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment is currently active (not expired or future dated)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment will come into effect in the future', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsPending'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'name of group member', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'DisplayName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'mobile (preferred) or home phone number', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'PhoneNumber'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the group member term is now over', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsTermExpired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that a replacement is required for this person', 'SCHEMA', N'sf', 'VIEW', N'vPersonGroupMember#Ext', 'COLUMN', N'IsReplacementRequired'
GO
