SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vPersonEmailAddress]
as
/*********************************************************************************************************************************
View    : sf.vPersonEmailAddress
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.PersonEmailAddress - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.PersonEmailAddress table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vPersonEmailAddressExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vPersonEmailAddressExt documentation for details. To add additional content to this view, customize
the sf.vPersonEmailAddressExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 pea.PersonEmailAddressSID
	,pea.PersonSID
	,pea.EmailAddress
	,pea.IsPrimary
	,pea.IsActive
	,pea.ChangeAudit
	,pea.UserDefinedColumns
	,pea.PersonEmailAddressXID
	,pea.LegacyKey
	,pea.IsDeleted
	,pea.CreateUser
	,pea.CreateTime
	,pea.UpdateUser
	,pea.UpdateTime
	,pea.RowGUID
	,pea.RowStamp
	,peax.GenderSID
	,peax.NamePrefixSID
	,peax.FirstName
	,peax.CommonName
	,peax.MiddleNames
	,peax.LastName
	,peax.BirthDate
	,peax.DeathDate
	,peax.HomePhone
	,peax.MobilePhone
	,peax.IsTextMessagingEnabled
	,peax.ImportBatch
	,peax.PersonRowGUID
	,peax.ChangeReason
	,peax.IsDeleteEnabled
	,peax.IsReselected
	,peax.IsNullApplied
	,peax.zContext
	,peax.IsEmailUsedForLogin
from
	sf.PersonEmailAddress      pea
join
	sf.vPersonEmailAddress#Ext peax	on pea.PersonEmailAddressSID = peax.PersonEmailAddressSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.PersonEmailAddress', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person email address assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'PersonEmailAddressSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this email address is based on', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this person email address record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'History of changes to the active status of the email address | Shows date, time and user where active status was toggled on/off.', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'ChangeAudit'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the person email address | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'PersonEmailAddressXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the person email address | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this person email address record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the person email address | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the person email address record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person email address record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'FirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'LastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Virtual column to capture latest reason for change that is written into audit log column', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'ChangeReason'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether this email, if primary, should be used for the login profile (defaults to YES)', 'SCHEMA', N'sf', 'VIEW', N'vPersonEmailAddress', 'COLUMN', N'IsEmailUsedForLogin'
GO
