SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vBusinessRule]
as
/*********************************************************************************************************************************
View    : sf.vBusinessRule
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.BusinessRule - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.BusinessRule table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vBusinessRuleExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vBusinessRuleExt documentation for details. To add additional content to this view, customize
the sf.vBusinessRuleExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 br.BusinessRuleSID
	,br.ApplicationEntitySID
	,br.MessageSID
	,br.ColumnName
	,br.BusinessRuleStatus
	,br.UserDefinedColumns
	,br.BusinessRuleXID
	,br.LegacyKey
	,br.IsDeleted
	,br.CreateUser
	,br.CreateTime
	,br.UpdateUser
	,br.UpdateTime
	,br.RowGUID
	,br.RowStamp
	,brx.ApplicationEntitySCD
	,brx.ApplicationEntityName
	,brx.IsMergeDataSource
	,brx.ApplicationEntityRowGUID
	,brx.MessageSCD
	,brx.MessageName
	,brx.MessageText
	,brx.MessageTextUpdateTime
	,brx.DefaultText
	,brx.DefaultTextUpdateTime
	,brx.MessageRowGUID
	,brx.IsDeleteEnabled
	,brx.IsReselected
	,brx.IsNullApplied
	,brx.zContext
	,brx.IsMandatory
	,brx.SchemaName
	,brx.TableName
	,brx.TableObjectID
	,brx.IsNewStatusOn
	,brx.RuleStatusLabel
	,brx.DataStatusLabel
from
	sf.BusinessRule      br
join
	sf.vBusinessRule#Ext brx	on br.BusinessRuleSID = brx.BusinessRuleSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.BusinessRule', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the business rule assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'BusinessRuleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this business rule', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The message assigned to this business rule', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'MessageSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The column name the rule applies to.  Required to distinguish betweeen rules when the same message is used on multiple columns in the same table.  If a rule involves multiple columns, choose the first column involved as it appears in the UI.', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'ColumnName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates whether rule is o-n, x-off, or p-ending (turned on but rule check not yet run on table)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'BusinessRuleStatus'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the business rule | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'BusinessRuleXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the business rule | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this business rule record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the business rule | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the business rule record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the business rule record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the application entity | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'ApplicationEntitySCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the application entity to display on search results and reports (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'ApplicationEntityName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this application entity should be a source of replacement values for note templates | Only the core entities of the application should be established as merge-field data sources ', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'IsMergeDataSource'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application entity record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'ApplicationEntityRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the message | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'MessageSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the message to display on search results and reports (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'MessageName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the message record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'MessageRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vBusinessRule', 'COLUMN', N'zContext'
GO
