SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vDataSourceApplicationPage]
as
/*********************************************************************************************************************************
View    : sf.vDataSourceApplicationPage
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.DataSourceApplicationPage - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.DataSourceApplicationPage table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vDataSourceApplicationPageExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vDataSourceApplicationPageExt documentation for details. To add additional content to this view, customize
the sf.vDataSourceApplicationPageExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 dsap.DataSourceApplicationPageSID
	,dsap.DataSourceSID
	,dsap.ApplicationPageSID
	,dsap.UserDefinedColumns
	,dsap.DataSourceApplicationPageXID
	,dsap.LegacyKey
	,dsap.IsDeleted
	,dsap.CreateUser
	,dsap.CreateTime
	,dsap.UpdateUser
	,dsap.UpdateTime
	,dsap.RowGUID
	,dsap.RowStamp
	,dsapx.ApplicationPageLabel
	,dsapx.ApplicationPageURI
	,dsapx.ApplicationRoute
	,dsapx.IsSearchPage
	,dsapx.ApplicationEntitySID
	,dsapx.ApplicationPageRowGUID
	,dsapx.DataSourceLabel
	,dsapx.DBObjectName
	,dsapx.ToolTip
	,dsapx.FileFormatSID
	,dsapx.LastExecuteTime
	,dsapx.LastExecuteUser
	,dsapx.ExecuteCount
	,dsapx.DataSourceRowGUID
	,dsapx.IsDeleteEnabled
	,dsapx.IsReselected
	,dsapx.IsNullApplied
	,dsapx.zContext
from
	sf.DataSourceApplicationPage      dsap
join
	sf.vDataSourceApplicationPage#Ext dsapx	on dsap.DataSourceApplicationPageSID = dsapx.DataSourceApplicationPageSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.DataSourceApplicationPage', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the data source application page assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DataSourceApplicationPageSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The data source this page is defined for', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DataSourceSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The page assigned to this data source', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationPageSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the data source application page | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DataSourceApplicationPageXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the data source application page | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this data source application page record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the data source application page | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the data source application page record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the data source application page record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the application page to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationPageLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The base link for the page in the application | This value is set by the development team and used as the basis for linking other components (reports, queries, etc.) to appear on the same page ', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationPageURI'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Technical information used by the application to identify the web page a link should go to | This values applies in Model-View-Controller architectures. This is the “route” used – controller + action – by the application.  The “Application Page URI” columns is provided for Silverlight architectures. This value is to navigate from tasks to the corresponding pages where work can be carried out and is also used in email links to navigate directly to action pages for the user. ', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationRoute'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this page supports query references being passed into it for automatic execution', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'IsSearchPage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this page', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application page record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ApplicationPageRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the data source to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DataSourceLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name of the database table, view or table-function | This is the technical name in the schema', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DBObjectName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A brief description to show to end-users selecting from among available data sources (e.g. for export)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ToolTip'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the file format assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'FileFormatSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time this query was last used | This value can be helpful in determining queries which are not being used and can be removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'LastExecuteTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The identity of the user who last used this query | This value can be helpful in investigating queries which are not being used to ensure they are removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'LastExecuteUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of times this query has been used | This value can be helpful in determining queries which are not being used and can be removed from the system', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'ExecuteCount'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the data source record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'DataSourceRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vDataSourceApplicationPage', 'COLUMN', N'zContext'
GO
