SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vTaskQueueSubscriber]
as
/*********************************************************************************************************************************
View    : sf.vTaskQueueSubscriber
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.TaskQueueSubscriber - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.TaskQueueSubscriber table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vTaskQueueSubscriberExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vTaskQueueSubscriberExt documentation for details. To add additional content to this view, customize
the sf.vTaskQueueSubscriberExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 tqs.TaskQueueSubscriberSID
	,tqs.TaskQueueSID
	,tqs.ApplicationUserSID
	,tqs.EffectiveTime
	,tqs.ExpiryTime
	,tqs.IsNewTaskEmailed
	,tqs.IsDailySummaryEmailed
	,tqs.ChangeAudit
	,tqs.UserDefinedColumns
	,tqs.TaskQueueSubscriberXID
	,tqs.LegacyKey
	,tqs.IsDeleted
	,tqs.CreateUser
	,tqs.CreateTime
	,tqs.UpdateUser
	,tqs.UpdateTime
	,tqs.RowGUID
	,tqs.RowStamp
	,tqsx.PersonSID
	,tqsx.CultureSID
	,tqsx.AuthenticationAuthoritySID
	,tqsx.UserName
	,tqsx.LastReviewTime
	,tqsx.LastReviewUser
	,tqsx.IsPotentialDuplicate
	,tqsx.IsTemplate
	,tqsx.GlassBreakPassword
	,tqsx.LastGlassBreakPasswordChangeTime
	,tqsx.ApplicationUserIsActive
	,tqsx.AuthenticationSystemID
	,tqsx.ApplicationUserRowGUID
	,tqsx.TaskQueueLabel
	,tqsx.TaskQueueCode
	,tqsx.IsAutoAssigned
	,tqsx.IsOpenSubscription
	,tqsx.TaskQueueApplicationUserSID
	,tqsx.TaskQueueIsActive
	,tqsx.TaskQueueIsDefault
	,tqsx.TaskQueueRowGUID
	,tqsx.IsActive
	,tqsx.IsPending
	,tqsx.ChangeReason
	,tqsx.IsDeleteEnabled
	,tqsx.IsReselected
	,tqsx.IsNullApplied
	,tqsx.zContext
	,tqsx.ApplicationUserDisplayName
from
	sf.TaskQueueSubscriber      tqs
join
	sf.vTaskQueueSubscriber#Ext tqsx	on tqs.TaskQueueSubscriberSID = tqsx.TaskQueueSubscriberSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.TaskQueueSubscriber', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the task queue subscriber assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueSubscriberSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The task queue this subscriber is defined for', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this task queue subscriber', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this subscription was put into effect or most recently changed | Check Change Audit column for history', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The ending time this subscription was effective.  When blank indicates subscription is active. | See Change Audit for history of subscription being turned on/off', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Directs the system to send an email to subscriber whenever a new task is assigned | It is recommended this value be left off for regular application users since open tasks are displayed on the dashboard', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsNewTaskEmailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Directs the system to send a daily email to the subscriber summarizing open and late tasks associated with this subscription | It is recommended this value be left off for regular application users since tasks status is displayed on the dashboard', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsDailySummaryEmailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'History of changes to this subscription | The UI prompts for a reason for disabling or re-enabling the subscription record and this reason, along with other audit information, is stored into this audit column.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ChangeAudit'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the task queue subscriber | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueSubscriberXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the task queue subscriber | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this task queue subscriber record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the task queue subscriber | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the task queue subscriber record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the task queue subscriber record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this user is based on', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The culture this user is assigned to', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'CultureSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The authentication authority used for logging in to the application (e.g. Google account) | For systems using Tenant Services for login, the value is copied from Tenant Services to the client database when the account is created.  The value of this column cannot be changed after the account is created (delete the account and recreate or create a new account).', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'AuthenticationAuthoritySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the identity of the user as recorded in Active Directory and using "user@domain" style - example:   tara.knowles@soa.com', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'UserName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'date and time this user profile was last reviewed to ensure it is still required', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'LastReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'identity of the user (usually an administrator) who completed the last review of this user profile', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'LastReviewUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When checked indicates this may be a duplicate user profile and requires review from an administrator', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsPotentialDuplicate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates this user will appear in the list of templates to copy from when creating new users - sets up same grants as starting point', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsTemplate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'stores the hashed value of a password applied by the user when seeking temporary elevated access to functions or data their profile does not normally provide', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'GlassBreakPassword'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this user profile last changed their glass-break password | This value remains blank until password is initially set.  If password is cleared later, the time the password is set to NULL is stored.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'LastGlassBreakPasswordChangeTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this application user record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ApplicationUserIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The GUID or similar identifier used by the authentication system to identify the user record | This value is used on federated logins (e.g. MS Account, Google Account) to identify the user since it is possible for the email captured in the UserName column to change over time.  The federated record identifier should not be captured into the UserName column since that value is used in the CreateUser and UpdateUser audit columns and GUID''s.  Note that where no federated provider is used (direct email login) this column is set to the same value as the RowGUID.  A bit in the entity view indicates whether the application user record is a federated login.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'AuthenticationSystemID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application user record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ApplicationUserRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the task queue to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates new users are automatically assigned to this queue | Note that value only impacts creation of new users.  If this setting is checked after users have already been created, they are not automatically assigned to the queue.', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsAutoAssigned'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that any user can assign themselves to this task queue', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsOpenSubscription'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this task queue', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this task queue record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default task queue to assign when new records are added', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the task queue record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'TaskQueueRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment is currently active (not expired or future dated)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the assignment will come into effect in the future', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsPending'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Virtual column to capture latest reason for change that is written into audit log column', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ChangeReason'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A label for the application user suitable for use on the UI and reports based on first name last name', 'SCHEMA', N'sf', 'VIEW', N'vTaskQueueSubscriber', 'COLUMN', N'ApplicationUserDisplayName'
GO
