SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vFormSubForm]
as
/*********************************************************************************************************************************
View    : sf.vFormSubForm
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.FormSubForm - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.FormSubForm table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vFormSubFormExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vFormSubFormExt documentation for details. To add additional content to this view, customize
the sf.vFormSubFormExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 fsf.FormSubFormSID
	,fsf.FormSID
	,fsf.SubFormSID
	,fsf.SubFormSequence
	,fsf.UserDefinedColumns
	,fsf.FormSubFormXID
	,fsf.LegacyKey
	,fsf.IsDeleted
	,fsf.CreateUser
	,fsf.CreateTime
	,fsf.UpdateUser
	,fsf.UpdateTime
	,fsf.RowGUID
	,fsf.RowStamp
	,fsfx.FormFormTypeSID
	,fsfx.FormFormName
	,fsfx.FormFormLabel
	,fsfx.FormFormContext
	,fsfx.FormAuthorCredit
	,fsfx.FormIsActive
	,fsfx.FormApplicationUserSID
	,fsfx.FormRowGUID
	,fsfx.FormSubFormTypeSID
	,fsfx.FormSubFormName
	,fsfx.FormSubFormLabel
	,fsfx.FormSubFormContext
	,fsfx.FormSubAuthorCredit
	,fsfx.FormSubIsActive
	,fsfx.FormSubApplicationUserSID
	,fsfx.FormSubRowGUID
	,fsfx.IsDeleteEnabled
	,fsfx.IsReselected
	,fsfx.IsNullApplied
	,fsfx.zContext
from
	sf.FormSubForm      fsf
join
	sf.vFormSubForm#Ext fsfx	on fsf.FormSubFormSID = fsfx.FormSubFormSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.FormSubForm', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the form sub form assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The form this sub is defined for', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The form this sub is defined for', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'SubFormSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the form sub form | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the form sub form | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this form sub form record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the form sub form | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the form sub form record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the form sub form record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the audit action assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormFormTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the form to display on search results and reports (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormFormName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the form to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormFormLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional identifier of the use-case or context where this form should be applied.  | This value enables 2 (or more) forms of the same type to be in effect at the same time.  By default the application chooses the latest published version but a context may be specified in the program code (e.g. a registration year) in which case the latest form for that context is selected.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormFormContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name, organization and other registrant information of the form''s author as along with any restrictions on use.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormAuthorCredit'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this form record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this form', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the form record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the audit action assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the form to display on search results and reports (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the form to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional identifier of the use-case or context where this form should be applied.  | This value enables 2 (or more) forms of the same type to be in effect at the same time.  By default the application chooses the latest published version but a context may be specified in the program code (e.g. a registration year) in which case the latest form for that context is selected.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubFormContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name, organization and other registrant information of the form''s author as along with any restrictions on use.', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubAuthorCredit'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this form record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this form', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the form record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'FormSubRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vFormSubForm', 'COLUMN', N'zContext'
GO
