SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vClearedAnnouncement]
as
/*********************************************************************************************************************************
View    : sf.vClearedAnnouncement
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.ClearedAnnouncement - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.ClearedAnnouncement table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vClearedAnnouncementExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vClearedAnnouncementExt documentation for details. To add additional content to this view, customize
the sf.vClearedAnnouncementExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 ca.ClearedAnnouncementSID
	,ca.AnnouncementSID
	,ca.ApplicationUserSID
	,ca.UserDefinedColumns
	,ca.ClearedAnnouncementXID
	,ca.LegacyKey
	,ca.IsDeleted
	,ca.CreateUser
	,ca.CreateTime
	,ca.UpdateUser
	,ca.UpdateTime
	,ca.RowGUID
	,ca.RowStamp
	,cax.Title
	,cax.AnnouncementText
	,cax.EffectiveTime
	,cax.ExpiryTime
	,cax.AdditionalInfoPageURI
	,cax.IsLoginAlert
	,cax.IsExtendedFormat
	,cax.AnnouncementRowGUID
	,cax.PersonSID
	,cax.CultureSID
	,cax.AuthenticationAuthoritySID
	,cax.UserName
	,cax.LastReviewTime
	,cax.LastReviewUser
	,cax.IsPotentialDuplicate
	,cax.IsTemplate
	,cax.GlassBreakPassword
	,cax.LastGlassBreakPasswordChangeTime
	,cax.ApplicationUserIsActive
	,cax.AuthenticationSystemID
	,cax.ApplicationUserRowGUID
	,cax.IsDeleteEnabled
	,cax.IsReselected
	,cax.IsNullApplied
	,cax.zContext
from
	sf.ClearedAnnouncement      ca
join
	sf.vClearedAnnouncement#Ext cax	on ca.ClearedAnnouncementSID = cax.ClearedAnnouncementSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.ClearedAnnouncement', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the cleared announcement assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ClearedAnnouncementSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The announcement assigned to this cleared', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'AnnouncementSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this cleared announcement', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the cleared announcement | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ClearedAnnouncementXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the cleared announcement | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this cleared announcement record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the cleared announcement | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the cleared announcement record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the cleared announcement record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Title of the announcement that appears as a heading on landing page control', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'Title'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time this announcement should first become available to users on the system | Announcements can be post dated to appear in the future', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'EffectiveTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A date (and optionally time) after which the announcement should no longer be displayed', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A link to a web page providing additional content on the announcement ', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'AdditionalInfoPageURI'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the announcement is displayed as an alert after login on the dashboard ', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsLoginAlert'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates all formatting for the announcement is embedded in the content (no standard wrapping applied by the application) | Used internally by the help desk to create custom-format announcements', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsExtendedFormat'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the announcement record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'AnnouncementRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this user is based on', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The culture this user is assigned to', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'CultureSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The authentication authority used for logging in to the application (e.g. Google account) | For systems using Tenant Services for login, the value is copied from Tenant Services to the client database when the account is created.  The value of this column cannot be changed after the account is created (delete the account and recreate or create a new account).', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'AuthenticationAuthoritySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the identity of the user as recorded in Active Directory and using "user@domain" style - example:   tara.knowles@soa.com', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'UserName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'date and time this user profile was last reviewed to ensure it is still required', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'LastReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'identity of the user (usually an administrator) who completed the last review of this user profile', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'LastReviewUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When checked indicates this may be a duplicate user profile and requires review from an administrator', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsPotentialDuplicate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates this user will appear in the list of templates to copy from when creating new users - sets up same grants as starting point', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsTemplate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'stores the hashed value of a password applied by the user when seeking temporary elevated access to functions or data their profile does not normally provide', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'GlassBreakPassword'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this user profile last changed their glass-break password | This value remains blank until password is initially set.  If password is cleared later, the time the password is set to NULL is stored.', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'LastGlassBreakPasswordChangeTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this application user record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ApplicationUserIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The GUID or similar identifier used by the authentication system to identify the user record | This value is used on federated logins (e.g. MS Account, Google Account) to identify the user since it is possible for the email captured in the UserName column to change over time.  The federated record identifier should not be captured into the UserName column since that value is used in the CreateUser and UpdateUser audit columns and GUID''s.  Note that where no federated provider is used (direct email login) this column is set to the same value as the RowGUID.  A bit in the entity view indicates whether the application user record is a federated login.', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'AuthenticationSystemID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application user record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'ApplicationUserRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vClearedAnnouncement', 'COLUMN', N'zContext'
GO
