SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vTask#Ext]
as
/*********************************************************************************************************************************
View    : sf.vTask#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the sf.Task base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vTask (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 task.TaskSID
	,tq.TaskQueueLabel
	,tq.TaskQueueCode
	,tq.IsAutoAssigned
	,tq.IsOpenSubscription
	,tq.ApplicationUserSID                                                  TaskQueueApplicationUserSID
	,tq.IsActive                                                            TaskQueueIsActive
	,tq.IsDefault                                                           TaskQueueIsDefault
	,tq.RowGUID                                                             TaskQueueRowGUID
	,ts.TaskStatusSCD
	,ts.TaskStatusLabel
	,ts.TaskStatusSequence
	,ts.IsDerived
	,ts.IsClosedStatus
	,ts.IsActive                                                            TaskStatusIsActive
	,ts.IsDefault                                                           TaskStatusIsDefault
	,ts.RowGUID                                                             TaskStatusRowGUID
	,tt.TaskTriggerLabel
	,tt.TaskTitleTemplate
	,tt.QuerySID
	,tt.TaskQueueSID                                                        TaskTriggerTaskQueueSID
	,tt.ApplicationUserSID                                                  TaskTriggerApplicationUserSID
	,tt.IsAlert                                                             TaskTriggerIsAlert
	,tt.PriorityLevel                                                       TaskTriggerPriorityLevel
	,tt.TargetCompletionDays
	,tt.OpenTaskLimit
	,tt.IsRegeneratedIfClosed
	,tt.ApplicationAction
	,tt.JobScheduleSID
	,tt.LastStartTime
	,tt.LastEndTime
	,tt.IsActive                                                            TaskTriggerIsActive
	,tt.RowGUID                                                             TaskTriggerRowGUID
	,ap.ApplicationPageLabel
	,ap.ApplicationPageURI
	,ap.ApplicationRoute
	,ap.IsSearchPage
	,ap.ApplicationEntitySID
	,ap.RowGUID                                                             ApplicationPageRowGUID
	,au.PersonSID
	,au.CultureSID
	,au.AuthenticationAuthoritySID
	,au.UserName
	,au.LastReviewTime
	,au.LastReviewUser
	,au.IsPotentialDuplicate
	,au.IsTemplate
	,au.GlassBreakPassword
	,au.LastGlassBreakPasswordChangeTime
	,au.IsActive                                                            ApplicationUserIsActive
	,au.AuthenticationSystemID
	,au.RowGUID                                                             ApplicationUserRowGUID
	,sf.fTask#IsDeleteEnabled(task.TaskSID)                                 IsDeleteEnabled						--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                     IsReselected							-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                         IsNullApplied							-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                      zContext									-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
	,case
		when task.ClosedTime is null and task.DueDate < sysdatetime()	then
			cast(1 as bit)
		else
			cast(0 as bit)
	 end																														 IsOverdue												--# indicates the task is overdue		
	,case
		when
			ts.TaskStatusSCD = 'OPEN'
		then
			cast(1 as bit)
		else
			cast(0 as bit)
		end
																																	 IsOpen														--# indicates the task is open
	,case
		when
			ts.TaskStatusSCD = 'CANCELLED'
		then
			cast(1 as bit)
		else
			cast(0 as bit)
		end																														 IsCancelled											--# indicates the task is cancelled
	,case
		when
			ts.TaskStatusSCD = 'CLOSED'
		then
			cast(1 as bit)
		else
			cast(0 as bit)
		end																														 IsClosed													--# indicates the task is closed
	,case
		when
			tqs.ApplicationUserSID is not null
		and
			sf.fIsDifferent(au.ApplicationUserSID, sf.fApplicationUserSessionUserSID()) = cast(1 as bit)
		and
			task.ClosedTime is null
		then
			cast(1 as bit)
		else
			cast(0 as bit)
	 end																														 IsTaskTakeOverEnabled						--# the task can be taken over by the logged in user
	,case
		when
			task.ClosedTime is null
		and
		(
			sf.fIsDifferent(au.ApplicationUserSID, sf.fApplicationUserSessionUserSID()) = cast(0 as bit)
		or
			tq.ApplicationUserSID = sf.fApplicationUserSessionUserSID()
		)
		then
			cast(1 as bit)
		else
			cast(0 as bit)
	 end																														 IsCloseEnabled										--# the task can be closed by the owner of the task or queue
	,case
		when
			sf.fIsDifferent(au.ApplicationUserSID, sf.fApplicationUserSessionUserSID()) = cast(0 as bit)
		or
			tq.ApplicationUserSID = sf.fApplicationUserSessionUserSID()
		then
			cast(1 as bit)
		else
			cast(0 as bit)
	 end																														 IsUpdateEnabled									--# the task can be updated by the owner of the task or queue
	,case
		when
			datediff(hh, ClosedTime, sysdatetimeoffset()) < 24
		then
			cast(1 as bit)
		else
			cast(0 as bit)
		end																														 IsClosedWithinADay								--# indicates the task has been closed within the last 24 hours
	,cast(null as nvarchar(250))																		 EntityLabel											--# the label for the entity (eg: Person) the task is targeted for | Override in product DB project to include supported entities--! </MoreColumns>from
from
	sf.Task            task
join
	sf.TaskQueue       tq     on task.TaskQueueSID = tq.TaskQueueSID
join
	sf.TaskStatus      ts     on task.TaskStatusSID = ts.TaskStatusSID
left outer join
	sf.TaskTrigger     tt     on task.TaskTriggerSID = tt.TaskTriggerSID
left outer join
	sf.ApplicationPage ap     on task.ApplicationPageSID = ap.ApplicationPageSID
left outer join
	sf.ApplicationUser au     on task.ApplicationUserSID = au.ApplicationUserSID
--! <MoreJoins>
left outer join	sf.TaskQueueSubscriber	tqs		on tqs.TaskQueueSID = tq.TaskQueueSID and tqs.ApplicationUserSID = sf.fApplicationUserSessionUserSID()
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the task assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the task queue to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskQueueLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates new users are automatically assigned to this queue | Note that value only impacts creation of new users.  If this setting is checked after users have already been created, they are not automatically assigned to the queue.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsAutoAssigned'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that any user can assign themselves to this task queue', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsOpenSubscription'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The user assigned to this task queue', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskQueueApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this task queue record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskQueueIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default task queue to assign when new records are added', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskQueueIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the task queue record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskQueueRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the task status | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the task status to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The order this status should appear in on the task (Kanban) board display', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusSequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the status is derived by the system. These types of statuses cannot be selected as parent statuses for Task Board columns.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsDerived'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates tasks in this status should be considered as closed by the application | This value cannot be set by the end user', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsClosedStatus'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this task status record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default task status to assign when new records are added', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the task status record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskStatusRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the task trigger to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The title to give the task created - may include replacement values | Replacement values available are defined by the application e.g. "{ContactName}"', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTitleTemplate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A reference to the query that locates records for which tasks need to be created | The query does not need to exclude records where open tasks already exist as duplicates are avoided by the built-in task trigger processor', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'QuerySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The task queue assigned to this task trigger', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerTaskQueueSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A reference to a specific application user if tasks generated by this trigger should automatically be assigned to the same person | This option is useful where one person is responsible for triaging and assigning all tasks in a queue (or there is only a single queue subscriber)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this task trigger should generate an "alert" type task | Alert tasks are created and assigned to all users in the queue', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerIsAlert'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A ranking value indicating the priority of this task compared with others - scale is 1-5 with "3" being medium (default) | The due date and this value are used to sort tasks in priority sequence on the user interface', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerPriorityLevel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Establishes the due date for tasks generated as the creation date + this number of days', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TargetCompletionDays'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Limits the total number of open tasks of this type allowed by the system - must be 1 or greater | This value is used in situations where the query may return hundreds or thousands of task records.  The limit ensures a manageable number of open tasks of this type will be allowed in the system at the same time.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'OpenTaskLimit'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates a new task should be created, even where a task for the record exists, if the old task is closed', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsRegeneratedIfClosed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This field contains technical information set by your configurator that controls the view the application displays when this task is accessed | This value applies in Model-View-Controller architectures. This is the "Action" called within the Controller when the user clicks/touches the task.   This data and the “Application Controller” value are used to complete the navigation. The “Application Page URI” columns is provided for Silverlight architectures. This value is included on the Task record as well as on the Task Trigger to allow users to create navigating-tasks, such as from the Application User module.   In these situations the application sets the value directly.  For task triggers, the value must be set by the configurator.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationAction'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the job schedule assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'JobScheduleSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time processing for this specific task trigger began | This value is used in determining when the trigger should be run next when a schedule is assigned', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'LastStartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The time the trigger completed successfully, failed, or was cancelled through the Task Trigger job | Records where this value is not filled in are considered to be running', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'LastEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this task trigger record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the task trigger record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'TaskTriggerRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the application page to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationPageLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The base link for the page in the application | This value is set by the development team and used as the basis for linking other components (reports, queries, etc.) to appear on the same page ', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationPageURI'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Technical information used by the application to identify the web page a link should go to | This values applies in Model-View-Controller architectures. This is the “route” used – controller + action – by the application.  The “Application Page URI” columns is provided for Silverlight architectures. This value is to navigate from tasks to the corresponding pages where work can be carried out and is also used in email links to navigate directly to action pages for the user. ', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationRoute'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this page supports query references being passed into it for automatic execution', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsSearchPage'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this page', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application page record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationPageRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The person record  this user is based on', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'PersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The culture this user is assigned to', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'CultureSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The authentication authority used for logging in to the application (e.g. Google account) | For systems using Tenant Services for login, the value is copied from Tenant Services to the client database when the account is created.  The value of this column cannot be changed after the account is created (delete the account and recreate or create a new account).', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'AuthenticationAuthoritySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the identity of the user as recorded in Active Directory and using "user@domain" style - example:   tara.knowles@soa.com', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'UserName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'date and time this user profile was last reviewed to ensure it is still required', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'LastReviewTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'identity of the user (usually an administrator) who completed the last review of this user profile', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'LastReviewUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When checked indicates this may be a duplicate user profile and requires review from an administrator', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsPotentialDuplicate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates this user will appear in the list of templates to copy from when creating new users - sets up same grants as starting point', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsTemplate'
GO
EXEC sp_addextendedproperty N'MS_Description', N'stores the hashed value of a password applied by the user when seeking temporary elevated access to functions or data their profile does not normally provide', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'GlassBreakPassword'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this user profile last changed their glass-break password | This value remains blank until password is initially set.  If password is cleared later, the time the password is set to NULL is stored.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'LastGlassBreakPasswordChangeTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this application user record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationUserIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The GUID or similar identifier used by the authentication system to identify the user record | This value is used on federated logins (e.g. MS Account, Google Account) to identify the user since it is possible for the email captured in the UserName column to change over time.  The federated record identifier should not be captured into the UserName column since that value is used in the CreateUser and UpdateUser audit columns and GUID''s.  Note that where no federated provider is used (direct email login) this column is set to the same value as the RowGUID.  A bit in the entity view indicates whether the application user record is a federated login.', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'AuthenticationSystemID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the application user record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'ApplicationUserRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'zContext'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates the task is overdue		', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsOverdue'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates the task is open', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsOpen'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates the task is cancelled', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsCancelled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates the task has been closed within the last 24 hours', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsClosed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the task can be taken over by the logged in user', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsTaskTakeOverEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the task can be closed by the owner of the task or queue', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsCloseEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the task can be updated by the owner of the task or queue', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsUpdateEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'indicates the task has been closed within the last 24 hours', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'IsClosedWithinADay'
GO
EXEC sp_addextendedproperty N'MS_Description', N'the label for the entity (eg: Person) the task is targeted for | Override in product DB project to include supported entities--! </MoreColumns>from', 'SCHEMA', N'sf', 'VIEW', N'vTask#Ext', 'COLUMN', N'EntityLabel'
GO
