SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vEmailMessageAttachment#Ext]
as
/*********************************************************************************************************************************
View    : sf.vEmailMessageAttachment#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the sf.EmailMessageAttachment base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vEmailMessageAttachment (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 ema.EmailMessageAttachmentSID
	,em.SenderEmailAddress
	,em.SenderDisplayName
	,em.PriorityLevel
	,em.Subject
	,em.FileTypeSCD                                                            EmailMessageFileTypeSCD
	,em.FileTypeSID                                                            EmailMessageFileTypeSID
	,em.IsApplicationUserRequired
	,em.ApplicationUserSID
	,em.MessageLinkSID
	,em.LinkExpiryHours
	,em.ApplicationEntitySID
	,em.ApplicationGrantSID
	,em.IsGenerateOnly
	,em.MergedTime
	,em.QueuedTime
	,em.CancelledTime
	,em.ArchivedTime
	,em.PurgedTime
	,em.RowGUID                                                                EmailMessageRowGUID
	,ftype.FileTypeSCD                                                         FileTypeFileTypeSCD
	,ftype.FileTypeLabel
	,ftype.MimeType
	,ftype.IsInline
	,ftype.IsActive                                                            FileTypeIsActive
	,ftype.RowGUID                                                             FileTypeRowGUID
	,sf.fEmailMessageAttachment#IsDeleteEnabled(ema.EmailMessageAttachmentSID) IsDeleteEnabled				--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                        IsReselected						-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                            IsNullApplied					-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                         zContext								-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
  --! </MoreColumns>
from
	sf.EmailMessageAttachment ema
join
	sf.EmailMessage           em     on ema.EmailMessageSID = em.EmailMessageSID
join
	sf.FileType               ftype  on ema.FileTypeSID = ftype.FileTypeSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the email message attachment assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'EmailMessageAttachmentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The sending email address for the note', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'SenderEmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the text which will be displayed as part of the ''from'' field in a user''s email client.  E.g. In outlook the combination of a display name and the sender''s email address is displayed as ''John Doe <john.d@mailinator.com>''.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'SenderDisplayName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A priority level used to rank emails for sending: 1 is the highest priority, 5 is medium and 10 is lowest | This value is used to sort emails for pickup by the email sending service', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'PriorityLevel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Subject of the email note', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'Subject'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document the email body is stored as | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".HTML" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'EmailMessageFileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of email message', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'EmailMessageFileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the eligibility check on recipients should ensure there is an active user account (recipient must be able to sign in) | Be sure this value is set for password reset emails', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsApplicationUserRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A reference to an existing user record to use as a template for grants to apply to new user accounts created when this email is confirmed | 
Applies to user invite emails only', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the email link assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'MessageLinkSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of hours after which any (confirmation) link included in the email is considered expired', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'LinkExpiryHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this email message', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the application grant assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'ApplicationGrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When checked, indicates the document is not to be mailed out. The PDF is saved to the member file for download and/or printing only.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsGenerateOnly'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the process of finalizing the email content begins | No changes to recipients or template contents can occur after this value is set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'MergedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time this message was provided to the service for sending', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'QueuedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the email message was cancelled (not sent) after being queued but before being sent (prior to queuing the message can be deleted)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'CancelledTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the email was put into archived status | Archived email remains available in the database but is not included in displays and searches by default', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'ArchivedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the email document is purged from online storage (documents can be exported at archive step)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'PurgedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the email message record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'EmailMessageRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the file type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'FileTypeFileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the file type to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'FileTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The MIME type to use when a client browser downloads or views a document.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'MimeType'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When a client browser downloads a document this indicates whether or not the browser should be asked to display rather than download the document. If the browser is unable to, due to lack of software or other settings, the file will instead be downloaded as normal.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsInline'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this file type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'FileTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the file type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'FileTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment#Ext', 'COLUMN', N'zContext'
GO
