SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [sf].[vEmailMessageAttachment]
as
/*********************************************************************************************************************************
View    : sf.vEmailMessageAttachment
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : entity view for sf.EmailMessageAttachment - includes all table columns and columns from extended view
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This is the main view for the sf.EmailMessageAttachment table.  The view provides a comprehensive set of attributes for the entity
 and is the recommended data source for user interface and detailed reporting queries.

This view joins to sf.vEmailMessageAttachmentExt which includes related columns from parent tables, counts of records from child tables
and calculated columns. See sf.vEmailMessageAttachmentExt documentation for details. To add additional content to this view, customize
the sf.vEmailMessageAttachmentExt view – do NOT customize this view directly. Customization of the "Example" block is the only area of
source code preserved on regeneration.  This view is NOT an extension point for client-specific configuration.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 ema.EmailMessageAttachmentSID
	,ema.EmailMessageSID
	,ema.DocumentTitle
	,ema.DocumentContent
	,ema.FileTypeSID
	,ema.FileTypeSCD
	,ema.UserDefinedColumns
	,ema.EmailMessageAttachmentXID
	,ema.LegacyKey
	,ema.IsDeleted
	,ema.CreateUser
	,ema.CreateTime
	,ema.UpdateUser
	,ema.UpdateTime
	,ema.RowGUID
	,ema.RowStamp
	,emax.SenderEmailAddress
	,emax.SenderDisplayName
	,emax.PriorityLevel
	,emax.Subject
	,emax.EmailMessageFileTypeSCD
	,emax.EmailMessageFileTypeSID
	,emax.IsApplicationUserRequired
	,emax.ApplicationUserSID
	,emax.MessageLinkSID
	,emax.LinkExpiryHours
	,emax.ApplicationEntitySID
	,emax.ApplicationGrantSID
	,emax.IsGenerateOnly
	,emax.MergedTime
	,emax.QueuedTime
	,emax.CancelledTime
	,emax.ArchivedTime
	,emax.PurgedTime
	,emax.EmailMessageRowGUID
	,emax.FileTypeFileTypeSCD
	,emax.FileTypeLabel
	,emax.MimeType
	,emax.IsInline
	,emax.FileTypeIsActive
	,emax.FileTypeRowGUID
	,emax.IsDeleteEnabled
	,emax.IsReselected
	,emax.IsNullApplied
	,emax.zContext
from
	sf.EmailMessageAttachment      ema
join
	sf.vEmailMessageAttachment#Ext emax	on ema.EmailMessageAttachmentSID = emax.EmailMessageAttachmentSID
GO
EXEC sp_addextendedproperty N'SGI_ApplicationEntitySCD', N'sf.EmailMessageAttachment', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the email message attachment assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageAttachmentSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the email message assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name or title of the document to show in the user interface (defaults to the file name uploaded)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'DocumentTitle'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of email message attachment', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".pdf" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An XML document defining additional values to store with the email message attachment | Forms customization is required to access extended XML content', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'UserDefinedColumns'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier value used in extended logic and business rules | Customization is required to apply the identifier', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageAttachmentXID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Key or linking value from previous system used in the conversion of records into the current database | No unique-constraint is enforced on this column', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'LegacyKey'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates deletion is in progress - enables capture of audit details of the deleting user', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsDeleted'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who created the email message attachment | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'CreateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time this email message attachment record was created | System assigned.  Value includes timezone offset.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'CreateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The application user who last updated the email message attachment | Application user names appear as: "user@domain" while database user names appear as: "domain\user"', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'UpdateUser'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the email message attachment record was last updated | Tracks updates through the application only. System assigned.  Value includes time zone offset.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'UpdateTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the email message attachment record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'RowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Record version identifier used to avoid overwrites during concurrent updates | This value is not displayed in the user interface', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'RowStamp'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The sending email address for the note', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'SenderEmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the text which will be displayed as part of the ''from'' field in a user''s email client.  E.g. In outlook the combination of a display name and the sender''s email address is displayed as ''John Doe <john.d@mailinator.com>''.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'SenderDisplayName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A priority level used to rank emails for sending: 1 is the highest priority, 5 is medium and 10 is lowest | This value is used to sort emails for pickup by the email sending service', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'PriorityLevel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Subject of the email note', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'Subject'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file extension or type of document the email body is stored as | This value must match one of the registered filter types for full-text searching.  The list of document types supported is limited by the master table.  The value includes the leading period - e.g. ".HTML" Note that the default value is updated by an AFTER trigger defined on the table.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageFileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of email message', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageFileTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether the eligibility check on recipients should ensure there is an active user account (recipient must be able to sign in) | Be sure this value is set for password reset emails', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsApplicationUserRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A reference to an existing user record to use as a template for grants to apply to new user accounts created when this email is confirmed | 
Applies to user invite emails only', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'ApplicationUserSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the email link assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'MessageLinkSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The number of hours after which any (confirmation) link included in the email is considered expired', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'LinkExpiryHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this email message', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the application grant assigned by the system | Primary key - not editable', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'ApplicationGrantSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When checked, indicates the document is not to be mailed out. The PDF is saved to the member file for download and/or printing only.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsGenerateOnly'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Date and time the process of finalizing the email content begins | No changes to recipients or template contents can occur after this value is set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'MergedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time this message was provided to the service for sending', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'QueuedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the email message was cancelled (not sent) after being queued but before being sent (prior to queuing the message can be deleted)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'CancelledTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the email was put into archived status | Archived email remains available in the database but is not included in displays and searches by default', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'ArchivedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the email document is purged from online storage (documents can be exported at archive step)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'PurgedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the email message record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'EmailMessageRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the file type | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeFileTypeSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the file type to present in lists and look ups (must be unique)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The MIME type to use when a client browser downloads or views a document.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'MimeType'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When a client browser downloads a document this indicates whether or not the browser should be asked to display rather than download the document. If the browser is unable to, due to lack of software or other settings, the file will instead be downloaded as normal.', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsInline'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this file type record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the file type record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'FileTypeRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'sf', 'VIEW', N'vEmailMessageAttachment', 'COLUMN', N'zContext'
GO
