SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [stg].[vRegistrantExamProfile#Ext]
as
/*********************************************************************************************************************************
View    : stg.vRegistrantExamProfile#Ext
Notice  : Copyright © 2019 Softworks Group Inc.
Summary : extends the stg.RegistrantExamProfile base entity with calculated values, entity properties and columns from related tables
-----------------------------------------------------------------------------------------------------------------------------------
Author  : Generated by DB Studio: pEVGen | Designer: Tim Edlund
Version : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This view includes the primary key of the table but no other content from the base entity. Descriptive columns from parent tables
and a set of columns required by the Entity Framework (EF) are provided. The content of this view is joined with the table columns
to provide complete attribution of the entity in the view vRegistrantExamProfile (referred to as the "entity" view in SGI documentation).

Columns required to support the EF include constants passed by client and middle tier modules into the table API procedures as
parameters. These values control the insert/update/delete behaviour of the sprocs. For example: the IsNullApplied bit is set ON
in the view so that update procedures overwrite column values when matching parameters are NULL on calls from the client tier.
The default for this column in the call signature of the sproc is 0 (off) so that calls from the back-end do not overwrite with
null values.  The zContext XML value is always null but is required for binding to sproc calls using EF and RIA.

You can add additional columns, joins and examples of calling syntax, by placing them between the code tag pairs provided.  Items
placed within code tag pairs are preserved on regeneration.  Note that all additions to this view become part of the base product
and deploy for all client configurations.  This view is NOT an extension point for client-specific configurations.

-------------------------------------------------------------------------------------------------------------------------------- */

select
	 rep.RegistrantExamProfileSID
	,imp.FileFormatSID
	,imp.ApplicationEntitySID
	,imp.FileName
	,imp.LoadStartTime
	,imp.LoadEndTime
	,imp.IsFailed
	,imp.MessageText
	,imp.RowGUID                                                              ImportFileRowGUID
	,ps.ProcessingStatusSCD
	,ps.ProcessingStatusLabel
	,ps.IsClosedStatus
	,ps.IsActive                                                              ProcessingStatusIsActive
	,ps.IsDefault                                                             ProcessingStatusIsDefault
	,ps.RowGUID                                                               ProcessingStatusRowGUID
	,person.GenderSID
	,person.NamePrefixSID
	,person.FirstName                                                         PersonFirstName
	,person.CommonName
	,person.MiddleNames
	,person.LastName                                                          PersonLastName
	,person.BirthDate                                                         PersonBirthDate
	,person.DeathDate
	,person.HomePhone
	,person.MobilePhone
	,person.IsTextMessagingEnabled
	,person.ImportBatch
	,person.RowGUID                                                           PersonRowGUID
	,e.ExamName
	,e.ExamCategory
	,e.PassingScore                                                           ExamPassingScore
	,e.EffectiveTime
	,e.ExpiryTime
	,e.IsOnlineExam
	,e.IsEnabledOnPortal
	,e.Sequence
	,e.CultureSID
	,e.LastVerifiedTime                                                       ExamLastVerifiedTime
	,e.MinLagDaysBetweenAttempts
	,e.MaxAttemptsPerYear
	,e.VendorExamID
	,e.RowGUID                                                                ExamRowGUID
	,eo.ExamSID                                                               ExamOfferingExamSID
	,eo.OrgSID                                                                ExamOfferingOrgSID
	,eo.ExamTime                                                              ExamOfferingExamTime
	,eo.SeatingCapacity
	,eo.CatalogItemSID
	,eo.BookingCutOffDate
	,eo.VendorExamOfferingID
	,eo.RowGUID                                                               ExamOfferingRowGUID
	,o.ParentOrgSID
	,o.OrgTypeSID
	,o.OrgName
	,o.OrgLabel                                                               OrgOrgLabel
	,o.StreetAddress1
	,o.StreetAddress2
	,o.StreetAddress3
	,o.CitySID
	,o.PostalCode
	,o.RegionSID
	,o.Phone
	,o.Fax
	,o.WebSite
	,o.EmailAddress                                                           OrgEmailAddress
	,o.InsuranceOrgSID
	,o.InsurancePolicyNo
	,o.InsuranceAmount
	,o.IsEmployer
	,o.IsCredentialAuthority
	,o.IsInsurer
	,o.IsInsuranceCertificateRequired
	,o.IsPublic
	,o.IsActive                                                               OrgIsActive
	,o.IsAdminReviewRequired
	,o.LastVerifiedTime                                                       OrgLastVerifiedTime
	,o.RowGUID                                                                OrgRowGUID
	,registrant.PersonSID                                                     RegistrantPersonSID
	,registrant.RegistrantNo                                                  RegistrantRegistrantNo
	,registrant.YearOfInitialEmployment
	,registrant.IsOnPublicRegistry
	,registrant.CityNameOfBirth
	,registrant.CountrySID
	,registrant.DirectedAuditYearCompetence
	,registrant.DirectedAuditYearPracticeHours
	,registrant.LateFeeExclusionYear
	,registrant.IsRenewalAutoApprovalBlocked
	,registrant.RenewalExtensionExpiryTime
	,registrant.ArchivedTime
	,registrant.RowGUID                                                       RegistrantRowGUID
	,stg.fRegistrantExamProfile#IsDeleteEnabled(rep.RegistrantExamProfileSID) IsDeleteEnabled					--# Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)
	,cast(1 as tinyint)                                                       IsReselected						-- parameter for sproc calls through EF - reselects row as dataset
	,cast(1 as bit)                                                           IsNullApplied						-- parameter for sproc calls through EF - writes null parameter values
	,cast(null as xml)                                                        zContext								-- parameter for sproc calls through EF - utility parameter for customization
  --! <MoreColumns>
	,dbo.fRegistrant#Label(isnull(rep.LastName, N'[No Last Name]'), isnull(rep.FirstName, N'[No First Name]'), null, rep.RegistrantNo, 'REGISTRATION') RegistrantLabel
  --! </MoreColumns>
from
	stg.RegistrantExamProfile rep
join
	sf.ImportFile             imp        on rep.ImportFileSID = imp.ImportFileSID
join
	sf.ProcessingStatus       ps         on rep.ProcessingStatusSID = ps.ProcessingStatusSID
left outer join
	sf.Person                 person     on rep.PersonSID = person.PersonSID
left outer join
	dbo.Exam                  e          on rep.ExamSID = e.ExamSID
left outer join
	dbo.ExamOffering          eo         on rep.ExamOfferingSID = eo.ExamOfferingSID
left outer join
	dbo.Org                   o          on rep.OrgSID = o.OrgSID
left outer join
	dbo.Registrant            registrant on rep.RegistrantSID = registrant.RegistrantSID
--! <MoreJoins>
--! </MoreJoins>
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the registrant exam profile assigned by the system | Primary key - not editable', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'RegistrantExamProfileSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The file format assigned to this import file', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'FileFormatSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The entity assigned to this import file', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ApplicationEntitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name of the source file the import was read from (not necessarily unique).', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'FileName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the import service picked up the job for importing (start of import)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'LoadStartTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date and time the import of the file was completed successfully | Value is blank if Is-Failed is ON', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'LoadEndTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the import of this file failed or was cancelled by the user.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsFailed'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Summary of processing result (blank until processing is attempted).', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'MessageText'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the import file record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ImportFileRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique code assigned by the product to identify the processing status | The code is not editable and records cannot be added or deleted from this table', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ProcessingStatusSCD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the processing status to present in lists and look ups (must be unique)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ProcessingStatusLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates records in this status should be considered as closed by the application (not retryable) | This value cannot be set by the end user', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsClosedStatus'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this processing status record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ProcessingStatusIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record is the default processing status to assign when new records are added', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ProcessingStatusIsDefault'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the processing status record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ProcessingStatusRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The gender this person is assigned', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'GenderSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The name prefix assigned to this person', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'NamePrefixSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'given name for the person', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'PersonFirstName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The usual first name of the person if different than the given first name', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CommonName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'middle name or middle names, if known, of the person', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'MiddleNames'
GO
EXEC sp_addextendedproperty N'MS_Description', N'surname/family name of the person Test', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'PersonLastName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether sending text messages is enabled for the user | Text messages are used for reminders and quick follow-ups and augment but do not replace email messaging.  If a person opts out of a Message Subscription type then messages for that type are not sent via email or text messaging.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsTextMessagingEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An identifier of the import batch used to add this record - if not imported this value is blank | This value is typically set to the date and time the import started followed by the importing user name.  The value is often used to query for latest imports.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ImportBatch'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the person record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'PersonRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the exam to display on search results and reports (must be unique)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional grouping or category label to organize exams (e.g. for display in different areas on member forms)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamCategory'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Minimum score for passing the exam (required for Alinity exams). Leave blank to always record pass/fail manually for external exams.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamPassingScore'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if the exam is enabled for selection on the member portal (applies only to online exams)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsEnabledOnPortal'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Controls order this exam appears in relative to other exams associated with the same credential | If not set the order defaults to entry order of the record', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'Sequence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the culture assigned by the system | Primary key - not editable', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CultureSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The minimum days a member must wait between attempts at writing the exam', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'MinLagDaysBetweenAttempts'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The maximum number of attempts a member is alloted to pass the exam within a registration year.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'MaxAttemptsPerYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional and unique identifier provided by the vendor/service to identify the exam  | This value can be used when importing exam candidates to associate results with the correct exam', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'VendorExamID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The exam this offering is defined for', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamOfferingExamSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org assigned to this exam offering', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamOfferingOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The date the exam was taken', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamOfferingExamTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The catalog item assigned to this exam offering', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CatalogItemSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional and unique identifier provided by the vendor/service to identify the exam offering | This value can be used when importing exam candidates to automatically book or associate a result with the exam offering ', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'VendorExamOfferingID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the exam offering record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ExamOfferingRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'ParentOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of org', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgTypeSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the org to display on search results and reports (must be unique)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgName'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Short (max 35 characters) label for the org to present in lists and look ups (must be unique)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgOrgLabel'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The first line of the street address', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'StreetAddress1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The second line of the street address', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'StreetAddress2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The third line of the street address', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'StreetAddress3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The city this org is in', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CitySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The postal or zip code of the organization', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'PostalCode'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The region assigned to this org', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'RegionSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The phone number for the organization.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'Phone'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The fax number for the organization.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'Fax'
GO
EXEC sp_addextendedproperty N'MS_Description', N'An optional email address to display on the Public Directory for general inquiries to the organization', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgEmailAddress'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The org this  is defined for', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'InsuranceOrgSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of employers applicants/registrants can choose from on forms | This value being enabled does not necessarily mean any applicants/registrants are actively employed by the organization', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsEmployer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of credential authorities user choose from when adding new credentials | This value being enabled does not necessarily mean any credentials are active for the organization', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsCredentialAuthority'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates the organization will be included in the list of insurers providing coverage to members | This value being enabled does not necessarily mean any member has identified this organization as an insurer', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsInsurer'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Applies to insurance companies only and indicates if member must provide their insurance certificate number. ', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsInsuranceCertificateRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this org record is in active use; un-check to eliminate from new record dialogs and active search results', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgIsActive'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates this record was added by a non-administrator and requires review (e.g. added as a new employer through an Application or Renewal entered online) The form can be configured to block automatic approval when new employer addresses are added in the case of renewals.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsAdminReviewRequired'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The last time the information collected on the organization was verified by an administrator (de-activate the record to avoid it being referenced going forward).', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgLastVerifiedTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the org record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'OrgRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique sequential identifier for the person assigned by the system | Primary key - not editable', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'RegistrantPersonSID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The year of initial employment in the profession if required for reporting and full history of employment was not converted', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'YearOfInitialEmployment'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Name for the city to display on search results and reports (must be unique)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CityNameOfBirth'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The country assigned to this registrant', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'CountrySID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of continuing competence/education claims (non-random, direct audit inclusion)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'DirectedAuditYearCompetence'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a year for which this registrant is to receive an audit of practice hours (non-random, direct audit inclusion)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'DirectedAuditYearPracticeHours'
GO
EXEC sp_addextendedproperty N'MS_Description', N'When filled out ensures the member will not be assessed late fees for the registration year selected (limited to one year)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'LateFeeExclusionYear'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates automatic approval of this form type is disabled for the registrant.  Administrator review and approval is required.  This setting is only required where rules in the form would not otherwise block automatic approval. (e.g. the form may block auto-approval if a criminal record is reported or other non-qualifying details.) The setting is relevant only where automatic approval is configured for the form type.', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsRenewalAutoApprovalBlocked'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Enter a date to extend the renewal period for this specific registrant to the end of the day entered.  | The later of this value and the standard schedule is applied. ', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'RenewalExtensionExpiryTime'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System assigned globally unique identifier for the registrant record used for offline synchronization | This is a GUID value with the "RowGUID" SQL Server property set', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'RegistrantRowGUID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates whether deletion of record is allowed | May be blocked by child records, security grants, and table-specific logic (see function)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsDeleteEnabled'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether the record should be reselected after update (not displayed)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsReselected'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to control whether blank values provided from the UI end should overwrite content (not displayed)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'IsNullApplied'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Parameter used by the application to allow the database API procedures to accept customized parameters (not displayed)', 'SCHEMA', N'stg', 'VIEW', N'vRegistrantExamProfile#Ext', 'COLUMN', N'zContext'
GO
