SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pStateProvince#EFInsert]
	 @StateProvinceName       nvarchar(30)      = null											-- required! if not passed value must be set in custom logic prior to insert
	,@StateProvinceCode       nvarchar(5)       = null											-- required! if not passed value must be set in custom logic prior to insert
	,@CountrySID              int               = null											-- required! if not passed value must be set in custom logic prior to insert
	,@ISONumber               smallint          = null											
	,@IsDisplayed             bit               = null											-- default: (1)
	,@IsDefault               bit               = null											-- default: (0)
	,@IsActive                bit               = null											-- default: (1)
	,@IsAdminReviewRequired   bit               = null											-- default: CONVERT(bit,(0))
	,@ChangeLog               xml               = null											-- default: CONVERT(xml,'<Changes />')
	,@UserDefinedColumns      xml               = null											
	,@StateProvinceXID        varchar(150)      = null											
	,@LegacyKey               nvarchar(50)      = null											
	,@CreateUser              nvarchar(75)      = null											-- default: suser_sname()
	,@IsReselected            tinyint           = null											-- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@zContext                xml               = null											-- other values defining context for the insert (if any)
	,@CountryName             nvarchar(50)      = null											-- not a base table column (default ignored)
	,@ISOA2                   char(2)           = null											-- not a base table column (default ignored)
	,@ISOA3                   char(3)           = null											-- not a base table column (default ignored)
	,@CountryISONumber        smallint          = null											-- not a base table column (default ignored)
	,@IsStateProvinceRequired bit               = null											-- not a base table column (default ignored)
	,@CountryIsDefault        bit               = null											-- not a base table column (default ignored)
	,@CountryIsActive         bit               = null											-- not a base table column (default ignored)
	,@CountryRowGUID          uniqueidentifier  = null											-- not a base table column (default ignored)
	,@IsDeleteEnabled         bit               = null											-- not a base table column (default ignored)
	,@StateProvinceSearch     nvarchar(81)      = null											-- not a base table column (default ignored)
as
/*********************************************************************************************************************************
Procedure : dbo.pStateProvince#EFInsert
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : Alternate call syntax for pStateProvince#Insert for use with MS Entity Framework (does not declare PK output parameter)
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is a wrapper for the standard insert procedure for the table. It is provided particularly for application using the
Microsoft Entity Framework (EF). The current version of the EF generates an error if an entity attribute is defined as an output
parameter. This procedure does not declare the primary key output parameter but passes all remaining parameters to the standard
insert procedure.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- call the main procedure

		exec @errorNo = dbo.pStateProvince#Insert
			 @StateProvinceName       = @StateProvinceName
			,@StateProvinceCode       = @StateProvinceCode
			,@CountrySID              = @CountrySID
			,@ISONumber               = @ISONumber
			,@IsDisplayed             = @IsDisplayed
			,@IsDefault               = @IsDefault
			,@IsActive                = @IsActive
			,@IsAdminReviewRequired   = @IsAdminReviewRequired
			,@ChangeLog               = @ChangeLog
			,@UserDefinedColumns      = @UserDefinedColumns
			,@StateProvinceXID        = @StateProvinceXID
			,@LegacyKey               = @LegacyKey
			,@CreateUser              = @CreateUser
			,@IsReselected            = @IsReselected
			,@zContext                = @zContext
			,@CountryName             = @CountryName
			,@ISOA2                   = @ISOA2
			,@ISOA3                   = @ISOA3
			,@CountryISONumber        = @CountryISONumber
			,@IsStateProvinceRequired = @IsStateProvinceRequired
			,@CountryIsDefault        = @CountryIsDefault
			,@CountryIsActive         = @CountryIsActive
			,@CountryRowGUID          = @CountryRowGUID
			,@IsDeleteEnabled         = @IsDeleteEnabled
			,@StateProvinceSearch     = @StateProvinceSearch

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
