SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pPersonGroupDoc#Insert]
	 @PersonGroupDocSID          int               = null output						-- identity value assigned to the new record
	,@PersonGroupFolderSID       int               = null										-- required! if not passed value must be set in custom logic prior to insert
	,@DocumentTitle              nvarchar(75)      = null										-- required! if not passed value must be set in custom logic prior to insert
	,@FileTypeSID                int               = null										-- required! if not passed value must be set in custom logic prior to insert
	,@FileTypeSCD                varchar(8)        = null										-- required! if not passed value must be set in custom logic prior to insert
	,@TagList                    xml               = null										-- default: CONVERT(xml,N'<Tags/>')
	,@DocumentContent            varbinary(max)    = null										-- required! if not passed value must be set in custom logic prior to insert
	,@DocumentNotes              nvarchar(max)     = null										
	,@UserDefinedColumns         xml               = null										
	,@PersonGroupDocXID          varchar(150)      = null										
	,@LegacyKey                  nvarchar(50)      = null										
	,@CreateUser                 nvarchar(75)      = null										-- default: suser_sname()
	,@IsReselected               tinyint           = null										-- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@zContext                   xml               = null										-- other values defining context for the insert (if any)
	,@ParentPersonGroupFolderSID int               = null										-- not a base table column (default ignored)
	,@PersonGroupSID             int               = null										-- not a base table column (default ignored)
	,@FolderName                 nvarchar(35)      = null										-- not a base table column (default ignored)
	,@IsRoot                     bit               = null										-- not a base table column (default ignored)
	,@PersonGroupFolderRowGUID   uniqueidentifier  = null										-- not a base table column (default ignored)
	,@FileTypeFileTypeSCD        varchar(8)        = null										-- not a base table column (default ignored)
	,@FileTypeLabel              nvarchar(35)      = null										-- not a base table column (default ignored)
	,@MimeType                   varchar(255)      = null										-- not a base table column (default ignored)
	,@IsInline                   bit               = null										-- not a base table column (default ignored)
	,@FileTypeIsActive           bit               = null										-- not a base table column (default ignored)
	,@FileTypeRowGUID            uniqueidentifier  = null										-- not a base table column (default ignored)
	,@IsDeleteEnabled            bit               = null										-- not a base table column (default ignored)
as
/*********************************************************************************************************************************
Procedure : dbo.pPersonGroupDoc#Insert
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : inserts 1 row into the dbo.PersonGroupDoc table
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the dbo.PersonGroupDoc table with parameter values represent columns of the table. Additional
parameters are provided for all columns in the vPersonGroupDoc entity view, however, the base logic of the procedure inserts the
the columns of the table only.

Note: This procedure cannot be called directly from the MS Entity Framework! Use the wrapper procedure instead (...#EFInsert) that
excludes the primary key output parameter, but includes all other parameters.

Table-specific logic can be added through tagged sections (pre and post insert) and a call to an extended procedure supports
configuration (client) specific logic. Code implemented within code tags (table-specific logic) is part of the base product and
applies to all client configurations. Calls to the extended procedure occurs immediately after the table-specific logic in both
"pre-insert" and "post-insert" contexts.  A transaction is used to commit/rollback all changes as a logical unit.

Client specific customizations must be implemented in the ext.pPersonGroupDoc procedure. The extended procedure is only called
where it exists in the DB. The first parameter passed @Mode is set to either "insert.pre" or "insert.post" to provide context for
the extended logic.

The @zContext parameter is an additional construct available to support overrides where different results are produced based on
content provided in the XML from the client tier. This parameter may contain multiple values.

The "@IsReselected" parameter controls whether the entity row is returned as a dataset (SELECT). There are 3 settings:
   0 - no data set is returned
   1 - return the full entity
   2 - return only the SID (primary key) of the row inserted

For client-tier calls using the Microsoft Entity Framework and RIA Services, the @IsReselected bit should be passed as 1 to
force re-selection of table columns + extended view columns (the entity view).

Values for parameters representing mandatory columns must be provided unless a database default exists.  The default values
displayed as comments next to the parameter declarations above, and the list of columns returned from the entity view when
@IsReselected = 1, were obtained from the data dictionary at generation time. If the table or view design has been
updated since then, the procedure must be regenerated to keep comments up to date. In the StudioDB run dbo.pEFGen
to update all views and procedures which appear out-of-date.

The procedure does not accept a parameter for UpdateUser since the @CreateUser value is applied into both the user audit
columns.  Audit times are set automatically through database defaults and cannot be passed or overwritten.

If the @CreateUser parameter is passed as the special value "SystemUser", then the system user established in sf.ConfigParam
is applied. This option is useful for conversion and system generated inserts the user would not recognize as have caused. Any
other value provided for the parameter (including null) is overwritten with the current application user.

Business rule compliance is checked through a table constraint which calls fPersonGroupDocCheck to test all rules.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@errorText                                    nvarchar(4000)					-- message text (for business rule errors)
		,@rowsAffected                                 int = 0								-- tracks rows impacted by the operation (error check)
		,@recordSID                                    int										-- tracks primary key value for clearing current default
		,@ON                                           bit = cast(1 as bit)		-- constant for bit comparison and assignments
		,@OFF                                          bit = cast(0 as bit)		-- constant for bit comparison and assignments

	set @PersonGroupDocSID = null																						-- initialize output parameter

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- remove leading and trailing spaces from character type columns

		set @DocumentTitle = ltrim(rtrim(@DocumentTitle))
		set @FileTypeSCD = ltrim(rtrim(@FileTypeSCD))
		set @DocumentNotes = ltrim(rtrim(@DocumentNotes))
		set @PersonGroupDocXID = ltrim(rtrim(@PersonGroupDocXID))
		set @LegacyKey = ltrim(rtrim(@LegacyKey))
		set @CreateUser = ltrim(rtrim(@CreateUser))
		set @FolderName = ltrim(rtrim(@FolderName))
		set @FileTypeFileTypeSCD = ltrim(rtrim(@FileTypeFileTypeSCD))
		set @FileTypeLabel = ltrim(rtrim(@FileTypeLabel))
		set @MimeType = ltrim(rtrim(@MimeType))

		-- set zero length strings to null to avoid storing them in the record

		if len(@DocumentTitle) = 0 set @DocumentTitle = null
		if len(@FileTypeSCD) = 0 set @FileTypeSCD = null
		if len(@DocumentNotes) = 0 set @DocumentNotes = null
		if len(@PersonGroupDocXID) = 0 set @PersonGroupDocXID = null
		if len(@LegacyKey) = 0 set @LegacyKey = null
		if len(@CreateUser) = 0 set @CreateUser = null
		if len(@FolderName) = 0 set @FolderName = null
		if len(@FileTypeFileTypeSCD) = 0 set @FileTypeFileTypeSCD = null
		if len(@FileTypeLabel) = 0 set @FileTypeLabel = null
		if len(@MimeType) = 0 set @MimeType = null

		-- set the ID of the user

		if isnull(@CreateUser, 'x') = N'SystemUser' set @CreateUser = left(sf.fConfigParam#Value('SystemUser'),75)-- override for "SystemUser"
		if isnull(@CreateUser, 'x') <> N'SystemUser' set @CreateUser = sf.fApplicationUserSession#UserName()			-- application user - or DB user if no application session set

		-- reset defaults on table parameters passed as NULL

		set @TagList = isnull(@TagList,CONVERT(xml,N'<Tags/>'))
		set @CreateUser = isnull(@CreateUser,suser_sname())
		set @IsReselected         = isnull(@IsReselected        ,(0))
		
		-- ensure both the file type code (SCD) and key (SID) are provided - default from the value provided
		
		if @FileTypeSCD is null and @FileTypeSID is not null
		begin
		
			select
				@FileTypeSCD = ft.FileTypeSCD
			from
				sf.FileType ft
			where
				ft.FileTypeSID = @FileTypeSID
			and
				ft.IsActive = @ON
			
		end
		
		if @FileTypeSID is null and @FileTypeSCD is not null
		begin
		
			select
				@FileTypeSID = ft.FileTypeSID
			from
				sf.FileType ft
			where
				ft.FileTypeSCD = @FileTypeSCD
			and
				ft.IsActive = @ON
			
		end
		
		-- ensure the file type SID value matches the code being set; a trigger
		-- enforces the rule for updates outside of the EF sprocs
		
		select
			@FileTypeSID = ft.FileTypeSID
		from
			sf.FileType ft
		where
			ft.FileTypeSCD = @FileTypeSCD
		and
			ft.IsActive = @ON
		
		if @@rowcount = 0
		begin
		
			exec sf.pMessage#Get
				@MessageSCD  = 'FileTypeNotFound'
				,@MessageText = @errorText output
				,@DefaultText = N'The file type "%1" is not supported. Upload a different file or ask your administrator if this type can be added to the configuration.'
				,@Arg1        = @FileTypeSCD
		
			raiserror(@errorText, 16, 1)
		end
		
		set @TagList = sf.fTagList#SetTagTimes(@TagList)											-- add times to the tags applied (if any)

		-- apply the table-specific pre-insert logic (if any)

		--! <PreInsert>
		--  insert pre-insert logic here ...
		--! </PreInsert>
	
		-- call the extended version of the procedure (if it exists) for "insert.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pPersonGroupDoc'
		)
		begin
		
			exec @errorNo = ext.pPersonGroupDoc
				 @Mode                       = 'insert.pre'
				,@PersonGroupFolderSID       = @PersonGroupFolderSID output
				,@DocumentTitle              = @DocumentTitle output
				,@FileTypeSID                = @FileTypeSID output
				,@FileTypeSCD                = @FileTypeSCD output
				,@TagList                    = @TagList output
				,@DocumentContent            = @DocumentContent output
				,@DocumentNotes              = @DocumentNotes output
				,@UserDefinedColumns         = @UserDefinedColumns output
				,@PersonGroupDocXID          = @PersonGroupDocXID output
				,@LegacyKey                  = @LegacyKey output
				,@CreateUser                 = @CreateUser
				,@IsReselected               = @IsReselected
				,@zContext                   = @zContext
				,@ParentPersonGroupFolderSID = @ParentPersonGroupFolderSID
				,@PersonGroupSID             = @PersonGroupSID
				,@FolderName                 = @FolderName
				,@IsRoot                     = @IsRoot
				,@PersonGroupFolderRowGUID   = @PersonGroupFolderRowGUID
				,@FileTypeFileTypeSCD        = @FileTypeFileTypeSCD
				,@FileTypeLabel              = @FileTypeLabel
				,@MimeType                   = @MimeType
				,@IsInline                   = @IsInline
				,@FileTypeIsActive           = @FileTypeIsActive
				,@FileTypeRowGUID            = @FileTypeRowGUID
				,@IsDeleteEnabled            = @IsDeleteEnabled
		
		end

		-- insert the record

		insert
			dbo.PersonGroupDoc
		(
			 PersonGroupFolderSID
			,DocumentTitle
			,FileTypeSID
			,FileTypeSCD
			,TagList
			,DocumentContent
			,DocumentNotes
			,UserDefinedColumns
			,PersonGroupDocXID
			,LegacyKey
			,CreateUser
			,UpdateUser
		)
		select
			 @PersonGroupFolderSID
			,@DocumentTitle
			,@FileTypeSID
			,@FileTypeSCD
			,@TagList
			,@DocumentContent
			,@DocumentNotes
			,@UserDefinedColumns
			,@PersonGroupDocXID
			,@LegacyKey
			,@CreateUser
			,@CreateUser

		select
			 @rowsAffected      = @@rowcount
			,@PersonGroupDocSID = scope_identity()															-- capture key value of new row

		-- check for errors

		if @rowsAffected <> 1																									-- ensure 1 row was inserted
		begin

			exec sf.pMessage#Get
				 @MessageSCD  = 'RowCountUnexpected'
				,@MessageText = @errorText output
				,@DefaultText = N'The "%1" operation on table "%2" affected an unexpected number of rows (%3). Record ID = %4.'
				,@Arg1        = 'insert'
				,@Arg2        = 'dbo.PersonGroupDoc'
				,@Arg3        = @rowsAffected
				,@Arg4        = @PersonGroupDocSID
			
			raiserror(@errorText, 18, 1)
			
		end

		-- apply the table-specific post-insert logic (if any)

		--! <PostInsert>
		--  insert post-insert logic here ...
		--! </PostInsert>
	
		-- call the extended version of the procedure (if it exists) for "insert.post" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pPersonGroupDoc'
		)
		begin
		
			exec @errorNo = ext.pPersonGroupDoc
				 @Mode                       = 'insert.post'
				,@PersonGroupDocSID          = @PersonGroupDocSID
				,@PersonGroupFolderSID       = @PersonGroupFolderSID
				,@DocumentTitle              = @DocumentTitle
				,@FileTypeSID                = @FileTypeSID
				,@FileTypeSCD                = @FileTypeSCD
				,@TagList                    = @TagList
				,@DocumentContent            = @DocumentContent
				,@DocumentNotes              = @DocumentNotes
				,@UserDefinedColumns         = @UserDefinedColumns
				,@PersonGroupDocXID          = @PersonGroupDocXID
				,@LegacyKey                  = @LegacyKey
				,@CreateUser                 = @CreateUser
				,@IsReselected               = @IsReselected
				,@zContext                   = @zContext
				,@ParentPersonGroupFolderSID = @ParentPersonGroupFolderSID
				,@PersonGroupSID             = @PersonGroupSID
				,@FolderName                 = @FolderName
				,@IsRoot                     = @IsRoot
				,@PersonGroupFolderRowGUID   = @PersonGroupFolderRowGUID
				,@FileTypeFileTypeSCD        = @FileTypeFileTypeSCD
				,@FileTypeLabel              = @FileTypeLabel
				,@MimeType                   = @MimeType
				,@IsInline                   = @IsInline
				,@FileTypeIsActive           = @FileTypeIsActive
				,@FileTypeRowGUID            = @FileTypeRowGUID
				,@IsDeleteEnabled            = @IsDeleteEnabled
		
		end

		if @trancount = 0 and xact_state() = 1 commit transaction

		-- return all columns for entity (1), just the PK value (2), or no returned value (0)

		if @IsReselected = 2
		begin

			select
				 ent.PersonGroupDocSID
			from
				dbo.vPersonGroupDoc ent
			where
				ent.PersonGroupDocSID = @PersonGroupDocSID

		end
		else if @IsReselected = 1
		begin

			select
				 ent.PersonGroupDocSID
				,ent.PersonGroupFolderSID
				,ent.DocumentTitle
				,ent.FileTypeSID
				,ent.FileTypeSCD
				,ent.TagList
				,ent.DocumentContent
				,ent.DocumentNotes
				,ent.UserDefinedColumns
				,ent.PersonGroupDocXID
				,ent.LegacyKey
				,ent.IsDeleted
				,ent.CreateUser
				,ent.CreateTime
				,ent.UpdateUser
				,ent.UpdateTime
				,ent.RowGUID
				,ent.RowStamp
				,ent.ParentPersonGroupFolderSID
				,ent.PersonGroupSID
				,ent.FolderName
				,ent.IsRoot
				,ent.PersonGroupFolderRowGUID
				,ent.FileTypeFileTypeSCD
				,ent.FileTypeLabel
				,ent.MimeType
				,ent.IsInline
				,ent.FileTypeIsActive
				,ent.FileTypeRowGUID
				,ent.IsDeleteEnabled
				,ent.IsReselected
				,ent.IsNullApplied
				,ent.zContext
			from
				dbo.vPersonGroupDoc ent
			where
				ent.PersonGroupDocSID = @PersonGroupDocSID

		end

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
