SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pRegistrantAudit#Default]
	 @zContext                       xml               = null                              -- default values provided from client-tier (if any)
	,@SetFKDefaults                  bit               = 0                                 -- when 1, mandatory FK's are returned as -1 instead of NULL
as
/*********************************************************************************************************************************
Procedure : dbo.pRegistrantAudit#Default
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : provides a blank row with default values for presentation in the UI for "new" dbo.RegistrantAudit records
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the dbo.RegistrantAudit table. When a new record is to be added from the UI, this procedure
is called to return a blank record with default values. If the client-tier is providing the context for the insert, such as a parent
key value for the new record, it must be passed in the @zContext XML parameter. Multiple values may be passed. The standard format
is: <Parameters MyParameter="1000001"/>.

The @SetFKDefaults parameter can be set to 1 to cause the procedure to return mandatory FK values as -1 rather than NULL. This avoids
the need to create complex types for the procedure on architectures which are not using RIA services.

Note that default values for text, ntext and binary type columns is not supported.  These data types are not permitted as local
variables in the current version of SQL Server and should be replaced by varchar(max) and nvarchar(max) where possible.

Some default values are built-in to the shell of the sproc.  The base table column defaults set in the variable declarations below
were obtained from database default constraints which existed at the time the procedure was generated. The declarations include all
columns of the vRegistrantAudit entity view, however, only some values (as noted above) are eligible for default setting.  The other
parameters are included for setting context for the table-specific or client-specific logic of the procedure (if any). Default values
returning a question mark "?", system date, or 0 are provided for non-base table columns which are mandatory.  This is done to avoid
compilation errors from the Entity Framework, however, the values will not be applied since they are not in the base table row.

Two levels of customization of the procedure shell are supported. Table-specific logic can be added through the tagged section and a
call to an extended procedure supports client-specific customization. Logic implemented within the code tags is part of the base
product and applies to all client configurations. Client-specific customizations must be implemented in the ext.pRegistrantAudit
procedure. The extended procedure is only called where it exists in database. The parameter "@Mode" is set to "default.pre" to
advise ext.pRegistrantAudit of the context of the call. All other parameters are also passed, however, only those parameters eligible
for default setting are passed for "output". All parameters corresponding to entity view columns are returned through a SELECT statement.

In order to simplify working with the XML parameter values, logic in the procedure parses the XML and assigns values to variables where
the variable name matches the column name in the XML (assumes single row).  The variables are then available to the table-specific and
client-specific logic.  The @zContext parameter is also passed, unmodified, to the extended procedure to support situations where values
are passed that are not mapped to column names.


-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@ON                             bit = cast(1 as bit)									-- constant for bit comparisons
		,@OFF                            bit = cast(0 as bit)									-- constant for bit comparisons
		,@registrantAuditSID             int               = -1								-- specific default required by EF - do not override
		,@registrantSID                  int               = null							-- no default provided from DB constraint - OK to override
		,@auditTypeSID                   int               = null							-- no default provided from DB constraint - OK to override
		,@registrationYear               smallint          = sf.fTodayYear()	-- default provided from DB constraint - OK to override
		,@formVersionSID                 int               = null							-- no default provided from DB constraint - OK to override
		,@formResponseDraft              xml               = CONVERT(xml,N'<FormResponses />')					-- default provided from DB constraint - OK to override
		,@lastValidateTime               datetimeoffset(7) = null							-- no default provided from DB constraint - OK to override
		,@adminComments                  xml               = CONVERT(xml,'<Comments />')								-- default provided from DB constraint - OK to override
		,@nextFollowUp                   date              = null							-- no default provided from DB constraint - OK to override
		,@pendingReviewers               xml               = null							-- no default provided from DB constraint - OK to override
		,@reasonSID                      int               = null							-- no default provided from DB constraint - OK to override
		,@confirmationDraft              nvarchar(max)     = null							-- no default provided from DB constraint - OK to override
		,@isAutoApprovalEnabled          bit               = CONVERT(bit,(0))	-- default provided from DB constraint - OK to override
		,@reviewReasonList               xml               = null							-- no default provided from DB constraint - OK to override
		,@userDefinedColumns             xml               = null							-- no default provided from DB constraint - OK to override
		,@registrantAuditXID             varchar(150)      = null							-- no default provided from DB constraint - OK to override
		,@legacyKey                      nvarchar(50)      = null							-- no default provided from DB constraint - OK to override
		,@isDeleted                      bit               = (0)							-- default provided from DB constraint - OK to override
		,@createUser                     nvarchar(75)      = suser_sname()		-- default value ignored (value set by UI)
		,@createTime                     datetimeoffset(7) = sysdatetimeoffset()												-- default value ignored (set to system time)
		,@updateUser                     nvarchar(75)      = suser_sname()		-- default value ignored (value set by UI)
		,@updateTime                     datetimeoffset(7) = sysdatetimeoffset()												-- default value ignored (set to system time)
		,@rowGUID                        uniqueidentifier  = newid()					-- default value ignored (value set by system)
		,@rowStamp                       timestamp         = null							-- default value ignored (value set by system)
		,@auditTypeLabel                 nvarchar(35)      = N'?'							-- not a base table column (default ignored)
		,@auditTypeCategory              nvarchar(65)													-- not a base table column (default ignored)
		,@auditTypeIsDefault             bit               = 0								-- not a base table column (default ignored)
		,@auditTypeIsActive              bit               = 0								-- not a base table column (default ignored)
		,@auditTypeRowGUID               uniqueidentifier  = newid()					-- not a base table column (default ignored)
		,@personSID                      int               = 0								-- not a base table column (default ignored)
		,@registrantNo                   varchar(50)       = '?'							-- not a base table column (default ignored)
		,@yearOfInitialEmployment        smallint															-- not a base table column (default ignored)
		,@isOnPublicRegistry             bit               = 0								-- not a base table column (default ignored)
		,@cityNameOfBirth                nvarchar(30)													-- not a base table column (default ignored)
		,@countrySID                     int																	-- not a base table column (default ignored)
		,@directedAuditYearCompetence    smallint															-- not a base table column (default ignored)
		,@directedAuditYearPracticeHours smallint															-- not a base table column (default ignored)
		,@lateFeeExclusionYear           smallint															-- not a base table column (default ignored)
		,@isRenewalAutoApprovalBlocked   bit               = 0								-- not a base table column (default ignored)
		,@renewalExtensionExpiryTime     datetime															-- not a base table column (default ignored)
		,@archivedTime                   datetimeoffset(7)										-- not a base table column (default ignored)
		,@registrantRowGUID              uniqueidentifier  = newid()					-- not a base table column (default ignored)
		,@formSID                        int               = 0								-- not a base table column (default ignored)
		,@versionNo                      smallint          = 0								-- not a base table column (default ignored)
		,@revisionNo                     smallint          = 0								-- not a base table column (default ignored)
		,@isSaveDisplayed                bit               = 0								-- not a base table column (default ignored)
		,@approvedTime                   datetimeoffset(7)										-- not a base table column (default ignored)
		,@formVersionRowGUID             uniqueidentifier  = newid()					-- not a base table column (default ignored)
		,@reasonGroupSID                 int																	-- not a base table column (default ignored)
		,@reasonName                     nvarchar(50)													-- not a base table column (default ignored)
		,@reasonCode                     varchar(25)													-- not a base table column (default ignored)
		,@reasonSequence                 smallint															-- not a base table column (default ignored)
		,@toolTip                        nvarchar(500)												-- not a base table column (default ignored)
		,@reasonIsActive                 bit																	-- not a base table column (default ignored)
		,@reasonRowGUID                  uniqueidentifier											-- not a base table column (default ignored)
		,@isDeleteEnabled                bit																	-- not a base table column (default ignored)
		,@isReselected                   tinyint           = 1								-- specific default required by EF - do not override
		,@isNullApplied                  bit               = 1								-- specific default required by EF - do not override
		,@isViewEnabled                  bit																	-- not a base table column (default ignored)
		,@isEditEnabled                  bit																	-- not a base table column (default ignored)
		,@isSaveBtnDisplayed             bit																	-- not a base table column (default ignored)
		,@isApproveEnabled               bit																	-- not a base table column (default ignored)
		,@isRejectEnabled                bit																	-- not a base table column (default ignored)
		,@isUnlockEnabled                bit																	-- not a base table column (default ignored)
		,@isWithdrawalEnabled            bit																	-- not a base table column (default ignored)
		,@isInProgress                   bit																	-- not a base table column (default ignored)
		,@isReviewRequired               bit																	-- not a base table column (default ignored)
		,@formStatusSID                  int																	-- not a base table column (default ignored)
		,@formStatusSCD                  varchar(25)													-- not a base table column (default ignored)
		,@formStatusLabel                nvarchar(35)													-- not a base table column (default ignored)
		,@lastStatusChangeUser           nvarchar(75)													-- not a base table column (default ignored)
		,@lastStatusChangeTime           datetimeoffset(7)										-- not a base table column (default ignored)
		,@formOwnerSID                   int																	-- not a base table column (default ignored)
		,@formOwnerSCD                   varchar(25)													-- not a base table column (default ignored)
		,@formOwnerLabel                 nvarchar(35)													-- not a base table column (default ignored)
		,@isPDFDisplayed                 bit																	-- not a base table column (default ignored)
		,@personDocSID                   int																	-- not a base table column (default ignored)
		,@personMailingAddressSID        int																	-- not a base table column (default ignored)
		,@personStreetAddress1           nvarchar(75)													-- not a base table column (default ignored)
		,@personStreetAddress2           nvarchar(75)													-- not a base table column (default ignored)
		,@personStreetAddress3           nvarchar(75)													-- not a base table column (default ignored)
		,@personCityName                 nvarchar(30)													-- not a base table column (default ignored)
		,@personStateProvinceName        nvarchar(30)													-- not a base table column (default ignored)
		,@personPostalCode               nvarchar(10)													-- not a base table column (default ignored)
		,@personCountryName              nvarchar(50)													-- not a base table column (default ignored)
		,@personCitySID                  int																	-- not a base table column (default ignored)
		,@registrationYearLabel          varchar(9)														-- not a base table column (default ignored)
		,@registrantAuditLabel           nvarchar(80)													-- not a base table column (default ignored)
		,@isSendForReviewEnabled         bit																	-- not a base table column (default ignored)
		,@isReviewInProgress             bit																	-- not a base table column (default ignored)
		,@isReviewFormConfigured         bit																	-- not a base table column (default ignored)
		,@recommendationLabel            nvarchar(20)													-- not a base table column (default ignored)
		,@newFormStatusSCD               varchar(25)													-- not a base table column (default ignored)
		,@reviewers                      xml																	-- not a base table column (default ignored)

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end
		-- set mandatory FK values to -1 where requested
		
		if @SetFKDefaults = @ON
		begin
			set @registrantSID = -1
			set @auditTypeSID = -1
			set @formVersionSID = -1
		end

		-- assign literal defaults passed through @zContext where
		-- provided otherwise leave database default in place
		
		select
			 @registrantSID          = isnull(context.node.value('@RegistrantSID'        ,'int'              ),@registrantSID)
			,@auditTypeSID           = isnull(context.node.value('@AuditTypeSID'         ,'int'              ),@auditTypeSID)
			,@registrationYear       = isnull(context.node.value('@RegistrationYear'     ,'smallint'         ),@registrationYear)
			,@formVersionSID         = isnull(context.node.value('@FormVersionSID'       ,'int'              ),@formVersionSID)
			,@lastValidateTime       = isnull(context.node.value('@LastValidateTime'     ,'datetimeoffset(7)'),@lastValidateTime)
			,@nextFollowUp           = isnull(context.node.value('@NextFollowUp'         ,'date'             ),@nextFollowUp)
			,@reasonSID              = isnull(context.node.value('@ReasonSID'            ,'int'              ),@reasonSID)
			,@confirmationDraft      = isnull(context.node.value('@ConfirmationDraft'    ,'nvarchar(max)'    ),@confirmationDraft)
			,@isAutoApprovalEnabled  = isnull(context.node.value('@IsAutoApprovalEnabled','bit'              ),@isAutoApprovalEnabled)
			,@registrantAuditXID     = isnull(context.node.value('@RegistrantAuditXID'   ,'varchar(150)'     ),@registrantAuditXID)
			,@legacyKey              = isnull(context.node.value('@LegacyKey'            ,'nvarchar(50)'     ),@legacyKey)
		from
			@zContext.nodes('Parameters') as context(node)
		
		-- set default value on foreign keys where configured
		-- and where no DB or literal value was passed for it
		
		if isnull(@auditTypeSID,0) = 0 select @auditTypeSID = x.AuditTypeSID from dbo.AuditType x where x.IsDefault = @ON

		--! <Overrides>
		-- Tim Edlund | Jan 2018
		-- If a form version is not provided, default it to the latest published form of the
		-- correct type. Context sub-selections (using the sf.form.FormContext column) do NOT
		-- apply for audits since audit forms are only completed for a single year at a time.
		-- If a FormContext is provided it is ignored.  Note also that a form version cannot
		-- be defaulted unless an audit type has been passed directly or derived from logic
		-- above.

		if isnull(@formVersionSID,0) = 0 and isnull(@auditTypeSID,0) <> 0
		begin
		
			select
				@formVersionSID = max(fv.FormVersionSID)
			from
				dbo.AuditTypeForm											atf
			join
				sf.Form                               f   on atf.FormSID = f.FormSID
			join
				sf.FormVersion                        fv  on f.FormSID = fv.FormSID and fv.VersionNo > 0																	-- filter out non-published versions
			where
				atf.AuditTypeSID = @auditTypeSID	
			and
				atf.IsReviewForm = @OFF																																																		-- filter out review forms

		end
		--! </Overrides>
	
		-- call the extended version of the procedure (if it exists) for "default.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pRegistrantAudit'
		)
		begin
		
			exec @errorNo = ext.pRegistrantAudit
				 @Mode                           = 'default.pre'
				,@RegistrantAuditSID = @registrantAuditSID
				,@RegistrantSID = @registrantSID output
				,@AuditTypeSID = @auditTypeSID output
				,@RegistrationYear = @registrationYear output
				,@FormVersionSID = @formVersionSID output
				,@FormResponseDraft = @formResponseDraft output
				,@LastValidateTime = @lastValidateTime output
				,@AdminComments = @adminComments output
				,@NextFollowUp = @nextFollowUp output
				,@PendingReviewers = @pendingReviewers output
				,@ReasonSID = @reasonSID output
				,@ConfirmationDraft = @confirmationDraft output
				,@IsAutoApprovalEnabled = @isAutoApprovalEnabled output
				,@ReviewReasonList = @reviewReasonList output
				,@UserDefinedColumns = @userDefinedColumns output
				,@RegistrantAuditXID = @registrantAuditXID output
				,@LegacyKey = @legacyKey output
				,@IsDeleted = @isDeleted
				,@CreateUser = @createUser
				,@CreateTime = @createTime
				,@UpdateUser = @updateUser
				,@UpdateTime = @updateTime
				,@RowGUID = @rowGUID
				,@RowStamp = @rowStamp
				,@AuditTypeLabel = @auditTypeLabel
				,@AuditTypeCategory = @auditTypeCategory
				,@AuditTypeIsDefault = @auditTypeIsDefault
				,@AuditTypeIsActive = @auditTypeIsActive
				,@AuditTypeRowGUID = @auditTypeRowGUID
				,@PersonSID = @personSID
				,@RegistrantNo = @registrantNo
				,@YearOfInitialEmployment = @yearOfInitialEmployment
				,@IsOnPublicRegistry = @isOnPublicRegistry
				,@CityNameOfBirth = @cityNameOfBirth
				,@CountrySID = @countrySID
				,@DirectedAuditYearCompetence = @directedAuditYearCompetence
				,@DirectedAuditYearPracticeHours = @directedAuditYearPracticeHours
				,@LateFeeExclusionYear = @lateFeeExclusionYear
				,@IsRenewalAutoApprovalBlocked = @isRenewalAutoApprovalBlocked
				,@RenewalExtensionExpiryTime = @renewalExtensionExpiryTime
				,@ArchivedTime = @archivedTime
				,@RegistrantRowGUID = @registrantRowGUID
				,@FormSID = @formSID
				,@VersionNo = @versionNo
				,@RevisionNo = @revisionNo
				,@IsSaveDisplayed = @isSaveDisplayed
				,@ApprovedTime = @approvedTime
				,@FormVersionRowGUID = @formVersionRowGUID
				,@ReasonGroupSID = @reasonGroupSID
				,@ReasonName = @reasonName
				,@ReasonCode = @reasonCode
				,@ReasonSequence = @reasonSequence
				,@ToolTip = @toolTip
				,@ReasonIsActive = @reasonIsActive
				,@ReasonRowGUID = @reasonRowGUID
				,@IsDeleteEnabled = @isDeleteEnabled
				,@IsReselected = @isReselected
				,@IsNullApplied = @isNullApplied
				,@zContext = @zContext output
				,@IsViewEnabled = @isViewEnabled
				,@IsEditEnabled = @isEditEnabled
				,@IsSaveBtnDisplayed = @isSaveBtnDisplayed
				,@IsApproveEnabled = @isApproveEnabled
				,@IsRejectEnabled = @isRejectEnabled
				,@IsUnlockEnabled = @isUnlockEnabled
				,@IsWithdrawalEnabled = @isWithdrawalEnabled
				,@IsInProgress = @isInProgress
				,@IsReviewRequired = @isReviewRequired
				,@FormStatusSID = @formStatusSID
				,@FormStatusSCD = @formStatusSCD
				,@FormStatusLabel = @formStatusLabel
				,@LastStatusChangeUser = @lastStatusChangeUser
				,@LastStatusChangeTime = @lastStatusChangeTime
				,@FormOwnerSID = @formOwnerSID
				,@FormOwnerSCD = @formOwnerSCD
				,@FormOwnerLabel = @formOwnerLabel
				,@IsPDFDisplayed = @isPDFDisplayed
				,@PersonDocSID = @personDocSID
				,@PersonMailingAddressSID = @personMailingAddressSID
				,@PersonStreetAddress1 = @personStreetAddress1
				,@PersonStreetAddress2 = @personStreetAddress2
				,@PersonStreetAddress3 = @personStreetAddress3
				,@PersonCityName = @personCityName
				,@PersonStateProvinceName = @personStateProvinceName
				,@PersonPostalCode = @personPostalCode
				,@PersonCountryName = @personCountryName
				,@PersonCitySID = @personCitySID
				,@RegistrationYearLabel = @registrationYearLabel
				,@RegistrantAuditLabel = @registrantAuditLabel
				,@IsSendForReviewEnabled = @isSendForReviewEnabled
				,@IsReviewInProgress = @isReviewInProgress
				,@IsReviewFormConfigured = @isReviewFormConfigured
				,@RecommendationLabel = @recommendationLabel
				,@NewFormStatusSCD = @newFormStatusSCD
				,@Reviewers = @reviewers
		
		end

		select
			 @registrantAuditSID RegistrantAuditSID
			,@registrantSID RegistrantSID
			,@auditTypeSID AuditTypeSID
			,@registrationYear RegistrationYear
			,@formVersionSID FormVersionSID
			,@formResponseDraft FormResponseDraft
			,@lastValidateTime LastValidateTime
			,@adminComments AdminComments
			,@nextFollowUp NextFollowUp
			,@pendingReviewers PendingReviewers
			,@reasonSID ReasonSID
			,@confirmationDraft ConfirmationDraft
			,@isAutoApprovalEnabled IsAutoApprovalEnabled
			,@reviewReasonList ReviewReasonList
			,@userDefinedColumns UserDefinedColumns
			,@registrantAuditXID RegistrantAuditXID
			,@legacyKey LegacyKey
			,@isDeleted IsDeleted
			,@createUser CreateUser
			,@createTime CreateTime
			,@updateUser UpdateUser
			,@updateTime UpdateTime
			,@rowGUID RowGUID
			,@rowStamp RowStamp
			,@auditTypeLabel AuditTypeLabel
			,@auditTypeCategory AuditTypeCategory
			,@auditTypeIsDefault AuditTypeIsDefault
			,@auditTypeIsActive AuditTypeIsActive
			,@auditTypeRowGUID AuditTypeRowGUID
			,@personSID PersonSID
			,@registrantNo RegistrantNo
			,@yearOfInitialEmployment YearOfInitialEmployment
			,@isOnPublicRegistry IsOnPublicRegistry
			,@cityNameOfBirth CityNameOfBirth
			,@countrySID CountrySID
			,@directedAuditYearCompetence DirectedAuditYearCompetence
			,@directedAuditYearPracticeHours DirectedAuditYearPracticeHours
			,@lateFeeExclusionYear LateFeeExclusionYear
			,@isRenewalAutoApprovalBlocked IsRenewalAutoApprovalBlocked
			,@renewalExtensionExpiryTime RenewalExtensionExpiryTime
			,@archivedTime ArchivedTime
			,@registrantRowGUID RegistrantRowGUID
			,@formSID FormSID
			,@versionNo VersionNo
			,@revisionNo RevisionNo
			,@isSaveDisplayed IsSaveDisplayed
			,@approvedTime ApprovedTime
			,@formVersionRowGUID FormVersionRowGUID
			,@reasonGroupSID ReasonGroupSID
			,@reasonName ReasonName
			,@reasonCode ReasonCode
			,@reasonSequence ReasonSequence
			,@toolTip ToolTip
			,@reasonIsActive ReasonIsActive
			,@reasonRowGUID ReasonRowGUID
			,@isDeleteEnabled IsDeleteEnabled
			,@isReselected IsReselected
			,@isNullApplied IsNullApplied
			,@zContext zContext
			,@isViewEnabled IsViewEnabled
			,@isEditEnabled IsEditEnabled
			,@isSaveBtnDisplayed IsSaveBtnDisplayed
			,@isApproveEnabled IsApproveEnabled
			,@isRejectEnabled IsRejectEnabled
			,@isUnlockEnabled IsUnlockEnabled
			,@isWithdrawalEnabled IsWithdrawalEnabled
			,@isInProgress IsInProgress
			,@isReviewRequired IsReviewRequired
			,@formStatusSID FormStatusSID
			,@formStatusSCD FormStatusSCD
			,@formStatusLabel FormStatusLabel
			,@lastStatusChangeUser LastStatusChangeUser
			,@lastStatusChangeTime LastStatusChangeTime
			,@formOwnerSID FormOwnerSID
			,@formOwnerSCD FormOwnerSCD
			,@formOwnerLabel FormOwnerLabel
			,@isPDFDisplayed IsPDFDisplayed
			,@personDocSID PersonDocSID
			,@personMailingAddressSID PersonMailingAddressSID
			,@personStreetAddress1 PersonStreetAddress1
			,@personStreetAddress2 PersonStreetAddress2
			,@personStreetAddress3 PersonStreetAddress3
			,@personCityName PersonCityName
			,@personStateProvinceName PersonStateProvinceName
			,@personPostalCode PersonPostalCode
			,@personCountryName PersonCountryName
			,@personCitySID PersonCitySID
			,@registrationYearLabel RegistrationYearLabel
			,@registrantAuditLabel RegistrantAuditLabel
			,@isSendForReviewEnabled IsSendForReviewEnabled
			,@isReviewInProgress IsReviewInProgress
			,@isReviewFormConfigured IsReviewFormConfigured
			,@recommendationLabel RecommendationLabel
			,@newFormStatusSCD NewFormStatusSCD
			,@reviewers Reviewers

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
