SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pRegistrationChange#Default]
	 @zContext                               xml               = null                -- default values provided from client-tier (if any)
	,@SetFKDefaults                          bit               = 0                   -- when 1, mandatory FK's are returned as -1 instead of NULL
as
/*********************************************************************************************************************************
Procedure : dbo.pRegistrationChange#Default
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : provides a blank row with default values for presentation in the UI for "new" dbo.RegistrationChange records
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the dbo.RegistrationChange table. When a new record is to be added from the UI, this procedure
is called to return a blank record with default values. If the client-tier is providing the context for the insert, such as a parent
key value for the new record, it must be passed in the @zContext XML parameter. Multiple values may be passed. The standard format
is: <Parameters MyParameter="1000001"/>.

The @SetFKDefaults parameter can be set to 1 to cause the procedure to return mandatory FK values as -1 rather than NULL. This avoids
the need to create complex types for the procedure on architectures which are not using RIA services.

Note that default values for text, ntext and binary type columns is not supported.  These data types are not permitted as local
variables in the current version of SQL Server and should be replaced by varchar(max) and nvarchar(max) where possible.

Some default values are built-in to the shell of the sproc.  The base table column defaults set in the variable declarations below
were obtained from database default constraints which existed at the time the procedure was generated. The declarations include all
columns of the vRegistrationChange entity view, however, only some values (as noted above) are eligible for default setting.  The other
parameters are included for setting context for the table-specific or client-specific logic of the procedure (if any). Default values
returning a question mark "?", system date, or 0 are provided for non-base table columns which are mandatory.  This is done to avoid
compilation errors from the Entity Framework, however, the values will not be applied since they are not in the base table row.

Two levels of customization of the procedure shell are supported. Table-specific logic can be added through the tagged section and a
call to an extended procedure supports client-specific customization. Logic implemented within the code tags is part of the base
product and applies to all client configurations. Client-specific customizations must be implemented in the ext.pRegistrationChange
procedure. The extended procedure is only called where it exists in database. The parameter "@Mode" is set to "default.pre" to
advise ext.pRegistrationChange of the context of the call. All other parameters are also passed, however, only those parameters eligible
for default setting are passed for "output". All parameters corresponding to entity view columns are returned through a SELECT statement.

In order to simplify working with the XML parameter values, logic in the procedure parses the XML and assigns values to variables where
the variable name matches the column name in the XML (assumes single row).  The variables are then available to the table-specific and
client-specific logic.  The @zContext parameter is also passed, unmodified, to the extended procedure to support situations where values
are passed that are not mapped to column names.


-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@ON                                     bit = cast(1 as bit)					-- constant for bit comparisons
		,@OFF                                    bit = cast(0 as bit)					-- constant for bit comparisons
		,@registrationChangeSID                  int               = -1				-- specific default required by EF - do not override
		,@registrationSID                        int               = null			-- no default provided from DB constraint - OK to override
		,@practiceRegisterSectionSID             int               = null			-- no default provided from DB constraint - OK to override
		,@registrationYear                       smallint          = null			-- no default provided from DB constraint - OK to override
		,@nextFollowUp                           date              = null			-- no default provided from DB constraint - OK to override
		,@registrationEffective                  date              = null			-- no default provided from DB constraint - OK to override
		,@reservedRegistrantNo                   varchar(50)       = null			-- no default provided from DB constraint - OK to override
		,@confirmationDraft                      nvarchar(max)     = null			-- no default provided from DB constraint - OK to override
		,@reasonSID                              int               = null			-- no default provided from DB constraint - OK to override
		,@invoiceSID                             int               = null			-- no default provided from DB constraint - OK to override
		,@complaintSID                           int               = null			-- no default provided from DB constraint - OK to override
		,@userDefinedColumns                     xml               = null			-- no default provided from DB constraint - OK to override
		,@registrationChangeXID                  varchar(150)      = null			-- no default provided from DB constraint - OK to override
		,@legacyKey                              nvarchar(50)      = null			-- no default provided from DB constraint - OK to override
		,@isDeleted                              bit               = (0)			-- default provided from DB constraint - OK to override
		,@createUser                             nvarchar(75)      = suser_sname()											-- default value ignored (value set by UI)
		,@createTime                             datetimeoffset(7) = sysdatetimeoffset()								-- default value ignored (set to system time)
		,@updateUser                             nvarchar(75)      = suser_sname()											-- default value ignored (value set by UI)
		,@updateTime                             datetimeoffset(7) = sysdatetimeoffset()								-- default value ignored (set to system time)
		,@rowGUID                                uniqueidentifier  = newid()	-- default value ignored (value set by system)
		,@rowStamp                               timestamp         = null			-- default value ignored (value set by system)
		,@practiceRegisterSID                    int               = 0				-- not a base table column (default ignored)
		,@practiceRegisterSectionLabel           nvarchar(35)      = N'?'			-- not a base table column (default ignored)
		,@practiceRegisterSectionIsDefault       bit               = 0				-- not a base table column (default ignored)
		,@isDisplayedOnLicense                   bit               = 0				-- not a base table column (default ignored)
		,@practiceRegisterSectionIsActive        bit               = 0				-- not a base table column (default ignored)
		,@practiceRegisterSectionRowGUID         uniqueidentifier  = newid()	-- not a base table column (default ignored)
		,@registrationRegistrantSID              int               = 0				-- not a base table column (default ignored)
		,@registrationPracticeRegisterSectionSID int               = 0				-- not a base table column (default ignored)
		,@registrationNo                         nvarchar(50)      = N'?'			-- not a base table column (default ignored)
		,@registrationRegistrationYear           smallint          = 0				-- not a base table column (default ignored)
		,@effectiveTime                          datetime          = sf.fNow()-- not a base table column (default ignored)
		,@expiryTime                             datetime          = sf.fNow()-- not a base table column (default ignored)
		,@cardPrintedTime                        datetime											-- not a base table column (default ignored)
		,@registrationInvoiceSID                 int													-- not a base table column (default ignored)
		,@registrationReasonSID                  int													-- not a base table column (default ignored)
		,@formGUID                               uniqueidentifier							-- not a base table column (default ignored)
		,@registrationRowGUID                    uniqueidentifier  = newid()	-- not a base table column (default ignored)
		,@reasonGroupSID                         int													-- not a base table column (default ignored)
		,@reasonName                             nvarchar(50)									-- not a base table column (default ignored)
		,@reasonCode                             varchar(25)									-- not a base table column (default ignored)
		,@reasonSequence                         smallint											-- not a base table column (default ignored)
		,@toolTip                                nvarchar(500)								-- not a base table column (default ignored)
		,@reasonIsActive                         bit													-- not a base table column (default ignored)
		,@reasonRowGUID                          uniqueidentifier							-- not a base table column (default ignored)
		,@complaintNo                            varchar(50)									-- not a base table column (default ignored)
		,@complaintRegistrantSID                 int													-- not a base table column (default ignored)
		,@complaintTypeSID                       int													-- not a base table column (default ignored)
		,@complainantTypeSID                     int													-- not a base table column (default ignored)
		,@applicationUserSID                     int													-- not a base table column (default ignored)
		,@openedDate                             date													-- not a base table column (default ignored)
		,@conductStartDate                       date													-- not a base table column (default ignored)
		,@conductEndDate                         date													-- not a base table column (default ignored)
		,@complaintSeveritySID                   int													-- not a base table column (default ignored)
		,@isDisplayedOnPublicRegistry            bit													-- not a base table column (default ignored)
		,@closedDate                             date													-- not a base table column (default ignored)
		,@dismissedDate                          date													-- not a base table column (default ignored)
		,@complaintReasonSID                     int													-- not a base table column (default ignored)
		,@fileExtension                          varchar(5)										-- not a base table column (default ignored)
		,@complaintRowGUID                       uniqueidentifier							-- not a base table column (default ignored)
		,@personSID                              int													-- not a base table column (default ignored)
		,@invoiceDate                            date													-- not a base table column (default ignored)
		,@tax1Label                              nvarchar(8)									-- not a base table column (default ignored)
		,@tax1Rate                               decimal(4,4)									-- not a base table column (default ignored)
		,@tax1GLAccountCode                      varchar(50)									-- not a base table column (default ignored)
		,@tax2Label                              nvarchar(8)									-- not a base table column (default ignored)
		,@tax2Rate                               decimal(4,4)									-- not a base table column (default ignored)
		,@tax2GLAccountCode                      varchar(50)									-- not a base table column (default ignored)
		,@tax3Label                              nvarchar(8)									-- not a base table column (default ignored)
		,@tax3Rate                               decimal(4,4)									-- not a base table column (default ignored)
		,@tax3GLAccountCode                      varchar(50)									-- not a base table column (default ignored)
		,@invoiceRegistrationYear                smallint											-- not a base table column (default ignored)
		,@cancelledTime                          datetimeoffset(7)						-- not a base table column (default ignored)
		,@invoiceReasonSID                       int													-- not a base table column (default ignored)
		,@isRefund                               bit													-- not a base table column (default ignored)
		,@invoiceComplaintSID                    int													-- not a base table column (default ignored)
		,@invoiceRowGUID                         uniqueidentifier							-- not a base table column (default ignored)
		,@isDeleteEnabled                        bit													-- not a base table column (default ignored)
		,@isReselected                           tinyint           = 1				-- specific default required by EF - do not override
		,@isNullApplied                          bit               = 1				-- specific default required by EF - do not override
		,@isViewEnabled                          bit													-- not a base table column (default ignored)
		,@isEditEnabled                          bit													-- not a base table column (default ignored)
		,@isApproveEnabled                       bit													-- not a base table column (default ignored)
		,@isRejectEnabled                        bit													-- not a base table column (default ignored)
		,@isUnlockEnabled                        bit													-- not a base table column (default ignored)
		,@isWithdrawalEnabled                    bit													-- not a base table column (default ignored)
		,@isInProgress                           bit													-- not a base table column (default ignored)
		,@formStatusSID                          int													-- not a base table column (default ignored)
		,@formStatusSCD                          varchar(25)									-- not a base table column (default ignored)
		,@formStatusLabel                        nvarchar(35)									-- not a base table column (default ignored)
		,@lastStatusChangeUser                   nvarchar(75)									-- not a base table column (default ignored)
		,@lastStatusChangeTime                   datetimeoffset(7)						-- not a base table column (default ignored)
		,@formOwnerSID                           int													-- not a base table column (default ignored)
		,@formOwnerSCD                           varchar(25)									-- not a base table column (default ignored)
		,@formOwnerLabel                         nvarchar(35)									-- not a base table column (default ignored)
		,@isPDFDisplayed                         bit													-- not a base table column (default ignored)
		,@personDocSID                           int													-- not a base table column (default ignored)
		,@totalDue                               decimal(11,2)								-- not a base table column (default ignored)
		,@isUnPaid                               bit													-- not a base table column (default ignored)
		,@personMailingAddressSID                int													-- not a base table column (default ignored)
		,@personStreetAddress1                   nvarchar(75)									-- not a base table column (default ignored)
		,@personStreetAddress2                   nvarchar(75)									-- not a base table column (default ignored)
		,@personStreetAddress3                   nvarchar(75)									-- not a base table column (default ignored)
		,@personCityName                         nvarchar(30)									-- not a base table column (default ignored)
		,@personStateProvinceName                nvarchar(30)									-- not a base table column (default ignored)
		,@personPostalCode                       nvarchar(10)									-- not a base table column (default ignored)
		,@personCountryName                      nvarchar(50)									-- not a base table column (default ignored)
		,@personCitySID                          int													-- not a base table column (default ignored)
		,@registrantPersonSID                    int													-- not a base table column (default ignored)
		,@registrationYearLabel                  varchar(9)										-- not a base table column (default ignored)
		,@practiceRegisterLabel                  nvarchar(35)									-- not a base table column (default ignored)
		,@practiceRegisterName                   nvarchar(65)									-- not a base table column (default ignored)
		,@registrationChangeLabel                nvarchar(100)								-- not a base table column (default ignored)
		,@isRegisterChange                       bit													-- not a base table column (default ignored)
		,@hasOpenAudit                           bit													-- not a base table column (default ignored)
		,@newFormStatusSCD                       varchar(25)									-- not a base table column (default ignored)
		,@reasonSIDOnApprove                     int													-- not a base table column (default ignored)

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end
		-- set mandatory FK values to -1 where requested
		
		if @SetFKDefaults = @ON
		begin
			set @registrationSID = -1
			set @practiceRegisterSectionSID = -1
		end

		-- assign literal defaults passed through @zContext where
		-- provided otherwise leave database default in place
		
		select
			 @registrationSID             = isnull(context.node.value('@RegistrationSID'           ,'int'          ),@registrationSID)
			,@practiceRegisterSectionSID  = isnull(context.node.value('@PracticeRegisterSectionSID','int'          ),@practiceRegisterSectionSID)
			,@registrationYear            = isnull(context.node.value('@RegistrationYear'          ,'smallint'     ),@registrationYear)
			,@nextFollowUp                = isnull(context.node.value('@NextFollowUp'              ,'date'         ),@nextFollowUp)
			,@registrationEffective       = isnull(context.node.value('@RegistrationEffective'     ,'date'         ),@registrationEffective)
			,@reservedRegistrantNo        = isnull(context.node.value('@ReservedRegistrantNo'      ,'varchar(50)'  ),@reservedRegistrantNo)
			,@confirmationDraft           = isnull(context.node.value('@ConfirmationDraft'         ,'nvarchar(max)'),@confirmationDraft)
			,@reasonSID                   = isnull(context.node.value('@ReasonSID'                 ,'int'          ),@reasonSID)
			,@invoiceSID                  = isnull(context.node.value('@InvoiceSID'                ,'int'          ),@invoiceSID)
			,@complaintSID                = isnull(context.node.value('@ComplaintSID'              ,'int'          ),@complaintSID)
			,@registrationChangeXID       = isnull(context.node.value('@RegistrationChangeXID'     ,'varchar(150)' ),@registrationChangeXID)
			,@legacyKey                   = isnull(context.node.value('@LegacyKey'                 ,'nvarchar(50)' ),@legacyKey)
		from
			@zContext.nodes('Parameters') as context(node)
		
		-- set default value on foreign keys where configured
		-- and where no DB or literal value was passed for it
		
		if isnull(@practiceRegisterSectionSID,0) = 0 select @practiceRegisterSectionSID = x.PracticeRegisterSectionSID from dbo.PracticeRegisterSection x where x.IsDefault = @ON and x.PracticeRegisterSID = @practiceRegisterSID

		--! <Overrides>
		--  insert default value logic here ...
		--! </Overrides>
	
		-- call the extended version of the procedure (if it exists) for "default.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pRegistrationChange'
		)
		begin
		
			exec @errorNo = ext.pRegistrationChange
				 @Mode                                   = 'default.pre'
				,@RegistrationChangeSID = @registrationChangeSID
				,@RegistrationSID = @registrationSID output
				,@PracticeRegisterSectionSID = @practiceRegisterSectionSID output
				,@RegistrationYear = @registrationYear output
				,@NextFollowUp = @nextFollowUp output
				,@RegistrationEffective = @registrationEffective output
				,@ReservedRegistrantNo = @reservedRegistrantNo output
				,@ConfirmationDraft = @confirmationDraft output
				,@ReasonSID = @reasonSID output
				,@InvoiceSID = @invoiceSID output
				,@ComplaintSID = @complaintSID output
				,@UserDefinedColumns = @userDefinedColumns output
				,@RegistrationChangeXID = @registrationChangeXID output
				,@LegacyKey = @legacyKey output
				,@IsDeleted = @isDeleted
				,@CreateUser = @createUser
				,@CreateTime = @createTime
				,@UpdateUser = @updateUser
				,@UpdateTime = @updateTime
				,@RowGUID = @rowGUID
				,@RowStamp = @rowStamp
				,@PracticeRegisterSID = @practiceRegisterSID
				,@PracticeRegisterSectionLabel = @practiceRegisterSectionLabel
				,@PracticeRegisterSectionIsDefault = @practiceRegisterSectionIsDefault
				,@IsDisplayedOnLicense = @isDisplayedOnLicense
				,@PracticeRegisterSectionIsActive = @practiceRegisterSectionIsActive
				,@PracticeRegisterSectionRowGUID = @practiceRegisterSectionRowGUID
				,@RegistrationRegistrantSID = @registrationRegistrantSID
				,@RegistrationPracticeRegisterSectionSID = @registrationPracticeRegisterSectionSID
				,@RegistrationNo = @registrationNo
				,@RegistrationRegistrationYear = @registrationRegistrationYear
				,@EffectiveTime = @effectiveTime
				,@ExpiryTime = @expiryTime
				,@CardPrintedTime = @cardPrintedTime
				,@RegistrationInvoiceSID = @registrationInvoiceSID
				,@RegistrationReasonSID = @registrationReasonSID
				,@FormGUID = @formGUID
				,@RegistrationRowGUID = @registrationRowGUID
				,@ReasonGroupSID = @reasonGroupSID
				,@ReasonName = @reasonName
				,@ReasonCode = @reasonCode
				,@ReasonSequence = @reasonSequence
				,@ToolTip = @toolTip
				,@ReasonIsActive = @reasonIsActive
				,@ReasonRowGUID = @reasonRowGUID
				,@ComplaintNo = @complaintNo
				,@ComplaintRegistrantSID = @complaintRegistrantSID
				,@ComplaintTypeSID = @complaintTypeSID
				,@ComplainantTypeSID = @complainantTypeSID
				,@ApplicationUserSID = @applicationUserSID
				,@OpenedDate = @openedDate
				,@ConductStartDate = @conductStartDate
				,@ConductEndDate = @conductEndDate
				,@ComplaintSeveritySID = @complaintSeveritySID
				,@IsDisplayedOnPublicRegistry = @isDisplayedOnPublicRegistry
				,@ClosedDate = @closedDate
				,@DismissedDate = @dismissedDate
				,@ComplaintReasonSID = @complaintReasonSID
				,@FileExtension = @fileExtension
				,@ComplaintRowGUID = @complaintRowGUID
				,@PersonSID = @personSID
				,@InvoiceDate = @invoiceDate
				,@Tax1Label = @tax1Label
				,@Tax1Rate = @tax1Rate
				,@Tax1GLAccountCode = @tax1GLAccountCode
				,@Tax2Label = @tax2Label
				,@Tax2Rate = @tax2Rate
				,@Tax2GLAccountCode = @tax2GLAccountCode
				,@Tax3Label = @tax3Label
				,@Tax3Rate = @tax3Rate
				,@Tax3GLAccountCode = @tax3GLAccountCode
				,@InvoiceRegistrationYear = @invoiceRegistrationYear
				,@CancelledTime = @cancelledTime
				,@InvoiceReasonSID = @invoiceReasonSID
				,@IsRefund = @isRefund
				,@InvoiceComplaintSID = @invoiceComplaintSID
				,@InvoiceRowGUID = @invoiceRowGUID
				,@IsDeleteEnabled = @isDeleteEnabled
				,@IsReselected = @isReselected
				,@IsNullApplied = @isNullApplied
				,@zContext = @zContext output
				,@IsViewEnabled = @isViewEnabled
				,@IsEditEnabled = @isEditEnabled
				,@IsApproveEnabled = @isApproveEnabled
				,@IsRejectEnabled = @isRejectEnabled
				,@IsUnlockEnabled = @isUnlockEnabled
				,@IsWithdrawalEnabled = @isWithdrawalEnabled
				,@IsInProgress = @isInProgress
				,@FormStatusSID = @formStatusSID
				,@FormStatusSCD = @formStatusSCD
				,@FormStatusLabel = @formStatusLabel
				,@LastStatusChangeUser = @lastStatusChangeUser
				,@LastStatusChangeTime = @lastStatusChangeTime
				,@FormOwnerSID = @formOwnerSID
				,@FormOwnerSCD = @formOwnerSCD
				,@FormOwnerLabel = @formOwnerLabel
				,@IsPDFDisplayed = @isPDFDisplayed
				,@PersonDocSID = @personDocSID
				,@TotalDue = @totalDue
				,@IsUnPaid = @isUnPaid
				,@PersonMailingAddressSID = @personMailingAddressSID
				,@PersonStreetAddress1 = @personStreetAddress1
				,@PersonStreetAddress2 = @personStreetAddress2
				,@PersonStreetAddress3 = @personStreetAddress3
				,@PersonCityName = @personCityName
				,@PersonStateProvinceName = @personStateProvinceName
				,@PersonPostalCode = @personPostalCode
				,@PersonCountryName = @personCountryName
				,@PersonCitySID = @personCitySID
				,@RegistrantPersonSID = @registrantPersonSID
				,@RegistrationYearLabel = @registrationYearLabel
				,@PracticeRegisterLabel = @practiceRegisterLabel
				,@PracticeRegisterName = @practiceRegisterName
				,@RegistrationChangeLabel = @registrationChangeLabel
				,@IsRegisterChange = @isRegisterChange
				,@HasOpenAudit = @hasOpenAudit
				,@NewFormStatusSCD = @newFormStatusSCD
				,@ReasonSIDOnApprove = @reasonSIDOnApprove
		
		end

		select
			 @registrationChangeSID RegistrationChangeSID
			,@registrationSID RegistrationSID
			,@practiceRegisterSectionSID PracticeRegisterSectionSID
			,@registrationYear RegistrationYear
			,@nextFollowUp NextFollowUp
			,@registrationEffective RegistrationEffective
			,@reservedRegistrantNo ReservedRegistrantNo
			,@confirmationDraft ConfirmationDraft
			,@reasonSID ReasonSID
			,@invoiceSID InvoiceSID
			,@complaintSID ComplaintSID
			,@userDefinedColumns UserDefinedColumns
			,@registrationChangeXID RegistrationChangeXID
			,@legacyKey LegacyKey
			,@isDeleted IsDeleted
			,@createUser CreateUser
			,@createTime CreateTime
			,@updateUser UpdateUser
			,@updateTime UpdateTime
			,@rowGUID RowGUID
			,@rowStamp RowStamp
			,@practiceRegisterSID PracticeRegisterSID
			,@practiceRegisterSectionLabel PracticeRegisterSectionLabel
			,@practiceRegisterSectionIsDefault PracticeRegisterSectionIsDefault
			,@isDisplayedOnLicense IsDisplayedOnLicense
			,@practiceRegisterSectionIsActive PracticeRegisterSectionIsActive
			,@practiceRegisterSectionRowGUID PracticeRegisterSectionRowGUID
			,@registrationRegistrantSID RegistrationRegistrantSID
			,@registrationPracticeRegisterSectionSID RegistrationPracticeRegisterSectionSID
			,@registrationNo RegistrationNo
			,@registrationRegistrationYear RegistrationRegistrationYear
			,@effectiveTime EffectiveTime
			,@expiryTime ExpiryTime
			,@cardPrintedTime CardPrintedTime
			,@registrationInvoiceSID RegistrationInvoiceSID
			,@registrationReasonSID RegistrationReasonSID
			,@formGUID FormGUID
			,@registrationRowGUID RegistrationRowGUID
			,@reasonGroupSID ReasonGroupSID
			,@reasonName ReasonName
			,@reasonCode ReasonCode
			,@reasonSequence ReasonSequence
			,@toolTip ToolTip
			,@reasonIsActive ReasonIsActive
			,@reasonRowGUID ReasonRowGUID
			,@complaintNo ComplaintNo
			,@complaintRegistrantSID ComplaintRegistrantSID
			,@complaintTypeSID ComplaintTypeSID
			,@complainantTypeSID ComplainantTypeSID
			,@applicationUserSID ApplicationUserSID
			,@openedDate OpenedDate
			,@conductStartDate ConductStartDate
			,@conductEndDate ConductEndDate
			,@complaintSeveritySID ComplaintSeveritySID
			,@isDisplayedOnPublicRegistry IsDisplayedOnPublicRegistry
			,@closedDate ClosedDate
			,@dismissedDate DismissedDate
			,@complaintReasonSID ComplaintReasonSID
			,@fileExtension FileExtension
			,@complaintRowGUID ComplaintRowGUID
			,@personSID PersonSID
			,@invoiceDate InvoiceDate
			,@tax1Label Tax1Label
			,@tax1Rate Tax1Rate
			,@tax1GLAccountCode Tax1GLAccountCode
			,@tax2Label Tax2Label
			,@tax2Rate Tax2Rate
			,@tax2GLAccountCode Tax2GLAccountCode
			,@tax3Label Tax3Label
			,@tax3Rate Tax3Rate
			,@tax3GLAccountCode Tax3GLAccountCode
			,@invoiceRegistrationYear InvoiceRegistrationYear
			,@cancelledTime CancelledTime
			,@invoiceReasonSID InvoiceReasonSID
			,@isRefund IsRefund
			,@invoiceComplaintSID InvoiceComplaintSID
			,@invoiceRowGUID InvoiceRowGUID
			,@isDeleteEnabled IsDeleteEnabled
			,@isReselected IsReselected
			,@isNullApplied IsNullApplied
			,@zContext zContext
			,@isViewEnabled IsViewEnabled
			,@isEditEnabled IsEditEnabled
			,@isApproveEnabled IsApproveEnabled
			,@isRejectEnabled IsRejectEnabled
			,@isUnlockEnabled IsUnlockEnabled
			,@isWithdrawalEnabled IsWithdrawalEnabled
			,@isInProgress IsInProgress
			,@formStatusSID FormStatusSID
			,@formStatusSCD FormStatusSCD
			,@formStatusLabel FormStatusLabel
			,@lastStatusChangeUser LastStatusChangeUser
			,@lastStatusChangeTime LastStatusChangeTime
			,@formOwnerSID FormOwnerSID
			,@formOwnerSCD FormOwnerSCD
			,@formOwnerLabel FormOwnerLabel
			,@isPDFDisplayed IsPDFDisplayed
			,@personDocSID PersonDocSID
			,@totalDue TotalDue
			,@isUnPaid IsUnPaid
			,@personMailingAddressSID PersonMailingAddressSID
			,@personStreetAddress1 PersonStreetAddress1
			,@personStreetAddress2 PersonStreetAddress2
			,@personStreetAddress3 PersonStreetAddress3
			,@personCityName PersonCityName
			,@personStateProvinceName PersonStateProvinceName
			,@personPostalCode PersonPostalCode
			,@personCountryName PersonCountryName
			,@personCitySID PersonCitySID
			,@registrantPersonSID RegistrantPersonSID
			,@registrationYearLabel RegistrationYearLabel
			,@practiceRegisterLabel PracticeRegisterLabel
			,@practiceRegisterName PracticeRegisterName
			,@registrationChangeLabel RegistrationChangeLabel
			,@isRegisterChange IsRegisterChange
			,@hasOpenAudit HasOpenAudit
			,@newFormStatusSCD NewFormStatusSCD
			,@reasonSIDOnApprove ReasonSIDOnApprove

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
