SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pComplaint#Default]
	 @zContext                         xml               = null                                -- default values provided from client-tier (if any)
	,@SetFKDefaults                    bit               = 0                                   -- when 1, mandatory FK's are returned as -1 instead of NULL
as
/*********************************************************************************************************************************
Procedure : dbo.pComplaint#Default
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : provides a blank row with default values for presentation in the UI for "new" dbo.Complaint records
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the dbo.Complaint table. When a new record is to be added from the UI, this procedure
is called to return a blank record with default values. If the client-tier is providing the context for the insert, such as a parent
key value for the new record, it must be passed in the @zContext XML parameter. Multiple values may be passed. The standard format
is: <Parameters MyParameter="1000001"/>.

The @SetFKDefaults parameter can be set to 1 to cause the procedure to return mandatory FK values as -1 rather than NULL. This avoids
the need to create complex types for the procedure on architectures which are not using RIA services.

Note that default values for text, ntext and binary type columns is not supported.  These data types are not permitted as local
variables in the current version of SQL Server and should be replaced by varchar(max) and nvarchar(max) where possible.

Some default values are built-in to the shell of the sproc.  The base table column defaults set in the variable declarations below
were obtained from database default constraints which existed at the time the procedure was generated. The declarations include all
columns of the vComplaint entity view, however, only some values (as noted above) are eligible for default setting.  The other
parameters are included for setting context for the table-specific or client-specific logic of the procedure (if any). Default values
returning a question mark "?", system date, or 0 are provided for non-base table columns which are mandatory.  This is done to avoid
compilation errors from the Entity Framework, however, the values will not be applied since they are not in the base table row.

Two levels of customization of the procedure shell are supported. Table-specific logic can be added through the tagged section and a
call to an extended procedure supports client-specific customization. Logic implemented within the code tags is part of the base
product and applies to all client configurations. Client-specific customizations must be implemented in the ext.pComplaint
procedure. The extended procedure is only called where it exists in database. The parameter "@Mode" is set to "default.pre" to
advise ext.pComplaint of the context of the call. All other parameters are also passed, however, only those parameters eligible
for default setting are passed for "output". All parameters corresponding to entity view columns are returned through a SELECT statement.

In order to simplify working with the XML parameter values, logic in the procedure parses the XML and assigns values to variables where
the variable name matches the column name in the XML (assumes single row).  The variables are then available to the table-specific and
client-specific logic.  The @zContext parameter is also passed, unmodified, to the extended procedure to support situations where values
are passed that are not mapped to column names.


-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@ON                               bit = cast(1 as bit)								-- constant for bit comparisons
		,@OFF                              bit = cast(0 as bit)								-- constant for bit comparisons
		,@complaintSID                     int               = -1							-- specific default required by EF - do not override
		,@complaintNo                      varchar(50)       = null						-- no default provided from DB constraint - OK to override
		,@registrantSID                    int               = null						-- no default provided from DB constraint - OK to override
		,@complaintTypeSID                 int               = null						-- no default provided from DB constraint - OK to override
		,@complainantTypeSID               int               = null						-- no default provided from DB constraint - OK to override
		,@applicationUserSID               int               = sf.fApplicationUserSessionUserSID()			-- default provided from DB constraint - OK to override
		,@openedDate                       date              = sf.fToday()		-- default provided from DB constraint - OK to override
		,@conductStartDate                 date              = null						-- no default provided from DB constraint - OK to override
		,@conductEndDate                   date              = null						-- no default provided from DB constraint - OK to override
		,@complaintSummary                 varbinary(max)    = null						-- no default provided from DB constraint - OK to override
		,@complaintSeveritySID             int               = null						-- no default provided from DB constraint - OK to override
		,@outcomeSummary                   varbinary(max)    = null						-- no default provided from DB constraint - OK to override
		,@isDisplayedOnPublicRegistry      bit               = (0)						-- default provided from DB constraint - OK to override
		,@closedDate                       date              = null						-- no default provided from DB constraint - OK to override
		,@dismissedDate                    date              = null						-- no default provided from DB constraint - OK to override
		,@reasonSID                        int               = null						-- no default provided from DB constraint - OK to override
		,@tagList                          xml               = CONVERT(xml,N'<Tags/>')									-- default provided from DB constraint - OK to override
		,@fileExtension                    varchar(5)        = '.html'				-- default provided from DB constraint - OK to override
		,@userDefinedColumns               xml               = null						-- no default provided from DB constraint - OK to override
		,@complaintXID                     varchar(150)      = null						-- no default provided from DB constraint - OK to override
		,@legacyKey                        nvarchar(50)      = null						-- no default provided from DB constraint - OK to override
		,@isDeleted                        bit               = (0)						-- default provided from DB constraint - OK to override
		,@createUser                       nvarchar(75)      = suser_sname()	-- default value ignored (value set by UI)
		,@createTime                       datetimeoffset(7) = sysdatetimeoffset()											-- default value ignored (set to system time)
		,@updateUser                       nvarchar(75)      = suser_sname()	-- default value ignored (value set by UI)
		,@updateTime                       datetimeoffset(7) = sysdatetimeoffset()											-- default value ignored (set to system time)
		,@rowGUID                          uniqueidentifier  = newid()				-- default value ignored (value set by system)
		,@rowStamp                         timestamp         = null						-- default value ignored (value set by system)
		,@complainantTypeLabel             nvarchar(35)      = N'?'						-- not a base table column (default ignored)
		,@complainantTypeCategory          nvarchar(65)												-- not a base table column (default ignored)
		,@complainantTypeIsDefault         bit               = 0							-- not a base table column (default ignored)
		,@complainantTypeIsActive          bit               = 0							-- not a base table column (default ignored)
		,@complainantTypeRowGUID           uniqueidentifier  = newid()				-- not a base table column (default ignored)
		,@complaintSeverityLabel           nvarchar(35)      = N'?'						-- not a base table column (default ignored)
		,@complaintSeverityCategory        nvarchar(65)												-- not a base table column (default ignored)
		,@complaintSeverityIsDefault       bit               = 0							-- not a base table column (default ignored)
		,@complaintSeverityIsActive        bit               = 0							-- not a base table column (default ignored)
		,@complaintSeverityRowGUID         uniqueidentifier  = newid()				-- not a base table column (default ignored)
		,@complaintTypeLabel               nvarchar(35)      = N'?'						-- not a base table column (default ignored)
		,@complaintTypeCategory            nvarchar(65)												-- not a base table column (default ignored)
		,@complaintTypeIsDefault           bit               = 0							-- not a base table column (default ignored)
		,@complaintTypeIsActive            bit               = 0							-- not a base table column (default ignored)
		,@complaintTypeRowGUID             uniqueidentifier  = newid()				-- not a base table column (default ignored)
		,@registrantPersonSID              int               = 0							-- not a base table column (default ignored)
		,@registrantNo                     varchar(50)       = '?'						-- not a base table column (default ignored)
		,@yearOfInitialEmployment          smallint														-- not a base table column (default ignored)
		,@isOnPublicRegistry               bit               = 0							-- not a base table column (default ignored)
		,@cityNameOfBirth                  nvarchar(30)												-- not a base table column (default ignored)
		,@countrySID                       int																-- not a base table column (default ignored)
		,@directedAuditYearCompetence      smallint														-- not a base table column (default ignored)
		,@directedAuditYearPracticeHours   smallint														-- not a base table column (default ignored)
		,@lateFeeExclusionYear             smallint														-- not a base table column (default ignored)
		,@isRenewalAutoApprovalBlocked     bit               = 0							-- not a base table column (default ignored)
		,@renewalExtensionExpiryTime       datetime														-- not a base table column (default ignored)
		,@archivedTime                     datetimeoffset(7)									-- not a base table column (default ignored)
		,@registrantRowGUID                uniqueidentifier  = newid()				-- not a base table column (default ignored)
		,@applicationUserPersonSID         int               = 0							-- not a base table column (default ignored)
		,@cultureSID                       int               = 0							-- not a base table column (default ignored)
		,@authenticationAuthoritySID       int               = 0							-- not a base table column (default ignored)
		,@userName                         nvarchar(75)      = N'?'						-- not a base table column (default ignored)
		,@lastReviewTime                   datetimeoffset(7) = sysdatetimeoffset()											-- not a base table column (default ignored)
		,@lastReviewUser                   nvarchar(75)      = N'?'						-- not a base table column (default ignored)
		,@isPotentialDuplicate             bit               = 0							-- not a base table column (default ignored)
		,@isTemplate                       bit               = 0							-- not a base table column (default ignored)
		,@glassBreakPassword               varbinary(8000)										-- not a base table column (default ignored)
		,@lastGlassBreakPasswordChangeTime datetimeoffset(7)									-- not a base table column (default ignored)
		,@applicationUserIsActive          bit               = 0							-- not a base table column (default ignored)
		,@authenticationSystemID           nvarchar(50)      = N'?'						-- not a base table column (default ignored)
		,@applicationUserRowGUID           uniqueidentifier  = newid()				-- not a base table column (default ignored)
		,@reasonGroupSID                   int																-- not a base table column (default ignored)
		,@reasonName                       nvarchar(50)												-- not a base table column (default ignored)
		,@reasonCode                       varchar(25)												-- not a base table column (default ignored)
		,@reasonSequence                   smallint														-- not a base table column (default ignored)
		,@toolTip                          nvarchar(500)											-- not a base table column (default ignored)
		,@reasonIsActive                   bit																-- not a base table column (default ignored)
		,@reasonRowGUID                    uniqueidentifier										-- not a base table column (default ignored)
		,@isDeleteEnabled                  bit																-- not a base table column (default ignored)
		,@isReselected                     tinyint           = 1							-- specific default required by EF - do not override
		,@isNullApplied                    bit               = 1							-- specific default required by EF - do not override
		,@complaintLabel                   nvarchar(115)											-- not a base table column (default ignored)
		,@isDismissed                      bit																-- not a base table column (default ignored)
		,@isClosed                         bit																-- not a base table column (default ignored)
		,@isCloseEnabled                   bit																-- not a base table column (default ignored)
		,@complaintProcessSID              int																-- not a base table column (default ignored)
		,@complainantPersonSID             int																-- not a base table column (default ignored)
		,@complaintStatusLabel             nvarchar(35)												-- not a base table column (default ignored)

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end
		-- set mandatory FK values to -1 where requested
		
		if @SetFKDefaults = @ON
		begin
			set @registrantSID = -1
			set @complaintTypeSID = -1
			set @complainantTypeSID = -1
			set @applicationUserSID = -1
			set @complaintSeveritySID = -1
		end

		-- assign literal defaults passed through @zContext where
		-- provided otherwise leave database default in place
		
		select
			 @complaintNo                  = isnull(context.node.value('@ComplaintNo'                ,'varchar(50)'   ),@complaintNo)
			,@registrantSID                = isnull(context.node.value('@RegistrantSID'              ,'int'           ),@registrantSID)
			,@complaintTypeSID             = isnull(context.node.value('@ComplaintTypeSID'           ,'int'           ),@complaintTypeSID)
			,@complainantTypeSID           = isnull(context.node.value('@ComplainantTypeSID'         ,'int'           ),@complainantTypeSID)
			,@applicationUserSID           = isnull(context.node.value('@ApplicationUserSID'         ,'int'           ),@applicationUserSID)
			,@openedDate                   = isnull(context.node.value('@OpenedDate'                 ,'date'          ),@openedDate)
			,@conductStartDate             = isnull(context.node.value('@ConductStartDate'           ,'date'          ),@conductStartDate)
			,@conductEndDate               = isnull(context.node.value('@ConductEndDate'             ,'date'          ),@conductEndDate)
			,@complaintSummary             = isnull(context.node.value('@ComplaintSummary'           ,'varbinary(max)'),@complaintSummary)
			,@complaintSeveritySID         = isnull(context.node.value('@ComplaintSeveritySID'       ,'int'           ),@complaintSeveritySID)
			,@outcomeSummary               = isnull(context.node.value('@OutcomeSummary'             ,'varbinary(max)'),@outcomeSummary)
			,@isDisplayedOnPublicRegistry  = isnull(context.node.value('@IsDisplayedOnPublicRegistry','bit'           ),@isDisplayedOnPublicRegistry)
			,@closedDate                   = isnull(context.node.value('@ClosedDate'                 ,'date'          ),@closedDate)
			,@dismissedDate                = isnull(context.node.value('@DismissedDate'              ,'date'          ),@dismissedDate)
			,@reasonSID                    = isnull(context.node.value('@ReasonSID'                  ,'int'           ),@reasonSID)
			,@fileExtension                = isnull(context.node.value('@FileExtension'              ,'varchar(5)'    ),@fileExtension)
			,@complaintXID                 = isnull(context.node.value('@ComplaintXID'               ,'varchar(150)'  ),@complaintXID)
			,@legacyKey                    = isnull(context.node.value('@LegacyKey'                  ,'nvarchar(50)'  ),@legacyKey)
		from
			@zContext.nodes('Parameters') as context(node)
		
		-- set default value on foreign keys where configured
		-- and where no DB or literal value was passed for it
		
		if isnull(@complainantTypeSID  ,0) = 0 select @complainantTypeSID   = x.ComplainantTypeSID   from dbo.ComplainantType   x where x.IsDefault = @ON
		if isnull(@complaintSeveritySID,0) = 0 select @complaintSeveritySID = x.ComplaintSeveritySID from dbo.ComplaintSeverity x where x.IsDefault = @ON
		if isnull(@complaintTypeSID    ,0) = 0 select @complaintTypeSID     = x.ComplaintTypeSID     from dbo.ComplaintType     x where x.IsDefault = @ON

		--! <Overrides>
		
		-- Cory Ng | Mar 2019
		-- Default the complaint no to "+" if not explicitly
		-- passed so the insert sproc will grab the next value
		-- in the sequence

		if @complaintNo is null
		begin
			set @complaintNo = '+'
		end
		

		--! </Overrides>
	
		-- call the extended version of the procedure (if it exists) for "default.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pComplaint'
		)
		begin
		
			exec @errorNo = ext.pComplaint
				 @Mode                             = 'default.pre'
				,@ComplaintSID = @complaintSID
				,@ComplaintNo = @complaintNo output
				,@RegistrantSID = @registrantSID output
				,@ComplaintTypeSID = @complaintTypeSID output
				,@ComplainantTypeSID = @complainantTypeSID output
				,@ApplicationUserSID = @applicationUserSID output
				,@OpenedDate = @openedDate output
				,@ConductStartDate = @conductStartDate output
				,@ConductEndDate = @conductEndDate output
				,@ComplaintSummary = @complaintSummary output
				,@ComplaintSeveritySID = @complaintSeveritySID output
				,@OutcomeSummary = @outcomeSummary output
				,@IsDisplayedOnPublicRegistry = @isDisplayedOnPublicRegistry output
				,@ClosedDate = @closedDate output
				,@DismissedDate = @dismissedDate output
				,@ReasonSID = @reasonSID output
				,@TagList = @tagList output
				,@FileExtension = @fileExtension output
				,@UserDefinedColumns = @userDefinedColumns output
				,@ComplaintXID = @complaintXID output
				,@LegacyKey = @legacyKey output
				,@IsDeleted = @isDeleted
				,@CreateUser = @createUser
				,@CreateTime = @createTime
				,@UpdateUser = @updateUser
				,@UpdateTime = @updateTime
				,@RowGUID = @rowGUID
				,@RowStamp = @rowStamp
				,@ComplainantTypeLabel = @complainantTypeLabel
				,@ComplainantTypeCategory = @complainantTypeCategory
				,@ComplainantTypeIsDefault = @complainantTypeIsDefault
				,@ComplainantTypeIsActive = @complainantTypeIsActive
				,@ComplainantTypeRowGUID = @complainantTypeRowGUID
				,@ComplaintSeverityLabel = @complaintSeverityLabel
				,@ComplaintSeverityCategory = @complaintSeverityCategory
				,@ComplaintSeverityIsDefault = @complaintSeverityIsDefault
				,@ComplaintSeverityIsActive = @complaintSeverityIsActive
				,@ComplaintSeverityRowGUID = @complaintSeverityRowGUID
				,@ComplaintTypeLabel = @complaintTypeLabel
				,@ComplaintTypeCategory = @complaintTypeCategory
				,@ComplaintTypeIsDefault = @complaintTypeIsDefault
				,@ComplaintTypeIsActive = @complaintTypeIsActive
				,@ComplaintTypeRowGUID = @complaintTypeRowGUID
				,@RegistrantPersonSID = @registrantPersonSID
				,@RegistrantNo = @registrantNo
				,@YearOfInitialEmployment = @yearOfInitialEmployment
				,@IsOnPublicRegistry = @isOnPublicRegistry
				,@CityNameOfBirth = @cityNameOfBirth
				,@CountrySID = @countrySID
				,@DirectedAuditYearCompetence = @directedAuditYearCompetence
				,@DirectedAuditYearPracticeHours = @directedAuditYearPracticeHours
				,@LateFeeExclusionYear = @lateFeeExclusionYear
				,@IsRenewalAutoApprovalBlocked = @isRenewalAutoApprovalBlocked
				,@RenewalExtensionExpiryTime = @renewalExtensionExpiryTime
				,@ArchivedTime = @archivedTime
				,@RegistrantRowGUID = @registrantRowGUID
				,@ApplicationUserPersonSID = @applicationUserPersonSID
				,@CultureSID = @cultureSID
				,@AuthenticationAuthoritySID = @authenticationAuthoritySID
				,@UserName = @userName
				,@LastReviewTime = @lastReviewTime
				,@LastReviewUser = @lastReviewUser
				,@IsPotentialDuplicate = @isPotentialDuplicate
				,@IsTemplate = @isTemplate
				,@GlassBreakPassword = @glassBreakPassword
				,@LastGlassBreakPasswordChangeTime = @lastGlassBreakPasswordChangeTime
				,@ApplicationUserIsActive = @applicationUserIsActive
				,@AuthenticationSystemID = @authenticationSystemID
				,@ApplicationUserRowGUID = @applicationUserRowGUID
				,@ReasonGroupSID = @reasonGroupSID
				,@ReasonName = @reasonName
				,@ReasonCode = @reasonCode
				,@ReasonSequence = @reasonSequence
				,@ToolTip = @toolTip
				,@ReasonIsActive = @reasonIsActive
				,@ReasonRowGUID = @reasonRowGUID
				,@IsDeleteEnabled = @isDeleteEnabled
				,@IsReselected = @isReselected
				,@IsNullApplied = @isNullApplied
				,@zContext = @zContext output
				,@ComplaintLabel = @complaintLabel
				,@IsDismissed = @isDismissed
				,@IsClosed = @isClosed
				,@IsCloseEnabled = @isCloseEnabled
				,@ComplaintProcessSID = @complaintProcessSID
				,@ComplainantPersonSID = @complainantPersonSID
				,@ComplaintStatusLabel = @complaintStatusLabel
		
		end

		select
			 @complaintSID ComplaintSID
			,@complaintNo ComplaintNo
			,@registrantSID RegistrantSID
			,@complaintTypeSID ComplaintTypeSID
			,@complainantTypeSID ComplainantTypeSID
			,@applicationUserSID ApplicationUserSID
			,@openedDate OpenedDate
			,@conductStartDate ConductStartDate
			,@conductEndDate ConductEndDate
			,@complaintSummary ComplaintSummary
			,@complaintSeveritySID ComplaintSeveritySID
			,@outcomeSummary OutcomeSummary
			,@isDisplayedOnPublicRegistry IsDisplayedOnPublicRegistry
			,@closedDate ClosedDate
			,@dismissedDate DismissedDate
			,@reasonSID ReasonSID
			,@tagList TagList
			,@fileExtension FileExtension
			,@userDefinedColumns UserDefinedColumns
			,@complaintXID ComplaintXID
			,@legacyKey LegacyKey
			,@isDeleted IsDeleted
			,@createUser CreateUser
			,@createTime CreateTime
			,@updateUser UpdateUser
			,@updateTime UpdateTime
			,@rowGUID RowGUID
			,@rowStamp RowStamp
			,@complainantTypeLabel ComplainantTypeLabel
			,@complainantTypeCategory ComplainantTypeCategory
			,@complainantTypeIsDefault ComplainantTypeIsDefault
			,@complainantTypeIsActive ComplainantTypeIsActive
			,@complainantTypeRowGUID ComplainantTypeRowGUID
			,@complaintSeverityLabel ComplaintSeverityLabel
			,@complaintSeverityCategory ComplaintSeverityCategory
			,@complaintSeverityIsDefault ComplaintSeverityIsDefault
			,@complaintSeverityIsActive ComplaintSeverityIsActive
			,@complaintSeverityRowGUID ComplaintSeverityRowGUID
			,@complaintTypeLabel ComplaintTypeLabel
			,@complaintTypeCategory ComplaintTypeCategory
			,@complaintTypeIsDefault ComplaintTypeIsDefault
			,@complaintTypeIsActive ComplaintTypeIsActive
			,@complaintTypeRowGUID ComplaintTypeRowGUID
			,@registrantPersonSID RegistrantPersonSID
			,@registrantNo RegistrantNo
			,@yearOfInitialEmployment YearOfInitialEmployment
			,@isOnPublicRegistry IsOnPublicRegistry
			,@cityNameOfBirth CityNameOfBirth
			,@countrySID CountrySID
			,@directedAuditYearCompetence DirectedAuditYearCompetence
			,@directedAuditYearPracticeHours DirectedAuditYearPracticeHours
			,@lateFeeExclusionYear LateFeeExclusionYear
			,@isRenewalAutoApprovalBlocked IsRenewalAutoApprovalBlocked
			,@renewalExtensionExpiryTime RenewalExtensionExpiryTime
			,@archivedTime ArchivedTime
			,@registrantRowGUID RegistrantRowGUID
			,@applicationUserPersonSID ApplicationUserPersonSID
			,@cultureSID CultureSID
			,@authenticationAuthoritySID AuthenticationAuthoritySID
			,@userName UserName
			,@lastReviewTime LastReviewTime
			,@lastReviewUser LastReviewUser
			,@isPotentialDuplicate IsPotentialDuplicate
			,@isTemplate IsTemplate
			,@glassBreakPassword GlassBreakPassword
			,@lastGlassBreakPasswordChangeTime LastGlassBreakPasswordChangeTime
			,@applicationUserIsActive ApplicationUserIsActive
			,@authenticationSystemID AuthenticationSystemID
			,@applicationUserRowGUID ApplicationUserRowGUID
			,@reasonGroupSID ReasonGroupSID
			,@reasonName ReasonName
			,@reasonCode ReasonCode
			,@reasonSequence ReasonSequence
			,@toolTip ToolTip
			,@reasonIsActive ReasonIsActive
			,@reasonRowGUID ReasonRowGUID
			,@isDeleteEnabled IsDeleteEnabled
			,@isReselected IsReselected
			,@isNullApplied IsNullApplied
			,@zContext zContext
			,@complaintLabel ComplaintLabel
			,@isDismissed IsDismissed
			,@isClosed IsClosed
			,@isCloseEnabled IsCloseEnabled
			,@complaintProcessSID ComplaintProcessSID
			,@complainantPersonSID ComplainantPersonSID
			,@complaintStatusLabel ComplaintStatusLabel

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
