SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pCatalogItemPrice#Default]
	 @zContext                     xml               = null                          -- default values provided from client-tier (if any)
	,@SetFKDefaults                bit               = 0                             -- when 1, mandatory FK's are returned as -1 instead of NULL
as
/*********************************************************************************************************************************
Procedure : dbo.pCatalogItemPrice#Default
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : provides a blank row with default values for presentation in the UI for "new" dbo.CatalogItemPrice records
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the dbo.CatalogItemPrice table. When a new record is to be added from the UI, this procedure
is called to return a blank record with default values. If the client-tier is providing the context for the insert, such as a parent
key value for the new record, it must be passed in the @zContext XML parameter. Multiple values may be passed. The standard format
is: <Parameters MyParameter="1000001"/>.

The @SetFKDefaults parameter can be set to 1 to cause the procedure to return mandatory FK values as -1 rather than NULL. This avoids
the need to create complex types for the procedure on architectures which are not using RIA services.

Note that default values for text, ntext and binary type columns is not supported.  These data types are not permitted as local
variables in the current version of SQL Server and should be replaced by varchar(max) and nvarchar(max) where possible.

Some default values are built-in to the shell of the sproc.  The base table column defaults set in the variable declarations below
were obtained from database default constraints which existed at the time the procedure was generated. The declarations include all
columns of the vCatalogItemPrice entity view, however, only some values (as noted above) are eligible for default setting.  The other
parameters are included for setting context for the table-specific or client-specific logic of the procedure (if any). Default values
returning a question mark "?", system date, or 0 are provided for non-base table columns which are mandatory.  This is done to avoid
compilation errors from the Entity Framework, however, the values will not be applied since they are not in the base table row.

Two levels of customization of the procedure shell are supported. Table-specific logic can be added through the tagged section and a
call to an extended procedure supports client-specific customization. Logic implemented within the code tags is part of the base
product and applies to all client configurations. Client-specific customizations must be implemented in the ext.pCatalogItemPrice
procedure. The extended procedure is only called where it exists in database. The parameter "@Mode" is set to "default.pre" to
advise ext.pCatalogItemPrice of the context of the call. All other parameters are also passed, however, only those parameters eligible
for default setting are passed for "output". All parameters corresponding to entity view columns are returned through a SELECT statement.

In order to simplify working with the XML parameter values, logic in the procedure parses the XML and assigns values to variables where
the variable name matches the column name in the XML (assumes single row).  The variables are then available to the table-specific and
client-specific logic.  The @zContext parameter is also passed, unmodified, to the extended procedure to support situations where values
are passed that are not mapped to column names.


-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@ON                           bit = cast(1 as bit)										-- constant for bit comparisons
		,@OFF                          bit = cast(0 as bit)										-- constant for bit comparisons
		,@catalogItemPriceSID          int               = -1									-- specific default required by EF - do not override
		,@catalogItemSID               int               = null								-- no default provided from DB constraint - OK to override
		,@price                        decimal(11,2)     = null								-- no default provided from DB constraint - OK to override
		,@effectiveTime                datetime          = CONVERT(datetime,sf.fToday())								-- default provided from DB constraint - OK to override
		,@userDefinedColumns           xml               = null								-- no default provided from DB constraint - OK to override
		,@catalogItemPriceXID          varchar(150)      = null								-- no default provided from DB constraint - OK to override
		,@legacyKey                    nvarchar(50)      = null								-- no default provided from DB constraint - OK to override
		,@isDeleted                    bit               = (0)								-- default provided from DB constraint - OK to override
		,@createUser                   nvarchar(75)      = suser_sname()			-- default value ignored (value set by UI)
		,@createTime                   datetimeoffset(7) = sysdatetimeoffset()-- default value ignored (set to system time)
		,@updateUser                   nvarchar(75)      = suser_sname()			-- default value ignored (value set by UI)
		,@updateTime                   datetimeoffset(7) = sysdatetimeoffset()-- default value ignored (set to system time)
		,@rowGUID                      uniqueidentifier  = newid()						-- default value ignored (value set by system)
		,@rowStamp                     timestamp         = null								-- default value ignored (value set by system)
		,@catalogItemLabel             nvarchar(35)      = N'?'								-- not a base table column (default ignored)
		,@invoiceItemDescription       nvarchar(500)     = N'?'								-- not a base table column (default ignored)
		,@isLateFee                    bit               = 0									-- not a base table column (default ignored)
		,@imageAlternateText           nvarchar(50)														-- not a base table column (default ignored)
		,@isAvailableOnClientPortal    bit               = 0									-- not a base table column (default ignored)
		,@isComplaintPenalty           bit               = 0									-- not a base table column (default ignored)
		,@gLAccountSID                 int               = 0									-- not a base table column (default ignored)
		,@isTaxRate1Applied            bit               = 0									-- not a base table column (default ignored)
		,@isTaxRate2Applied            bit               = 0									-- not a base table column (default ignored)
		,@isTaxRate3Applied            bit               = 0									-- not a base table column (default ignored)
		,@isTaxDeductible              bit               = 0									-- not a base table column (default ignored)
		,@catalogItemEffectiveTime     datetime          = sf.fNow()					-- not a base table column (default ignored)
		,@expiryTime                   datetime																-- not a base table column (default ignored)
		,@fileTypeSCD                  varchar(8)        = '?'								-- not a base table column (default ignored)
		,@fileTypeSID                  int               = 0									-- not a base table column (default ignored)
		,@catalogItemRowGUID           uniqueidentifier  = newid()						-- not a base table column (default ignored)
		,@isDeleteEnabled              bit																		-- not a base table column (default ignored)
		,@isReselected                 tinyint           = 1									-- specific default required by EF - do not override
		,@isNullApplied                bit               = 1									-- specific default required by EF - do not override
		,@catalogItemPriceProrationSID int																		-- not a base table column (default ignored)
		,@currentPrice                 decimal(11,2)													-- not a base table column (default ignored)
		,@isProrated                   bit																		-- not a base table column (default ignored)

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end
		-- set mandatory FK values to -1 where requested
		
		if @SetFKDefaults = @ON
		begin
			set @catalogItemSID = -1
		end

		-- assign literal defaults passed through @zContext where
		-- provided otherwise leave database default in place
		
		select
			 @catalogItemSID       = isnull(context.node.value('@CatalogItemSID'     ,'int'          ),@catalogItemSID)
			,@price                = isnull(context.node.value('@Price'              ,'decimal(11,2)'),@price)
			,@effectiveTime        = isnull(context.node.value('@EffectiveTime'      ,'datetime'     ),@effectiveTime)
			,@catalogItemPriceXID  = isnull(context.node.value('@CatalogItemPriceXID','varchar(150)' ),@catalogItemPriceXID)
			,@legacyKey            = isnull(context.node.value('@LegacyKey'          ,'nvarchar(50)' ),@legacyKey)
		from
			@zContext.nodes('Parameters') as context(node)
		

		--! <Overrides>
		--  insert default value logic here ...
		--! </Overrides>
	
		-- call the extended version of the procedure (if it exists) for "default.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pCatalogItemPrice'
		)
		begin
		
			exec @errorNo = ext.pCatalogItemPrice
				 @Mode                         = 'default.pre'
				,@CatalogItemPriceSID = @catalogItemPriceSID
				,@CatalogItemSID = @catalogItemSID output
				,@Price = @price output
				,@EffectiveTime = @effectiveTime output
				,@UserDefinedColumns = @userDefinedColumns output
				,@CatalogItemPriceXID = @catalogItemPriceXID output
				,@LegacyKey = @legacyKey output
				,@IsDeleted = @isDeleted
				,@CreateUser = @createUser
				,@CreateTime = @createTime
				,@UpdateUser = @updateUser
				,@UpdateTime = @updateTime
				,@RowGUID = @rowGUID
				,@RowStamp = @rowStamp
				,@CatalogItemLabel = @catalogItemLabel
				,@InvoiceItemDescription = @invoiceItemDescription
				,@IsLateFee = @isLateFee
				,@ImageAlternateText = @imageAlternateText
				,@IsAvailableOnClientPortal = @isAvailableOnClientPortal
				,@IsComplaintPenalty = @isComplaintPenalty
				,@GLAccountSID = @gLAccountSID
				,@IsTaxRate1Applied = @isTaxRate1Applied
				,@IsTaxRate2Applied = @isTaxRate2Applied
				,@IsTaxRate3Applied = @isTaxRate3Applied
				,@IsTaxDeductible = @isTaxDeductible
				,@CatalogItemEffectiveTime = @catalogItemEffectiveTime
				,@ExpiryTime = @expiryTime
				,@FileTypeSCD = @fileTypeSCD
				,@FileTypeSID = @fileTypeSID
				,@CatalogItemRowGUID = @catalogItemRowGUID
				,@IsDeleteEnabled = @isDeleteEnabled
				,@IsReselected = @isReselected
				,@IsNullApplied = @isNullApplied
				,@zContext = @zContext output
				,@CatalogItemPriceProrationSID = @catalogItemPriceProrationSID
				,@CurrentPrice = @currentPrice
				,@IsProrated = @isProrated
		
		end

		select
			 @catalogItemPriceSID CatalogItemPriceSID
			,@catalogItemSID CatalogItemSID
			,@price Price
			,@effectiveTime EffectiveTime
			,@userDefinedColumns UserDefinedColumns
			,@catalogItemPriceXID CatalogItemPriceXID
			,@legacyKey LegacyKey
			,@isDeleted IsDeleted
			,@createUser CreateUser
			,@createTime CreateTime
			,@updateUser UpdateUser
			,@updateTime UpdateTime
			,@rowGUID RowGUID
			,@rowStamp RowStamp
			,@catalogItemLabel CatalogItemLabel
			,@invoiceItemDescription InvoiceItemDescription
			,@isLateFee IsLateFee
			,@imageAlternateText ImageAlternateText
			,@isAvailableOnClientPortal IsAvailableOnClientPortal
			,@isComplaintPenalty IsComplaintPenalty
			,@gLAccountSID GLAccountSID
			,@isTaxRate1Applied IsTaxRate1Applied
			,@isTaxRate2Applied IsTaxRate2Applied
			,@isTaxRate3Applied IsTaxRate3Applied
			,@isTaxDeductible IsTaxDeductible
			,@catalogItemEffectiveTime CatalogItemEffectiveTime
			,@expiryTime ExpiryTime
			,@fileTypeSCD FileTypeSCD
			,@fileTypeSID FileTypeSID
			,@catalogItemRowGUID CatalogItemRowGUID
			,@isDeleteEnabled IsDeleteEnabled
			,@isReselected IsReselected
			,@isNullApplied IsNullApplied
			,@zContext zContext
			,@catalogItemPriceProrationSID CatalogItemPriceProrationSID
			,@currentPrice CurrentPrice
			,@isProrated IsProrated

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
