SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pAuditTypeForm#Update]
	 @AuditTypeFormSID   int               = null -- required! id of row to update - must be set in custom logic if not passed
	,@AuditTypeSID       int               = null -- table column values to update:
	,@FormSID            int               = null
	,@IsReviewForm       bit               = null
	,@UserDefinedColumns xml               = null
	,@AuditTypeFormXID   varchar(150)      = null
	,@LegacyKey          nvarchar(50)      = null
	,@UpdateUser         nvarchar(75)      = null -- set to current application user unless "SystemUser" passed
	,@RowStamp           timestamp         = null -- row time stamp - pass for preemptive check for overwrites
	,@IsReselected       tinyint           = 0    -- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@IsNullApplied      bit               = 0    -- when 1 null parameters overwrite corresponding columns with null
	,@zContext           xml               = null -- other values defining context for the update (if any)
	,@AuditTypeLabel     nvarchar(35)      = null -- not a base table column
	,@AuditTypeCategory  nvarchar(65)      = null -- not a base table column
	,@AuditTypeIsDefault bit               = null -- not a base table column
	,@AuditTypeIsActive  bit               = null -- not a base table column
	,@AuditTypeRowGUID   uniqueidentifier  = null -- not a base table column
	,@FormTypeSID        int               = null -- not a base table column
	,@FormName           nvarchar(65)      = null -- not a base table column
	,@FormLabel          nvarchar(35)      = null -- not a base table column
	,@FormContext        varchar(25)       = null -- not a base table column
	,@AuthorCredit       nvarchar(500)     = null -- not a base table column
	,@FormIsActive       bit               = null -- not a base table column
	,@ApplicationUserSID int               = null -- not a base table column
	,@FormRowGUID        uniqueidentifier  = null -- not a base table column
	,@IsDeleteEnabled    bit               = null -- not a base table column
as
/*********************************************************************************************************************************
Procedure : dbo.pAuditTypeForm#Update
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : updates 1 row in the dbo.AuditTypeForm table
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used to update the dbo.AuditTypeForm table. The procedure requires a primary key to locate the record to update.
Additional parameters are provided for all columns in the vAuditTypeForm entity view, however, the base logic of the procedure
updates the columns of the table only. Table-specific logic can be added through tagged sections (pre and post update) and a call
to an extended procedure supports client-specific logic. Logic implemented within code tags (table-specific logic) is part of the
base product and applies to all client configurations. Calls to the extended procedure occur immediately after the table-specific
logic in both "pre-update" and "post-update" contexts.  A transaction is used to commit/rollback all changes as a logical unit.

Client specific customizations must be implemented in the ext.pAuditTypeForm procedure. The extended procedure is only called
where it exists in the DB. The first parameter passed @Mode is set to either "update.pre" or "update.post" to provide context for
the extended logic.

The @zContext parameter is an additional construct available to support overrides where different results are produced based on
content provided in the XML from the client tier. This parameter may contain multiple values.

The "@IsReselected" parameter controls output and "@IsNullApplied" controls whether or not parameters with null values overwrite
corresponding columns on the row.

For client-tier calls using the Microsoft Entity Framework and RIA Services, the @IsReselected bit should be passed as 1 to
force re-selection of table columns + extended view columns (the entity view).

Values for parameters representing mandatory columns must be provided unless @IsNullApplied is passed as 0. If @IsNullApplied = 1
any parameter with a null value overwrites the corresponding column value with null.  @IsNullApplied defaults to 0 but should be
passed as 1 when calling through the entity framework domain service since all columns are mapped to the procedure.

If the @UpdateUser parameter is passed as the special value "SystemUser", then the system user established in sf.ConfigParam
is applied. This option is useful for conversion and system generated updates the user would not recognize as having caused. Any
other value provided for the parameter (including null) is overwritten with the current application user.

The @RowStamp parameter should always be passed when calling from the user interface. The @RowStamp parameter is used to
preemptively check for an overwrite.  The value should be passed as the RowStamp value from the row when it was last
retrieved into the UI. If the RowStamp on the record changes from the value passed, this procedure will raise an exception and
avoid the overwrite.  For calls from back-end procedures, the @RowStamp parameter can be left blank and it will default to the
current time stamp on the record (avoiding the need to look up the value prior to calling.)

Business rule compliance is checked through a table constraint which calls fAuditTypeFormCheck to test all rules.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@errorText                                    nvarchar(4000)					-- message text (for business rule errors)
		,@rowsAffected                                 int = 0								-- tracks rows impacted by the operation (error check)
		,@recordSID                                    int										-- tracks primary key value for clearing current default
		,@ON                                           bit = cast(1 as bit)		-- constant for bit comparison and assignments
		,@OFF                                          bit = cast(0 as bit)		-- constant for bit comparison and assignments

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- check parameters

		if @AuditTypeFormSID is null
		begin

			exec sf.pMessage#Get
				 @MessageSCD  	= 'BlankParameter'
				,@MessageText 	= @errorText output
				,@DefaultText 	= N'A parameter (%1) required by the database procedure was left blank.'
				,@Arg1					= '@AuditTypeFormSID'

			raiserror(@errorText, 18, 1)
		end

		-- remove leading and trailing spaces from character type columns

		set @AuditTypeFormXID = ltrim(rtrim(@AuditTypeFormXID))
		set @LegacyKey = ltrim(rtrim(@LegacyKey))
		set @UpdateUser = ltrim(rtrim(@UpdateUser))
		set @AuditTypeLabel = ltrim(rtrim(@AuditTypeLabel))
		set @AuditTypeCategory = ltrim(rtrim(@AuditTypeCategory))
		set @FormName = ltrim(rtrim(@FormName))
		set @FormLabel = ltrim(rtrim(@FormLabel))
		set @FormContext = ltrim(rtrim(@FormContext))
		set @AuthorCredit = ltrim(rtrim(@AuthorCredit))

		-- set zero length strings to null to avoid storing them in the record

		if len(@AuditTypeFormXID) = 0 set @AuditTypeFormXID = null
		if len(@LegacyKey) = 0 set @LegacyKey = null
		if len(@UpdateUser) = 0 set @UpdateUser = null
		if len(@AuditTypeLabel) = 0 set @AuditTypeLabel = null
		if len(@AuditTypeCategory) = 0 set @AuditTypeCategory = null
		if len(@FormName) = 0 set @FormName = null
		if len(@FormLabel) = 0 set @FormLabel = null
		if len(@FormContext) = 0 set @FormContext = null
		if len(@AuthorCredit) = 0 set @AuthorCredit = null

		-- set the ID of the user

		if isnull(@UpdateUser, 'x') = N'SystemUser' set @UpdateUser = left(sf.fConfigParam#Value('SystemUser'),75)-- override for "SystemUser"
		if isnull(@UpdateUser, 'x') <> N'SystemUser' set @UpdateUser = sf.fApplicationUserSession#UserName()			-- application user - or DB user if no application session set

		-- avoid overwriting with null parameter values (unless specified)
		-- by retrieving existing values from the entity row for blank parameters

		if @IsNullApplied = 0
		begin

			select
				 @AuditTypeSID       = isnull(@AuditTypeSID,atf.AuditTypeSID)
				,@FormSID            = isnull(@FormSID,atf.FormSID)
				,@IsReviewForm       = isnull(@IsReviewForm,atf.IsReviewForm)
				,@UserDefinedColumns = isnull(@UserDefinedColumns,atf.UserDefinedColumns)
				,@AuditTypeFormXID   = isnull(@AuditTypeFormXID,atf.AuditTypeFormXID)
				,@LegacyKey          = isnull(@LegacyKey,atf.LegacyKey)
				,@UpdateUser         = isnull(@UpdateUser,atf.UpdateUser)
				,@IsReselected       = isnull(@IsReselected,atf.IsReselected)
				,@IsNullApplied      = isnull(@IsNullApplied,atf.IsNullApplied)
				,@zContext           = isnull(@zContext,atf.zContext)
				,@AuditTypeLabel     = isnull(@AuditTypeLabel,atf.AuditTypeLabel)
				,@AuditTypeCategory  = isnull(@AuditTypeCategory,atf.AuditTypeCategory)
				,@AuditTypeIsDefault = isnull(@AuditTypeIsDefault,atf.AuditTypeIsDefault)
				,@AuditTypeIsActive  = isnull(@AuditTypeIsActive,atf.AuditTypeIsActive)
				,@AuditTypeRowGUID   = isnull(@AuditTypeRowGUID,atf.AuditTypeRowGUID)
				,@FormTypeSID        = isnull(@FormTypeSID,atf.FormTypeSID)
				,@FormName           = isnull(@FormName,atf.FormName)
				,@FormLabel          = isnull(@FormLabel,atf.FormLabel)
				,@FormContext        = isnull(@FormContext,atf.FormContext)
				,@AuthorCredit       = isnull(@AuthorCredit,atf.AuthorCredit)
				,@FormIsActive       = isnull(@FormIsActive,atf.FormIsActive)
				,@ApplicationUserSID = isnull(@ApplicationUserSID,atf.ApplicationUserSID)
				,@FormRowGUID        = isnull(@FormRowGUID,atf.FormRowGUID)
				,@IsDeleteEnabled    = isnull(@IsDeleteEnabled,atf.IsDeleteEnabled)
			from
				dbo.vAuditTypeForm atf
			where
				atf.AuditTypeFormSID = @AuditTypeFormSID

		end

		-- block changing FK values to parent records which are inactive (UI should prevent this)
		
		if (select x.AuditTypeSID from dbo.AuditTypeForm x where x.AuditTypeFormSID = @AuditTypeFormSID) <> @AuditTypeSID
		begin
			if (select x.IsActive from dbo.AuditType x where x.AuditTypeSID = @AuditTypeSID) = @OFF
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'AssignmentToInactiveParent'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 assigned is marked inactive. Leave the record unchanged or set to an active %1.'
					,@Arg1        = N'audit type'
				
				raiserror(@errorText, 16, 1)
				
			end
		end
		
		if (select x.FormSID from dbo.AuditTypeForm x where x.AuditTypeFormSID = @AuditTypeFormSID) <> @FormSID
		begin
			if (select x.IsActive from sf.Form x where x.FormSID = @FormSID) = @OFF
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'AssignmentToInactiveParent'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 assigned is marked inactive. Leave the record unchanged or set to an active %1.'
					,@Arg1        = N'form'
				
				raiserror(@errorText, 16, 1)
				
			end
		end

		-- apply the table-specific pre-update logic (if any)

		--! <PreUpdate>
		--  insert pre-update logic here ...
		--! </PreUpdate>
	
		-- call the extended version of the procedure (if it exists) for "update.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pAuditTypeForm'
		)
		begin
		
			exec @errorNo = ext.pAuditTypeForm
				 @Mode               = 'update.pre'
				,@AuditTypeFormSID   = @AuditTypeFormSID
				,@AuditTypeSID       = @AuditTypeSID output
				,@FormSID            = @FormSID output
				,@IsReviewForm       = @IsReviewForm output
				,@UserDefinedColumns = @UserDefinedColumns output
				,@AuditTypeFormXID   = @AuditTypeFormXID output
				,@LegacyKey          = @LegacyKey output
				,@UpdateUser         = @UpdateUser
				,@RowStamp           = @RowStamp
				,@IsReselected       = @IsReselected
				,@IsNullApplied      = @IsNullApplied
				,@zContext           = @zContext
				,@AuditTypeLabel     = @AuditTypeLabel
				,@AuditTypeCategory  = @AuditTypeCategory
				,@AuditTypeIsDefault = @AuditTypeIsDefault
				,@AuditTypeIsActive  = @AuditTypeIsActive
				,@AuditTypeRowGUID   = @AuditTypeRowGUID
				,@FormTypeSID        = @FormTypeSID
				,@FormName           = @FormName
				,@FormLabel          = @FormLabel
				,@FormContext        = @FormContext
				,@AuthorCredit       = @AuthorCredit
				,@FormIsActive       = @FormIsActive
				,@ApplicationUserSID = @ApplicationUserSID
				,@FormRowGUID        = @FormRowGUID
				,@IsDeleteEnabled    = @IsDeleteEnabled
		
		end

		-- update the record

		update
			dbo.AuditTypeForm
		set
			 AuditTypeSID = @AuditTypeSID
			,FormSID = @FormSID
			,IsReviewForm = @IsReviewForm
			,UserDefinedColumns = @UserDefinedColumns
			,AuditTypeFormXID = @AuditTypeFormXID
			,LegacyKey = @LegacyKey
			,UpdateUser = @UpdateUser
			,UpdateTime = sysdatetimeoffset()
		where
			AuditTypeFormSID = @AuditTypeFormSID
			and
			RowStamp = isnull(@RowStamp, RowStamp)

		set @rowsAffected = @@rowcount

		-- check for errors

		if @rowsAffected = 0
		begin
			
			if exists (select 1 from dbo.AuditTypeForm where AuditTypeFormSID = @auditTypeFormSID)
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'UpdateBlocked'
					,@MessageText = @errorText output
					,@DefaultText = N'A change was made to the "%1" record since it was last retrieved. The overwrite was avoided. Refresh the record and try again.'
					,@Arg1        = 'dbo.AuditTypeForm'
				
				raiserror(@errorText, 16, 1)
			end
			else
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'RecordNotFound'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 record was not found. Record ID = "%2". The record may have been deleted or the identifier is invalid.'
					,@Arg1        = 'dbo.AuditTypeForm'
					,@Arg2        = @auditTypeFormSID
				
				raiserror(@errorText, 18, 1)
			end

		end
		else if @rowsAffected <> 1
		begin

			exec sf.pMessage#Get
				 @MessageSCD  = 'RowCountUnexpected'
				,@MessageText = @errorText output
				,@DefaultText = N'The %1 operation on table "%2" affected an unexpected number of rows (%3). Record ID = %4.'
				,@Arg1        = 'update'
				,@Arg2        = 'dbo.AuditTypeForm'
				,@Arg3        = @rowsAffected
				,@Arg4        = @auditTypeFormSID
			
			raiserror(@errorText, 18, 1)
		end

		-- apply the table-specific post-update logic (if any)

		--! <PostUpdate>
		--  insert post-update logic here ...
		--! </PostUpdate>
	
		-- call the extended version of the procedure for update.post - if it exists
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pAuditTypeForm'
		)
		begin
		
			exec @errorNo = ext.pAuditTypeForm
				 @Mode               = 'update.post'
				,@AuditTypeFormSID   = @AuditTypeFormSID
				,@AuditTypeSID       = @AuditTypeSID
				,@FormSID            = @FormSID
				,@IsReviewForm       = @IsReviewForm
				,@UserDefinedColumns = @UserDefinedColumns
				,@AuditTypeFormXID   = @AuditTypeFormXID
				,@LegacyKey          = @LegacyKey
				,@UpdateUser         = @UpdateUser
				,@RowStamp           = @RowStamp
				,@IsReselected       = @IsReselected
				,@IsNullApplied      = @IsNullApplied
				,@zContext           = @zContext
				,@AuditTypeLabel     = @AuditTypeLabel
				,@AuditTypeCategory  = @AuditTypeCategory
				,@AuditTypeIsDefault = @AuditTypeIsDefault
				,@AuditTypeIsActive  = @AuditTypeIsActive
				,@AuditTypeRowGUID   = @AuditTypeRowGUID
				,@FormTypeSID        = @FormTypeSID
				,@FormName           = @FormName
				,@FormLabel          = @FormLabel
				,@FormContext        = @FormContext
				,@AuthorCredit       = @AuthorCredit
				,@FormIsActive       = @FormIsActive
				,@ApplicationUserSID = @ApplicationUserSID
				,@FormRowGUID        = @FormRowGUID
				,@IsDeleteEnabled    = @IsDeleteEnabled
		
		end

		if @trancount = 0 and xact_state() = 1 commit transaction

		-- return all columns for entity (1), just the PK value (2), or no returned value (0)

		if @IsReselected = 2
		begin

			select
				 ent.AuditTypeFormSID
			from
				dbo.vAuditTypeForm ent
			where
				ent.AuditTypeFormSID = @AuditTypeFormSID

		end
		else if @IsReselected = 1
		begin

			select
				 ent.AuditTypeFormSID
				,ent.AuditTypeSID
				,ent.FormSID
				,ent.IsReviewForm
				,ent.UserDefinedColumns
				,ent.AuditTypeFormXID
				,ent.LegacyKey
				,ent.IsDeleted
				,ent.CreateUser
				,ent.CreateTime
				,ent.UpdateUser
				,ent.UpdateTime
				,ent.RowGUID
				,ent.RowStamp
				,ent.AuditTypeLabel
				,ent.AuditTypeCategory
				,ent.AuditTypeIsDefault
				,ent.AuditTypeIsActive
				,ent.AuditTypeRowGUID
				,ent.FormTypeSID
				,ent.FormName
				,ent.FormLabel
				,ent.FormContext
				,ent.AuthorCredit
				,ent.FormIsActive
				,ent.ApplicationUserSID
				,ent.FormRowGUID
				,ent.IsDeleteEnabled
				,ent.IsReselected
				,ent.IsNullApplied
				,ent.zContext
			from
				dbo.vAuditTypeForm ent
			where
				ent.AuditTypeFormSID = @AuditTypeFormSID

		end

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
