SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pPracticeRegisterChangeRequirement#Update]
	 @PracticeRegisterChangeRequirementSID int               = null -- required! id of row to update - must be set in custom logic if not passed
	,@PracticeRegisterChangeSID            int               = null -- table column values to update:
	,@RegistrationRequirementSID           int               = null
	,@IsMandatory                          bit               = null
	,@ExpiryMonths                         smallint          = null
	,@IsActive                             bit               = null
	,@RequirementSequence                  int               = null
	,@UserDefinedColumns                   xml               = null
	,@PracticeRegisterChangeRequirementXID varchar(150)      = null
	,@LegacyKey                            nvarchar(50)      = null
	,@UpdateUser                           nvarchar(75)      = null -- set to current application user unless "SystemUser" passed
	,@RowStamp                             timestamp         = null -- row time stamp - pass for preemptive check for overwrites
	,@IsReselected                         tinyint           = 0    -- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@IsNullApplied                        bit               = 0    -- when 1 null parameters overwrite corresponding columns with null
	,@zContext                             xml               = null -- other values defining context for the update (if any)
	,@PracticeRegisterSID                  int               = null -- not a base table column
	,@PracticeRegisterSectionSID           int               = null -- not a base table column
	,@PracticeRegisterChangeIsActive       bit               = null -- not a base table column
	,@ToolTip                              nvarchar(500)     = null -- not a base table column
	,@IsEnabledForRegistrant               bit               = null -- not a base table column
	,@PracticeRegisterChangeRowGUID        uniqueidentifier  = null -- not a base table column
	,@RegistrationRequirementTypeSID       int               = null -- not a base table column
	,@RegistrationRequirementLabel         nvarchar(35)      = null -- not a base table column
	,@PersonDocTypeSID                     int               = null -- not a base table column
	,@ExamSID                              int               = null -- not a base table column
	,@RegistrationRequirementExpiryMonths  smallint          = null -- not a base table column
	,@RegistrationRequirementIsActive      bit               = null -- not a base table column
	,@RegistrationRequirementRowGUID       uniqueidentifier  = null -- not a base table column
	,@IsDeleteEnabled                      bit               = null -- not a base table column
	,@PracticeRegisterChangeLabel          nvarchar(110)     = null -- not a base table column
as
/*********************************************************************************************************************************
Procedure : dbo.pPracticeRegisterChangeRequirement#Update
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : updates 1 row in the dbo.PracticeRegisterChangeRequirement table
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used to update the dbo.PracticeRegisterChangeRequirement table. The procedure requires a primary key to locate the record to update.
Additional parameters are provided for all columns in the vPracticeRegisterChangeRequirement entity view, however, the base logic of the procedure
updates the columns of the table only. Table-specific logic can be added through tagged sections (pre and post update) and a call
to an extended procedure supports client-specific logic. Logic implemented within code tags (table-specific logic) is part of the
base product and applies to all client configurations. Calls to the extended procedure occur immediately after the table-specific
logic in both "pre-update" and "post-update" contexts.  A transaction is used to commit/rollback all changes as a logical unit.

Client specific customizations must be implemented in the ext.pPracticeRegisterChangeRequirement procedure. The extended procedure is only called
where it exists in the DB. The first parameter passed @Mode is set to either "update.pre" or "update.post" to provide context for
the extended logic.

The @zContext parameter is an additional construct available to support overrides where different results are produced based on
content provided in the XML from the client tier. This parameter may contain multiple values.

The "@IsReselected" parameter controls output and "@IsNullApplied" controls whether or not parameters with null values overwrite
corresponding columns on the row.

For client-tier calls using the Microsoft Entity Framework and RIA Services, the @IsReselected bit should be passed as 1 to
force re-selection of table columns + extended view columns (the entity view).

Values for parameters representing mandatory columns must be provided unless @IsNullApplied is passed as 0. If @IsNullApplied = 1
any parameter with a null value overwrites the corresponding column value with null.  @IsNullApplied defaults to 0 but should be
passed as 1 when calling through the entity framework domain service since all columns are mapped to the procedure.

If the @UpdateUser parameter is passed as the special value "SystemUser", then the system user established in sf.ConfigParam
is applied. This option is useful for conversion and system generated updates the user would not recognize as having caused. Any
other value provided for the parameter (including null) is overwritten with the current application user.

The @RowStamp parameter should always be passed when calling from the user interface. The @RowStamp parameter is used to
preemptively check for an overwrite.  The value should be passed as the RowStamp value from the row when it was last
retrieved into the UI. If the RowStamp on the record changes from the value passed, this procedure will raise an exception and
avoid the overwrite.  For calls from back-end procedures, the @RowStamp parameter can be left blank and it will default to the
current time stamp on the record (avoiding the need to look up the value prior to calling.)

Business rule compliance is checked through a table constraint which calls fPracticeRegisterChangeRequirementCheck to test all rules.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@errorText                                    nvarchar(4000)					-- message text (for business rule errors)
		,@rowsAffected                                 int = 0								-- tracks rows impacted by the operation (error check)
		,@recordSID                                    int										-- tracks primary key value for clearing current default
		,@ON                                           bit = cast(1 as bit)		-- constant for bit comparison and assignments
		,@OFF                                          bit = cast(0 as bit)		-- constant for bit comparison and assignments

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- check parameters

		if @PracticeRegisterChangeRequirementSID is null
		begin

			exec sf.pMessage#Get
				 @MessageSCD  	= 'BlankParameter'
				,@MessageText 	= @errorText output
				,@DefaultText 	= N'A parameter (%1) required by the database procedure was left blank.'
				,@Arg1					= '@PracticeRegisterChangeRequirementSID'

			raiserror(@errorText, 18, 1)
		end

		-- remove leading and trailing spaces from character type columns

		set @PracticeRegisterChangeRequirementXID = ltrim(rtrim(@PracticeRegisterChangeRequirementXID))
		set @LegacyKey = ltrim(rtrim(@LegacyKey))
		set @UpdateUser = ltrim(rtrim(@UpdateUser))
		set @ToolTip = ltrim(rtrim(@ToolTip))
		set @RegistrationRequirementLabel = ltrim(rtrim(@RegistrationRequirementLabel))
		set @PracticeRegisterChangeLabel = ltrim(rtrim(@PracticeRegisterChangeLabel))

		-- set zero length strings to null to avoid storing them in the record

		if len(@PracticeRegisterChangeRequirementXID) = 0 set @PracticeRegisterChangeRequirementXID = null
		if len(@LegacyKey) = 0 set @LegacyKey = null
		if len(@UpdateUser) = 0 set @UpdateUser = null
		if len(@ToolTip) = 0 set @ToolTip = null
		if len(@RegistrationRequirementLabel) = 0 set @RegistrationRequirementLabel = null
		if len(@PracticeRegisterChangeLabel) = 0 set @PracticeRegisterChangeLabel = null

		-- set the ID of the user

		if isnull(@UpdateUser, 'x') = N'SystemUser' set @UpdateUser = left(sf.fConfigParam#Value('SystemUser'),75)-- override for "SystemUser"
		if isnull(@UpdateUser, 'x') <> N'SystemUser' set @UpdateUser = sf.fApplicationUserSession#UserName()			-- application user - or DB user if no application session set

		-- avoid overwriting with null parameter values (unless specified)
		-- by retrieving existing values from the entity row for blank parameters

		if @IsNullApplied = 0
		begin

			select
				 @PracticeRegisterChangeSID            = isnull(@PracticeRegisterChangeSID,prcr.PracticeRegisterChangeSID)
				,@RegistrationRequirementSID           = isnull(@RegistrationRequirementSID,prcr.RegistrationRequirementSID)
				,@IsMandatory                          = isnull(@IsMandatory,prcr.IsMandatory)
				,@ExpiryMonths                         = isnull(@ExpiryMonths,prcr.ExpiryMonths)
				,@IsActive                             = isnull(@IsActive,prcr.IsActive)
				,@RequirementSequence                  = isnull(@RequirementSequence,prcr.RequirementSequence)
				,@UserDefinedColumns                   = isnull(@UserDefinedColumns,prcr.UserDefinedColumns)
				,@PracticeRegisterChangeRequirementXID = isnull(@PracticeRegisterChangeRequirementXID,prcr.PracticeRegisterChangeRequirementXID)
				,@LegacyKey                            = isnull(@LegacyKey,prcr.LegacyKey)
				,@UpdateUser                           = isnull(@UpdateUser,prcr.UpdateUser)
				,@IsReselected                         = isnull(@IsReselected,prcr.IsReselected)
				,@IsNullApplied                        = isnull(@IsNullApplied,prcr.IsNullApplied)
				,@zContext                             = isnull(@zContext,prcr.zContext)
				,@PracticeRegisterSID                  = isnull(@PracticeRegisterSID,prcr.PracticeRegisterSID)
				,@PracticeRegisterSectionSID           = isnull(@PracticeRegisterSectionSID,prcr.PracticeRegisterSectionSID)
				,@PracticeRegisterChangeIsActive       = isnull(@PracticeRegisterChangeIsActive,prcr.PracticeRegisterChangeIsActive)
				,@ToolTip                              = isnull(@ToolTip,prcr.ToolTip)
				,@IsEnabledForRegistrant               = isnull(@IsEnabledForRegistrant,prcr.IsEnabledForRegistrant)
				,@PracticeRegisterChangeRowGUID        = isnull(@PracticeRegisterChangeRowGUID,prcr.PracticeRegisterChangeRowGUID)
				,@RegistrationRequirementTypeSID       = isnull(@RegistrationRequirementTypeSID,prcr.RegistrationRequirementTypeSID)
				,@RegistrationRequirementLabel         = isnull(@RegistrationRequirementLabel,prcr.RegistrationRequirementLabel)
				,@PersonDocTypeSID                     = isnull(@PersonDocTypeSID,prcr.PersonDocTypeSID)
				,@ExamSID                              = isnull(@ExamSID,prcr.ExamSID)
				,@RegistrationRequirementExpiryMonths  = isnull(@RegistrationRequirementExpiryMonths,prcr.RegistrationRequirementExpiryMonths)
				,@RegistrationRequirementIsActive      = isnull(@RegistrationRequirementIsActive,prcr.RegistrationRequirementIsActive)
				,@RegistrationRequirementRowGUID       = isnull(@RegistrationRequirementRowGUID,prcr.RegistrationRequirementRowGUID)
				,@IsDeleteEnabled                      = isnull(@IsDeleteEnabled,prcr.IsDeleteEnabled)
				,@PracticeRegisterChangeLabel          = isnull(@PracticeRegisterChangeLabel,prcr.PracticeRegisterChangeLabel)
			from
				dbo.vPracticeRegisterChangeRequirement prcr
			where
				prcr.PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID

		end

		-- block changing FK values to parent records which are inactive (UI should prevent this)
		
		if (select x.PracticeRegisterChangeSID from dbo.PracticeRegisterChangeRequirement x where x.PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID) <> @PracticeRegisterChangeSID
		begin
			if (select x.IsActive from dbo.PracticeRegisterChange x where x.PracticeRegisterChangeSID = @PracticeRegisterChangeSID) = @OFF
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'AssignmentToInactiveParent'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 assigned is marked inactive. Leave the record unchanged or set to an active %1.'
					,@Arg1        = N'practice register change'
				
				raiserror(@errorText, 16, 1)
				
			end
		end
		
		if (select x.RegistrationRequirementSID from dbo.PracticeRegisterChangeRequirement x where x.PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID) <> @RegistrationRequirementSID
		begin
			if (select x.IsActive from dbo.RegistrationRequirement x where x.RegistrationRequirementSID = @RegistrationRequirementSID) = @OFF
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'AssignmentToInactiveParent'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 assigned is marked inactive. Leave the record unchanged or set to an active %1.'
					,@Arg1        = N'registration requirement'
				
				raiserror(@errorText, 16, 1)
				
			end
		end

		-- apply the table-specific pre-update logic (if any)

		--! <PreUpdate>
		--  insert pre-update logic here ...
		--! </PreUpdate>
	
		-- call the extended version of the procedure (if it exists) for "update.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pPracticeRegisterChangeRequirement'
		)
		begin
		
			exec @errorNo = ext.pPracticeRegisterChangeRequirement
				 @Mode                                 = 'update.pre'
				,@PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID
				,@PracticeRegisterChangeSID            = @PracticeRegisterChangeSID output
				,@RegistrationRequirementSID           = @RegistrationRequirementSID output
				,@IsMandatory                          = @IsMandatory output
				,@ExpiryMonths                         = @ExpiryMonths output
				,@IsActive                             = @IsActive output
				,@RequirementSequence                  = @RequirementSequence output
				,@UserDefinedColumns                   = @UserDefinedColumns output
				,@PracticeRegisterChangeRequirementXID = @PracticeRegisterChangeRequirementXID output
				,@LegacyKey                            = @LegacyKey output
				,@UpdateUser                           = @UpdateUser
				,@RowStamp                             = @RowStamp
				,@IsReselected                         = @IsReselected
				,@IsNullApplied                        = @IsNullApplied
				,@zContext                             = @zContext
				,@PracticeRegisterSID                  = @PracticeRegisterSID
				,@PracticeRegisterSectionSID           = @PracticeRegisterSectionSID
				,@PracticeRegisterChangeIsActive       = @PracticeRegisterChangeIsActive
				,@ToolTip                              = @ToolTip
				,@IsEnabledForRegistrant               = @IsEnabledForRegistrant
				,@PracticeRegisterChangeRowGUID        = @PracticeRegisterChangeRowGUID
				,@RegistrationRequirementTypeSID       = @RegistrationRequirementTypeSID
				,@RegistrationRequirementLabel         = @RegistrationRequirementLabel
				,@PersonDocTypeSID                     = @PersonDocTypeSID
				,@ExamSID                              = @ExamSID
				,@RegistrationRequirementExpiryMonths  = @RegistrationRequirementExpiryMonths
				,@RegistrationRequirementIsActive      = @RegistrationRequirementIsActive
				,@RegistrationRequirementRowGUID       = @RegistrationRequirementRowGUID
				,@IsDeleteEnabled                      = @IsDeleteEnabled
				,@PracticeRegisterChangeLabel          = @PracticeRegisterChangeLabel
		
		end

		-- update the record

		update
			dbo.PracticeRegisterChangeRequirement
		set
			 PracticeRegisterChangeSID = @PracticeRegisterChangeSID
			,RegistrationRequirementSID = @RegistrationRequirementSID
			,IsMandatory = @IsMandatory
			,ExpiryMonths = @ExpiryMonths
			,IsActive = @IsActive
			,RequirementSequence = @RequirementSequence
			,UserDefinedColumns = @UserDefinedColumns
			,PracticeRegisterChangeRequirementXID = @PracticeRegisterChangeRequirementXID
			,LegacyKey = @LegacyKey
			,UpdateUser = @UpdateUser
			,UpdateTime = sysdatetimeoffset()
		where
			PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID
			and
			RowStamp = isnull(@RowStamp, RowStamp)

		set @rowsAffected = @@rowcount

		-- check for errors

		if @rowsAffected = 0
		begin
			
			if exists (select 1 from dbo.PracticeRegisterChangeRequirement where PracticeRegisterChangeRequirementSID = @practiceRegisterChangeRequirementSID)
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'UpdateBlocked'
					,@MessageText = @errorText output
					,@DefaultText = N'A change was made to the "%1" record since it was last retrieved. The overwrite was avoided. Refresh the record and try again.'
					,@Arg1        = 'dbo.PracticeRegisterChangeRequirement'
				
				raiserror(@errorText, 16, 1)
			end
			else
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'RecordNotFound'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 record was not found. Record ID = "%2". The record may have been deleted or the identifier is invalid.'
					,@Arg1        = 'dbo.PracticeRegisterChangeRequirement'
					,@Arg2        = @practiceRegisterChangeRequirementSID
				
				raiserror(@errorText, 18, 1)
			end

		end
		else if @rowsAffected <> 1
		begin

			exec sf.pMessage#Get
				 @MessageSCD  = 'RowCountUnexpected'
				,@MessageText = @errorText output
				,@DefaultText = N'The %1 operation on table "%2" affected an unexpected number of rows (%3). Record ID = %4.'
				,@Arg1        = 'update'
				,@Arg2        = 'dbo.PracticeRegisterChangeRequirement'
				,@Arg3        = @rowsAffected
				,@Arg4        = @practiceRegisterChangeRequirementSID
			
			raiserror(@errorText, 18, 1)
		end

		-- apply the table-specific post-update logic (if any)

		--! <PostUpdate>
		--  insert post-update logic here ...
		--! </PostUpdate>
	
		-- call the extended version of the procedure for update.post - if it exists
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'pPracticeRegisterChangeRequirement'
		)
		begin
		
			exec @errorNo = ext.pPracticeRegisterChangeRequirement
				 @Mode                                 = 'update.post'
				,@PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID
				,@PracticeRegisterChangeSID            = @PracticeRegisterChangeSID
				,@RegistrationRequirementSID           = @RegistrationRequirementSID
				,@IsMandatory                          = @IsMandatory
				,@ExpiryMonths                         = @ExpiryMonths
				,@IsActive                             = @IsActive
				,@RequirementSequence                  = @RequirementSequence
				,@UserDefinedColumns                   = @UserDefinedColumns
				,@PracticeRegisterChangeRequirementXID = @PracticeRegisterChangeRequirementXID
				,@LegacyKey                            = @LegacyKey
				,@UpdateUser                           = @UpdateUser
				,@RowStamp                             = @RowStamp
				,@IsReselected                         = @IsReselected
				,@IsNullApplied                        = @IsNullApplied
				,@zContext                             = @zContext
				,@PracticeRegisterSID                  = @PracticeRegisterSID
				,@PracticeRegisterSectionSID           = @PracticeRegisterSectionSID
				,@PracticeRegisterChangeIsActive       = @PracticeRegisterChangeIsActive
				,@ToolTip                              = @ToolTip
				,@IsEnabledForRegistrant               = @IsEnabledForRegistrant
				,@PracticeRegisterChangeRowGUID        = @PracticeRegisterChangeRowGUID
				,@RegistrationRequirementTypeSID       = @RegistrationRequirementTypeSID
				,@RegistrationRequirementLabel         = @RegistrationRequirementLabel
				,@PersonDocTypeSID                     = @PersonDocTypeSID
				,@ExamSID                              = @ExamSID
				,@RegistrationRequirementExpiryMonths  = @RegistrationRequirementExpiryMonths
				,@RegistrationRequirementIsActive      = @RegistrationRequirementIsActive
				,@RegistrationRequirementRowGUID       = @RegistrationRequirementRowGUID
				,@IsDeleteEnabled                      = @IsDeleteEnabled
				,@PracticeRegisterChangeLabel          = @PracticeRegisterChangeLabel
		
		end

		if @trancount = 0 and xact_state() = 1 commit transaction

		-- return all columns for entity (1), just the PK value (2), or no returned value (0)

		if @IsReselected = 2
		begin

			select
				 ent.PracticeRegisterChangeRequirementSID
			from
				dbo.vPracticeRegisterChangeRequirement ent
			where
				ent.PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID

		end
		else if @IsReselected = 1
		begin

			select
				 ent.PracticeRegisterChangeRequirementSID
				,ent.PracticeRegisterChangeSID
				,ent.RegistrationRequirementSID
				,ent.IsMandatory
				,ent.ExpiryMonths
				,ent.IsActive
				,ent.RequirementSequence
				,ent.UserDefinedColumns
				,ent.PracticeRegisterChangeRequirementXID
				,ent.LegacyKey
				,ent.IsDeleted
				,ent.CreateUser
				,ent.CreateTime
				,ent.UpdateUser
				,ent.UpdateTime
				,ent.RowGUID
				,ent.RowStamp
				,ent.PracticeRegisterSID
				,ent.PracticeRegisterSectionSID
				,ent.PracticeRegisterChangeIsActive
				,ent.ToolTip
				,ent.IsEnabledForRegistrant
				,ent.PracticeRegisterChangeRowGUID
				,ent.RegistrationRequirementTypeSID
				,ent.RegistrationRequirementLabel
				,ent.PersonDocTypeSID
				,ent.ExamSID
				,ent.RegistrationRequirementExpiryMonths
				,ent.RegistrationRequirementIsActive
				,ent.RegistrationRequirementRowGUID
				,ent.IsDeleteEnabled
				,ent.IsReselected
				,ent.IsNullApplied
				,ent.zContext
				,ent.PracticeRegisterChangeLabel
			from
				dbo.vPracticeRegisterChangeRequirement ent
			where
				ent.PracticeRegisterChangeRequirementSID = @PracticeRegisterChangeRequirementSID

		end

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
