SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [sf].[pEmailTemplateAttachment#Update]
	 @EmailTemplateAttachmentSID int               = null -- required! id of row to update - must be set in custom logic if not passed
	,@EmailTemplateSID           int               = null -- table column values to update:
	,@DocumentTitle              nvarchar(75)      = null
	,@FileTypeSID                int               = null
	,@FileTypeSCD                varchar(8)        = null
	,@DocumentContent            varbinary(max)    = null
	,@UserDefinedColumns         xml               = null
	,@EmailTemplateAttachmentXID varchar(150)      = null
	,@LegacyKey                  nvarchar(50)      = null
	,@UpdateUser                 nvarchar(75)      = null -- set to current application user unless "SystemUser" passed
	,@RowStamp                   timestamp         = null -- row time stamp - pass for preemptive check for overwrites
	,@IsReselected               tinyint           = 0    -- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@IsNullApplied              bit               = 0    -- when 1 null parameters overwrite corresponding columns with null
	,@zContext                   xml               = null -- other values defining context for the update (if any)
	,@EmailTemplateLabel         nvarchar(35)      = null -- not a base table column
	,@PriorityLevel              tinyint           = null -- not a base table column
	,@Subject                    nvarchar(120)     = null -- not a base table column
	,@IsApplicationUserRequired  bit               = null -- not a base table column
	,@LinkExpiryHours            int               = null -- not a base table column
	,@ApplicationEntitySID       int               = null -- not a base table column
	,@ApplicationGrantSID        int               = null -- not a base table column
	,@EmailTemplateRowGUID       uniqueidentifier  = null -- not a base table column
	,@FileTypeFileTypeSCD        varchar(8)        = null -- not a base table column
	,@FileTypeLabel              nvarchar(35)      = null -- not a base table column
	,@MimeType                   varchar(255)      = null -- not a base table column
	,@IsInline                   bit               = null -- not a base table column
	,@FileTypeIsActive           bit               = null -- not a base table column
	,@FileTypeRowGUID            uniqueidentifier  = null -- not a base table column
	,@IsDeleteEnabled            bit               = null -- not a base table column
as
/*********************************************************************************************************************************
Procedure : sf.pEmailTemplateAttachment#Update
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : updates 1 row in the sf.EmailTemplateAttachment table
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used to update the sf.EmailTemplateAttachment table. The procedure requires a primary key to locate the record to update.
Additional parameters are provided for all columns in the vEmailTemplateAttachment entity view, however, the base logic of the procedure
updates the columns of the table only. Table-specific logic can be added through tagged sections (pre and post update) and a call
to an extended procedure supports client-specific logic. Logic implemented within code tags (table-specific logic) is part of the
base product and applies to all client configurations. Calls to the extended procedure occur immediately after the table-specific
logic in both "pre-update" and "post-update" contexts.  A transaction is used to commit/rollback all changes as a logical unit.

Client specific customizations must be implemented in the ext.pEmailTemplateAttachment procedure. The extended procedure is only called
where it exists in the DB. The first parameter passed @Mode is set to either "update.pre" or "update.post" to provide context for
the extended logic.

The @zContext parameter is an additional construct available to support overrides where different results are produced based on
content provided in the XML from the client tier. This parameter may contain multiple values.

The "@IsReselected" parameter controls output and "@IsNullApplied" controls whether or not parameters with null values overwrite
corresponding columns on the row.

For client-tier calls using the Microsoft Entity Framework and RIA Services, the @IsReselected bit should be passed as 1 to
force re-selection of table columns + extended view columns (the entity view).

Values for parameters representing mandatory columns must be provided unless @IsNullApplied is passed as 0. If @IsNullApplied = 1
any parameter with a null value overwrites the corresponding column value with null.  @IsNullApplied defaults to 0 but should be
passed as 1 when calling through the entity framework domain service since all columns are mapped to the procedure.

If the @UpdateUser parameter is passed as the special value "SystemUser", then the system user established in sf.ConfigParam
is applied. This option is useful for conversion and system generated updates the user would not recognize as having caused. Any
other value provided for the parameter (including null) is overwritten with the current application user.

The @RowStamp parameter should always be passed when calling from the user interface. The @RowStamp parameter is used to
preemptively check for an overwrite.  The value should be passed as the RowStamp value from the row when it was last
retrieved into the UI. If the RowStamp on the record changes from the value passed, this procedure will raise an exception and
avoid the overwrite.  For calls from back-end procedures, the @RowStamp parameter can be left blank and it will default to the
current time stamp on the record (avoiding the need to look up the value prior to calling.)

Business rule compliance is checked through a table constraint which calls fEmailTemplateAttachmentCheck to test all rules.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@errorText                                    nvarchar(4000)					-- message text (for business rule errors)
		,@rowsAffected                                 int = 0								-- tracks rows impacted by the operation (error check)
		,@recordSID                                    int										-- tracks primary key value for clearing current default
		,@ON                                           bit = cast(1 as bit)		-- constant for bit comparison and assignments
		,@OFF                                          bit = cast(0 as bit)		-- constant for bit comparison and assignments

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- check parameters

		if @EmailTemplateAttachmentSID is null
		begin

			exec sf.pMessage#Get
				 @MessageSCD  	= 'BlankParameter'
				,@MessageText 	= @errorText output
				,@DefaultText 	= N'A parameter (%1) required by the database procedure was left blank.'
				,@Arg1					= '@EmailTemplateAttachmentSID'

			raiserror(@errorText, 18, 1)
		end

		-- remove leading and trailing spaces from character type columns

		set @DocumentTitle = ltrim(rtrim(@DocumentTitle))
		set @FileTypeSCD = ltrim(rtrim(@FileTypeSCD))
		set @EmailTemplateAttachmentXID = ltrim(rtrim(@EmailTemplateAttachmentXID))
		set @LegacyKey = ltrim(rtrim(@LegacyKey))
		set @UpdateUser = ltrim(rtrim(@UpdateUser))
		set @EmailTemplateLabel = ltrim(rtrim(@EmailTemplateLabel))
		set @Subject = ltrim(rtrim(@Subject))
		set @FileTypeFileTypeSCD = ltrim(rtrim(@FileTypeFileTypeSCD))
		set @FileTypeLabel = ltrim(rtrim(@FileTypeLabel))
		set @MimeType = ltrim(rtrim(@MimeType))

		-- set zero length strings to null to avoid storing them in the record

		if len(@DocumentTitle) = 0 set @DocumentTitle = null
		if len(@FileTypeSCD) = 0 set @FileTypeSCD = null
		if len(@EmailTemplateAttachmentXID) = 0 set @EmailTemplateAttachmentXID = null
		if len(@LegacyKey) = 0 set @LegacyKey = null
		if len(@UpdateUser) = 0 set @UpdateUser = null
		if len(@EmailTemplateLabel) = 0 set @EmailTemplateLabel = null
		if len(@Subject) = 0 set @Subject = null
		if len(@FileTypeFileTypeSCD) = 0 set @FileTypeFileTypeSCD = null
		if len(@FileTypeLabel) = 0 set @FileTypeLabel = null
		if len(@MimeType) = 0 set @MimeType = null

		-- set the ID of the user

		if isnull(@UpdateUser, 'x') = N'SystemUser' set @UpdateUser = left(sf.fConfigParam#Value('SystemUser'),75)-- override for "SystemUser"
		if isnull(@UpdateUser, 'x') <> N'SystemUser' set @UpdateUser = sf.fApplicationUserSession#UserName()			-- application user - or DB user if no application session set

		-- avoid overwriting with null parameter values (unless specified)
		-- by retrieving existing values from the entity row for blank parameters

		if @IsNullApplied = 0
		begin

			select
				 @EmailTemplateSID           = isnull(@EmailTemplateSID,eta.EmailTemplateSID)
				,@DocumentTitle              = isnull(@DocumentTitle,eta.DocumentTitle)
				,@FileTypeSID                = isnull(@FileTypeSID,eta.FileTypeSID)
				,@FileTypeSCD                = isnull(@FileTypeSCD,eta.FileTypeSCD)
				,@DocumentContent            = isnull(@DocumentContent,eta.DocumentContent)
				,@UserDefinedColumns         = isnull(@UserDefinedColumns,eta.UserDefinedColumns)
				,@EmailTemplateAttachmentXID = isnull(@EmailTemplateAttachmentXID,eta.EmailTemplateAttachmentXID)
				,@LegacyKey                  = isnull(@LegacyKey,eta.LegacyKey)
				,@UpdateUser                 = isnull(@UpdateUser,eta.UpdateUser)
				,@IsReselected               = isnull(@IsReselected,eta.IsReselected)
				,@IsNullApplied              = isnull(@IsNullApplied,eta.IsNullApplied)
				,@zContext                   = isnull(@zContext,eta.zContext)
				,@EmailTemplateLabel         = isnull(@EmailTemplateLabel,eta.EmailTemplateLabel)
				,@PriorityLevel              = isnull(@PriorityLevel,eta.PriorityLevel)
				,@Subject                    = isnull(@Subject,eta.Subject)
				,@IsApplicationUserRequired  = isnull(@IsApplicationUserRequired,eta.IsApplicationUserRequired)
				,@LinkExpiryHours            = isnull(@LinkExpiryHours,eta.LinkExpiryHours)
				,@ApplicationEntitySID       = isnull(@ApplicationEntitySID,eta.ApplicationEntitySID)
				,@ApplicationGrantSID        = isnull(@ApplicationGrantSID,eta.ApplicationGrantSID)
				,@EmailTemplateRowGUID       = isnull(@EmailTemplateRowGUID,eta.EmailTemplateRowGUID)
				,@FileTypeFileTypeSCD        = isnull(@FileTypeFileTypeSCD,eta.FileTypeFileTypeSCD)
				,@FileTypeLabel              = isnull(@FileTypeLabel,eta.FileTypeLabel)
				,@MimeType                   = isnull(@MimeType,eta.MimeType)
				,@IsInline                   = isnull(@IsInline,eta.IsInline)
				,@FileTypeIsActive           = isnull(@FileTypeIsActive,eta.FileTypeIsActive)
				,@FileTypeRowGUID            = isnull(@FileTypeRowGUID,eta.FileTypeRowGUID)
				,@IsDeleteEnabled            = isnull(@IsDeleteEnabled,eta.IsDeleteEnabled)
			from
				sf.vEmailTemplateAttachment eta
			where
				eta.EmailTemplateAttachmentSID = @EmailTemplateAttachmentSID

		end
		
		-- ensure the file type SID value matches the code being set; a trigger
		-- enforces the rule for updates outside of the EF sprocs
		
		select
			@FileTypeSID = ft.FileTypeSID
		from
			sf.FileType ft
		where
			ft.FileTypeSCD = @FileTypeSCD
		and
			ft.IsActive = @ON
		
		if @@rowcount = 0
		begin
		
			exec sf.pMessage#Get
				@MessageSCD  = 'FileTypeNotFound'
				,@MessageText = @errorText output
				,@DefaultText = N'The file type "%1" is not supported. Upload a different file or ask your administrator if this type can be added to the configuration.'
				,@Arg1        = @FileTypeSCD
		
			raiserror(@errorText, 16, 1)
		end

		-- block changing FK values to parent records which are inactive (UI should prevent this)
		
		if (select x.FileTypeSID from sf.EmailTemplateAttachment x where x.EmailTemplateAttachmentSID = @EmailTemplateAttachmentSID) <> @FileTypeSID
		begin
			if (select x.IsActive from sf.FileType x where x.FileTypeSID = @FileTypeSID) = @OFF
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'AssignmentToInactiveParent'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 assigned is marked inactive. Leave the record unchanged or set to an active %1.'
					,@Arg1        = N'file type'
				
				raiserror(@errorText, 16, 1)
				
			end
		end

		-- apply the table-specific pre-update logic (if any)

		--! <PreUpdate>
		--  insert pre-update logic here ...
		--! </PreUpdate>

		-- update the record

		update
			sf.EmailTemplateAttachment
		set
			 EmailTemplateSID = @EmailTemplateSID
			,DocumentTitle = @DocumentTitle
			,FileTypeSID = @FileTypeSID
			,FileTypeSCD = @FileTypeSCD
			,DocumentContent = @DocumentContent
			,UserDefinedColumns = @UserDefinedColumns
			,EmailTemplateAttachmentXID = @EmailTemplateAttachmentXID
			,LegacyKey = @LegacyKey
			,UpdateUser = @UpdateUser
			,UpdateTime = sysdatetimeoffset()
		where
			EmailTemplateAttachmentSID = @EmailTemplateAttachmentSID
			and
			RowStamp = isnull(@RowStamp, RowStamp)

		set @rowsAffected = @@rowcount

		-- check for errors

		if @rowsAffected = 0
		begin
			
			if exists (select 1 from sf.EmailTemplateAttachment where EmailTemplateAttachmentSID = @emailTemplateAttachmentSID)
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'UpdateBlocked'
					,@MessageText = @errorText output
					,@DefaultText = N'A change was made to the "%1" record since it was last retrieved. The overwrite was avoided. Refresh the record and try again.'
					,@Arg1        = 'sf.EmailTemplateAttachment'
				
				raiserror(@errorText, 16, 1)
			end
			else
			begin
				
				exec sf.pMessage#Get
					 @MessageSCD  = 'RecordNotFound'
					,@MessageText = @errorText output
					,@DefaultText = N'The %1 record was not found. Record ID = "%2". The record may have been deleted or the identifier is invalid.'
					,@Arg1        = 'sf.EmailTemplateAttachment'
					,@Arg2        = @emailTemplateAttachmentSID
				
				raiserror(@errorText, 18, 1)
			end

		end
		else if @rowsAffected <> 1
		begin

			exec sf.pMessage#Get
				 @MessageSCD  = 'RowCountUnexpected'
				,@MessageText = @errorText output
				,@DefaultText = N'The %1 operation on table "%2" affected an unexpected number of rows (%3). Record ID = %4.'
				,@Arg1        = 'update'
				,@Arg2        = 'sf.EmailTemplateAttachment'
				,@Arg3        = @rowsAffected
				,@Arg4        = @emailTemplateAttachmentSID
			
			raiserror(@errorText, 18, 1)
		end

		-- apply the table-specific post-update logic (if any)

		--! <PostUpdate>
		--  insert post-update logic here ...
		--! </PostUpdate>

		if @trancount = 0 and xact_state() = 1 commit transaction

		-- return all columns for entity (1), just the PK value (2), or no returned value (0)

		if @IsReselected = 2
		begin

			select
				 ent.EmailTemplateAttachmentSID
			from
				sf.vEmailTemplateAttachment ent
			where
				ent.EmailTemplateAttachmentSID = @EmailTemplateAttachmentSID

		end
		else if @IsReselected = 1
		begin

			select
				 ent.EmailTemplateAttachmentSID
				,ent.EmailTemplateSID
				,ent.DocumentTitle
				,ent.FileTypeSID
				,ent.FileTypeSCD
				,ent.DocumentContent
				,ent.UserDefinedColumns
				,ent.EmailTemplateAttachmentXID
				,ent.LegacyKey
				,ent.IsDeleted
				,ent.CreateUser
				,ent.CreateTime
				,ent.UpdateUser
				,ent.UpdateTime
				,ent.RowGUID
				,ent.RowStamp
				,ent.EmailTemplateLabel
				,ent.PriorityLevel
				,ent.Subject
				,ent.IsApplicationUserRequired
				,ent.LinkExpiryHours
				,ent.ApplicationEntitySID
				,ent.ApplicationGrantSID
				,ent.EmailTemplateRowGUID
				,ent.FileTypeFileTypeSCD
				,ent.FileTypeLabel
				,ent.MimeType
				,ent.IsInline
				,ent.FileTypeIsActive
				,ent.FileTypeRowGUID
				,ent.IsDeleteEnabled
				,ent.IsReselected
				,ent.IsNullApplied
				,ent.zContext
			from
				sf.vEmailTemplateAttachment ent
			where
				ent.EmailTemplateAttachmentSID = @EmailTemplateAttachmentSID

		end

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
