SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [sf].[pAnnouncement#Insert]
	 @AnnouncementSID       int               = null output									-- identity value assigned to the new record
	,@Title                 nvarchar(75)      = null												-- required! if not passed value must be set in custom logic prior to insert
	,@AnnouncementText      nvarchar(1000)    = null												-- required! if not passed value must be set in custom logic prior to insert
	,@EffectiveTime         datetime          = null												-- required! if not passed value must be set in custom logic prior to insert
	,@ExpiryTime            datetime          = null												-- required! if not passed value must be set in custom logic prior to insert
	,@AdditionalInfoPageURI varchar(150)      = null												
	,@TagList               xml               = null												-- default: CONVERT(xml,N'<TagList/>',(0))
	,@IsLoginAlert          bit               = null												-- default: CONVERT(bit,(0))
	,@IsExtendedFormat      bit               = null												-- default: CONVERT(bit,(0))
	,@UserDefinedColumns    xml               = null												
	,@AnnouncementXID       varchar(150)      = null												
	,@LegacyKey             nvarchar(50)      = null												
	,@CreateUser            nvarchar(75)      = null												-- default: suser_sname()
	,@IsReselected          tinyint           = null												-- when 1 all columns in entity view are returned, 2 PK only, 0 none
	,@zContext              xml               = null												-- other values defining context for the insert (if any)
	,@IsActive              bit               = null												-- not a base table column (default ignored)
	,@IsPending             bit               = null												-- not a base table column (default ignored)
	,@IsDeleteEnabled       bit               = null												-- not a base table column (default ignored)
	,@IsClearedOrExpired    bit               = null												-- not a base table column (default ignored)
	,@IsNew                 bit               = null												-- not a base table column (default ignored)
	,@ApplicationGrantSCD   varchar(30)       = null												-- not a base table column (default ignored)
as
/*********************************************************************************************************************************
Procedure : sf.pAnnouncement#Insert
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : inserts 1 row into the sf.Announcement table
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : March 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the sf.Announcement table with parameter values represent columns of the table. Additional
parameters are provided for all columns in the vAnnouncement entity view, however, the base logic of the procedure inserts the
the columns of the table only.

Note: This procedure cannot be called directly from the MS Entity Framework! Use the wrapper procedure instead (...#EFInsert) that
excludes the primary key output parameter, but includes all other parameters.

Table-specific logic can be added through tagged sections (pre and post insert) and a call to an extended procedure supports
configuration (client) specific logic. Code implemented within code tags (table-specific logic) is part of the base product and
applies to all client configurations. Calls to the extended procedure occurs immediately after the table-specific logic in both
"pre-insert" and "post-insert" contexts.  A transaction is used to commit/rollback all changes as a logical unit.

Client specific customizations must be implemented in the ext.pAnnouncement procedure. The extended procedure is only called
where it exists in the DB. The first parameter passed @Mode is set to either "insert.pre" or "insert.post" to provide context for
the extended logic.

The @zContext parameter is an additional construct available to support overrides where different results are produced based on
content provided in the XML from the client tier. This parameter may contain multiple values.

The "@IsReselected" parameter controls whether the entity row is returned as a dataset (SELECT). There are 3 settings:
   0 - no data set is returned
   1 - return the full entity
   2 - return only the SID (primary key) of the row inserted

For client-tier calls using the Microsoft Entity Framework and RIA Services, the @IsReselected bit should be passed as 1 to
force re-selection of table columns + extended view columns (the entity view).

Values for parameters representing mandatory columns must be provided unless a database default exists.  The default values
displayed as comments next to the parameter declarations above, and the list of columns returned from the entity view when
@IsReselected = 1, were obtained from the data dictionary at generation time. If the table or view design has been
updated since then, the procedure must be regenerated to keep comments up to date. In the StudioDB run dbo.pEFGen
to update all views and procedures which appear out-of-date.

The procedure does not accept a parameter for UpdateUser since the @CreateUser value is applied into both the user audit
columns.  Audit times are set automatically through database defaults and cannot be passed or overwritten.

If the @CreateUser parameter is passed as the special value "SystemUser", then the system user established in sf.ConfigParam
is applied. This option is useful for conversion and system generated inserts the user would not recognize as have caused. Any
other value provided for the parameter (including null) is overwritten with the current application user.

Business rule compliance is checked through a table constraint which calls fAnnouncementCheck to test all rules.

-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@errorText                                    nvarchar(4000)					-- message text (for business rule errors)
		,@rowsAffected                                 int = 0								-- tracks rows impacted by the operation (error check)
		,@recordSID                                    int										-- tracks primary key value for clearing current default
		,@ON                                           bit = cast(1 as bit)		-- constant for bit comparison and assignments
		,@OFF                                          bit = cast(0 as bit)		-- constant for bit comparison and assignments

	set @AnnouncementSID = null																							-- initialize output parameter

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end

		-- remove leading and trailing spaces from character type columns

		set @Title = ltrim(rtrim(@Title))
		set @AnnouncementText = ltrim(rtrim(@AnnouncementText))
		set @AdditionalInfoPageURI = ltrim(rtrim(@AdditionalInfoPageURI))
		set @AnnouncementXID = ltrim(rtrim(@AnnouncementXID))
		set @LegacyKey = ltrim(rtrim(@LegacyKey))
		set @CreateUser = ltrim(rtrim(@CreateUser))
		set @ApplicationGrantSCD = ltrim(rtrim(@ApplicationGrantSCD))

		-- set zero length strings to null to avoid storing them in the record

		if len(@Title) = 0 set @Title = null
		if len(@AnnouncementText) = 0 set @AnnouncementText = null
		if len(@AdditionalInfoPageURI) = 0 set @AdditionalInfoPageURI = null
		if len(@AnnouncementXID) = 0 set @AnnouncementXID = null
		if len(@LegacyKey) = 0 set @LegacyKey = null
		if len(@CreateUser) = 0 set @CreateUser = null
		if len(@ApplicationGrantSCD) = 0 set @ApplicationGrantSCD = null

		-- set the ID of the user

		if isnull(@CreateUser, 'x') = N'SystemUser' set @CreateUser = left(sf.fConfigParam#Value('SystemUser'),75)-- override for "SystemUser"
		if isnull(@CreateUser, 'x') <> N'SystemUser' set @CreateUser = sf.fApplicationUserSession#UserName()			-- application user - or DB user if no application session set

		-- reset defaults on table parameters passed as NULL

		set @TagList = isnull(@TagList,CONVERT(xml,N'<TagList/>',(0)))
		set @IsLoginAlert = isnull(@IsLoginAlert,CONVERT(bit,(0)))
		set @IsExtendedFormat = isnull(@IsExtendedFormat,CONVERT(bit,(0)))
		set @CreateUser = isnull(@CreateUser,suser_sname())
		set @IsReselected          = isnull(@IsReselected         ,(0))
		
		set @TagList = sf.fTagList#SetTagTimes(@TagList)											-- add times to the tags applied (if any)

		-- apply the table-specific pre-insert logic (if any)

		--! <PreInsert>
		-- Tim Edlund | Mar 2015
		-- For login alerts, default the expiry to the end of the effective
		-- time day (client timezone).  For other announcements, default to 1
		-- month + end-of-day.  The effective time default is always
		-- the start of the current day.

		if @EffectiveTime is null set @effectiveTime = sf.fDatePlusTimeToDT(sf.fToday(), cast('00:00:00' as time(0)))

		if @ExpiryTime is null
		begin
			if @IsLoginAlert = cast(1 as bit)
			begin
				set @ExpiryTime = sf.fDatePlusTimeToDT(cast(@EffectiveTime as date), cast('23:59:59' as time(0)))
			end
			else
			begin
				set @ExpiryTime = sf.fDatePlusTimeToDT(dateadd(month, 1, cast(@EffectiveTime as date)), cast('23:59:59' as time(0)))
			end
		end
		--! </PreInsert>
		
		exec sf.pEffectiveExpiry#Set																					-- ensure values have start/end of day time components or current time if today
		   @EffectiveTime = @EffectiveTime output
		  ,@ExpiryTime    = @ExpiryTime    output

		-- insert the record

		insert
			sf.Announcement
		(
			 Title
			,AnnouncementText
			,EffectiveTime
			,ExpiryTime
			,AdditionalInfoPageURI
			,TagList
			,IsLoginAlert
			,IsExtendedFormat
			,UserDefinedColumns
			,AnnouncementXID
			,LegacyKey
			,CreateUser
			,UpdateUser
		)
		select
			 @Title
			,@AnnouncementText
			,@EffectiveTime
			,@ExpiryTime
			,@AdditionalInfoPageURI
			,@TagList
			,@IsLoginAlert
			,@IsExtendedFormat
			,@UserDefinedColumns
			,@AnnouncementXID
			,@LegacyKey
			,@CreateUser
			,@CreateUser

		select
			 @rowsAffected    = @@rowcount
			,@AnnouncementSID = scope_identity()																-- capture key value of new row

		-- check for errors

		if @rowsAffected <> 1																									-- ensure 1 row was inserted
		begin

			exec sf.pMessage#Get
				 @MessageSCD  = 'RowCountUnexpected'
				,@MessageText = @errorText output
				,@DefaultText = N'The "%1" operation on table "%2" affected an unexpected number of rows (%3). Record ID = %4.'
				,@Arg1        = 'insert'
				,@Arg2        = 'sf.Announcement'
				,@Arg3        = @rowsAffected
				,@Arg4        = @AnnouncementSID
			
			raiserror(@errorText, 18, 1)
			
		end

		-- apply the table-specific post-insert logic (if any)

		--! <PostInsert>
		-- Tim Edlund | Oct 2018
		-- If a grant was passed for access to this announcement,
		-- insert it now.  Note that if the grant is for the
		-- client portal (EXTERNAL.%), the admin base grant is
		-- automatically added so they see the announcement.

		if @ApplicationGrantSCD is not null
		begin

			select
				@recordSID = ag.ApplicationGrantSID
			from
				sf.ApplicationGrant ag
			where
				ag.ApplicationGrantSCD = @ApplicationGrantSCD;

			if @recordSID is null
			begin

				exec sf.pMessage#Get
					@MessageSCD = 'RecordNotFound'
				 ,@MessageText = @errorText output
				 ,@DefaultText = N'The %1 record was not found. Record ID = "%2". The record may have been deleted or the identifier is invalid.'
				 ,@Arg1 = 'sf.ApplicationGrant'
				 ,@Arg2 = @ApplicationGrantSCD;

				raiserror(@errorText, 18, 1);
			end;

			insert
				sf.AnnouncementApplicationGrant (AnnouncementSID, ApplicationGrantSID)
			values
			(@AnnouncementSID, @recordSID);

			if @ApplicationGrantSCD like 'EXTERNAL.%'
			begin

				select
					@recordSID = ag.ApplicationGrantSID
				from
					sf.ApplicationGrant ag
				where
					ag.ApplicationGrantSCD = 'ADMIN.BASE';

				if @recordSID is not null
				begin

					insert
						sf.AnnouncementApplicationGrant (AnnouncementSID, ApplicationGrantSID)
					values
					(@AnnouncementSID, @recordSID);

				end;

			end;

		end;
		--! </PostInsert>

		if @trancount = 0 and xact_state() = 1 commit transaction

		-- return all columns for entity (1), just the PK value (2), or no returned value (0)

		if @IsReselected = 2
		begin

			select
				 ent.AnnouncementSID
			from
				sf.vAnnouncement ent
			where
				ent.AnnouncementSID = @AnnouncementSID

		end
		else if @IsReselected = 1
		begin

			select
				 ent.AnnouncementSID
				,ent.Title
				,ent.AnnouncementText
				,ent.EffectiveTime
				,ent.ExpiryTime
				,ent.AdditionalInfoPageURI
				,ent.TagList
				,ent.IsLoginAlert
				,ent.IsExtendedFormat
				,ent.UserDefinedColumns
				,ent.AnnouncementXID
				,ent.LegacyKey
				,ent.IsDeleted
				,ent.CreateUser
				,ent.CreateTime
				,ent.UpdateUser
				,ent.UpdateTime
				,ent.RowGUID
				,ent.RowStamp
				,ent.IsActive
				,ent.IsPending
				,ent.IsDeleteEnabled
				,ent.IsReselected
				,ent.IsNullApplied
				,ent.zContext
				,ent.IsClearedOrExpired
				,ent.IsNew
				,ent.ApplicationGrantSCD
			from
				sf.vAnnouncement ent
			where
				ent.AnnouncementSID = @AnnouncementSID

		end

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
