SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [stg].[pRegistrantExamProfile#Default]
	 @zContext                       xml               = null                -- default values provided from client-tier (if any)
	,@SetFKDefaults                  bit               = 0                   -- when 1, mandatory FK's are returned as -1 instead of NULL
as
/*********************************************************************************************************************************
Procedure : stg.pRegistrantExamProfile#Default
Notice    : Copyright © 2019 Softworks Group Inc.
Summary   : provides a blank row with default values for presentation in the UI for "new" stg.RegistrantExamProfile records
-----------------------------------------------------------------------------------------------------------------------------------
Author    : Generated by DB Studio: pSprocGen | Designer: Tim Edlund
Version   : April 2019
-----------------------------------------------------------------------------------------------------------------------------------
Comments
--------
This procedure is used in maintenance of the stg.RegistrantExamProfile table. When a new record is to be added from the UI, this procedure
is called to return a blank record with default values. If the client-tier is providing the context for the insert, such as a parent
key value for the new record, it must be passed in the @zContext XML parameter. Multiple values may be passed. The standard format
is: <Parameters MyParameter="1000001"/>.

The @SetFKDefaults parameter can be set to 1 to cause the procedure to return mandatory FK values as -1 rather than NULL. This avoids
the need to create complex types for the procedure on architectures which are not using RIA services.

Note that default values for text, ntext and binary type columns is not supported.  These data types are not permitted as local
variables in the current version of SQL Server and should be replaced by varchar(max) and nvarchar(max) where possible.

Some default values are built-in to the shell of the sproc.  The base table column defaults set in the variable declarations below
were obtained from database default constraints which existed at the time the procedure was generated. The declarations include all
columns of the vRegistrantExamProfile entity view, however, only some values (as noted above) are eligible for default setting.  The other
parameters are included for setting context for the table-specific or client-specific logic of the procedure (if any). Default values
returning a question mark "?", system date, or 0 are provided for non-base table columns which are mandatory.  This is done to avoid
compilation errors from the Entity Framework, however, the values will not be applied since they are not in the base table row.

Two levels of customization of the procedure shell are supported. Table-specific logic can be added through the tagged section and a
call to an extended procedure supports client-specific customization. Logic implemented within the code tags is part of the base
product and applies to all client configurations. Client-specific customizations must be implemented in the ext.pRegistrantExamProfile
procedure. The extended procedure is only called where it exists in database. The parameter "@Mode" is set to "default.pre" to
advise ext.pRegistrantExamProfile of the context of the call. All other parameters are also passed, however, only those parameters eligible
for default setting are passed for "output". All parameters corresponding to entity view columns are returned through a SELECT statement.

In order to simplify working with the XML parameter values, logic in the procedure parses the XML and assigns values to variables where
the variable name matches the column name in the XML (assumes single row).  The variables are then available to the table-specific and
client-specific logic.  The @zContext parameter is also passed, unmodified, to the extended procedure to support situations where values
are passed that are not mapped to column names.


-------------------------------------------------------------------------------------------------------------------------------- */

begin
	set nocount on

	declare
		 @errorNo                                      int = 0								-- 0 no error, <50000 SQL error, else business rule
		,@tranCount                                    int = @@trancount			-- determines whether a wrapping transaction exists
		,@sprocName                                    nvarchar(128) = object_name(@@procid)						-- name of currently executing procedure
		,@xState                                       int										-- error state detected in catch block
		,@ON                             bit = cast(1 as bit)									-- constant for bit comparisons
		,@OFF                            bit = cast(0 as bit)									-- constant for bit comparisons
		,@registrantExamProfileSID       int               = -1								-- specific default required by EF - do not override
		,@importFileSID                  int               = null							-- no default provided from DB constraint - OK to override
		,@processingStatusSID            int               = null							-- no default provided from DB constraint - OK to override
		,@registrantNo                   varchar(50)       = null							-- no default provided from DB constraint - OK to override
		,@emailAddress                   varchar(150)      = null							-- no default provided from DB constraint - OK to override
		,@firstName                      nvarchar(30)      = null							-- no default provided from DB constraint - OK to override
		,@lastName                       nvarchar(35)      = null							-- no default provided from DB constraint - OK to override
		,@birthDate                      date              = null							-- no default provided from DB constraint - OK to override
		,@examIdentifier                 nvarchar(50)      = null							-- no default provided from DB constraint - OK to override
		,@examDate                       date              = null							-- no default provided from DB constraint - OK to override
		,@examTime                       time(0)           = null							-- no default provided from DB constraint - OK to override
		,@orgLabel                       nvarchar(35)      = null							-- no default provided from DB constraint - OK to override
		,@examResultDate                 date              = null							-- no default provided from DB constraint - OK to override
		,@passingScore                   int               = null							-- no default provided from DB constraint - OK to override
		,@score                          int               = null							-- no default provided from DB constraint - OK to override
		,@assignedLocation               varchar(15)       = null							-- no default provided from DB constraint - OK to override
		,@examReference                  varchar(25)       = null							-- no default provided from DB constraint - OK to override
		,@personSID                      int               = null							-- no default provided from DB constraint - OK to override
		,@registrantSID                  int               = null							-- no default provided from DB constraint - OK to override
		,@orgSID                         int               = null							-- no default provided from DB constraint - OK to override
		,@examSID                        int               = null							-- no default provided from DB constraint - OK to override
		,@examOfferingSID                int               = null							-- no default provided from DB constraint - OK to override
		,@processingComments             nvarchar(max)     = null							-- no default provided from DB constraint - OK to override
		,@userDefinedColumns             xml               = null							-- no default provided from DB constraint - OK to override
		,@registrantExamProfileXID       varchar(150)      = null							-- no default provided from DB constraint - OK to override
		,@legacyKey                      nvarchar(50)      = null							-- no default provided from DB constraint - OK to override
		,@isDeleted                      bit               = (0)							-- default provided from DB constraint - OK to override
		,@createUser                     nvarchar(75)      = suser_sname()		-- default value ignored (value set by UI)
		,@createTime                     datetimeoffset(7) = sysdatetimeoffset()												-- default value ignored (set to system time)
		,@updateUser                     nvarchar(75)      = suser_sname()		-- default value ignored (value set by UI)
		,@updateTime                     datetimeoffset(7) = sysdatetimeoffset()												-- default value ignored (set to system time)
		,@rowGUID                        uniqueidentifier  = newid()					-- default value ignored (value set by system)
		,@rowStamp                       timestamp         = null							-- default value ignored (value set by system)
		,@fileFormatSID                  int               = 0								-- not a base table column (default ignored)
		,@applicationEntitySID           int               = 0								-- not a base table column (default ignored)
		,@fileName                       nvarchar(100)     = N'?'							-- not a base table column (default ignored)
		,@loadStartTime                  datetimeoffset(7)										-- not a base table column (default ignored)
		,@loadEndTime                    datetimeoffset(7)										-- not a base table column (default ignored)
		,@isFailed                       bit               = 0								-- not a base table column (default ignored)
		,@messageText                    nvarchar(4000)												-- not a base table column (default ignored)
		,@importFileRowGUID              uniqueidentifier  = newid()					-- not a base table column (default ignored)
		,@processingStatusSCD            varchar(10)       = '?'							-- not a base table column (default ignored)
		,@processingStatusLabel          nvarchar(35)      = N'?'							-- not a base table column (default ignored)
		,@isClosedStatus                 bit               = 0								-- not a base table column (default ignored)
		,@processingStatusIsActive       bit               = 0								-- not a base table column (default ignored)
		,@processingStatusIsDefault      bit               = 0								-- not a base table column (default ignored)
		,@processingStatusRowGUID        uniqueidentifier  = newid()					-- not a base table column (default ignored)
		,@genderSID                      int																	-- not a base table column (default ignored)
		,@namePrefixSID                  int																	-- not a base table column (default ignored)
		,@personFirstName                nvarchar(30)													-- not a base table column (default ignored)
		,@commonName                     nvarchar(30)													-- not a base table column (default ignored)
		,@middleNames                    nvarchar(30)													-- not a base table column (default ignored)
		,@personLastName                 nvarchar(35)													-- not a base table column (default ignored)
		,@personBirthDate                date																	-- not a base table column (default ignored)
		,@deathDate                      date																	-- not a base table column (default ignored)
		,@homePhone                      varchar(25)													-- not a base table column (default ignored)
		,@mobilePhone                    varchar(25)													-- not a base table column (default ignored)
		,@isTextMessagingEnabled         bit																	-- not a base table column (default ignored)
		,@importBatch                    nvarchar(100)												-- not a base table column (default ignored)
		,@personRowGUID                  uniqueidentifier											-- not a base table column (default ignored)
		,@examName                       nvarchar(50)													-- not a base table column (default ignored)
		,@examCategory                   nvarchar(65)													-- not a base table column (default ignored)
		,@examPassingScore               int																	-- not a base table column (default ignored)
		,@effectiveTime                  datetime															-- not a base table column (default ignored)
		,@expiryTime                     datetime															-- not a base table column (default ignored)
		,@isOnlineExam                   bit																	-- not a base table column (default ignored)
		,@isEnabledOnPortal              bit																	-- not a base table column (default ignored)
		,@sequence                       int																	-- not a base table column (default ignored)
		,@cultureSID                     int																	-- not a base table column (default ignored)
		,@examLastVerifiedTime           datetimeoffset(7)										-- not a base table column (default ignored)
		,@minLagDaysBetweenAttempts      smallint															-- not a base table column (default ignored)
		,@maxAttemptsPerYear             tinyint															-- not a base table column (default ignored)
		,@vendorExamID                   varchar(25)													-- not a base table column (default ignored)
		,@examRowGUID                    uniqueidentifier											-- not a base table column (default ignored)
		,@examOfferingExamSID            int																	-- not a base table column (default ignored)
		,@examOfferingOrgSID             int																	-- not a base table column (default ignored)
		,@examOfferingExamTime           datetime															-- not a base table column (default ignored)
		,@seatingCapacity                int																	-- not a base table column (default ignored)
		,@catalogItemSID                 int																	-- not a base table column (default ignored)
		,@bookingCutOffDate              date																	-- not a base table column (default ignored)
		,@vendorExamOfferingID           varchar(25)													-- not a base table column (default ignored)
		,@examOfferingRowGUID            uniqueidentifier											-- not a base table column (default ignored)
		,@parentOrgSID                   int																	-- not a base table column (default ignored)
		,@orgTypeSID                     int																	-- not a base table column (default ignored)
		,@orgName                        nvarchar(150)												-- not a base table column (default ignored)
		,@orgOrgLabel                    nvarchar(35)													-- not a base table column (default ignored)
		,@streetAddress1                 nvarchar(75)													-- not a base table column (default ignored)
		,@streetAddress2                 nvarchar(75)													-- not a base table column (default ignored)
		,@streetAddress3                 nvarchar(75)													-- not a base table column (default ignored)
		,@citySID                        int																	-- not a base table column (default ignored)
		,@postalCode                     varchar(10)													-- not a base table column (default ignored)
		,@regionSID                      int																	-- not a base table column (default ignored)
		,@phone                          varchar(25)													-- not a base table column (default ignored)
		,@fax                            varchar(25)													-- not a base table column (default ignored)
		,@webSite                        varchar(250)													-- not a base table column (default ignored)
		,@orgEmailAddress                varchar(150)													-- not a base table column (default ignored)
		,@insuranceOrgSID                int																	-- not a base table column (default ignored)
		,@insurancePolicyNo              varchar(25)													-- not a base table column (default ignored)
		,@insuranceAmount                decimal(11,2)												-- not a base table column (default ignored)
		,@isEmployer                     bit																	-- not a base table column (default ignored)
		,@isCredentialAuthority          bit																	-- not a base table column (default ignored)
		,@isInsurer                      bit																	-- not a base table column (default ignored)
		,@isInsuranceCertificateRequired bit																	-- not a base table column (default ignored)
		,@isPublic                       nchar(10)														-- not a base table column (default ignored)
		,@orgIsActive                    bit																	-- not a base table column (default ignored)
		,@isAdminReviewRequired          bit																	-- not a base table column (default ignored)
		,@orgLastVerifiedTime            datetimeoffset(7)										-- not a base table column (default ignored)
		,@orgRowGUID                     uniqueidentifier											-- not a base table column (default ignored)
		,@registrantPersonSID            int																	-- not a base table column (default ignored)
		,@registrantRegistrantNo         varchar(50)													-- not a base table column (default ignored)
		,@yearOfInitialEmployment        smallint															-- not a base table column (default ignored)
		,@isOnPublicRegistry             bit																	-- not a base table column (default ignored)
		,@cityNameOfBirth                nvarchar(30)													-- not a base table column (default ignored)
		,@countrySID                     int																	-- not a base table column (default ignored)
		,@directedAuditYearCompetence    smallint															-- not a base table column (default ignored)
		,@directedAuditYearPracticeHours smallint															-- not a base table column (default ignored)
		,@lateFeeExclusionYear           smallint															-- not a base table column (default ignored)
		,@isRenewalAutoApprovalBlocked   bit																	-- not a base table column (default ignored)
		,@renewalExtensionExpiryTime     datetime															-- not a base table column (default ignored)
		,@archivedTime                   datetimeoffset(7)										-- not a base table column (default ignored)
		,@registrantRowGUID              uniqueidentifier											-- not a base table column (default ignored)
		,@isDeleteEnabled                bit																	-- not a base table column (default ignored)
		,@isReselected                   tinyint           = 1								-- specific default required by EF - do not override
		,@isNullApplied                  bit               = 1								-- specific default required by EF - do not override
		,@registrantLabel                nvarchar(75)													-- not a base table column (default ignored)

	begin try

		-- use a transaction so that any additional updates implemented through the extended
		-- procedure or through table-specific logic succeed or fail as a logical unit

		if @tranCount = 0																											-- no outer transaction
		begin
			begin transaction
		end
		else																																	-- outer transaction so create save point
		begin
			save transaction @sprocName
		end
		-- set mandatory FK values to -1 where requested
		
		if @SetFKDefaults = @ON
		begin
			set @importFileSID = -1
			set @processingStatusSID = -1
		end

		-- assign literal defaults passed through @zContext where
		-- provided otherwise leave database default in place
		
		select
			 @importFileSID             = isnull(context.node.value('@ImportFileSID'           ,'int'          ),@importFileSID)
			,@processingStatusSID       = isnull(context.node.value('@ProcessingStatusSID'     ,'int'          ),@processingStatusSID)
			,@registrantNo              = isnull(context.node.value('@RegistrantNo'            ,'varchar(50)'  ),@registrantNo)
			,@emailAddress              = isnull(context.node.value('@EmailAddress'            ,'varchar(150)' ),@emailAddress)
			,@firstName                 = isnull(context.node.value('@FirstName'               ,'nvarchar(30)' ),@firstName)
			,@lastName                  = isnull(context.node.value('@LastName'                ,'nvarchar(35)' ),@lastName)
			,@birthDate                 = isnull(context.node.value('@BirthDate'               ,'date'         ),@birthDate)
			,@examIdentifier            = isnull(context.node.value('@ExamIdentifier'          ,'nvarchar(50)' ),@examIdentifier)
			,@examDate                  = isnull(context.node.value('@ExamDate'                ,'date'         ),@examDate)
			,@examTime                  = isnull(context.node.value('@ExamTime'                ,'time(0)'      ),@examTime)
			,@orgLabel                  = isnull(context.node.value('@OrgLabel'                ,'nvarchar(35)' ),@orgLabel)
			,@examResultDate            = isnull(context.node.value('@ExamResultDate'          ,'date'         ),@examResultDate)
			,@passingScore              = isnull(context.node.value('@PassingScore'            ,'int'          ),@passingScore)
			,@score                     = isnull(context.node.value('@Score'                   ,'int'          ),@score)
			,@assignedLocation          = isnull(context.node.value('@AssignedLocation'        ,'varchar(15)'  ),@assignedLocation)
			,@examReference             = isnull(context.node.value('@ExamReference'           ,'varchar(25)'  ),@examReference)
			,@personSID                 = isnull(context.node.value('@PersonSID'               ,'int'          ),@personSID)
			,@registrantSID             = isnull(context.node.value('@RegistrantSID'           ,'int'          ),@registrantSID)
			,@orgSID                    = isnull(context.node.value('@OrgSID'                  ,'int'          ),@orgSID)
			,@examSID                   = isnull(context.node.value('@ExamSID'                 ,'int'          ),@examSID)
			,@examOfferingSID           = isnull(context.node.value('@ExamOfferingSID'         ,'int'          ),@examOfferingSID)
			,@processingComments        = isnull(context.node.value('@ProcessingComments'      ,'nvarchar(max)'),@processingComments)
			,@registrantExamProfileXID  = isnull(context.node.value('@RegistrantExamProfileXID','varchar(150)' ),@registrantExamProfileXID)
			,@legacyKey                 = isnull(context.node.value('@LegacyKey'               ,'nvarchar(50)' ),@legacyKey)
		from
			@zContext.nodes('Parameters') as context(node)
		
		-- set default value on foreign keys where configured
		-- and where no DB or literal value was passed for it
		
		if isnull(@processingStatusSID,0) = 0 select @processingStatusSID = x.ProcessingStatusSID from sf.ProcessingStatus  x where x.IsDefault = @ON

		--! <Overrides>
		--  insert default value logic here ...
		--! </Overrides>
	
		-- call the extended version of the procedure (if it exists) for "default.pre" mode
		
		if exists
		(
			select
				1
			from
				sf.vRoutine r
			where
				r.SchemaName = 'ext'
			and
				r.RoutineName = 'stg#pRegistrantExamProfile'
		)
		begin
		
			exec @errorNo = ext.stg#pRegistrantExamProfile
				 @Mode                           = 'default.pre'
				,@RegistrantExamProfileSID = @registrantExamProfileSID
				,@ImportFileSID = @importFileSID output
				,@ProcessingStatusSID = @processingStatusSID output
				,@RegistrantNo = @registrantNo output
				,@EmailAddress = @emailAddress output
				,@FirstName = @firstName output
				,@LastName = @lastName output
				,@BirthDate = @birthDate output
				,@ExamIdentifier = @examIdentifier output
				,@ExamDate = @examDate output
				,@ExamTime = @examTime output
				,@OrgLabel = @orgLabel output
				,@ExamResultDate = @examResultDate output
				,@PassingScore = @passingScore output
				,@Score = @score output
				,@AssignedLocation = @assignedLocation output
				,@ExamReference = @examReference output
				,@PersonSID = @personSID output
				,@RegistrantSID = @registrantSID output
				,@OrgSID = @orgSID output
				,@ExamSID = @examSID output
				,@ExamOfferingSID = @examOfferingSID output
				,@ProcessingComments = @processingComments output
				,@UserDefinedColumns = @userDefinedColumns output
				,@RegistrantExamProfileXID = @registrantExamProfileXID output
				,@LegacyKey = @legacyKey output
				,@IsDeleted = @isDeleted
				,@CreateUser = @createUser
				,@CreateTime = @createTime
				,@UpdateUser = @updateUser
				,@UpdateTime = @updateTime
				,@RowGUID = @rowGUID
				,@RowStamp = @rowStamp
				,@FileFormatSID = @fileFormatSID
				,@ApplicationEntitySID = @applicationEntitySID
				,@FileName = @fileName
				,@LoadStartTime = @loadStartTime
				,@LoadEndTime = @loadEndTime
				,@IsFailed = @isFailed
				,@MessageText = @messageText
				,@ImportFileRowGUID = @importFileRowGUID
				,@ProcessingStatusSCD = @processingStatusSCD
				,@ProcessingStatusLabel = @processingStatusLabel
				,@IsClosedStatus = @isClosedStatus
				,@ProcessingStatusIsActive = @processingStatusIsActive
				,@ProcessingStatusIsDefault = @processingStatusIsDefault
				,@ProcessingStatusRowGUID = @processingStatusRowGUID
				,@GenderSID = @genderSID
				,@NamePrefixSID = @namePrefixSID
				,@PersonFirstName = @personFirstName
				,@CommonName = @commonName
				,@MiddleNames = @middleNames
				,@PersonLastName = @personLastName
				,@PersonBirthDate = @personBirthDate
				,@DeathDate = @deathDate
				,@HomePhone = @homePhone
				,@MobilePhone = @mobilePhone
				,@IsTextMessagingEnabled = @isTextMessagingEnabled
				,@ImportBatch = @importBatch
				,@PersonRowGUID = @personRowGUID
				,@ExamName = @examName
				,@ExamCategory = @examCategory
				,@ExamPassingScore = @examPassingScore
				,@EffectiveTime = @effectiveTime
				,@ExpiryTime = @expiryTime
				,@IsOnlineExam = @isOnlineExam
				,@IsEnabledOnPortal = @isEnabledOnPortal
				,@Sequence = @sequence
				,@CultureSID = @cultureSID
				,@ExamLastVerifiedTime = @examLastVerifiedTime
				,@MinLagDaysBetweenAttempts = @minLagDaysBetweenAttempts
				,@MaxAttemptsPerYear = @maxAttemptsPerYear
				,@VendorExamID = @vendorExamID
				,@ExamRowGUID = @examRowGUID
				,@ExamOfferingExamSID = @examOfferingExamSID
				,@ExamOfferingOrgSID = @examOfferingOrgSID
				,@ExamOfferingExamTime = @examOfferingExamTime
				,@SeatingCapacity = @seatingCapacity
				,@CatalogItemSID = @catalogItemSID
				,@BookingCutOffDate = @bookingCutOffDate
				,@VendorExamOfferingID = @vendorExamOfferingID
				,@ExamOfferingRowGUID = @examOfferingRowGUID
				,@ParentOrgSID = @parentOrgSID
				,@OrgTypeSID = @orgTypeSID
				,@OrgName = @orgName
				,@OrgOrgLabel = @orgOrgLabel
				,@StreetAddress1 = @streetAddress1
				,@StreetAddress2 = @streetAddress2
				,@StreetAddress3 = @streetAddress3
				,@CitySID = @citySID
				,@PostalCode = @postalCode
				,@RegionSID = @regionSID
				,@Phone = @phone
				,@Fax = @fax
				,@WebSite = @webSite
				,@OrgEmailAddress = @orgEmailAddress
				,@InsuranceOrgSID = @insuranceOrgSID
				,@InsurancePolicyNo = @insurancePolicyNo
				,@InsuranceAmount = @insuranceAmount
				,@IsEmployer = @isEmployer
				,@IsCredentialAuthority = @isCredentialAuthority
				,@IsInsurer = @isInsurer
				,@IsInsuranceCertificateRequired = @isInsuranceCertificateRequired
				,@IsPublic = @isPublic
				,@OrgIsActive = @orgIsActive
				,@IsAdminReviewRequired = @isAdminReviewRequired
				,@OrgLastVerifiedTime = @orgLastVerifiedTime
				,@OrgRowGUID = @orgRowGUID
				,@RegistrantPersonSID = @registrantPersonSID
				,@RegistrantRegistrantNo = @registrantRegistrantNo
				,@YearOfInitialEmployment = @yearOfInitialEmployment
				,@IsOnPublicRegistry = @isOnPublicRegistry
				,@CityNameOfBirth = @cityNameOfBirth
				,@CountrySID = @countrySID
				,@DirectedAuditYearCompetence = @directedAuditYearCompetence
				,@DirectedAuditYearPracticeHours = @directedAuditYearPracticeHours
				,@LateFeeExclusionYear = @lateFeeExclusionYear
				,@IsRenewalAutoApprovalBlocked = @isRenewalAutoApprovalBlocked
				,@RenewalExtensionExpiryTime = @renewalExtensionExpiryTime
				,@ArchivedTime = @archivedTime
				,@RegistrantRowGUID = @registrantRowGUID
				,@IsDeleteEnabled = @isDeleteEnabled
				,@IsReselected = @isReselected
				,@IsNullApplied = @isNullApplied
				,@zContext = @zContext output
				,@RegistrantLabel = @registrantLabel
		
		end

		select
			 @registrantExamProfileSID RegistrantExamProfileSID
			,@importFileSID ImportFileSID
			,@processingStatusSID ProcessingStatusSID
			,@registrantNo RegistrantNo
			,@emailAddress EmailAddress
			,@firstName FirstName
			,@lastName LastName
			,@birthDate BirthDate
			,@examIdentifier ExamIdentifier
			,@examDate ExamDate
			,@examTime ExamTime
			,@orgLabel OrgLabel
			,@examResultDate ExamResultDate
			,@passingScore PassingScore
			,@score Score
			,@assignedLocation AssignedLocation
			,@examReference ExamReference
			,@personSID PersonSID
			,@registrantSID RegistrantSID
			,@orgSID OrgSID
			,@examSID ExamSID
			,@examOfferingSID ExamOfferingSID
			,@processingComments ProcessingComments
			,@userDefinedColumns UserDefinedColumns
			,@registrantExamProfileXID RegistrantExamProfileXID
			,@legacyKey LegacyKey
			,@isDeleted IsDeleted
			,@createUser CreateUser
			,@createTime CreateTime
			,@updateUser UpdateUser
			,@updateTime UpdateTime
			,@rowGUID RowGUID
			,@rowStamp RowStamp
			,@fileFormatSID FileFormatSID
			,@applicationEntitySID ApplicationEntitySID
			,@fileName FileName
			,@loadStartTime LoadStartTime
			,@loadEndTime LoadEndTime
			,@isFailed IsFailed
			,@messageText MessageText
			,@importFileRowGUID ImportFileRowGUID
			,@processingStatusSCD ProcessingStatusSCD
			,@processingStatusLabel ProcessingStatusLabel
			,@isClosedStatus IsClosedStatus
			,@processingStatusIsActive ProcessingStatusIsActive
			,@processingStatusIsDefault ProcessingStatusIsDefault
			,@processingStatusRowGUID ProcessingStatusRowGUID
			,@genderSID GenderSID
			,@namePrefixSID NamePrefixSID
			,@personFirstName PersonFirstName
			,@commonName CommonName
			,@middleNames MiddleNames
			,@personLastName PersonLastName
			,@personBirthDate PersonBirthDate
			,@deathDate DeathDate
			,@homePhone HomePhone
			,@mobilePhone MobilePhone
			,@isTextMessagingEnabled IsTextMessagingEnabled
			,@importBatch ImportBatch
			,@personRowGUID PersonRowGUID
			,@examName ExamName
			,@examCategory ExamCategory
			,@examPassingScore ExamPassingScore
			,@effectiveTime EffectiveTime
			,@expiryTime ExpiryTime
			,@isOnlineExam IsOnlineExam
			,@isEnabledOnPortal IsEnabledOnPortal
			,@sequence Sequence
			,@cultureSID CultureSID
			,@examLastVerifiedTime ExamLastVerifiedTime
			,@minLagDaysBetweenAttempts MinLagDaysBetweenAttempts
			,@maxAttemptsPerYear MaxAttemptsPerYear
			,@vendorExamID VendorExamID
			,@examRowGUID ExamRowGUID
			,@examOfferingExamSID ExamOfferingExamSID
			,@examOfferingOrgSID ExamOfferingOrgSID
			,@examOfferingExamTime ExamOfferingExamTime
			,@seatingCapacity SeatingCapacity
			,@catalogItemSID CatalogItemSID
			,@bookingCutOffDate BookingCutOffDate
			,@vendorExamOfferingID VendorExamOfferingID
			,@examOfferingRowGUID ExamOfferingRowGUID
			,@parentOrgSID ParentOrgSID
			,@orgTypeSID OrgTypeSID
			,@orgName OrgName
			,@orgOrgLabel OrgOrgLabel
			,@streetAddress1 StreetAddress1
			,@streetAddress2 StreetAddress2
			,@streetAddress3 StreetAddress3
			,@citySID CitySID
			,@postalCode PostalCode
			,@regionSID RegionSID
			,@phone Phone
			,@fax Fax
			,@webSite WebSite
			,@orgEmailAddress OrgEmailAddress
			,@insuranceOrgSID InsuranceOrgSID
			,@insurancePolicyNo InsurancePolicyNo
			,@insuranceAmount InsuranceAmount
			,@isEmployer IsEmployer
			,@isCredentialAuthority IsCredentialAuthority
			,@isInsurer IsInsurer
			,@isInsuranceCertificateRequired IsInsuranceCertificateRequired
			,@isPublic IsPublic
			,@orgIsActive OrgIsActive
			,@isAdminReviewRequired IsAdminReviewRequired
			,@orgLastVerifiedTime OrgLastVerifiedTime
			,@orgRowGUID OrgRowGUID
			,@registrantPersonSID RegistrantPersonSID
			,@registrantRegistrantNo RegistrantRegistrantNo
			,@yearOfInitialEmployment YearOfInitialEmployment
			,@isOnPublicRegistry IsOnPublicRegistry
			,@cityNameOfBirth CityNameOfBirth
			,@countrySID CountrySID
			,@directedAuditYearCompetence DirectedAuditYearCompetence
			,@directedAuditYearPracticeHours DirectedAuditYearPracticeHours
			,@lateFeeExclusionYear LateFeeExclusionYear
			,@isRenewalAutoApprovalBlocked IsRenewalAutoApprovalBlocked
			,@renewalExtensionExpiryTime RenewalExtensionExpiryTime
			,@archivedTime ArchivedTime
			,@registrantRowGUID RegistrantRowGUID
			,@isDeleteEnabled IsDeleteEnabled
			,@isReselected IsReselected
			,@isNullApplied IsNullApplied
			,@zContext zContext
			,@registrantLabel RegistrantLabel

	end try

	begin catch
		set @xState = xact_state()
		
		if @tranCount > 0 and @xState = 1
		begin
			rollback transaction @sprocName																			-- committable wrapping trx exists: rollback to savepoint
		end
		else if @xState <> 0																									-- full rollback
		begin
			rollback
		end
		
		exec @errorNo = sf.pErrorRethrow																			-- process message text and re-throw the error
	end catch

	return(@errorNo)

end
GO
